### ISSUE TITLE
很棒，不过候选词多的时候会卡，不支持顶功

### ISSUE THREAD

**Issue by Attiv** [imfuxiao/Hamster#1]
我用的是键道6 的方案，打字特别卡，怀疑是因为候选词太多，另外好像是不支持顶功的，这个可以处理下么

**Comment by imfuxiao** [comment]
您好, 谢谢您的使用, 我没太理解"顶功"的意思, 可以在说下吗?

**Comment by Attiv** [comment]
已经5★好评了，很棒。
有交流群之类的吗？
顶功就是不按空格出字，比如我用的键道6方案，https://github.com/Attiv/Rime-1/tree/jiandao6
打字的话可以不按空格，比如： 不按空格 bjxfvkyge ，打完bjvxf候选出现 「不按」,再打k 的时候 「不按」 会自动上屏

**Comment by imfuxiao** [comment]
目前还没有交流群. 因为用的人太少了...以后人多了, 看是否在建个电报群.

目前我用的小鹤双拼方案, 可以4码自动上屏. 我先看下"键道6"的方案, 试下您说的. 有消息给您回复.

**Comment by Attiv** [comment]
感谢🙏
我是从另一个支持rime 的iOS 输入法群里了解的，里面用键道6的还不少-

**Comment by Attiv** [comment]
卡顿的问题应该是开了逐码显示导致的

**Comment by wzxmer** [comment]
支持建群~

**Comment by imfuxiao** [comment]
@Attiv 刚测试下下你提供的方案, 确实是因为候选字太多了, 目前没有候选字多少的限制, 按照你提供的案例输入有上千候选字了, 所以卡顿.

我这里打算做候选字限制处理, App提供候选字大小的限制选项, 默认打算100字.

**Comment by Attiv** [comment]
> @Attiv 刚测试下下你提供的方案，确实是因为候选字太多了，目前没有候选字多少的限制，按照你提供的案例输入有上千候选字了，所以卡顿.
> 
> 我这里打算做候选字限制处理，App 提供候选字大小的限制选项，默认打算 100 字.

是的，有些第一个字会有特别多的。给大佬提个小建议，候选词不一次加载完，滑动的时候懒加载，一次加载固定的数量。这样可能会好点

**Comment by imfuxiao** [comment]
UI方面已做懒加载了处理了, 但是候选字多了还是会有卡顿.

**Comment by Attiv** [comment]
@imfuxiao ..大佬有联系方式吗？有些问题想请教下。我编译 LibrimeKit 失败了。
```
Could NOT find Boost (missing: filesystem regex system) (found suitable
  version "1.81.0", minimum required is "1.46.0")
```

我的 Boost 是用 homebrew装的。

**Comment by imfuxiao** [comment]
> @imfuxiao ..大佬有联系方式吗？有些问题想请教下。我编译 LibrimeKit 失败了。
> 
> ```
> Could NOT find Boost (missing: filesystem regex system) (found suitable
>   version "1.81.0", minimum required is "1.46.0")
> ```
> 
> 我的 Boost 是用 homebrew装的。
看你的报错信息是没有找到 boost. 因为Librime编译的时候需要引用boost.
你可以看下LibrieKit的Makefile, 里面有boost和librime的编译脚本.

**Comment by Attiv** [comment]
大佬不想开群组的话可以在github 上开个 discuss. 我们在其他输入法的微信群聊这个还挺多的

**Comment by imfuxiao** [comment]
> 大佬不想开群组的话可以在github 上开个 discuss. 我们在其他输入法的微信群聊这个还挺多的

已开.

昨天的问题没有回答全, brew安装的Boost我想了下应该无法使用. 因为SPM中需要引入Boost的framwork. 所以还是需要你源码编译.

<img width="538" alt="image" src="https://user-images.githubusercontent.com/6482586/231612244-900db62f-7548-4976-8275-2874e36bab5a.png">

**Comment by lost-melody** [comment]
你好，补充一下顶功相关的问题。当前1.1.0版本中，编码顶字表现正常，即 (逸码) 输入编码 `dguyqidornw` 能够正常切分为 `dgu/yqi/dor/nw` 并上屏“仓输入”，候选栏显示“法”，并补加空格上屏。

但仍有两个需要规划解决的问题；
- 无法使用符号顶字。一般的顶功方案中，在候选“法”字的情况下，继续输入符号 (如 `，`、`。`、`！` 等) 预期应先上屏候选字再上屏符号，但当前实际是丢弃了候选字，只上屏了符号。
- 空格不能作为编码。部分输入方案有需要使用空格/符号作为编码的需求，当前输入空格是直接上屏首选了。例如：
  - 顶功单字方案中可能不使用数字次选实现多重简码，而是通过将分号等直接作为编码。如 `yyi` →“陈”，`yyi;` →“幕”，通常这是为了保持顶功体验的一致性，能够让“幕”字仍然保留在候选栏，直到输入下一字才上屏。
  - 纯单字顶功方案中，偶尔需要分号或空格来引导词语和成语。如 `bv_bd` 中间使用空格引导，能够快速打出联绵词“蝴蝶”，而不是打出 `bvoubdu` 长达七码的单字全码。

**Comment by imfuxiao** [comment]
> 你好，补充一下顶功相关的问题。当前1.1.0版本中，编码顶字表现正常，即 (逸码) 输入编码 `dguyqidornw` 能够正常切分为 `dgu/yqi/dor/nw` 并上屏“仓输入”，候选栏显示“法”，并补加空格上屏。
> 
> 但仍有两个需要规划解决的问题；
> 
> * 无法使用符号顶字。一般的顶功方案中，在候选“法”字的情况下，继续输入符号 (如 `，`、`。`、`！` 等) 预期应先上屏候选字再上屏符号，但当前实际是丢弃了候选字，只上屏了符号。
> * 空格不能作为编码。部分输入方案有需要使用空格/符号作为编码的需求，当前输入空格是直接上屏首选了。例如：
>   
>   * 顶功单字方案中可能不使用数字次选实现多重简码，而是通过将分号等直接作为编码。如 `yyi` →“陈”，`yyi;` →“幕”，通常这是为了保持顶功体验的一致性，能够让“幕”字仍然保留在候选栏，直到输入下一字才上屏。
>   * 纯单字顶功方案中，偶尔需要分号或空格来引导词语和成语。如 `bv_bd` 中间使用空格引导，能够快速打出联绵词“蝴蝶”，而不是打出 `bvoubdu` 长达七码的单字全码。

感谢您的反馈的问题, 我随后看如何处理.

**Comment by imfuxiao** [comment]
> 你好，补充一下顶功相关的问题。当前1.1.0版本中，编码顶字表现正常，即 (逸码) 输入编码 `dguyqidornw` 能够正常切分为 `dgu/yqi/dor/nw` 并上屏“仓输入”，候选栏显示“法”，并补加空格上屏。
> 
> 但仍有两个需要规划解决的问题；
> 
> * 无法使用符号顶字。一般的顶功方案中，在候选“法”字的情况下，继续输入符号 (如 `，`、`。`、`！` 等) 预期应先上屏候选字再上屏符号，但当前实际是丢弃了候选字，只上屏了符号。
> * 空格不能作为编码。部分输入方案有需要使用空格/符号作为编码的需求，当前输入空格是直接上屏首选了。例如：
>   
>   * 顶功单字方案中可能不使用数字次选实现多重简码，而是通过将分号等直接作为编码。如 `yyi` →“陈”，`yyi;` →“幕”，通常这是为了保持顶功体验的一致性，能够让“幕”字仍然保留在候选栏，直到输入下一字才上屏。
>   * 纯单字顶功方案中，偶尔需要分号或空格来引导词语和成语。如 `bv_bd` 中间使用空格引导，能够快速打出联绵词“蝴蝶”，而不是打出 `bvoubdu` 长达七码的单字全码。

@lost-melody 您好, 请教下您说到输入示例用的是什么输入方案, 可以方便提供一下吗? 我需要测试下.

**Comment by lost-melody** [comment]
> @lost-melody 您好, 请教下您说到输入示例用的是什么输入方案, 可以方便提供一下吗? 我需要测试下.

我使用逸码，方案配置在我仓库的 `output/` 目录下：[lost-melody/rime-yima](https://github.com/lost-melody/rime-yima)。

可用的测试场景：
- 使用空格编码的 `bv_bd`；
- 使用 `&` 代替空格的 `bv&bd`；
- 逗号、句号等顶字上屏。

谢谢！

**Comment by imfuxiao** [comment]
> > @lost-melody 您好, 请教下您说到输入示例用的是什么输入方案, 可以方便提供一下吗? 我需要测试下.
> 
> 我使用逸码，方案配置在我仓库的 `output/` 目录下：[lost-melody/rime-yima](https://github.com/lost-melody/rime-yima)。
> 
> 可用的测试场景：
> 
> * 使用空格编码的 `bv_bd`；
> * 使用 `&` 代替空格的 `bv&bd`；
> * 逗号、句号等顶字上屏。
> 
> 谢谢！

收到, 谢谢
