### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by mengnimen** [imfuxiao/Hamster#100]
感谢作者带来手机端Rime，我推荐不少群友使用了
下面是我使用中的问题和建议
1、输入功能调整-空格右边按键-里面的文字描述有错误，现在显示的是‘空格左边按键’。
2、切换到西文状态下，空格左右两边的按键不随着状态变化（我个人理解左边逗号右边句号是随着状态切换的，不知道是不是我理解问题）或者说不随着变化的话可不可以可以设置成点（.)，而不是设置成点了按完之后还是句号(。）
3、在中文状态下 V的上下划都是、并没有\ B和N也是这样（不过我切换到英文状态下，确实可以显示）

建议
1、是否可以像官方那样，点击123到数字页面之后，点击完自己跳回文字输入状态（增加一个开关选项，可能有些人需要不跳回去）
2、空格滑动是否能做成官方那样，长按震动一下，然后可以滑动，现在的感觉过于灵敏相对官方（不知道权限苹果能不能给到，苹果静音状态，也是会有震动的，对于日常使用打字不需要震动，但是滑动震动一下确实习惯了）
3、主题我看有人提了就是自动切换白天和夜晚的。我希望给一份官方默认的配置，我还是觉得官方的好看一些，自己改改选中词组的颜色就可以了。
4、键盘布局希望和官方一致。

最后还是感谢能开发出这么棒的输入法~

**Comment by imfuxiao** [comment]
收到, 感谢您的反馈. 目前App确实有问题 , 还在优化中.

**Comment by imfuxiao** [comment]
问题2: 目前键盘符号已可以跟随中英文变化而变化。空格两边符号为自定义使用，不随状态变化，因为使用者有需求一直使用如`字符，用来查码表。
建议1:  关联问题 #130
建议2:  目前震动开关是一起的，就是开启了所有操作都会有震动反馈，没有做到输入不反馈，只有正在启用某项功能时才震动。
建议3/4: 默认不开启配色方案就是类似官方的样式，可以跟随系统配色变化而变化。

**Comment by mengnimen** [comment]
> 

我这边重置并且重新部署之后，空格左右的自定义，在中文状态下还是不能设置为点（.)，在设置为点（.）之后，输出的还是句号（。）英文状态下，是可以输出为点（.)的，不知道是这样设置的，还是说 在中文状态下不允许把左右设置成点（.）
