### ISSUE TITLE
下面太挤了

### ISSUE THREAD

**Issue by dnxxymcj** [imfuxiao/Hamster#102]
非常感谢，做的太棒了！！！ 有一个小问题，最后一排有点太挤了，能把那个地球图标放到数字键盘里吗，我看有的输入法是这么做的
![IMG_4763](https://user-images.githubusercontent.com/7660888/233254649-36cc42c6-5dab-4ac6-b12e-973d97a22a58.PNG)

**Comment by imfuxiao** [comment]
您好, 可以关闭掉,和.两个按键

**Comment by dnxxymcj** [comment]
> 您好, 可以关闭掉,和.两个按键

嗯，我知道这个，这两个对我来说有点用呀，次选和三选。。

**Comment by imfuxiao** [comment]
囧...暂时您需要折中下, 先隐藏一个按键...后续上下滑动和符号输入会做调整

**Comment by dnxxymcj** [comment]
> 囧...暂时您需要折中下, 先隐藏一个按键...后续上下滑动和符号输入会做调整

好的好的，非常感谢。要是能自定义键盘就更好了。

**Comment by imfuxiao** [comment]
自定义键盘也在规划中, 但是目前主要精力在修复bug及小功能的优化开发. 等app基本稳定了, 就会做自定义键盘布局. 

感谢您的支持与理解~
