### ISSUE TITLE
建议增加类似rrime的hint功能

### ISSUE THREAD

**Issue by derek0x** [imfuxiao/Hamster#106]
建议增加类似rrime的hint功能

**Comment by imfuxiao** [comment]
> 建议增加类似rrime的hint功能

您好,能详细描述下这个功能么? 提供相关的资料也可以.

**Comment by derek0x** [comment]
> 您好,能详细描述下这个功能么? 提供相关的资料也可以.

其实就是助记皮肤功能，在26个键盘上排列上自己想要设置的字根或者声母、韵母 
这种需求基本对接触新输入法的用户特别有用，而rrime 、irime 、 仓 的用户群体很多 都是接触新的输入法方案才会下载新的输入法的，所以这个功能特别友好。希望作者考虑！

**Comment by imfuxiao** [comment]
此功能关联 自定义键盘UI #172
