### ISSUE TITLE
bug：内嵌模式下，文本框的清空按钮不会清空rime已经输入的内容

### ISSUE THREAD

**Issue by maogm12** [imfuxiao/Hamster#113]
如下录屏的例子：
输入了nihao，还没有上屏，这时使用输入框右边的x清空输入框内容，rime里面的nihao并没有被清除，不是很符合直觉。

https://user-images.githubusercontent.com/1658974/233392861-f710701b-b408-4dc6-9ba8-1c3b8c68cb37.MOV

**Comment by imfuxiao** [comment]
您好, 您用的输入方案是什么, 如果不是内置的最好能提供下您完整的输入方案, 方便排查.

**Comment by maogm12** [comment]
> 您好, 您用的输入方案是什么, 如果不是内置的最好能提供下您完整的输入方案, 方便排查.

这个不分方案的，用自带的方案也能复现，复现方法：
1. 开启候选栏嵌入模式
2. 找个输入框输入一些字，先不要上屏
3. 用输入框右边的x把输入框清空
4. 这个时候候选字还在，继续输入的时候，之前清空的没上屏的字符会重新回来。

我没做过keyboard extension，不知道文本框清空的时候，键盘会不会收到通知。上午稍微看了下。可能在`textDidChange`里可以判断一下document proxy有没有text，没有的话，reset rime engine？
