### ISSUE TITLE
小鹤双拼下句号和逗号是英文形式的

### ISSUE THREAD

**Issue by elonj** [imfuxiao/Hamster#117]
在小鹤双拼下输入的句号和逗号是英文形式的,全拼下没问题.不知道是什么问题

**Comment by chca2** [comment]
> 在小鹤双拼下输入的句号和逗号是英文形式的,全拼下没问题.不知道是什么问题

default.yaml 第85、86行，符号映射改为中文符号。

**Comment by imfuxiao** [comment]
您好, 符号的问题已经在准备开发了, 临时只能使用我们伙伴推荐的方案.

**Comment by elonj** [comment]
> 您好, 符号的问题已经在准备开发了, 临时只能使用我们伙伴推荐的方案. 

好的，感谢付出！

**Comment by elonj** [comment]
> > 在小鹤双拼下输入的句号和逗号是英文形式的,全拼下没问题.不知道是什么问题
> 
> default.yaml 第85、86行，符号映射改为中文符号。

我试试，谢谢

**Comment by elonj** [comment]
我把RIME/build和SharedSupport文件double_pinyin_flypy.schema.yaml里的ascii_punct reset改为0之后，重新部署，标点正常了
  - name: ascii_punct
    reset: 0
    states: ["。，", "．，"]

**Comment by elonj** [comment]
> > 
> 
> 
> 
> 还有一种可能是，你是不是用的雾凇拼音，default.yaml里面原本，。两个按键的映射关系是英文标点，但是我看最新版本雾凇拼音改为了中文标点，应该就没有上面问题了。

不是。我用的是仓自带的小鹤双拼。每次输入法更新我都得先删掉再重装，不然有些feature出不来。重装之后还是有逗号句号的中文标点问题。不知道为什么

**Comment by imfuxiao** [comment]
此问题关联 #24 添加符号功能键盘
