### ISSUE TITLE
由于上游 HamsterInputSchemas 路径改动，构建失败

### ISSUE THREAD

**Issue by amorphobia** [imfuxiao/Hamster#119]
上游的路径改为了 `.tmp/SharedSupport`

**Comment by amorphobia** [comment]
这个 PR 只有一个 commit, 显示为两个是因为我 reset 过

**Comment by imfuxiao** [comment]
您好, 是由于早上, 我改动 #116  造成的, HamsterInputSchema项目提交了, 但是Hamster代码还没提交

**Comment by amorphobia** [comment]
了解了
