### ISSUE TITLE
大赞，不过需要一个文档

### ISSUE THREAD

**Issue by kimitrois** [imfuxiao/Hamster#12]
感谢作者的精力和时间！
支持squirrel 主题很赞，不过能不能给个文档的example? 因为直接用squirrel.custom.yaml会有点问题，知道自己能怎么写会好些…
比如，squirrel 并没有键盘背景色和按钮背景色的值

**Comment by imfuxiao** [comment]
感谢您支持, 文档后续补上.

**Comment by imfuxiao** [comment]
关联 #14

**Comment by Attiv** [comment]
+1
