### ISSUE TITLE
请教一下，候选字列表里的问号怎么消除？

### ISSUE THREAD

**Issue by tarkky** [imfuxiao/Hamster#121]
IOS版本： 16.4.1
如图，请问这种问号怎么解决？是需要添加字库么？谢谢。
![question mark](https://user-images.githubusercontent.com/19773978/233521402-38ea1be2-ace5-4874-bc69-4440951c4bd5.png)

**Comment by maogm12** [comment]
这是rime方案词库里面收录了些生僻字，iPhone的字体没收录，需要清理词库

**Comment by kerwincsc** [comment]
> 这是rime方案词库里面收录了些生僻字，iPhone的字体没收录，需要清理词库

除了清理 rime 词库, 有无方法增加 iPhone 的字库

**Comment by maogm12** [comment]
> > 这是rime方案词库里面收录了些生僻字，iPhone的字体没收录，需要清理词库
> 
> 
> 
> 除了清理 rime 词库, 有无方法增加 iPhone 的字库
> 
> 

不能

**Comment by flay0303** [comment]
两个方案，一个就是作者后续能支持第三方字体，比如参考mac上的解决方案添加花园明朝字体，第二个就是用lua脚本过滤掉这些问号。参考https://github.com/jimmy54/rime-lua 里面有个charset.lua就能过滤掉这些，rime.lua里面有使用方法。

**Comment by imfuxiao** [comment]
TF 最新版本已支持字体功能，可以使用自定义的字体，从而消除？文字。

注意：目前只支持配置文件方式，界面暂不支持。
