### ISSUE TITLE
在打开候选栏内嵌的时候闲鱼app输入会导致编码一同上屏

### ISSUE THREAD

**Issue by lianyis** [imfuxiao/Hamster#122]
无论按候选字上屏，还是按空格默认选第一个，都会在上屏的汉字前加上英文编码。

**Comment by kerwincsc** [comment]
确实. 但是阿里系的淘宝, 支付宝, 高德, 菜鸟, 云盘, 语雀并无此现象产生

**Comment by offlineface** [comment]
确实,附个视频https://user-images.githubusercontent.com/67045102/233623511-36da0365-61b9-4c5c-af1a-fb7c6b5cad23.MOV

**Comment by imfuxiao** [comment]
收到, 感谢您的反馈及帮助.
