### ISSUE TITLE
偶发性打字不上屏

### ISSUE THREAD

**Issue by offlineface** [imfuxiao/Hamster#123]
任一界面初次打字前几个字母偶尔不上屏。

**Comment by imfuxiao** [comment]
您好, 已经注到这个问题了, 目前启动时间比较长, 导致您看到键盘, 其实键盘还是启动完毕状态, 所以开始输入不成功.

后续会做优化.

**Comment by imfuxiao** [comment]
关联问题：#143 键盘性能优化
