### ISSUE TITLE
不能保留手工造词

### ISSUE THREAD

**Issue by edison0808** [imfuxiao/Hamster#127]
您好，目前使用发现手动造词后，再次输入时无对应的候选词语，软件是否没有用户词典以致无法存储手动造出的词语？ 希望可以增加该
功能，谢谢！

**Comment by wzxmer** [comment]
这个是跟方案有关的，得检查你使用的方案

**Comment by edison0808** [comment]
> 这个是跟方案有关的，得检查你使用的方案

喔喔，但是在电脑上用小狼毫和iRime手动造词都是正常的

**Comment by wzxmer** [comment]
> > 这个是跟方案有关的，得检查你使用的方案
> 
> 喔喔，但是在电脑上用小狼毫和iRime手动造词都是正常的

方案排查后，我也尝试了下，确实是不行，等作者来处理吧

**Comment by flay0303** [comment]
我也发现了这个问题，我记得最开始使用仓的时候用内置方案会自动生成extended.userdb目录来记录用户词库，我今天重置了app，发现不会生成这个目录了。这样的效果就是每次重新部署后之前打过的词会丢失掉。没有搞明白是哪里的问题。

**Comment by imfuxiao** [comment]
用户提供的测试用例：
1. 在键盘上随便设置一个上滑键的符号为‘（‘为触发手动造词功能的按钮），成功触发时如下图
    ![image](https://user-images.githubusercontent.com/6482586/233836312-9013fd08-427f-4906-a3fa-940ffcd02c61.png)
2. 触发之后可以手动造词，例如“声笔”一词，可以通过输入“sgebiu”，其中sg为声的声母+韵母，e为声的首笔”一“，bi为笔的声母+韵母，u为笔的首笔”丿“，造词之后效果如下图：
![image](https://user-images.githubusercontent.com/6482586/233836339-13fc2021-d444-4b6f-a9ec-436f4e0bec41.png)
3. 第一次造词成功后，后续再输入声笔的声母+云母“sgbi”，无需输入其首笔，则会直接出现”声笔“，即使重新部署也依旧有效，如下图：
![image](https://user-images.githubusercontent.com/6482586/233836363-6eda7908-750b-44cf-8d73-a8c6950e4f89.png)
4. 目前仓输入法手动造词可以成功，但过几分钟后词语会消失，重新部署后也会消失，无法达到造词的预期效果。

使用方案为：苹果声笔小鹤

**Comment by imfuxiao** [comment]
经在PC上使用`苹果声笔小鹤`方案验证。

自造词是先保存在内存中，但落盘时机未知，目前我在PC上测试，手工点击重新部署会落盘，还没发现其他落盘时机。

测试方案的方案落盘会在Rime目录下生成`sbjm_smart.txt`文件，里面保存有自造词。

PC和App的区别在于，PC的输入法线程可以常驻系统后台，所以内存中的数据会长时间保留，而App中是不行的，当App中的Rime线程被系统关闭后，没有落盘的内存中的自造词就会丢失。

我目前的困惑点在于，rime的落盘机制是什么，什么时候落盘。这部分需要看Rime的代码，有点费时间，暂时只能排查到这里了，等有时间在继续排查。

如果有伙伴对Rime了解，欢迎解答。非常感谢。

**Comment by ufo169** [comment]
tet只是用户词典的一种格式，据我个人了解，用户词典是记录词频造词那些的

**Comment by edison0808** [comment]
辛苦大佬了
按照作者目前的排查结果，是不是可以理解为手动造词完马上手工部署，词库就不会丢失呢？但从测试结果来看，似乎也不是呢。另外前面有用户提到一开始的版本是有用户词典的，会不会是后续优化的时候误改了？

**Comment by imfuxiao** [comment]
> 辛苦大佬了 按照作者目前的排查结果，是不是可以理解为手动造词完马上手工部署，词库就不会丢失呢？但从测试结果来看，似乎也不是呢。另外前面有用户提到一开始的版本是有用户词典的，会不会是后续优化的时候误改了？

PC中输入法的RIME目录是固定的，iOS有安全机制，所以键盘使用的Rime目录与App中看到的Rime目录是不同的。App中点击重新部署，是用一个新的Rime的线程去部署Rime目录，其不同于键盘的线程。所以不会有用的。

解决这个问题的思路还是要找到Rime自造词的落盘机制，然后在键盘线程关闭前落盘。

**Comment by ufo169** [comment]
我对开发不懂，对rime方案稍微了解一些。txt只是一种用户词典格式而已，仓好像是没有用户词典，用户词典应该是记录词频和造词的相关信息的，你会发现，音码方案没有调频功能。比如，你用四叶草拼音方案，你关闭应用再进入，之前的用词习惯就没有了，和手动造词一样

**Comment by imfuxiao** [comment]
自造词的问题解决了，在键盘UI进入后台后，主动调用RIME的RimeFinalize() api可以将自造词落盘。

预计下个版本(1.6.8)发布。

**Comment by imfuxiao** [comment]
1.6.8已发布。注意：
1. 默认键盘自造词是在键盘目录下，需要通过点击 “拷贝键盘词库文件至应用”，才能将自造词文件复制到应用目录下，否则每次“重新部署”都会覆盖键盘自造词文件。
2. 如果没有开启“完全访问权限“，键盘的自造词是在自己的沙箱环境下，应用App无法访问，所以也就没法复制到应用目录下。
