### ISSUE TITLE
使用。，、后自动返回默认键盘

### ISSUE THREAD

**Issue by imfuxiao** [imfuxiao/Hamster#130]
期望增加常用标点符号输入后自动返回主键盘。例如使用。，、后自动返回默认键盘。
在添加一个开关选项，对需要的人可以开启，并把下面把常用的几个符号做为选择项。

**Comment by keminu** [comment]
期望

**Comment by imfuxiao** [comment]
关联问题 #107 输入部分符号可以返回主键盘
