### ISSUE TITLE
优化输入方案包减少体积

### ISSUE THREAD

**Issue by imfuxiao** [imfuxiao/Hamster#131]
期望减少输入方案内置压缩包，减少应用体积

**Comment by lewangdev** [comment]
四叶草好像是去掉低频的词，雾凇也是有这个问题，我精简之后，打开输入法的时候，感觉快了不少

**Comment by imfuxiao** [comment]
> 四叶草好像可以去掉低频的词，雾凇也是有这个问题，我精简之后，打开输入法的时候，感觉快了不少

您好，感谢反馈，可否提供下您修改后的输入方案，我可以按照您说到方式优化下，另外如果您有时间，也可以参与这个项目。

输入方案的仓库在：[HamsterInputSchemas](https://github.com/imfuxiao/HamsterInputSchemas)

**Comment by lewangdev** [comment]
好的，我再测试一下再发 PR

**Comment by amorphobia** [comment]
请问输入方案提前编译的目的是什么呢？目前最占空间的文件其实是 build 目录里的文件，这些可以在用户首次打开仓输入法或者手动点击 rime 重置的时候编译

![图片](https://user-images.githubusercontent.com/523025/233833761-05a33b51-ff9d-4f67-844a-37072107566d.png)

**Comment by imfuxiao** [comment]
> 请问输入方案提前编译的目的是什么呢？目前最占空间的文件其实是 build 目录里的文件，这些可以在用户首次打开仓输入法或者手动点击 rime 重置的时候编译
> 
> ![图片](https://user-images.githubusercontent.com/523025/233833761-05a33b51-ff9d-4f67-844a-37072107566d.png)

您好，我是为了防止Build时候内存占用过大，导致被系统Kill。个人想法，不一定对。

**Comment by amorphobia** [comment]
我有一个想法，可能是馊主意

鉴于仓目前仍在频繁更新，可以改为本地部署，让大家一起测试一下，以后如果发现内存问题严重可以再换回来😂

**Comment by imfuxiao** [comment]
> 我有一个想法，可能是馊主意
> 
> 鉴于仓目前仍在频繁更新，可以改为本地部署，让大家一起测试一下，以后如果发现内存问题严重可以再换回来😂

目前方案不多还行，我测试过，是没有出现过Kill过的情况，这个改动不需要改代码，把shell里面的编译内容注释掉就好了。

**Comment by lewangdev** [comment]
四叶草方案 fork 了一份，把 minfreq 设为 500（默认是100），打包了一下，zip包大小稍微小了一点，不知道有没有必要提 PR 到 [HamsterInputSchemas](https://github.com/imfuxiao/HamsterInputSchemas)

https://github.com/lewangdev/rime-cloverpinyin/releases/tag/1.1.4-alpha%2Bhamster.1

另外，雾凇的方案我也 fork 了一份，单独弄了[仓输入法的分支](https://github.com/lewangdev/rime-ice/tree/feat/hamster)，词库太大了，只保留了 base 词库（weight>=200），单独添加了 sogou 网络流行词库，zip 压缩包大小为 14.3MB

https://github.com/lewangdev/rime-ice/releases/tag/1.1.4-alpha%2Bhamster.3

比较适合自己上传到手机上使用

**Comment by imfuxiao** [comment]
目前除了包体积的问题要考虑还需要考虑内置方案的问题，现在内置方案有6种，启动已经很慢了。需要考虑怎么优化了，关联 #143

**Comment by lewangdev** [comment]
是的，我在 iPhone 13 上使用，默认的输入方案和我自己的输入方案，在切换 App 后打开输入法，启动都是有点慢，不过也不影响使用了

**Comment by imfuxiao** [comment]
> 是的，我在 iPhone 13 上使用，默认的输入方案和我自己的输入方案，在切换 App 后打开输入法，启动都是有点慢，不过也不影响使用了

可以尝试修改下，只保留一个输入方案，会快很多。
