### ISSUE TITLE
自定义主题如何自定义基础按键样式和功能键样式?

### ISSUE THREAD

**Issue by kunpehx** [imfuxiao/Hamster#132]
默认主题功能键盘和字母按键样式有所不同，能做到很好的区分。但是，通过对主题中`back_color`进行修改后，所有按键的背景都是用`back_color`进入填充，请教一下如果定制功能键盘和字母按键样式？

**Comment by imfuxiao** [comment]
关联问题 #172 自定义键盘UI布局
