### ISSUE TITLE
输入区属性为数字时，应弹出数字键盘

### ISSUE THREAD

**Issue by amorphobia** [imfuxiao/Hamster#138]
一个例子：[公历和农历日期对照(公元前722年—公元2200年)](https://ytliu0.github.io/ChineseCalendar/index_simp.html)

网页的输入框代码是

```html
<input type="number" id="year" step="1" min="-721" max="2200">
```

系统输入法和 iRime 都可以选择数字键盘，但仓还是选择了默认的字母键盘。

https://user-images.githubusercontent.com/523025/233829365-3021b77a-8c9a-492a-8c1d-04e5a0961f39.MP4

**Comment by imfuxiao** [comment]
收到，感谢反馈
