### ISSUE TITLE
优化横屏布局和按钮文字

### ISSUE THREAD

**Issue by amorphobia** [imfuxiao/Hamster#140]
横屏的时候按钮高度和间距可以优化一些，留出更多屏幕空间，按钮上的文字显示也有些不协调，可以对比一下系统输入法

![image](https://user-images.githubusercontent.com/523025/233848398-12e40a23-9880-436c-96ac-ad065e9c3598.png)

![image](https://user-images.githubusercontent.com/523025/233848423-62360ad1-ea9f-4c54-8c99-483d21d1a720.png)

**Comment by imfuxiao** [comment]
感谢反馈，确实很丑。继续优化~

**Comment by imfuxiao** [comment]
关联 #172 键盘自定义UI布局。
