### ISSUE TITLE
重置功能建议放在设置页面最下方

### ISSUE THREAD

**Issue by chca2** [imfuxiao/Hamster#141]
设置界面Rime栏目下包含重新部署和Rime重置两个功能，考虑前者常用后者少用，且一般App逻辑都会让重置类似的危险功能，在一个不容易误触的位置。因此建议考虑放在设置页面最下方。

**Comment by imfuxiao** [comment]
感谢您的建议，最早还未上架前是把重置功能放在了关于里面，但是最后担心找不到这个功能，就移置了首屏。

后续可以将此按钮继续放到关于里面。

**Comment by Machductor** [comment]
确实，重新部署和Rime重置两个功能相隔过近，不过，放“关于”里面不符合逻辑，吧……

**Comment by imfuxiao** [comment]
确实有的不相干，页面现在也有点乱，随后会进行功能调整。大家如果好的建议，也可以提。

**Comment by imfuxiao** [comment]
1.6.8已添加RIME独立页面
