### ISSUE TITLE
收录至rime官网

### ISSUE THREAD

**Issue by eagleoflqj** [imfuxiao/Hamster#142]
好输入法值得收录，让更多人看见
类似https://github.com/osfans/trime/issues/60
https://github.com/rime/home/commit/47cbdca5a588e889eb1ab398ce1cc92779200666

**Comment by imfuxiao** [comment]
您好，您的建议非常棒，但是目前App还不够完善，还需继续打磨后在提交。

**Comment by kerwincsc** [comment]
感觉已经可以提交了, 后面反正还会逐步完善

**Comment by imfuxiao** [comment]
感谢 @eagleoflqj  的 PR。
