### ISSUE TITLE
键盘性能优化

### ISSUE THREAD

**Issue by imfuxiao** [imfuxiao/Hamster#143]
问题：目前键盘首次使用时会有几秒的卡顿。期望：可以对键盘进行优化，减少卡顿时间。

**Comment by imfuxiao** [comment]
目前输入方案越少，启动加载时间越长。如果是自己有自己的输入方案，建议上传自己的个人方案，只有一个方案列表时加载速度还是可以接受的。

**Comment by imfuxiao** [comment]
增加了一个新功能，参考Android的同文输入法，输入方案需要用户选择下，比如App有10个输入方案，你只需要用到其中1个或者2个，在App界面选择这两个输入方案，键盘启动时会打入default.custom.yaml patch. 覆盖schema_list选项。
这样做的原因是：加入这个patch后 rime启动会快很多，不然schema_list越多，启动越慢。

**Comment by chca2** [comment]
> 

但这个选择加载方案的功能，对于用户手动上传类似雾凇拼音这种方案的是否就不适用了？

**Comment by imfuxiao** [comment]
> > 
> 
> 但这个选择加载方案的功能，对于用户手动上传类似雾凇拼音这种方案的是否就不适用了？

这点有过考虑，通过功能导入的，默认就是导入方案，如果导入方案有多个，那么首次加载的方案会按schema_id排序后，取的第一个方案。

**Comment by imfuxiao** [comment]
> 增加了一个新功能，参考Android的同文输入法，输入方案需要用户选择下，比如App有10个输入方案，你只需要用到其中1个或者2个，在App界面选择这两个输入方案，键盘启动时会打入default.custom.yaml patch. 覆盖schema_list选项。 这样做的原因是：加入这个patch后 rime启动会快很多，不然schema_list越多，启动越慢。

刚看了同文的代码，它调用了 rime_levers_api.h 里面的api。仓改用与同文同样的方式。通过 rime_levers_api.h 中的api操作，不在手工生成 default.custom.yaml 文件的方式打 patch.

**Comment by imfuxiao** [comment]
LIbrimeKit库已添加对 rime_levers_api 的桥接。可以通过rime的api设置用户选择方案。其现原理跟自己手工创建`default.custom.yaml`添加schema_list的path相同。

**Comment by DawnLi-code** [comment]
是的，我也怕功能越来越多，性能越来越差，这个例子就太多了🙂
