### ISSUE TITLE
上屏后的成对符号光标可以自动移动到符号中间

### ISSUE THREAD

**Issue by imfuxiao** [imfuxiao/Hamster#145]
问题：目前成对符号上屏后没有将光标移动到符号中间，期望：上下滑动的成对符号可以将光标自动移动到符号中间。

**Comment by Machductor** [comment]
光标移动到符号中间会注意到一个新问题：使用空格键移动光标，如果松手过快(其实不快)，会在移动后追加一次空格。

**Comment by imfuxiao** [comment]
> 光标移动到符号中间会注意到一个新问题：使用空格键移动光标，如果松手过快(其实不快)，会在移动后追加一次空格。

您好，这是因为长按手势有一个识别时间，如果您开启了震动反馈，你应该可以感受到两次震动，第一次是点击空格时的反馈，然后按住不动，等待一会会出现第二次震动，这时就是长按手势开始的反馈。

**Comment by Machductor** [comment]
> 

建议缩短这个时间，毕竟这是个习惯动作，可以非常快的。

**Comment by imfuxiao** [comment]
> > 
> 
> 
> 
> 建议缩短这个时间，毕竟这是个习惯动作，可以非常快的： 输入完内容以后立即右划，跳过右半个符号。如果等待长按手势反馈，有点卡节奏。

这个建议不错，可以增加空格右滑的手势。

**Comment by imfuxiao** [comment]
1.6.11版本以上线符号设置功能，可在返回主键盘符号列表中添加/修改/删除自己想要点击后返回主键盘的符号。
