### ISSUE TITLE
将键盘副区域显示与滑动动作定义功能拆分

### ISSUE THREAD

**Issue by imfuxiao** [imfuxiao/Hamster#146]
问题：目前键盘副区域（即目前的滑动动作显示区域）是与滑动手势放在一起的，但是根据反馈，部分用户是不需要滑动手势的功能，只需要键盘副区域显示功能，如双拼提示等。
期望：将按键副区域显示功能与滑动手势定义区分开。

**Comment by Machductor** [comment]
“双拼提示” 这类东西一生可能只需要一个星期，而且有双拼练习网站还可以缩短这个时间。

**Comment by imfuxiao** [comment]
关联 #172  键盘UI自定义功能
