### ISSUE TITLE
作者是否考虑出一个上传输入法文件的教程

### ISSUE THREAD

**Issue by zxy970511** [imfuxiao/Hamster#150]
想自己上传rime输入法内使用的朙月拼音，无奈技术稚嫩，上传后重新部署也无法使用，麻烦作者出个教程

**Comment by imfuxiao** [comment]
您好，如果这个方案在PC上使用正常，尤其是mac下，那么就可以直接拖拽上传到Rime文件夹下，在点击下重新部署就好了

**Comment by zxy970511** [comment]
> 您好，如果这个方案在PC上使用正常，尤其是mac下，那么就可以直接拖拽上传到Rime文件夹下，在点击下重新部署就好了

好的，谢谢，感谢您的开发，能够让我这种习惯使用rime输入法的人在手机端使用
