### ISSUE TITLE
功能建议：增加空格下滑三选

### ISSUE THREAD

**Issue by wzxmer** [imfuxiao/Hamster#157]
已有上滑选择第二个候选了，下滑可以对应第三个候选

**Comment by imfuxiao** [comment]
这个可以有。

**Comment by imfuxiao** [comment]
刚测试空格键下滑不行，因为空格到键盘的边界太近了，下滑距离太短，识别不了，增加了#三选上屏功能，自己可以绑定到其他键的方向上。
