### ISSUE TITLE
1.61 版本内置输入法反查功能失效

### ISSUE THREAD

**Issue by forFudan** [imfuxiao/Hamster#159]
1.61 版本内置的「五笔86」和「宇浩」输入法的 Z 键反差功能都无法使用。按 Z 没有任何反应。

用户自主导入「宇浩输入法」方案后，Z 键反查可以使用。

查看文件后发现，这些输入法 schema 文件中的 engine/translators 中的 reverse_lookup_translator 一项都被注释掉了。

不知道是什么原因造成的，或者是有其他的目的？

**Comment by forFudan** [comment]
> 您好，请问具体是那些文件？

我知道原因了，是拉去方案的 sh 文件中有这样的一段

```
for schema in *.schema.yaml; do
  sed '{
    s/version: \(["]*\)\([0-9.]*\)\(["]*\)$/version: \1\2.minimal\3/
    s/\(- stroke\)$/#\1/
    s/\(- reverse_lookup_translator\)$/#\1/
  }' ${schema} > ${schema}.min
  mv ${schema}.min ${schema}
done
```

**Comment by imfuxiao** [comment]
HamsterInputSchemas仓库已调整了shell, 预计1.7.0版本会发布。
