### ISSUE TITLE
输入法配置使用 hamster 而不是 squirrel

### ISSUE THREAD

**Issue by amorphobia** [imfuxiao/Hamster#16]
在代码中发现仓输入法读取用于本输入法的设定时使用的是鼠须管的 yaml 文件

https://github.com/imfuxiao/Hamster/blob/main/Hamster/RimeEngine/RimeEngine.swift#L420
https://github.com/imfuxiao/Hamster/blob/main/Hamster/RimeEngine/RimeEngine.swift#L453

这两行会读取 squirrel.yaml 和 squirrel.custom.yaml

依据 rime 系列输入法的惯例，是否应该改为使用 hamster? 这样会方便同时使用仓输入法和鼠须管的用户可以更好地维护自己的 squirrel.custom.yaml 和 hamster.custom.yaml

**Comment by imfuxiao** [comment]
很高兴收到您的意见, 

开始的想法是想无脑支持Squirrel输入方案, 即Squirrel下的方案直接上传部署即可使用, 无需在维护另一套方案了.

如果这样认为不友好, 后面版本可以改掉. 看大家的意见

**Comment by imfuxiao** [comment]
不错的想法. 两者都可兼顾.

**Comment by kimitrois** [comment]
比较支持无脑鼠须管…方便的地方是，网上找鼠须管配置很容易…自己改改就行…如果完全弄个hamster.custom.yaml很多average users就比较麻烦…不过这两天碰到的问题是，键盘按钮和底色完全一样，如果能更改设置这两个颜色就好了…

**Comment by wd** [comment]
可以都支持，设置 hamster.xx 的优先级最高。。。。
^^^ 说实话我这可能是馊主意，小白用户应该是主流，越简单越好。

**Comment by amorphobia** [comment]
使用 hamster.xxx.yaml 的另一个好处是，以后可以拓展复杂配置，比如实现自定义键盘布局这种繁杂的配置，纯 GUI 设置会戳屏幕到天荒地老，比较适合文本配置。目前的上下划的设置其实也属于这类，文本配置比 GUI 更方便。

对于小白，正如我提到的

> 或许可以在 UI 界面增加一个开关“使用鼠须管配置”来方便用户自行选择，这个开关可以默认打开以向后兼容

这个方式可以兼容

**Comment by wd** [comment]
> 比如实现自定义键盘布局这种繁杂的配置，纯 GUI 设置会戳屏幕到天荒地老，比较适合文本配置。

像这样的功能，我觉得压根就没必要实现 GUI 配置功能。这种就定义为高阶用户的功能好了，想配置可以使用文本配置。

**Comment by amorphobia** [comment]
@imfuxiao 这个是我提的，我搞了版代码，一会儿发布一个 draft pull request
