### ISSUE TITLE
自定义符号的上下滑动

### ISSUE THREAD

**Issue by scomper** [imfuxiao/Hamster#161]
系统输入法的双击空格输入。
长按空格自由移动光标（系统输入法可上下移动光标）的特性；
空格旁边的自定义逗号和句号键能否合并到一起，例如：上划逗号，下滑句号；
长按 123 保持， 能否临时切换成符号和标点输入，输入完成后松开回到拼音模式

**Comment by imfuxiao** [comment]
您的建议非常棒，后续考入如何加入此功能。

1. 自定义符号的上下滑动；
2. 空格上下滑动功能

输入符号返回主键盘关联问题 #130

**Comment by imfuxiao** [comment]
1.6.11版本已上线。可以通过修改文件内容的方式。修改自定义按键的滑动。UI设置暂不支持。
