### ISSUE TITLE
请问，分词符号是哪个键？

### ISSUE THREAD

**Issue by tarkky** [imfuxiao/Hamster#166]
我的意思是，比如我想输入西安。输入“xi”以后有个类似单引号的键，然后再输入“an”各位都是怎么输入的？谢谢

**Comment by chca2** [comment]
> 我的意思是，比如我想输入西安。输入“xi”以后有个类似单引号的键，然后再输入“an”各位都是怎么输入的？谢谢
回车旁边的'键

**Comment by tarkky** [comment]
> > 我的意思是，比如我想输入西安。输入“xi”以后有个类似单引号的键，然后再输入“an”各位都是怎么输入的？谢谢
> 
> 回车旁边的'键
我的是逗号和点号，不起作用，一按逗号，直接变逗号上屏了，不是xi后面多了哥单引号的那种。

**Comment by chca2** [comment]
> > > 我的意思是，比如我想输入西安。输入“xi”以后有个类似单引号的键，然后再输入“an”各位都是怎么输入的？谢谢
> > 
> > 
> > 回车旁边的'键
> > 我的是逗号和点号，不起作用，一按逗号，直接变逗号上屏了，不是xi后面多了哥单引号的那种。

你用的什么方案，分词应该在全拼下才有必要。不是逗号（</，）而是回车键旁边的引号（“/‘）。一般分词都是这个键吧，我用的双拼，测试全拼这个分词按键正常。

**Comment by tarkky** [comment]
> Reference

我的就是四叶草全拼的方案，默认的空格旁边的是 左边是，右边是. 我试了找到’输入但是并没有分拼音，而是直接当前首字+ ‘上屏了。

**Comment by imfuxiao** [comment]
> > Reference
> 
> 我的就是四叶草全拼的方案，默认的空格旁边的是 左边是，右边是. 我试了找到’输入但是并没有分拼音，而是直接当前首字+ ‘上屏了。

您好，您可以修改空格左右两边的符号，改成您想要的符号。

**Comment by tarkky** [comment]
> > > Reference
> > 
> > 
> > 我的就是四叶草全拼的方案，默认的空格旁边的是 左边是，右边是. 我试了找到’输入但是并没有分拼音，而是直接当前首字+ ‘上屏了。
> 
> 您好，您可以修改空格左右两边的符号，改成您想要的符号。

谢谢，这就是我的空格左侧的键盘设置，以及输入时的问题。
![IMG_2702](https://user-images.githubusercontent.com/19773978/236115141-c842fa6d-3c72-4aaf-a9fc-0f142eb53d36.PNG)

![IMG_2701](https://user-images.githubusercontent.com/19773978/236115157-c2aa5238-9c65-447c-86bb-770339292f1f.PNG)

**Comment by tarkky** [comment]
> > > > > Reference
> > > > 
> > > > 
> > > > 我的就是四叶草全拼的方案，默认的空格旁边的是 左边是，右边是. 我试了找到’输入但是并没有分拼音，而是直接当前首字+ ‘上屏了。
> > > 
> > > 
> > > 您好，您可以修改空格左右两边的符号，改成您想要的符号。
> > 
> > 
> > 谢谢，这就是我的空格左侧的键盘设置，以及输入时的问题。 ![IMG_2702](https://user-images.githubusercontent.com/19773978/236115141-c842fa6d-3c72-4aaf-a9fc-0f142eb53d36.PNG)
> > ![IMG_2701](https://user-images.githubusercontent.com/19773978/236115157-c2aa5238-9c65-447c-86bb-770339292f1f.PNG)
> 
> 默认分词是**直单引号**`'`，你设置成**开单引号**`‘`了

@groverlynn 谢谢兄弟，解决了我的问题。非常感谢。不过，在pc上面，从来都是单引号就是，回车左边的那个键，请问这个直单引号在手机上怎么输入？我目前是复制粘贴了你的输出。但是还不知道怎么直接从键盘输入这个直单引号。

**Comment by groverlynn** [comment]
> > > > > > Reference
> > > > > 
> > > > > 
> > > > > 我的就是四叶草全拼的方案，默认的空格旁边的是 左边是，右边是. 我试了找到’输入但是并没有分拼音，而是直接当前首字+ ‘上屏了。
> > > > 
> > > > 
> > > > 您好，您可以修改空格左右两边的符号，改成您想要的符号。
> > > 
> > > 
> > > 谢谢，这就是我的空格左侧的键盘设置，以及输入时的问题。 ![IMG_2702](https://user-images.githubusercontent.com/19773978/236115141-c842fa6d-3c72-4aaf-a9fc-0f142eb53d36.PNG)
> > > ![IMG_2701](https://user-images.githubusercontent.com/19773978/236115157-c2aa5238-9c65-447c-86bb-770339292f1f.PNG)
> > 
> > 
> > 默认分词是**直单引号**`'`，你设置成**开单引号**`‘`了
> 
> @groverlynn 谢谢兄弟，解决了我的问题。非常感谢。不过，在pc上面，从来都是单引号就是，回车左边的那个键，请问这个直单引号在手机上怎么输入？我目前是复制粘贴了你的输出。但是还不知道怎么直接从键盘输入这个直单引号。

換系統輸入法。

**Comment by lawlerhwang** [comment]
大佬好，我是小白
请问
九宫格模式下按1无法分词，应该如何处理？

虽然 t9.schema.yaml 中有：
`# 输入时按 1 可以分词
key_binder:
  bindings:
    - { when: has_menu, accept: at, send: apostrophe }`

但实际使用的时候并没有生效。
以「西安」一次为例：
![IMG_2279](https://github.com/user-attachments/assets/08a39834-26de-4533-be74-9f81befadf48)

**Comment by imfuxiao** [comment]
> @imfuxiao 大佬好，我是小白 请问 九宫格模式下按1无法分词，应该如何处理？
> 
> 虽然 t9.schema.yaml 中有： `# 输入时按 1 可以分词 key_binder: bindings: - { when: has_menu, accept: at, send: apostrophe }`
> 
> 但实际使用的时候并没有生效。 以「西安」一词为例： ![IMG_2279](https://private-user-images.githubusercontent.com/49749460/359826848-08a39834-26de-4533-be74-9f81befadf48.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMzQ3MjYsIm5iZiI6MTcyNDIzNDQyNiwicGF0aCI6Ii80OTc0OTQ2MC8zNTk4MjY4NDgtMDhhMzk4MzQtMjZkZS00NTMzLWJlNzQtOWY4MWJlZmFkZjQ4LlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDEwMDAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzOTFmM2ZmOTgwYTI0MzM5ZDk0OTU2ZjIyOTY0YjgwYjg3NjI5ZTY5YWFhOTE0ZWY4YjEzYzM3MTNhZmE1YzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Vh-Biem4-remWN0QzJIqGDQ_1dz-ooUVnMplpinR03c)

[QQ 文档](https://docs.qq.com/doc/DVGJoY2pac21WREZU?_t=1724234452774&u=8555408877f240b1aba170ae09b3a28a)中有这个介绍，请按此调整。

<img width="689" alt="image" src="https://github.com/user-attachments/assets/bd2d6280-eb78-49ea-be26-0a953a741b19">
