### ISSUE TITLE
建议：输入法方案上传默认启动

### ISSUE THREAD

**Issue by Ningscode** [imfuxiao/Hamster#168]
输入法方案上传默认启动，并把“启动”按钮改为“复制IP地址”

**Comment by imfuxiao** [comment]
很好的建议，不过目前还有一些问题，比如 IP 地址不一定是对的/空的等等，需要用户用户手工去 WiFi 下查看网络 IP，等这个 BUG 修复了在加优化。

感谢您的反馈。
