### ISSUE TITLE
仅代表南方人恳请加入模糊音😅

### ISSUE THREAD

**Issue by geekbb** [imfuxiao/Hamster#170]
![IMG_5146](https://user-images.githubusercontent.com/46196358/234867791-22639f73-5851-41a9-9b3b-9b37165488b2.PNG)

**Comment by imfuxiao** [comment]
您好，模糊音可以在输入方案中自己设置，App没有加这些特性的可视化。因为每种输入方案都是不相同的。

**Comment by geekbb** [comment]
> 

<img width="635" alt="image" src="https://user-images.githubusercontent.com/46196358/235034658-1007bf26-aba8-4455-8da7-d2351e52b472.png">
找到了，谢谢
