### ISSUE TITLE
Bug反馈，中文模式下，上下滑动均输入中文符号

### ISSUE THREAD

**Issue by Ricadre** [imfuxiao/Hamster#175]
![942f8835-d389-4dc6-83ea-c386dbb0be7e](https://user-images.githubusercontent.com/3013056/235036573-e364c3d7-374e-485a-8810-e8697d420acb.jpeg)
默认的VBN三个按键，在中文模式下，上下滑动输入的都是中文符号

**Comment by imfuxiao** [comment]
您好，目前符号是经过底层Rime处理，如果输入方案中有对符号的处理，那么上屏的就是处理后的符号。

这个暂时没有好的解决方案，因为有些方案需要做符号处理，有的可能不需要。

我目前想做的是方案是：在符号键盘中，所有符号的上屏是不会经过Rime的，其余情况保持现状。

拿你现在反馈的例子来说，那么输入特定符号就需要去符号键盘输入了。

已上只是我的初步思路，还未进行开发，大家先讨论下。
