### ISSUE TITLE
iCloud备份及导入

### ISSUE THREAD

**Issue by imfuxiao** [imfuxiao/Hamster#176]
希望在完成在完成 #173 后实现iCloud备份及导入功能

**Comment by wayjam** [comment]
此功能可以实现将MacOS的配置通过iCloud同步让iOS读取直接使用？实现多端同一配置

**Comment by BerryBie** [comment]
支持！这样就可以和mac端进行同步了！

**Comment by g6ai** [comment]
我使用了一天v1.6.8的iCloud同步功能，体验良好。
