### ISSUE TITLE
空格左右自定义按键可跟随中英切换

### ISSUE THREAD

**Issue by lamons** [imfuxiao/Hamster#179]
空格左右按键开启后，目前只能分别设置一组字符。默认的逗号和句号可能是最常见的情况，这样的话如果能跟随中英切换转换为半角逗号和句号（或者增加一组英文状态的自定义）会更合理一些。

**Comment by imfuxiao** [comment]
您好，感谢反馈。RIME的设计设计思路，符号可以由RIME引擎来映射的，您可在RIME方案中自己配置符号对应的映射。
