### ISSUE TITLE
细节优化- spotlight搜索时按键气泡在候选栏顶端被切割

### ISSUE THREAD

**Issue by liamtsyue** [imfuxiao/Hamster#181]
不知道是系统原因还是啥，spotlight搜索的时候，上排qwerty这一行的按键气泡顶端会被切掉一部分，如图：
![IMG_0151](https://user-images.githubusercontent.com/58595280/235151308-1ce4cb38-73fe-4eeb-ae78-14b7ea11e4f2.jpeg)

而自带输入法的气泡顶端是可以越过搜索框显示的，整体看起来比较和谐：
![IMG_0155](https://user-images.githubusercontent.com/58595280/235151457-de2e17af-e2fe-4e37-b1ce-c97af3c43064.jpeg)

如果不是系统限制的话，能否优化一下这个地方？
iOS版本是16.4.1
仓输入法1.6.4

ps. 还有个不知道是我不会用还是怎么，键盘滑动手势里设置了f键下滑切换为繁体输入，但是怎么滑输出的都是简体……求指教

**Comment by imfuxiao** [comment]
感谢反馈，目前简繁切换的Key是写死的，对有些方案是无效的，所以不起作用，这个后续会做优化。

按键气泡的问题，第三方浮动无法升至最顶层，这个暂时无解。

**Comment by imfuxiao** [comment]
2.0.0 版本已对按键气泡做了优化。
