### ISSUE TITLE
冗余方案从“输入方案”列表中移除

### ISSUE THREAD

**Issue by forFudan** [imfuxiao/Hamster#182]
当前，冗余方案已经从 default.yaml 中移除
![image](https://user-images.githubusercontent.com/12560439/235180820-df53a1ca-5b91-4983-9f01-7e9fff46bf6d.jpeg)。

然而在“输入方案”界面中，依旧有大量冗余方案。![image](https://user-images.githubusercontent.com/12560439/235180913-6db7768b-255c-4355-bce0-db17986ae675.png)

注意到，这个“输入方案”中的列表似乎依旧遍历了 Build 文件夹中所有的 schema 文件。

是否可以更新它，使得它同 default.yaml 中的方案列表保持一致？

谢谢！

**Comment by tamhaywoo** [comment]
你在不需要的输入法方案前添加#号，比如：
# - schema: wubi86

**Comment by imfuxiao** [comment]
> 当前，冗余方案已经从 default.yaml 中移除 ![image](https://user-images.githubusercontent.com/12560439/235180820-df53a1ca-5b91-4983-9f01-7e9fff46bf6d.jpeg)。
> 
> 然而在“输入方案”界面中，依旧有大量冗余方案。![image](https://user-images.githubusercontent.com/12560439/235180913-6db7768b-255c-4355-bce0-db17986ae675.png)
> 
> 注意到，这个“输入方案”中的列表似乎依旧遍历了 Build 文件夹中所有的 schema 文件。
> 
> 是否可以更新它，使得它同 default.yaml 中的方案列表保持一致？
> 
> 谢谢！

最新版本应该不会的， 您点击重置功能测试下。
