### ISSUE TITLE
候选词滑动选择时经常无反应

### ISSUE THREAD

**Issue by Nicked639** [imfuxiao/Hamster#189]
相比原生输入法，Hamster在输入字母后若想上屏的候选词不在第一页滑动选择时难以选中滑动可响应区域导致滑动困难。

**Comment by imfuxiao** [comment]
您好，请问您是指横向滑动条的候选字选择时不容易上屏吗？

**Comment by Nicked639** [comment]
> 您好，请问您是指横向滑动条的候选字选择时不容易上屏吗？

是指横向滑动条经常无法滑动，不如原生输入法跟手。

**Comment by imfuxiao** [comment]
抱歉，给您带来不便，我尽快处理。

**Comment by imfuxiao** [comment]
1.6.8 版本已修复
