### ISSUE TITLE
候选词默认字体能修改吗

### ISSUE THREAD

**Issue by flay0303** [imfuxiao/Hamster#19]
候选词默认字体看着有点粗，像黑体，不知道用的是什么字体，想咨询一下能不能通过修改squirrel.yaml里面的font face来修改，如果能修改，iOS下有哪些字体是可以使用的，我试了苹方字体没有用。像iRime或系统自带输入法的字体就行。

**Comment by imfuxiao** [comment]
您好, 目前用的是系统字体. 如果要使用第三方字体, 就需要把字体打包到应用里, 所以没有加这个功能. 
还有一个问题, 就是字体的版权问题. 

您看您这边需要什么字体. 是否是开源的, 我思考下看是否加到后续版本中.

**Comment by imfuxiao** [comment]
已删除候选栏字体默认加粗. 关联版本1.1.2

**Comment by Attiv** [comment]
@imfuxiao 我试着写了个从文件/icloud 导入自定义字体的，但是没生效，代码比较烂，思路是：
1. 主 app 导入字体，移动到 `group` 目录
2. 键盘找到 `group` 目录下导入的这个字体，注册
3. 偷懒想用运行时直接替换 `system font`, 没生效，不过貌似影响到了计算候选字宽度的代码
![CleanShot 2023-05-03 at 22 31 58@2x](https://user-images.githubusercontent.com/15698129/235947752-114045e5-63a9-4196-8def-e75995611d9f.png)

您要做的时候可以看看有没有参考价值
https://github.com/Attiv/Hamster/commit/f94ed2fdd0cfb3251b21be229dbe1d17c5a7ec83
