### ISSUE TITLE
按键滑动手势的触发优化

### ISSUE THREAD

**Issue by Nicked639** [imfuxiao/Hamster#190]
1.相比上下滑动，左右滑动的触发移动距离似乎要小一些，导致快速输入时经常误触发，建议延长左右滑动的触发移动距离。

2.![image](https://user-images.githubusercontent.com/11361855/235434727-4504f7c0-8315-4139-a072-8e305475dcac.jpeg)
如图，在小鹤输入法中在输入第一个字母x后，如果这时候是想打出「新」，则要再输入一个 b 就能在候选词中看到对应的 xin 的全拼候选词，但如果这时输入b的手指带上了滑动，不管哪个方向，都会让「想」这个字直接上屏，而不是对应的 xin 的全拼候选词。
这个处理方式和原生输入法不一样，容错性较低，容易打错字，可否修改成和原生一样的方式？

**Comment by imfuxiao** [comment]
感谢您的反馈，看现象貌似滑动手势的bug，我尽快排查处理。

**Comment by imfuxiao** [comment]
fix 1.6.8
