### ISSUE TITLE
標點符號

### ISSUE THREAD

**Issue by groverlynn** [imfuxiao/Hamster#191]
ASCII的95個可打印字符，除去52個拉丁字母，還應該有43個標點符號，但倉居然只保留了12個最不常用的，而常用的被強制替換成非ASCII的標點符號，從根本上破壞了用戶的自定義標點符號以及更複雜的自定義符號輸入。其中最重要的 `｀`（沉音符，默認反查鍵，不過倉好像也不支持反查）、`'`（縮略號，默認分詞鍵）被捨棄，基本上rime的優勢功能全都被廢了。還有`"`（直雙引號）、`'`（直單引號）也被捨棄，而彎單引號居然只有開（`‘`）沒有閉（`‘`），貨幣符號居然佔用了四個寶貴的鍵位（其中只有一個可以被定義），西文狀態居然還有一個根本不是標點的項目符號`•`。基本上想用這個輸入法修改自己的配置文件都做不到，缺了一半的標點

**Comment by imfuxiao** [comment]
非常棒的反馈，目前符号确实存在不少问题，关联问题 #24 后续会做优化调整。

还有几个点可能需要说明下，还请您理解：
1. 符号的处理默认是走Rime的，自己在方案中定义的符号映射是可以实现的，所以是支持`（反查）等功能的，比如我自己在用的小鹤音形就把空格左边的按键替换为反查符号`。
2. 目前App中文输入模式下会显示中文的符号，英文模式下才会显示英文符号。
3. 如您所说，默认显示的符号确实有些不合理，希望您可以反馈下您所希望的符号布局，可以帮助更好的优化符号布局。

**Comment by groverlynn** [comment]
> 非常棒的反馈，目前符号确实存在不少问题，关联问题 #24 后续会做优化调整。
> 
> 还有几个点可能需要说明下，还请您理解：
> 
> 1. 符号的处理默认是走Rime的，自己在方案中定义的符号映射是可以实现的，所以是支持`（反查）等功能的，比如我自己在用的小鹤音形就把空格左边的按键替换为反查符号`。

但是輸入法自己的鍵盤是沒有`鍵的，沒辦法自己修改自己，也沒有默認值可以恢復，添加按鍵還得依靠其他輸入法

> 2. 目前App中文输入模式下会显示中文的符号，英文模式下才会显示英文符号。

不存在所謂的「中文的符號」和「英文符號」。比如簡中橫排的引號和美式英文的引號是完全一致，和英式英文符號一致但內外用法相反。繁中橫排和簡中繁中豎排的引號根本就沒有。你現在所謂「英文模式下顯示英文符號」，是只有閉雙引號和閉單引號，沒有開雙引號、開單引號，也沒有直單引號、直雙引號、沉音符。

尤其是直引號。原本rime是會自動將直引號成對轉換成彎引號的，你改成彎引號以後rime直接忽略，於是你需要4個鍵位分別放置開雙引號、閉雙引號、開單引號、閉單引號，而原本只要直雙引號和直單引號2個鍵位。

> 3. 如您所说，默认显示的符号确实有些不合理，希望您可以反馈下您所希望的符号布局，可以帮助更好的优化符号布局。

專門的符號鍵盤是違背rime的設計思路的，列全所有可打印ascii字符（U+0020至U+007F）然後交給用戶自己定義每個字符對應的候選標點符號，以及組合成符合一定格式的代碼來輸入符號，這才是rime的思路。我自己有一個按照latex語法輸入符號的碼表，有近千個字符，你無論怎麼設計符號鍵盤都是不可能實現直接選擇上千個字母和符號的

**Comment by imfuxiao** [comment]
> > 非常棒的反馈，目前符号确实存在不少问题，关联问题 #24 后续会做优化调整。
> > 还有几个点可能需要说明下，还请您理解：
> > 
> > 1. 符号的处理默认是走Rime的，自己在方案中定义的符号映射是可以实现的，所以是支持`（反查）等功能的，比如我自己在用的小鹤音形就把空格左边的按键替换为反查符号`。
> 
> 但是輸入法自己的鍵盤是沒有`鍵的，沒辦法自己修改自己，也沒有默認值可以恢復，添加按鍵還得依靠其他輸入法
> 
> > 2. 目前App中文输入模式下会显示中文的符号，英文模式下才会显示英文符号。
> 
> 不存在所謂的「中文的符號」和「英文符號」。比如簡中橫排的引號和美式英文的引號是完全一致，和英式英文符號一致但內外用法相反。繁中橫排和簡中繁中豎排的引號根本就沒有。你現在所謂「英文模式下顯示英文符號」，是只有閉雙引號和閉單引號，沒有開雙引號、開單引號，也沒有直單引號、直雙引號、沉音符。
> 
> 尤其是直引號。原本rime是會自動將直引號成對轉換成彎引號的，你改成彎引號以後rime直接忽略，於是你需要4個鍵位分別放置開雙引號、閉雙引號、開單引號、閉單引號，而原本只要直雙引號和直單引號2個鍵位。
> 
> 至於在中文狀態下顯示的那些符號，`#` `%` `^` `*` `+` `=` `_` `\` `$` `&` `-` `/` `@` `.`是ascii字符，中文行文中多數是需要使用對應的全寬字符的（U+FF00至U+FFEF），不過這些可以由用戶定義。反而是直接調用了全寬字符的`｛` `｝` `￨` `～` `！` `？` `，` `：` `；`用戶無法定義。至於`【` `】`和`《` `》`根本不是`[` `]`和`<` `>`對應的全寬字符。`—` `…` `·`都是西文標點，因為GBK偷懶所以共用了西文標點。另一種方案是用`―` `⋯` `・`。這裏不應該替用戶選擇。
> 
> > 3. 如您所说，默认显示的符号确实有些不合理，希望您可以反馈下您所希望的符号布局，可以帮助更好的优化符号布局。
> 
> 專門的符號鍵盤是違背rime的設計思路的，列全所有可打印ascii字符（U+0020至U+007F）然後交給用戶自己定義每個字符對應的候選標點符號，以及組合成符合一定格式的代碼來輸入符號，這才是rime的思路。我自己有一個按照latex語法輸入符號的碼表，有近千個字符，你無論怎麼設計符號鍵盤都是不可能實現直接選擇上千個字母和符號的

非常感谢，感谢您的耐心解答。我之前对符号的理解就只是符号，没有这么深的理解。后面会按您的这个思路重新定义符号功能。希望您多提意见和建议。

**Comment by groverlynn** [comment]
> > > 非常棒的反馈，目前符号确实存在不少问题，关联问题 #24 后续会做优化调整。
> > > 还有几个点可能需要说明下，还请您理解：
> > > 
> > > 1. 符号的处理默认是走Rime的，自己在方案中定义的符号映射是可以实现的，所以是支持`（反查）等功能的，比如我自己在用的小鹤音形就把空格左边的按键替换为反查符号`。
> > 
> > 
> > 但是輸入法自己的鍵盤是沒有`鍵的，沒辦法自己修改自己，也沒有默認值可以恢復，添加按鍵還得依靠其他輸入法
> > > 2. 目前App中文输入模式下会显示中文的符号，英文模式下才会显示英文符号。
> > 
> > 
> > 不存在所謂的「中文的符號」和「英文符號」。比如簡中橫排的引號和美式英文的引號是完全一致，和英式英文符號一致但內外用法相反。繁中橫排和簡中繁中豎排的引號根本就沒有。你現在所謂「英文模式下顯示英文符號」，是只有閉雙引號和閉單引號，沒有開雙引號、開單引號，也沒有直單引號、直雙引號、沉音符。
> > 尤其是直引號。原本rime是會自動將直引號成對轉換成彎引號的，你改成彎引號以後rime直接忽略，於是你需要4個鍵位分別放置開雙引號、閉雙引號、開單引號、閉單引號，而原本只要直雙引號和直單引號2個鍵位。
> > 至於在中文狀態下顯示的那些符號，`#` `%` `^` `*` `+` `=` `_` `\` `$` `&` `-` `/` `@` `.`是ascii字符，中文行文中多數是需要使用對應的全寬字符的（U+FF00至U+FFEF），不過這些可以由用戶定義。反而是直接調用了全寬字符的`｛` `｝` `￨` `～` `！` `？` `，` `：` `；`用戶無法定義。至於`【` `】`和`《` `》`根本不是`[` `]`和`<` `>`對應的全寬字符。`—` `…` `·`都是西文標點，因為GBK偷懶所以共用了西文標點。另一種方案是用`―` `⋯` `・`。這裏不應該替用戶選擇。
> > > 3. 如您所说，默认显示的符号确实有些不合理，希望您可以反馈下您所希望的符号布局，可以帮助更好的优化符号布局。
> > 
> > 
> > 專門的符號鍵盤是違背rime的設計思路的，列全所有可打印ascii字符（U+0020至U+007F）然後交給用戶自己定義每個字符對應的候選標點符號，以及組合成符合一定格式的代碼來輸入符號，這才是rime的思路。我自己有一個按照latex語法輸入符號的碼表，有近千個字符，你無論怎麼設計符號鍵盤都是不可能實現直接選擇上千個字母和符號的
> 
> 非常感谢，感谢您的耐心解答。我之前对符号的理解就只是符号，没有这么深的理解。后面会按您的这个思路重新定义符号功能。希望您多提意见和建议。

默認的`symbols.yaml`裏面就有大量範例

**Comment by groverlynn** [comment]
又發現一個bug：使用符號鍵盤輸入（不論是不是ASCII範圍內）或是主鍵盤的非ASCII範圍內的符號，因爲是不經librime處理的，所以不記錄在rime的history中，導致rime的部分需要參考歷史輸入的功能異常。
典型的就是緊跟數字的主鍵盤的`.`或`:`是不轉換爲相應的CJK標點符號的。現在變成了數字＋符號鍵盤的符號或主鍵盤的非ASCII符號＋主鍵盤的`.`或`:`也不再轉換爲相應的CJK標點符號了。
