### ISSUE TITLE
关于标点和⬆️键的建议

### ISSUE THREAD

**Issue by sgou548** [imfuxiao/Hamster#193]
在使用过程中我发现有两点是否可以改进。

第一点，如果想输入 `.` 就必须得切换成英文才能使用半角符号，否则上屏的会是 `。`，这给输入带来了很大的不便。比如，我想在中文键盘输入 `github.com`，就会变成 `github。com`。当然，我不确定这是我输入方案的问题，还是程序设定的问题。如果是程序的问题，能否可以允许在中文键盘中实现全角、半角混录呢？

第二点，应该是要防止误触，所以每次都得按两次⬆️键才能在中文键盘中输入大写字母。这个防误触能否考虑交给使用者选择是否开启？

非常好用的输入法 app，感谢开发者！！！

**Comment by kingname** [comment]
@sgou548 试一试长按。看看会不会出现.

**Comment by imfuxiao** [comment]
> 在使用过程中我发现有两点是否可以改进。
> 
> 第一点，如果想输入 `.` 就必须得切换成英文才能使用半角符号，否则上屏的会是 `。`，这给输入带来了很大的不便。比如，我想在中文键盘输入 `github.com`，就会变成 `github。com`。当然，我不确定这是我输入方案的问题，还是程序设定的问题。如果是程序的问题，能否可以允许在中文键盘中实现全角、半角混录呢？
> 
> 第二点，应该是要防止误触，所以每次都得按两次⬆️键才能在中文键盘中输入大写字母。这个防误触能否考虑交给使用者选择是否开启？
> 
> 非常好用的输入法 app，感谢开发者！！！

您好，感谢您的反馈。

您看是否可以将空格左右两边的自定义按键定义为您需要的符号。另外，Shift键默认是锁定大小写状态的，如果需要改变这种模式在输入功能调整中调整，调整后就是首字母大写。另外也可设置一个中英文切换键来切换中英文输入。还有一种方案就是自己内置方案中设置英文码表。

**Comment by Machductor** [comment]
> 第一点，如果想输入 `.` 就必须得切换成英文才能使用半角符号，否则上屏的会是 `。`，这给输入带来了很大的不便。比如，我想在中文键盘输入 `github.com`，就会变成 `github。com`。当然，我不确定这是我输入方案的问题，还是程序设定的问题。如果是程序的问题，能否可以允许在中文键盘中实现全角、半角混录呢？


有没有可能是你 Yaml 文件 “punctuator:” 这一项没有设置好呢？比如设置了
  half_shape:
    '.' : { commit: 。 }

**Comment by sgou548** [comment]
> > 第一点，如果想输入 `.` 就必须得切换成英文才能使用半角符号，否则上屏的会是 `。`，这给输入带来了很大的不便。比如，我想在中文键盘输入 `github.com`，就会变成 `github。com`。当然，我不确定这是我输入方案的问题，还是程序设定的问题。如果是程序的问题，能否可以允许在中文键盘中实现全角、半角混录呢？
> 
> 有没有可能是你 Yaml 文件 “punctuator:” 这一项没有设置好呢？比如设置了 half_shape: '.' : { commit: 。 }

查了一下，并不是这个原因。没关系，我改一下自己的输入习惯就好。谢谢啦。
