### ISSUE TITLE
非常难点击到切换输入法的按钮

### ISSUE THREAD

**Issue by aben** [imfuxiao/Hamster#195]
我输入英文习惯用滑动输入，所以更喜欢用系统自带的英文输入法。我发现在Rime输入法时候，非常难点击到切换输入法的按钮（123右边的按钮）。iOS 版本是 15.7.1。

另外一个小问题是，我电脑上的某些lua脚本在手机上不生效。

感谢大佬打造的Rime手机版。

**Comment by imfuxiao** [comment]
感谢您的反馈，关于lua的问题，您看是否可以这样测试下，以mac系统为例，可以将Rime下的所有内容，上传至App的Rime目录下，上传前先删除之前Rime下得内容。Windows下也类似。

**Comment by aben** [comment]
我看lua脚本是放到SharedSupport目录下的。我把电脑上Rime目录上传手机app的Rime下的话，是不是应该把SharedSupport目录下的文件也清空？

**Comment by imfuxiao** [comment]
您好，个人理解应该将您的方案全部放在 Rime 目录下。

**Comment by aben** [comment]
另外还有一个小建议，我第一次使用上下滑输入符号，体验很赞。唯一的问题是我好像更习惯左下右上?不知道能添加一个滑动对调的设置不?

**Comment by aben** [comment]
我想非常dirty对调一下actionKey返回值，但是一直编程失败。项目依赖librime是编译成功。错误提示 
```
HamsterApp
  Missing package product 'LibrimeKit'
HamsterKeyboard
  Missing package product 'LibrimeKit'
```

**Comment by imfuxiao** [comment]
> 我想非常dirty对调一下actionKey返回值，但是一直编程失败。项目依赖librime是编译成功。错误提示
> 
> ```
> HamsterApp
>   Missing package product 'LibrimeKit'
> HamsterKeyboard
>   Missing package product 'LibrimeKit'
> ```

LibrimeKit 是 Hamster 下的gitmodule, 您先检查下这里

**Comment by aben** [comment]
昨天把电脑系统升级到ventura就编译成功了。
