### ISSUE TITLE
关于 Qwerty 键盘布局之外的方案

### ISSUE THREAD

**Issue by Azeril** [imfuxiao/Hamster#196]
万望作者后续能加入对自定义键盘布局的支持. 比如德沃夏克键盘 Dvorak Keyboard. 虽然这属于相当小众的需求了... 
不胜感激.

**Comment by imfuxiao** [comment]
感谢您的反馈，目前自定义键盘UI方案还在制定中，等这个功能推出后就可以支持各种需要的键盘布局了。

关联 [discusstions#172](https://github.com/imfuxiao/Hamster/discussions/172)

如果您对键盘UI自定义布局有什么好的建议和意见，欢迎一起讨论，谢谢。

**Comment by imfuxiao** [comment]
2.0.0 版本已支持自定义布局。
