### ISSUE TITLE
重新部署不生效

### ISSUE THREAD

**Issue by selong1234** [imfuxiao/Hamster#198]
修改rime文件夹内文件的内容，重新部署后，build文件夹下对应的文件没有同步改变。
有两个现象，
1是修改用户自定义码表，添加词条及编码，重新部署后不生效。
2是更改rime内的输入法配置文件，xxx.schema.yaml，重新部署后，build文件夹内的xxx.schema.yaml没有同步更新。

在电脑小狼毫上做以上2条同样的操作，重新部署后都能正常生效。

**Comment by imfuxiao** [comment]
收到，感谢您的反馈。

**Comment by imfuxiao** [comment]
1.6.8以后版本如果遇到此现象，先确认是否修改了SharedSupport下文件，确保此文件夹下存在default.yaml文件。否则会引发如上问题。
