### ISSUE TITLE
支持！反馈一下UI，键盘布局无法修改，候选栏过高

### ISSUE THREAD

**Issue by wzxmer** [imfuxiao/Hamster#2]
跟前面的来自同一个地方，使用同一个方案。不过由于我关闭了辅助码，候选词少，所以我使用时能正常顶功。另外我尝试了自定义增加配色方案，已成功，目前使用比较困扰的就是因个人习惯，键盘UI无法调整带来的误触的问题。

**Comment by imfuxiao** [comment]
非常高兴收到您的反馈, UI的问题我尽快处理.

**Comment by wzxmer** [comment]
希望能建个TG群，这边还是挺多人期待的，另外，针对顶功功能的问题，我可以提供所使用的键道6方案

**Comment by wzxmer** [comment]
> 非常高兴收到您的反馈，UI 的问题我尽速处理。

希望能建个TG群，这边还是挺多人期待的，另外，针对顶功功能的问题，我可以提供所使用的键道6方案

**Comment by imfuxiao** [comment]
1. 键盘布局 #52 
2. 候选栏过高 #21
