### ISSUE TITLE
[BUG] 无法输入「闹钟」等时间选择器的时间

### ISSUE THREAD

**Issue by MiracleXYZ** [imfuxiao/Hamster#201]
iOS的「闹钟」等时间选择器可以输入时间，但是使用Hamster无法正常输入，切换到系统自带输入法后可正常输入。

https://user-images.githubusercontent.com/30370926/236219263-667fa6db-b3ce-4400-907c-fbc52e1617f9.mov

**Comment by imfuxiao** [comment]
收到，感谢您的反馈。
