### ISSUE TITLE
[Feature Request]查阅部署及运行时日志

### ISSUE THREAD

**Issue by thelastlin** [imfuxiao/Hamster#204]
在上传所使用的配置方案后可能会发现输入时无法出词上屏，需要查看部署及运行时的日志以尝试定位问题。

Console.app的日志串流功能或许可使用，但似乎缺少对应的过滤标签来查找键盘所需的日志文件。

**Comment by imfuxiao** [comment]
感谢您的反馈，后续增加此特性。

**Comment by imfuxiao** [comment]
2.0.0 功能已内置了 RIME 引擎日志的记录功能。
