### ISSUE TITLE
关于微软双拼方案的「ing」问题

### ISSUE THREAD

**Issue by Domonlee** [imfuxiao/Hamster#205]
微软双拼的ing对应的是「;」，原生键盘的布局会多出一个分号，仓输入法目前没有提供这个功能，希望开发者可以增加一个选项，增加一个分号布局。

目前我尝试的两种曲线救国的方案：
1. 用下滑x键输入ing，体验不是很好，会中断打字节奏。
2. 讲空格右侧的句号改成分号，这又会损失句号键（顺带一提，能不能加上双击空格上屏句号）。

也感谢开发者，做出来这么好的软件，让iOS打字体验上升了不少。

**Comment by imfuxiao** [comment]
收到，感谢您的反馈与支持。

**Comment by Domonlee** [comment]
> > 微软双拼的ing对应的是「;」，原生键盘的布局会多出一个分号，仓输入法目前没有提供这个功能，希望开发者可以增加一个选项，增加一个分号布局。
> > 目前我尝试的两种曲线救国的方案：
> > 
> > 1. 用下滑x键输入ing，体验不是很好，会中断打字节奏。
> > 2. 讲空格右侧的句号改成分号，这又会损失句号键（顺带一提，能不能加上双击空格上屏句号）。
> > 
> > 也感谢开发者，做出来这么好的软件，让iOS打字体验上升了不少。
> 
> 空格左右两边不是有两个键位？不能用其中一个作为分号吗

这就是我所说的方案2，也是目前我采用的方案。只是这样句号键只能下滑输入。如果提供双击空格上屏句号，也算是一种折中的替代方案。

**Comment by imfuxiao** [comment]
1.6.11版本已上线『分号键』功能。

**Comment by fascal** [comment]
如果你在使用微软拼音，没法输入 -ing，前面 imfuxiao 所说的方法其实是：新的版本中，进入“键盘布局”，进入“中文26键”，手动勾选“启用分号按键”的开关。然后在键盘上点";"就能打上 -ing 了。
