### ISSUE TITLE
请问是否有支持注音的计划？

### ISSUE THREAD

**Issue by kanwakyuudai** [imfuxiao/Hamster#206]
实现了键盘布局可自定义之后，希望可以支持一下注音。

**Comment by imfuxiao** [comment]
感谢反馈，如果自定义键盘实现了，那么注音就可以通过自定义方式自己实现。

**Comment by groverlynn** [comment]
> 感谢反馈，如果自定义键盘实现了，那么注音就可以通过自定义方式自己实现。

注音需要四排按鍵。如果你的自定義鍵盤仍舊只有三排按鍵的話，依然無法使用注音。反之，如果有第四排數字鍵，那麼rime的注音方案可以直接使用

**Comment by imfuxiao** [comment]
2.0.0 已支持自定义键盘，并已内置了注音的自定义键盘。注意，需要搭配注音的输入方案一起使用。
