### ISSUE TITLE
无法同步至iCloud，提示无权限

### ISSUE THREAD

**Issue by Jmdayou** [imfuxiao/Hamster#208]
如图，tf版，点击拷贝到iCloud提示没有权限，完全访问、iCloud储存也开了。
<img width="414" alt="image" src="https://github.com/imfuxiao/Hamster/assets/130811752/61f71019-6244-4ea5-aa01-68fc7b6ef903">

**Comment by imfuxiao** [comment]
收到，感谢反馈。谢谢。

**Comment by Jmdayou** [comment]
> 收到，感谢反馈。谢谢。

大佬，我的手机XR，IOS 16.5 ,软件版本TF 1.70（48）还是一样没法用icloud同步，提示没有权限（完全访问和icloud都开了）。是还没有修复吗？

**Comment by imfuxiao** [comment]
> 收到，感谢反馈。谢谢。
> 
> 大佬，我的手机XR，IOS 16.5 ,软件版本TF 1.70（48）还是一样没法用icloud同步，提示没有权限（完全访问和icloud都开了）。是还没有修复吗？

不应该，群里之前也有位伙伴出现这种情况，最后是重新登录iCloud后正常了，您看能否这样测试下。

**Comment by Jmdayou** [comment]
> > 收到，感谢反馈。谢谢。
> > 大佬，我的手机XR，IOS 16.5 ,软件版本TF 1.70（48）还是一样没法用icloud同步，提示没有权限（完全访问和icloud都开了）。是还没有修复吗？
> 
> 不应该，群里之前也有位伙伴出现这种情况，最后是重新登录iCloud后正常了，您看能否这样测试下。

谢谢，可以了，需要退出APPLE ID 然后重新登录
