### ISSUE TITLE
期待加入拼音九宫格输入法

### ISSUE THREAD

**Issue by ryanblog** [imfuxiao/Hamster#209]
用惯了拼音九宫格，全键盘戳起来就十分不适应。另外，如果支持iCloud 同步词库就更好啦，毕竟用了很久的鼠须管。
请大神酌情考虑哈。

**Comment by zhaohai1024** [comment]
好久都不更新

**Comment by imfuxiao** [comment]
TF版本测试修改中，因本次功能调整比较大，所时间久了些，抱歉。

**Comment by noisay** [comment]
非常需要拼音九宫格，作者加油呀！appstore已经五星好评了

**Comment by LadyDeDe** [comment]
我也需要拼音九宫格，强烈支持作者，蹲一下九宫格功能！

**Comment by imfuxiao** [comment]
收到 加速中

**Comment by jiutian998** [comment]
期待九宫格啊~

**Comment by HeminWon** [comment]
期待九宫格

**Comment by zhaohai1024** [comment]
怎么那么就还没有九宫格，我真的是服了

**Comment by Jonney** [comment]
强烈需要九宫格

**Comment by Leslan** [comment]
等待九宫格中

**Comment by imfuxiao** [comment]
2.0.0版本已内置中文九宫格布局，需要搭配相关的输入方案使用，目前雾凇输入方案已支持，推荐使用。
