### ISSUE TITLE
输入法可不可以直接调用苹果表情键盘和英语输入

### ISSUE THREAD

**Issue by keaidu** [imfuxiao/Hamster#210]
想问一下可不可以让输入法直接调用苹果的表情键盘。还有就是关于英语输入这个，既然可以做到直接用拼音输入单词，那能不能让英文输入模式也可以直接输入单词？类似苹果自带的英语输入法那种。

**Comment by imfuxiao** [comment]
您好，这个是不可以的。建议使用rime的英文输入方案，或支持中文英文混合输入的雾淞也可以。
