### ISSUE TITLE
请问仓输入法的高阶设置在哪呀，app里没找到

### ISSUE THREAD

**Issue by WoChen5770** [imfuxiao/Hamster#212]
想设置iCloud备份，感谢作者开发这款应用

**Comment by imfuxiao** [comment]
感谢支持，TF版本iCloud功能测试中，一切如果顺利，本周发布。

**Comment by WoChen5770** [comment]
> 感谢支持，TF版本iCloud功能测试中，一切如果顺利，本周发布。
> 
> 高阶设置在TF版本中，商店版本暂时没有。

现在tf还有名额吗，我想加入

**Comment by imfuxiao** [comment]
> > 感谢支持，TF版本iCloud功能测试中，一切如果顺利，本周发布。
> > 高阶设置在TF版本中，商店版本暂时没有。
> 
> 现在tf还有名额吗，我想加入

https://testflight.apple.com/join/6AkRfQYZ

**Comment by WoChen5770** [comment]
> > > 感谢支持，TF版本iCloud功能测试中，一切如果顺利，本周发布。
> > > 高阶设置在TF版本中，商店版本暂时没有。
> > 
> > 
> > 现在tf还有名额吗，我想加入
> 
> https://testflight.apple.com/join/6AkRfQYZ

加入了，多谢
