### ISSUE TITLE
最新tf版1.7.0.39，设置同步路径为iCloud上其他目录闪退

### ISSUE THREAD

**Issue by WoChen5770** [imfuxiao/Hamster#213]
wiki上的路径示例是iCloud下的Hamster/Rime目录下
`sync_dir: "/private/var/mobile/Library/Mobile Documents/iCloud~dev~fuxiao~app~hamsterapp/Documents/RIME/Rime/sync"`，
但是我想配置其他目录，比如SoftwareDataSync/Rime下，点击RIME同步，app会闪退
`sync_dir: "/private/var/mobile/Library/Mobile Documents/com~apple~CloudDocs/SoftwareDataSync/Rime/sync"`

**Comment by imfuxiao** [comment]
您好，因iOS系统限制，不能写入别的iCloud路径下，只能在自己应用的iCloud容器路径下。

**Comment by WoChen5770** [comment]
> > 您好，因iOS系统限制，不能写入别的iCloud路径下，只能在自己应用的iCloud容器路径下。
> 
> 好的，那我用示例目录了。 刚刚发现有个问题，在同步目录下有两个installation，一个命名iphone，一个mac。 各自点击Rime同步，mac能同步到来自iPhone的词库，而在iPhone上点击Rime同步，却同步不到来自mac文件夹里的词库

经测试，已经修复。（当天发现作者就修复了，赞）
