### ISSUE TITLE
上划“” 「」等符号，建议默认光标在符号内

### ISSUE THREAD

**Issue by Ricadre** [imfuxiao/Hamster#215]
如题，可以提升不少输入效率，另外符号键盘的按键希望可以居中显示，比如图中的，！。（有点强迫症）
![image](https://github.com/imfuxiao/Hamster/assets/3013056/80250cd6-e4f9-48f6-b558-f6aa833a599a)

**Comment by imfuxiao** [comment]
1.6.11版本已上线符号设置功能，可在光标居中中设置。
