### ISSUE TITLE
最近不更新了吗？

### ISSUE THREAD

**Issue by SeongBrave** [imfuxiao/Hamster#216]
之后的的代码是不是不开源了呢🤣

**Comment by Ricadre** [comment]
tf每天都在更新，正式版会慢点

**Comment by imfuxiao** [comment]
持续开源，不会变的，目前功能在TF测试中，上星期测试未通过，延期本周。

我个人的代码是每次发布商店版本的时候，同步到Github中，与商店版本保持一致。
