### ISSUE TITLE
界面語言

### ISSUE THREAD

**Issue by groverlynn** [imfuxiao/Hamster#218]
AppStore和系統設置中均宣稱有簡中、繁中、港中、英文四種界面語言，且英文為默認語言，然而實際上只有簡中一種界面語言

**Comment by imfuxiao** [comment]
抱歉，UI确实没有做国际化处理，后面会加上。

**Comment by groverlynn** [comment]
那麼目前應該把其他三種語言標籤去掉，以免誤導

**Comment by zizicici** [comment]
这个其实另外两种繁体中文可以使用 opencc 进行处理。
