### ISSUE TITLE
关于installation.yaml的sync_dir

### ISSUE THREAD

**Issue by cactusnix** [imfuxiao/Hamster#220]
我写错了sync_dir的目录,但是点击同步并没有报错,是否会把对应的结果写入到错误的目录呢?
目录大致如下:
/Users/cactusnix/Library/Mobile Documents/iCloud~dev~fuxiao~app~hamsterapp/Documents/RimeSync/

**Comment by cactusnix** [comment]
> > /private/var/mobile/Library/Mobile Documents/iCloud~dev~fuxiao~app~hamsterapp/Documents
> 
> ---
> 
> 上面这一段不能修改。
> 
> 于是，你可以是这样：
> 
> > /private/var/mobile/Library/Mobile Documents/iCloud~dev~fuxiao~app~hamsterapp/Documents/RimeSync/
> 
> 
> 
> ---
> 
> 我看你写的这个目录大致意思是想直接在macOS端同步到iOS端的目录里面去，是吧？

我是不小心将macOS的installation里面的sync_dir复制到了iOS端了，然后点击同步显示成功了，不清楚是否将对应数据已经同步至错误的目录了，虽然iOS似乎不是哪个目录都能写入，但显示成功了，所以不是很确定。

**Comment by tamhaywoo** [comment]
我昨天也在处理这个事情，你可以通过iCloud里面的文件更新时间来确认是否有效。目前我还没有实现macOS端与iOS端共用同一个目录。我准备每周手动将iCloud里面的macOS端Rime同步文件复制替换掉iOS端Hamster里面的同步文件。

**Comment by cactusnix** [comment]
> ster里面的同步文件。

其实分开同步是可以的 我现在的问题是不清楚是否有把数据同步至了错误的目录里面了 我看源码里面是直接调用的librimekit的RimeSyncUserData的

**Comment by tamhaywoo** [comment]
应该将文件同步到错误的目录去，毕竟iOS端的目录结构不同，且不能同步到本App之外的目录。

**Comment by cactusnix** [comment]
@imfuxiao 作者可以帮忙解答一下吗, 看源码不是特别清楚,只能理解没有捕获到异常直接成功了,所以担心是否将错误的数据已经写入到了一个错误的目录.

**Comment by cactusnix** [comment]
> 应该不会将文件同步到错误的目录去，毕竟iOS端的目录结构不同，且不能同步到本App之外的目录。

是的,理论上是不会的,但源码捕获异常那块应该是没有捕获到异常的.

**Comment by imfuxiao** [comment]
1. 错误的sync地址：这个不会写入成功的，iOS的沙盒机制有保护的，根据您反馈的路径，对这个路径是没有写入权限的。
2. 目前确实没有对sync配置路径做校验，后面应该会加个同步地址参数校验，看是否有写入权限。
3. 之前看到过异常路径的同步会引发app的crash，不清楚现在为什么没法发生，这个我下来在看看。
4. 异常捕获，如您所见，异常捕获是有添加，但是底层api貌似并没有异常，有点费解。
5. sync的api，可以返回bool值，但目前api这里写错了，没有获取这个返回变量，我后面加一下。

感谢各位的反馈。
