### ISSUE TITLE
嵌入模式下，在未上屏编码区点击输入栏，异常显示

### ISSUE THREAD

**Issue by imfuxiao** [imfuxiao/Hamster#222]
如题，在嵌入模式状态下，存在未上屏编码时，这时点击输入栏，编码区会被清空，但键盘状态中并未清空，这时在输入任何键，会发现已被清空的编码区，除了包含刚输入的键值外，还包含之前已被清空的键值。

**Comment by Nikkiiw** [comment]
😄😄对的 目前还没有解决呢

**Comment by imfuxiao** [comment]
> 😄😄对的 目前还没有解决呢

暂时无解，iOS 系统没有提供相关接口。
