### ISSUE TITLE
[BUG] 南京官话字体有缺失

### ISSUE THREAD

**Issue by peterzhu1992** [imfuxiao/Hamster#223]
自行导入南京官话：
https://github.com/uliloewi/lang2jin1

在另一个软件iRime貌似是没问题的，但是在Hamster上找不到相应的字体，比如langjin，这个南字就不显示。
![image](https://github.com/imfuxiao/Hamster/assets/35495810/bcaa8faf-1143-4ab4-ab33-a7df83c33355)

很喜欢这个软件，但是目前这个问题很久也没找到解决办法。
而且貌似还不是输入法的问题，因为在iRime是能用，但是在Hamster就缺失。

谢谢。

**Comment by imfuxiao** [comment]
新版本已支持字体自定义设置。

**Comment by peterzhu1992** [comment]
![image](https://github.com/imfuxiao/Hamster/assets/35495810/26e9a5dd-c307-4730-9730-2eb834c6d351)

感谢，亲测有效！
