### ISSUE TITLE
请问，升级以后中文输入法没有了

### ISSUE THREAD

**Issue by tarkky** [imfuxiao/Hamster#225]
我女儿的iphone升级到最新的1.6.8后，中文输入法没有了，输入方案那里是空白的。我记得当初我有一次升级以后默认的输入方案里面是空的。我记得好像关闭鼠须管后，默认的四叶草输入法才出来。我让我女儿关了鼠须管后，输入方案里面还是空白的，请问如何恢复默认的四叶草输入方案？谢谢

**Comment by imfuxiao** [comment]
抱歉，给您造成不便了，你可以在屏幕下方， 点击Tab中的其他设置，然后选择“RIME”，进入RIME页面后，点击重置。看看是否可以恢复。

**Comment by tarkky** [comment]
> 抱歉，给您造成不便了，你可以在屏幕下方， 点击Tab中的其他设置，然后选择“RIME”，进入RIME页面后，点击重置。看看是否可以恢复。
您没有给我们造成任何不便，您这是免费的，已经提供很多便利了，我只是反馈使用中出现的问题，以便您更好的发现和解决。
我正在尝试您提供的方法，晚些时候过来更新结果。
另外，还是希望能够把捐助链接放出来，我愿意捐助表达一下心意。谢谢。

**Comment by tarkky** [comment]
重置以后，输入方案有了。谢谢。

**Comment by imfuxiao** [comment]
谢谢您的肯定，现在软件还不完善，等完善点我在贴码。
