### ISSUE TITLE
iPad小键盘模式出现布局排版问题 不能切换输入法

### ISSUE THREAD

**Issue by fengyupiaoyao75** [imfuxiao/Hamster#227]
![IMG_0557](https://github.com/imfuxiao/Hamster/assets/82947109/b92701d0-fd9e-4303-b2df-9f42b924c6cc)
![IMG_0556](https://github.com/imfuxiao/Hamster/assets/82947109/1d69003d-b474-4235-a24a-72533a0cb30d)

**Comment by imfuxiao** [comment]
收到，感谢反馈。
