### ISSUE TITLE
怎么调整字体大小

### ISSUE THREAD

**Issue by net2023** [imfuxiao/Hamster#230]
麻烦我#问下这个大小怎么调整 谢谢
![51EA8FAC-3ECE-4C68-9ECB-215D3D00B148](https://github.com/imfuxiao/Hamster/assets/125739213/5f67e0c0-b804-4fb0-868f-ac1fe648cbe0)

**Comment by imfuxiao** [comment]
抱歉，目前候选栏编码区字体大小不能调整。

**Comment by net2023** [comment]
> 抱歉，目前候选栏编码区字体大小不能调整。

感谢回复，希望以后可以支持修改！ 刚有人说我是不是眼瞎了！找到锅侠了 哈哈哈

**Comment by imfuxiao** [comment]
嗯嗯，加，一定加。

**Comment by imfuxiao** [comment]
2.0.0 版本已支持调整候选栏字体及高度选项。
