### ISSUE TITLE
多台移动设备可以互相同步用户日常使用而生成的词库吗？

### ISSUE THREAD

**Issue by tamhaywoo** [imfuxiao/Hamster#231]
## 情况描述：
- 在1台iPad和2台iPhone上使用相同的`installation.yaml`文件
- 设置同步目录为`sync_dir: "/private/var/mobile/Library/Mobile Documents/iCloud~dev~fuxiao~app~hamsterapp/Documents/"`
- 在各个设备都点击`RIME同步`按钮
- 再回到iCloud的`Hamster`文件夹，能看到目录下生成了`user.yaml`、`user 2.yaml`、`user 3.yaml`以及1个`rime_ice.userdb.txt`和1个`rime_ice.userdb 2.txt`
- 且`rime_ice.userdb.txt`和`rime_ice.userdb 2.txt`文件的内容不完全相同

## 疑惑
- 在3台macOS设备上使用相同的`installation.yaml`文件在同步之后并没有生成额外的`user.yaml`和`rime_ice.userdb.txt`，为什么仓输入法在同步的时候会有不一样的情况？
- 是否是因为同步机制不一样，只能单向同步？

**Comment by imfuxiao** [comment]
您好：

## 首先 MacOS 的 iCloud 路径与 iOS 路径是不一样的。

iOS 仓的固定路径为前缀为 `/private/var/mobile/Library/Mobile Documents/iCloud~dev~fuxiao~app~hamsterapp/Documents`

而 MacOS 没有固定前缀，如我的系统为`/Users/morse/Library/Mobile Documents/iCloud~dev~fuxiao~app~hamsterapp/Documents`，其中`morse`为系统用户名称。

## 其次不同设备同步的文件夹是不同的，而非同一个文件夹

[雾淞配置教程](https://dvel.me/posts/rime-ice/#%E5%A4%9A%E8%AE%BE%E5%A4%87%E5%90%8C%E6%AD%A5)

我本地测试，用6s和x生成不同的文件夹，`installation_id: "hamster_6s"`，`installation_id: "hamster_x"`

<img width="715" alt="image" src="https://github.com/imfuxiao/Hamster/assets/6482586/95d12699-4207-42ea-a60b-a9bf3f17c1c3">

## 文件名前面相同，后面却带不同的数字

比如 `user.yaml`，`user 2.yaml` 这个是iCloud同步时文件冲突造成的。

**Comment by tamhaywoo** [comment]
谢谢答复，关于同步路径我是了解了的。嗯，我主要想表达的困惑就是：在这些情况下，是否各个设备实现了相互之间的同步。

**Comment by imfuxiao** [comment]
你可以给我一个测试用例，我测试下。

**Comment by tamhaywoo** [comment]
> 你可以给我一个测试用例，我测试下。

我刚才换了一种思路进行验证：
---
- 把2台设备分别同步到2个文件夹中，分别命名为`14`和`x`
- 然后将设备`x`同步文件夹内的`rime_ice.userdb.txt`文件复制到设备`14`的同步文件夹
- 并修改`rime_ice.userdb.txt`文件第6行，将`#@/user_id`从`x`修改为`14`
- 然后在设备`14`上点击仓输入法的RIME同步
- iCloud的`14`目录下出现了`rime_ice.userdb 2.txt`，且文件小于复制进来的`rime_ice.userdb.txt`，打开这两个文件后发现`rime_ice.userdb 2.txt`文件为7826行、`rime_ice.userdb.txt`文件为7854行，也就是说设备`14`在同步的时候只做了保存的动作。

**Comment by imfuxiao** [comment]
您好，您提供的测试用例不是rime同步原理的的正常测试方式。且后缀2的文件是iCloud同步冲突时生成的文件，非rime同步生成文件。

**Comment by imfuxiao** [comment]
我已内置星猫键道方案作为测试用例，未开启仓输入法的“iCloud同步”开关，两台设备x和6s。

1. 修改同步配置`installation.yaml`中分别为:
```yaml
installation_id: "hamster_6s"
sync_dir: "/private/var/mobile/Library/Mobile Documents/iCloud~dev~fuxiao~app~hamsterapp/Documents/sync"
```
```yaml
installation_id: "hamster_x"
sync_dir: "/private/var/mobile/Library/Mobile Documents/iCloud~dev~fuxiao~app~hamsterapp/Documents/sync"
```

2.将星猫键道词库格式改为`userdb`类型，文件为`xmjd6.schema.yaml` 308~310行

```yaml
# ↓ 用户词典格式，tabledb（文本） 或 userdb （二进制）。
  #db_class: tabledb
  db_class: userdb
```
3. 两台设备修改完毕后点击重新部署。
4. x设备输入自造词，输入`a`进入自造词模式，键入`poof`，空格，生成自造词`凭空这`
5. 6s设备输入自造词，输入`a`进入自造词模式，键入`foop`，空格，生成自造词`放学平`
6. 两台设备分别点击`拷贝词库文件至应用`，然后在点击`RIME 同步`
7. 查看iCloud，可以看到两个设备各自生成的同步词库文件`xmjd6_user.userdb.txt`，文件内容为各自生成的自造词。
8. 在两台设备上其中任意一台，使用内置应用Files文件打开sync目录，使用Files强制下载另一台的词库文件，下载完毕后，在app中再次点击“RIME同步”，发现当前设备的`xmjd6_user.userdb.txt`文件内容增加了对方设备的自造词内容。

**Comment by tamhaywoo** [comment]
明白了。谢谢你费时解释和验证。

**Comment by g6ai** [comment]
使用不同installation id，在同一个sync文件夹里生成以id为名的不同文件夹。Rime在同步时会比较几个文件夹的内容，并对本installation id的词库进行增量备份。参见https://github.com/rime/home/wiki/UserGuide#同步用戶資料

**Comment by Walt-Zh** [comment]
感谢您为我们带来了这么好的应用，而且居然是免费的！非常感谢！请开一个捐赠通道，起码让我请你喝杯咖啡！@imfuxiao

使用iPhone上使用仓输入法和Mac的鼠须管同步用户词库没有成功，具体情况如下：

1、installation.yaml文件：
Mac鼠须管：
installation_id: "Mac"
sync_dir: /Users/walt/Library/Mobile Documents/iCloud~dev~fuxiao~app~hamsterapp/Documents/sync
iPhone仓输入法：
installation_id: iPhone
sync_dir: "/private/var/mobile/Library/Mobile Documents/iCloud~dev~fuxiao~app~hamsterapp/Documents/sync"

2、我使用的是小鹤音形，分别编辑Mac端和iPhone端flypy.schema.yaml：
  dictionary: ""
  user_dict: flypy_user
 #db_class: stabledb
  db_class: userdb

3、鼠须管点击“同步用户数据”，仓输入法点击“RIME"同步，同步文件夹生成两个文件夹：
![IMG_3789](https://github.com/imfuxiao/Hamster/assets/117001223/42e40be7-2e50-4924-9a4b-2b8def983b5a)
![IMG_3792](https://github.com/imfuxiao/Hamster/assets/117001223/28fd520b-7643-410e-a67f-577079161709)
![IMG_3793](https://github.com/imfuxiao/Hamster/assets/117001223/f6cbf52e-20d4-4e90-8e04-c58318c6d9bb)

4、Mac鼠须管“用户设定”，打开“flypy_user.txt”，输入自造词：
“哇哈哈        whha”

5、再次鼠须管点击“同步用户数据”，仓输入法点击“RIME"同步，但仓输入法中未能同步到自造词


仓输入法作为Rime家族的应用，用户数据同步非常重要，请帮我看看问题出在那里，再次感谢！

**Comment by tamhaywoo** [comment]
> 

# 你留意下
Mac端如果不点同步，那么你在Mac端修改的自定义短语词库只是在你的电脑本地，而不是在iCloud，正确的做法是：
- 在Mac端修改你的`flypy_user.txt`
- 在菜单点击`同步用户数据`
- 在iPhone上点击`文件`app，找到`iCloud云盘`，进入`Hamster`目录
- 查看iCloud云盘上对应文件夹里面的文件更新日期是不是最近的时间，如果是，则表示云端有新的文件
- 在iPhone上打开仓输入法，点击同步，应该就已经更新了。

---
如果上面的步骤都做了，还是没有同步。你需要看看Mac端的配置文件与iPhone端的配置文件是不是一样的。最稳妥的做法是：
- 直接把Mac端除`build`文件夹之外的文件打个包，放在iCloud云盘
- 在iPhone端导入方案
- 修改iPhone端的`installation.yaml`文件，把`installation_id`修改掉
- 同步用户数据

**Comment by Walt-Zh** [comment]
> # 你留意下
> Mac端如果不点同步，那么你在Mac端修改的自定义短语词库只是在你的电脑本地，而不是在iCloud，正确的做法是：
> 
> * 在Mac端修改你的`flypy_user.txt`
> * 在菜单点击`同步用户数据`
> * 在iPhone上点击`文件`app，找到`iCloud云盘`，进入`Hamster`目录
> * 查看iCloud云盘上对应文件夹里面的文件更新日期是不是最近的时间，如果是，则表示云端有新的文件
> * 在iPhone上打开仓输入法，点击同步，应该就已经更新了。
> 
> 如果上面的步骤都做了，还是没有同步。你需要看看Mac端的配置文件与iPhone端的配置文件是不是一样的。最稳妥的做法是：
> 
> * 直接把Mac端除`build`文件夹之外的文件打个包，放在iCloud云盘
> * 在iPhone端导入方案
> * 修改iPhone端的`installation.yaml`文件，把`installation_id`修改掉
> * 同步用户数据

1、Mac端数据可以同步到iCloud，日期为最新;
2、将Mac端数据打包，iPhone成功导入方案;
3、修改了iPhone端的installation.yaml文件，把installation_id改成了新的，并改了同步地址（Mac的iCloud同步地址和iPhone不同）;
4、经测试，iPhone端的数据也可同步到iCloud;
5、在Mac端新建了一个自造词，鼠须管点击“同步用户数据”，仓输入法点击“RIME同步“，但仓输入法中依然未能同步到该自造词。

**Comment by Walt-Zh** [comment]
> # 你留意下
> Mac端如果不点同步，那么你在Mac端修改的自定义短语词库只是在你的电脑本地，而不是在iCloud，正确的做法是：
> 
> * 在Mac端修改你的`flypy_user.txt`
> * 在菜单点击`同步用户数据`
> * 在iPhone上点击`文件`app，找到`iCloud云盘`，进入`Hamster`目录
> * 查看iCloud云盘上对应文件夹里面的文件更新日期是不是最近的时间，如果是，则表示云端有新的文件
> * 在iPhone上打开仓输入法，点击同步，应该就已经更新了。
> 
> 如果上面的步骤都做了，还是没有同步。你需要看看Mac端的配置文件与iPhone端的配置文件是不是一样的。最稳妥的做法是：
> 
> * 直接把Mac端除`build`文件夹之外的文件打个包，放在iCloud云盘
> * 在iPhone端导入方案
> * 修改iPhone端的`installation.yaml`文件，把`installation_id`修改掉
> * 同步用户数据

“部署时覆盖键盘词库文件”这个功能是否要关掉？或者是其它功能设置不对？

**Comment by ShawLocke** [comment]
> 部署时覆盖键盘词库文件”这个功能是否要关

我实验下来是要关掉的。请看我自己的总结，如何在 Mac 和 iOS 中保持个人词典同步？

Mac <-> iOS 同步词库操作流程：
      1. Mac 上启用iCloud Drive，iOS 设备上启用 iCloud Drive，在允许使用 iCloud Drive 的 app 列表中 启用 Hamster（即保持 switcher 是 on 的状态）
      1. Mac: 将 “Squirrel程序目录中除了 build 外的文件（实验下来：包含 build 也可以，为了节省空间，不建议包含 build）“ 压缩，将压缩文件拷贝到 iCloud Drive 中（根目录即可）
      1. iOS 设备 -> Hamster app: “输入方案设置” / 右上角加号 / 导入方案 / 左上角回到或者中间切换到 iCloud Drive / 选择上一步中提到的压缩文件，会自动完导入并部署
      1. iOS 设备：打字验证你在 Mac 中的个人词典，输入`yxl`，看会不会出来 `原型链`（前提是 Mac 中已经养成了 `yxl` 对应为 `原型链`），**注意必须启用** allow Full Access: 设置 -> 通用 -> 键盘 -> keyboards -> Hamster -> 启用 Allow Full Access
      1. iOS 设备 -> Hamster app: 文件管理 -> 应用文件 -> Rime -> installation.yaml: 修改 installation_id 为 "phone", 修改 sync_dir 为 "/private/var/mobile/Library/Mobile Documents/iCloud~dev~fuxiao~app~hamsterapp/Documents/RIME/Rime/sync", 点击保存，回到app主界面, RIME -> 点击 RIME同步，查看iCloud Drive会发现出现了新目录 “Hamster / RIME / Rime / sync”
      1. Mac -> iCloud Drive: 获取 “Hamster / RIME / Rime / sync” 路径（右键 sync 目录，然后打开一个 terminal，然后输入 pwd），可以得到路径是 "/Users/edz/Library/Mobile Documents/iCloud~dev~fuxiao~app~hamsterapp/Documents/RIME/Rime/sync" (edz 是 Mac 用户名)，然后去 Squirrel 程序目录，找到 installation.yaml, 修改 sync_dir 为 前面的路径，保存，然后 sync user data
      1. iOS -> Mac: iOS 中 养成 `liudd` 对应为 `溜叮叮`，然后 点击 RIME同步，**注意必须关闭** 部署时覆盖键盘词库文件，在 Mac 中点击 sync user data，然后打字 `liudd`，看结果是不是 `溜叮叮`
      1. Mac -> iOS: Mac 中 养成 `doudd` 对应为 `逗叮叮`，然后 点击 sync user data，在 iOS 中点击 RIME同步，然后打字 `ddd`，看结果是不是 `逗叮叮`

**Comment by luochen1990** [comment]
请问 iOS 上其他的文件同步APP （比如 resilio sync 或 syncthing)  的路径是怎么拼出来的？

**Comment by ShawLocke** [comment]
> > # 你留意下
> > Mac端如果不点同步，那么你在Mac端修改的自定义短语词库只是在你的电脑本地，而不是在iCloud，正确的做法是：
> > 
> > * 在Mac端修改你的`flypy_user.txt`
> > * 在菜单点击`同步用户数据`
> > * 在iPhone上点击`文件`app，找到`iCloud云盘`，进入`Hamster`目录
> > * 查看iCloud云盘上对应文件夹里面的文件更新日期是不是最近的时间，如果是，则表示云端有新的文件
> > * 在iPhone上打开仓输入法，点击同步，应该就已经更新了。
> > 
> > 如果上面的步骤都做了，还是没有同步。你需要看看Mac端的配置文件与iPhone端的配置文件是不是一样的。最稳妥的做法是：
> > 
> > * 直接把Mac端除`build`文件夹之外的文件打个包，放在iCloud云盘
> > * 在iPhone端导入方案
> > * 修改iPhone端的`installation.yaml`文件，把`installation_id`修改掉
> > * 同步用户数据
> 
> “部署时覆盖键盘词库文件”这个功能是否要关掉？或者是其它功能设置不对？

可以参考我评论试试

**Comment by h0cheung** [comment]
可以使用 iCloud 以外的云盘，或者 syncthing 等进行同步吗

**Comment by imfuxiao** [comment]
抱歉，暂不支持其他网盘同步。
