### ISSUE TITLE
中文模式下英文标点符号异常

### ISSUE THREAD

**Issue by mfanlei** [imfuxiao/Hamster#233]
在中文模式下，n和m两个键上划的“,”及“.”，以及符号键盘的“.”，都会输出中文的“，”和“。”，但是英文模式下，中英文标点符号都可以正常输出。

**Comment by imfuxiao** [comment]
这个也不算是bug，中文模式下符号是经过rime引擎处理的，您的输入方案可能对符号做了映射，导致英文符号转了中文。
