### ISSUE TITLE
[Bug] switches 中的 ascii_mode 开关没有与"中英切换键"对应

### ISSUE THREAD

**Issue by gugu33** [imfuxiao/Hamster#234]
见新版1.6.10已经支持全键盘的单手模式和方案选单开关，欣喜之，立马更新，使用中发现一些小问题：
因在pc端我习惯将输入法设为默认键盘，并且输入法的默认状态是英文。
所以我用到了switches中的 ascii_mode 开关，来记忆输入法键盘初始状态为英文，
两处配置如下：
```yaml
// default.yaml
...
switcher:
...
  save_options:  
    - ascii_mode  # 此处设定记住该开关的状态
    ...
...

// rime_ice.yaml
...
switches:
  - name: ascii_mode
    states: [ 中, A ]
   # reset: 0   # 此处注释掉rest 以支持开关的记忆
  ...
...
```

同样将仓输入法设为置顶，并尝试能否默认英文状态。
首先两处配置文件同上
其次我通过在按键滑动手势中配置了某字母的⬇️为 #RimeSwitcher ，来打开方案选单，打开"中->A"切为"A-> 中"。 
其结果是：无论现在中/英切换键是中还是英，打字都是英文状态，切换键等于失效了，无法切回中文，只能再次将开关置回"中->A"，此处可能是个bug。
该配置的记忆功能执行正常！
选单的其他切换开关执行正常！

我预期是：像pc端一样，该开关控制的是键盘启动后的初始状态，状态应能反映到键盘的中/英切换键上，但不会影响中/英切换键切换。

其他优化小建议：
新上的单手键盘好评！！不过还不够紧凑，参照原生可以再靠紧点，原生输入法的全键盘单手状态下拇指更容易够到最远的按键。

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by imfuxiao** [comment]
感谢反馈，RIME的switcher功能目前还是实验性质的，是存在bug。后续会着手修复。

**Comment by imfuxiao** [comment]
1.6.11已优化此功能。

**Comment by gugu33** [comment]
v1.6.12(1)
报告已经可用，但仍有一个小问题：

在当前键盘已呼出情况下，尝试来回切换 `中->A`和`A->中`，发现 功能实现和UI 显示都正常。

在键盘呼出情况下，切换到 `中->A`，此时键盘UI的`中/英`键为`英`，空格键显示`EN`。
此时关闭键盘，再呼出键盘，键盘UI的`中/英`键为`中`，空格键显示`输入法名`， 但实际打字发现是英文键盘状态！此时点击一次`中/英`键，其切换为`英`，打字也是英文状态，再按一次`中/英`键，其切换为`中`，此时打字为中文输入法状态。
结论： 再呼出键盘时，其功能状态与预期相符，但其UI显示不符。导致当这时需要切换到中文输入法时需要按**两次**`中/英`键
