### ISSUE TITLE
[Feature] 关于hamster.yaml的支持

### ISSUE THREAD

**Issue by cactusnix** [imfuxiao/Hamster#235]
### 背景

期望能够控制键盘某个按键的颜色、背景色或者自定义文本内容(举例a字母的位置展示成其他符号等)，这些都和桌面端的逻辑不太一致的定义。

### 期望

目前使用Rime输入法的基本都是多设备同步的，不同设备的操作系统对应着不同的软件，它们都有各自特定的配置文件，比如weasel.yaml、squirrel.yaml等。所以期望有个Hamster.yaml文件主要负责移动端特定的一些配置。

简单来说就是把Hamster特定的配置使用hamster.yaml文件配置，补充现有UI的方案，而不是和squirrel.yaml是同样的作用。

**Comment by imfuxiao** [comment]
已有相关设计，只不过目前只有颜色方案可以配置在Hamster.yaml中，其他的配置还是单独的文件。后面可以加上此功能。

**Comment by cactusnix** [comment]
> 已有相关设计，只不过目前只有颜色方案可以配置在Hamster.yaml中，其他的配置还是单独的文件。后面可以加上此功能。

好的🫰
