### ISSUE TITLE
123页面选择符号或者数字后无法自动跳回ABC页面

### ISSUE THREAD

**Issue by xy464193** [imfuxiao/Hamster#236]
在打字后，点击左下角的“123”选择符号或者数字后，无法返回ABC页面，需要手动ABC点击。
ios自带可以，习惯了这个操作。

**Comment by imfuxiao** [comment]
嗯嗯，感谢反馈，这个会在下个版本优化。

**Comment by imfuxiao** [comment]
1.6.11版本以上线符号设置功能，可在返回主键盘符号列表中添加/修改/删除自己想要点击后返回主键盘的符号。
