### ISSUE TITLE
按键高度在不同机型不统一

### ISSUE THREAD

**Issue by Jmdayou** [imfuxiao/Hamster#237]
目前好像在不同的设备上键盘按键的高度不是统一的，部分机型是和系统按键一致的，一些机型又偏短一些。
猜测代码可能是写了绝对高度，而不是根据分辩率调整的百分比形式？
希望可以调整下，让不同分辨率的机型UI体验一致。

再次感谢大佬的辛苦开发！

**Comment by imfuxiao** [comment]
感谢反馈，最近在开发新功能，抽空我看下。
