### ISSUE TITLE
无法在App资源库使用本输入法

### ISSUE THREAD

**Issue by tamhaywoo** [imfuxiao/Hamster#238]
如题，在iPhone 14 pro max的App资源库顶部的搜索栏中无法使用本输入法。
---
机型：iPhone 14 Pro Max
系统：iOS 16.5

![image](https://s1.ax1x.com/2023/05/26/p9bjusU.jpg)

**Comment by tamhaywoo** [comment]
补充了图片

**Comment by imfuxiao** [comment]
收到

**Comment by snylonue** [comment]
same issue

**Comment by tamhaywoo** [comment]
重新部署和重启手机可以了
