### ISSUE TITLE
英文输入无法自动识别 / UI问题

### ISSUE THREAD

**Issue by pointerto** [imfuxiao/Hamster#239]
感谢您的开发工作！有两个小问题想向您反馈一下：

1. 如图使用墨墨背单词APP时，每输入完成、APP跳转到下一个单词，都需要手动将输入法切换为英文，否则会自动变为中文模式

2. UI上有个小问题，空格键能否隐去输入方案名称？如图“虎码官方词库”，总感觉有点碍眼，我记得刚发布时好像就不显示。
![微信图片_20230526162821](https://github.com/imfuxiao/Hamster/assets/45778522/1cb2c194-9551-4dc0-bb12-7bebfe0e1532)

**Comment by imfuxiao** [comment]
感谢反馈，

**Comment by pointerto** [comment]
1. 我在使用搜狗输入法的时候倒是可以在进入记单词app后自动切换为英文UI，并且不随着单词文本的切换跳转回中文，不知道它的解决方案是什么
2. 关于空格键的显示方案名称的问题，期待改进

**Comment by Jmdayou** [comment]
建议默认：中文显示成「空格」，英文建议显示成「 Space 」，与系统原生一致
也可自定义（显示方案名称），可做功能开关（因为有些用户总欢显示在自定义的文本）

**Comment by imfuxiao** [comment]
1.「仓」2.0 版本空格已支持多种状态显示自定义的功能
2. 关于中英状态的问题，可以参考[「简繁状态保持说明」](https://ihsiao.com/apps/hamster/docs/Questions.html#%E5%A6%82%E4%BD%95%E6%B0%B8%E4%B9%85%E4%BF%9D%E6%8C%81%E7%AE%80%E7%B9%81%E7%8A%B6%E6%80%81%EF%BC%8C%E7%9B%B4%E5%88%B0%E6%89%8B%E5%8A%A8%E5%88%87%E6%8D%A2%E7%AE%80%E7%B9%81%E7%8A%B6%E6%80%81)
