### ISSUE TITLE
键盘添加符号功能

### ISSUE THREAD

**Issue by imfuxiao** [imfuxiao/Hamster#24]
在键盘输入的时候, 可以有一个符号功能. 提供以下符号输入
* emoji
* 数学
* 英文符号
* 中文符号
* 列表符号
* 等等

**Comment by wzxmer** [comment]
说说一点想法，总得来说，就是缺少了对键盘整体UI的自定义，无论是候选的编码嵌入方式，候选栏的高度自由调整，
中英的切换也好，缺少的是像irime那样，能够对布局高度自定义的操作，要想方便大众，就得增加UI布局的统一设置页面了。相对，工作量就大了，是否可以考虑下先出一个通过自行修改配置文件的方式来自定义键盘的整体布局呢，类似irime，而在软件里增设统一的设置页面后续再增设？我们很多人，现状就差一个UI自定义，就能当作主用输入法软件了，所以比较期待

**Comment by imfuxiao** [comment]
> 说说一点想法，总得来说，就是缺少了对键盘整体UI的自定义，无论是候选的编码嵌入方式，候选栏的高度自由调整， 中英的切换也好，缺少的是像irime那样，能够对布局高度自定义的操作，要想方便大众，就得增加UI布局的统一设置页面了。相对，工作量就大了，是否可以考虑下先出一个通过自行修改配置文件的方式来自定义键盘的整体布局呢，类似irime，而在软件里增设统一的设置页面后续再增设？我们很多人，现状就差一个UI自定义，就能当作主用输入法软件了，所以比较期待

很赞的想法~之前也有用户提过这样的需求, 但是正如你所说, 一个完全自定义键盘布局UI的开发工作量会多一些.

我是这样想的, 完全自定义适合深度动手的用户, 大部分用户都是开箱即用, 太复杂的配置可能会劝退这些用户.  所以我想先做其他功能的开发. 至于高度可定制的键盘UI配置, 我想优先级放低一些.

**Comment by wzxmer** [comment]
是的。除开目前已经增加的几个UI的调整，希望能加上键盘的行距，列距的调整，如此一来，在没有完全自定义键盘布局UI配置前，可以有一个很好的过度了。提这个的原因是因为，在自定义键盘布局的时候，发现除了高度以外，这两个也会很影响打字的误触几率，手感会有很大的提升。这么说，我之前甚至想换手机，但后来把高度，行距，列距，调到自己手指适应的位置，完全没有了那种想法，键盘调整好，就能解决手感的问题。所以，希望能考虑一下

**Comment by imfuxiao** [comment]
> 是的。除开目前已经增加的几个UI的调整，希望能加上键盘的行距，列距的调整，如此一来，在没有完全自定义键盘布局UI配置前，可以有一个很好的过度了。提这个的原因是因为，在自定义键盘布局的时候，发现除了高度以外，这两个也会很影响打字的误触几率，手感会有很大的提升。这么说，我之前甚至想换手机，但后来把高度，行距，列距，调到自己手指适应的位置，完全没有了那种想法，键盘调整好，就能解决手感的问题。所以，希望能考虑一下

嗯嗯, 想法很赞~我也打算先优化UI, 后续在考虑开发自动布局的功能.

**Comment by AeonWorks** [comment]
可以考虑增加一个功能或按钮，直接调用系统的emoji，这样用户可以通过上下滑或空格左右按钮配置，或者像irime，直接放在没有任何输入时的候选栏上。
