### ISSUE TITLE
后续会加默认的微软双拼方案吗，还是必须手动导入呢，ing的方案大概在什么时间会出呢

### ISSUE THREAD

**Issue by Sailffo** [imfuxiao/Hamster#241]

**Comment by imfuxiao** [comment]
微软双拼方案雾淞输入方案就有内置，您可自行导入。

微软双拼需要；键，近期就会添加。

**Comment by Sailffo** [comment]
好的 感谢您！

**Comment by absir1949** [comment]
请教下，小鹤音形怎么导入呢 @imfuxiao

**Comment by imfuxiao** [comment]
> 请教下，小鹤音形怎么导入呢 @imfuxiao

去小鹤音形官网[下载 鼠须管 版本挂接包](http://ys-n.ysepan.com/116124318/319108762/i6652396545NJGTIvIjs81/%E5%B0%8F%E9%B9%A4%E9%9F%B3%E5%BD%A2%E2%80%9C%E9%BC%A0%E9%A1%BB%E7%AE%A1%E2%80%9Dfor%20macOS.zip)，然后操作流程和雾凇方案导入是一样的。

参考 [雾凇方案导入教程](https://github.com/imfuxiao/Hamster/wiki/%E5%A6%82%E4%BD%95%E5%AF%BC%E5%85%A5%22%E9%9B%BE%E6%B7%9E%E6%8B%BC%E9%9F%B3%E8%BE%93%E5%85%A5%E6%96%B9%E6%A1%88%22)
