### ISSUE TITLE
可以支持 索引字体大小的自定义呢

### ISSUE THREAD

**Issue by SeongBrave** [imfuxiao/Hamster#244]
![image](https://github.com/imfuxiao/Hamster/assets/10784393/7a7b79d0-8cda-4136-b9d2-d022ebeb43e4)
 其他端的可以通过 label_font_point 来自定义序号字体的大小，希望仓输入法可以支持💪

**Comment by imfuxiao** [comment]
2.0.0版本候选栏支持调整字体大小。
