### ISSUE TITLE
上传输入法方案失败

### ISSUE THREAD

**Issue by lovelock** [imfuxiao/Hamster#245]
rime-ice方案中的`build/rime-ice.table.bin`有79MB，上传到手机的时候下面这个请求报错如下：

http:///api/resources/Rime/build/rime_ice.table.bin?override=false

```json
{"error":true,"reason":"Payload Too Large"}
```

请问是否可以放大这个限制？

**Comment by imfuxiao** [comment]
感谢反馈，可以的。后面调节下限制。

**Comment by lovelock** [comment]
后来了解到不需要传输.bin文件，所以这个应该不是问题了。
