### ISSUE TITLE
相同配置相同按键内容，但与其他客户端输出不同

### ISSUE THREAD

**Issue by xenowei** [imfuxiao/Hamster#247]
使用了https://github.com/ssnhd/rime 提供的配置，mac端与windows端输出的内容相同，但仓输入法输出的内容有很大的不同。
仓输入法：![ios](https://github.com/imfuxiao/Hamster/assets/20449641/86598420-5caf-41a8-84a7-dd6563b2ae91)

Mac端：![mac](https://github.com/imfuxiao/Hamster/assets/20449641/7d389622-ad9d-4366-a1b4-36b49248623f)

windows端：![windows](https://github.com/imfuxiao/Hamster/assets/20449641/00b6b0ff-8d66-4269-b571-78d17b71410b)

**Comment by cactusnix** [comment]
如何你没有同步你的用户数据的话，这是个正常现象。

**Comment by cactusnix** [comment]
> 碰到了相同的问题，请问怎么同步用户数据？

目前本身就自带了Rime的同步功能 需要在不同的设备上都指向同一个同步目录 分别点击同步即可 这是Rime的同步机制

**Comment by imfuxiao** [comment]
见 wiki 的[同步教程](https://github.com/imfuxiao/Hamster/wiki/%E5%90%8C%E6%AD%A5%E6%95%99%E7%A8%8B)
