### ISSUE TITLE
[question] 外区 App Store 上架的问题

### ISSUE THREAD

**Issue by Steven1677** [imfuxiao/Hamster#248]
在我尝试点击使用 README 中的 App Store 的链接进行安装时提示 `This app is currently not available in your country or region.`（我的 Apple ID 在英区）。

想请问一下开发者是否在上架的区域上有所限制？不知道多加一些国家地区是否方便（我不是 iOS 开发者，不太了解多增加国家地区是否会得来额外的负担）？这样或许能方便主要的 Apple ID 在外区的人。

**Comment by Steven1677** [comment]
感谢您的回复。

不知道您在未来是否有上架欧洲区域的打算呢？（如果不会增加太多负担的话）

**Comment by imfuxiao** [comment]
可以，如果您有需求，我这边可以调整下。

**Comment by imfuxiao** [comment]
> 感谢您的回复。
> 
> 不知道您在未来是否有上架欧洲区域的打算呢？（如果不会增加太多负担的话）

另外您也可以使用 TF 版本：https://testflight.apple.com/join/6AkRfQYZ

**Comment by Steven1677** [comment]
感谢指路 TF !
已经成功用上了。
