### ISSUE TITLE
希望可以调整下数字键盘自定义符号区的按键高度，使其默认可以显示4个符号（如+-*/）

### ISSUE THREAD

**Issue by Jmdayou** [imfuxiao/Hamster#253]
<img width="414" alt="image" src="https://github.com/imfuxiao/Hamster/assets/130811752/cbc6a3a5-2079-497e-9205-6a00653345de">

如图，目前只能显示3个符号

**Comment by imfuxiao** [comment]
您好，这里是可以滑动的。

**Comment by Jmdayou** [comment]
> 您好，这里是可以滑动的。

明白，这个调整主要是方便使用了计算器lua的用户，可以不用滑动就输入计算符号。
参考微信键盘（主要是减少输入符号的滑动，日常使用可以少一个下滑的动作）
<img width="414" alt="image" src="https://github.com/imfuxiao/Hamster/assets/130811752/8716bf42-5e66-4624-b5c9-5eaad6a65d41">

**Comment by imfuxiao** [comment]
👌，我降低下符号栏的高度。

**Comment by Jmdayou** [comment]
> 👌，我降低下符号栏的高度。

感谢感谢，目前日常使用已近完美
