### ISSUE TITLE
雾凇和默认方案能共存吗

### ISSUE THREAD

**Issue by chca2** [imfuxiao/Hamster#254]
如默认xmjd6和雾凇如何共存呢？

**Comment by Jmdayou** [comment]
可以在dafault.yaml文件的方案列表里新增一行：
如： - schema: xmjd6 （对应的方案名称）
<img width="414" alt="image" src="https://github.com/imfuxiao/Hamster/assets/130811752/ae4e332e-c617-4b98-be1c-096b2f15a612">

**Comment by chca2** [comment]
> 可以在dafault.yaml文件的方案列表里新增一行：
> 
> 如： - schema: xmjd6 （对应的方案名称）
> 
> <img width="654" alt="Screenshot 2023-06-03 at 19 16 09" src="https://github.com/imfuxiao/Hamster/assets/130811752/bf9e7266-c7e0-49e6-897b-1f1cb753e809">
> 
> 
> 
>
那应该要复制进xmjd6的schema文件和附带的opencc，bin这些文件吧，如果有和rime-ice重复的文件怎么处理呢。另外用户词库应该不能公用吧，我看rime-ice用户词库改了自己的名字（rime-ice），xmjd6用的还是朙月拼音的。

**Comment by Jmdayou** [comment]
> > 可以在dafault.yaml文件的方案列表里新增一行：
> > 如： - schema: xmjd6 （对应的方案名称）
> > <img alt="Screenshot 2023-06-03 at 19 16 09" width="654" src="https://user-images.githubusercontent.com/130811752/243086048-bf9e7266-c7e0-49e6-897b-1f1cb753e809.png">
> 
> 那应该要复制进xmjd6的schema文件和附带的opencc，bin这些文件吧，如果有和rime-ice重复的文件怎么处理呢。另外用户词库应该不能公用吧，我看rime-ice用户词库改了自己的名字（rime-ice），xmjd6用的还是朙月拼音的。

要把xmjd6的文件连同雾凇的方案文件一起拷贝（bin可以不用拷） 
如果你要替换xmjd6里的拼音依赖，你就要打开它的schema文件改dependency为Rime_ice，对应反查滤镜的词库也改成Rime_ice

**Comment by chca2** [comment]
> > > 可以在dafault.yaml文件的方案列表里新增一行：
> 
> > > 如： - schema: xmjd6 （对应的方案名称）
> 
> > > <img alt="Screenshot 2023-06-03 at 19 16 09" width="654" src="https://user-images.githubusercontent.com/130811752/243086048-bf9e7266-c7e0-49e6-897b-1f1cb753e809.png">
> 
> > 
> 
> > 那应该要复制进xmjd6的schema文件和附带的opencc，bin这些文件吧，如果有和rime-ice重复的文件怎么处理呢。另外用户词库应该不能公用吧，我看rime-ice用户词库改了自己的名字（rime-ice），xmjd6用的还是朙月拼音的。
> 
> 
> 
> 要把xmjd6的文件连同雾凇的方案文件一起拷贝（bin可以不用拷） 
> 
> 如果你要替换xmjd6里的拼音依赖，你就要打开它的schema文件改dependency为Rime_ice，对应反查滤镜的词库也改成Rime_ice

谢谢，我试试

**Comment by imfuxiao** [comment]
如果只用雾淞，可以删除SharedSupport内置的方案，不需要共存。opencc文件夹只保留自己方案中使用文件即可。

另外，default.yaml/Squirrel.yaml文件不能删除。
