### ISSUE TITLE
成对上屏和光标居中也导致成对删除 不能只留一个符号

### ISSUE THREAD

**Issue by fengyupiaoyao75** [imfuxiao/Hamster#255]
成对上屏没问题 是光标居中的问题

**Comment by imfuxiao** [comment]
嗯嗯，别的伙伴也反馈此问题了。这个特性是我专门加的，没想到大家反而觉的不好用，目前TF版本已取消此特性。商店版本这几天发布。

**Comment by ZZZ7664** [comment]
不然做个开关吧  我个人认为这个删除还是挺好的
