### ISSUE TITLE
单手模式无法设置生效🫠

### ISSUE THREAD

**Issue by vkingw** [imfuxiao/Hamster#259]
iOS版本：16.5，13 Pro，软件版本：1.6.12（1），系统设置左手模式，不生效。系统自带的输入法和 Gboard 都正常。是需要哪里做设置吗？谢谢！
![IMG_6CF119E4DD75-1](https://github.com/imfuxiao/Hamster/assets/10920154/3ce100c6-1a3a-47e6-a63a-4bfa6078f55c)
![IMG_87B9F593F1B9-1](https://github.com/imfuxiao/Hamster/assets/10920154/c8090965-d0e5-445a-a9fc-f04440eb264b)

**Comment by imfuxiao** [comment]
您好，您说的设置是系统级别的设置，仓是不支持的。

仓的单手模式设置：
1. 在滑动设置中为某个键配置滑动指令，指令对应左手模式或右手模式。
2. 键盘上滑动对应手势，切换单手模式。

**Comment by luolisheng** [comment]
> 您好，您说的设置是系统级别的设置，仓是不支持的。
> 
> 仓的单手模式设置：
> 
> 1. 在滑动设置中为某个键配置滑动指令，指令对应左手模式或右手模式。
> 2. 键盘上滑动对应手势，切换单手模式。

请问怎么配置滑动指令，新增滑动Action输入字符后，没有什么效果？

**Comment by imfuxiao** [comment]
> > 您好，您说的设置是系统级别的设置，仓是不支持的。
> > 仓的单手模式设置：
> > 
> > 1. 在滑动设置中为某个键配置滑动指令，指令对应左手模式或右手模式。
> > 2. 键盘上滑动对应手势，切换单手模式。
> 
> 请问怎么配置滑动指令，新增滑动Action输入字符后，没有什么效果？

参考文档：https://github.com/imfuxiao/Hamster/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89%E5%B8%83%E5%B1%80#Action%E9%80%89%E9%A1%B9
