### ISSUE TITLE
对已有上下划动功能进行优化

### ISSUE THREAD

**Issue by imfuxiao** [imfuxiao/Hamster#26]
对已有上下划动功能进行优化.
1. 支持上传文件直接改动
2. 支持只开启上划功能
3. 其他....

**Comment by amorphobia** [comment]
补充一点：

3. 上下划可以让用户配置是否交给 `librime` 来处理，目前的上下划会直接 commit 字符，如果可以配置为 `librime` 处理，会更大地增加灵活性和易用性

**Comment by DreamAfar** [comment]
更新1.1.2版后，上滑和下滑交由librime
处理后，可以实现和iRime那样，通过绑定符号切换输入方案和Emoji和symbol符号切换了，但是判定上滑或下滑的距离有点长，能否优化缩短一些。经常上下滑动输入符号有很强的中断停顿感，输入节奏不连贯。
或者可以自定义，给个短中长这样的选项可选。

还有上下滑动输入符号，没有对应符号的气泡显示提示，可以优化一下。谢谢！

**Comment by imfuxiao** [comment]
引发bug #33
