### ISSUE TITLE
[Bug] v1.6.12(1) 单手模式下候选栏内容溢出屏幕，切换到数字九宫格 UI有溢出

### ISSUE THREAD

**Issue by gugu33** [imfuxiao/Hamster#260]
1. 单手模式下：
1.1 左手模式：输入法打字时，候选栏的候选字向左超出屏幕，导致无法看见和选择
![IMG_6969 2023-06-06 16_27_24](https://github.com/imfuxiao/Hamster/assets/6137969/7b8aa556-96b5-479d-9579-51ea520a8dc2)
1.2 右手模式：同样，向右溢出，导致无法看到和选择更多按钮
![IMG_6970 2023-06-06 16_27_24](https://github.com/imfuxiao/Hamster/assets/6137969/df61828f-7090-44d4-8551-bf06767e03b8)

2. 单手模式下切换到数字九宫格：
左/右手模式 UI 都被部分遮挡，并与模式切换按钮重叠
![IMG_6971 2023-06-06 16_27_25](https://github.com/imfuxiao/Hamster/assets/6137969/8ba4261c-ba48-417d-8e0d-920a9448a842)

**Comment by imfuxiao** [comment]
收到，感谢反馈。
