### ISSUE TITLE
请教中文模式下的键盘字母怎么变成大写的样式

### ISSUE THREAD

**Issue by gxmving** [imfuxiao/Hamster#267]
以前用的输入法中文模式下习惯把键盘字母设置为大写的样式，目前使用hamster输入法，没找到怎么才能实现，希望开发者百忙之中抽空解答一下，非常感谢🙏

**Comment by g6ai** [comment]
属于键盘自定义UI的任务，还在做。参见 https://github.com/imfuxiao/Hamster/discussions/172

**Comment by gxmving** [comment]
> 属于键盘自定义UI的任务，还在做。参见 #172

好的
