### ISSUE TITLE
数字九宫格键盘上下滑符号可显示

### ISSUE THREAD

**Issue by Anber55** [imfuxiao/Hamster#268]
主键盘的上下滑符号是可以显示的，很方便，但是数字九宫格键盘的上下滑可以操作，但是不能显示，有点崩溃，希望可以显示出来

**Comment by imfuxiao** [comment]
收到，感谢反馈。最近在做自定义相关开发，后面有时间做优化。

**Comment by imfuxiao** [comment]
2.0 已支持数字九宫格按键上下滑动设置，具体参考 `SharedSupport/hamster_swipe.yaml` 中的配置。
