### ISSUE TITLE
关于键盘布局

### ISSUE THREAD

**Issue by Anber55** [imfuxiao/Hamster#269]
能不能在键盘布局中可以自选增加一行，我习惯性的把数字放在最上面，iRime里面就是，对我来说很方便，希望仓也可以实现，谢谢

**Comment by imfuxiao** [comment]
感谢反馈，此功能将会在自定义键盘功能中实现

**Comment by royccg** [comment]
想咨询一下，自定义键盘布局的功能有在开发进度吗，我自己用的 格道17键的布局，哈哈哈哈，很期待能在这个app上实现。

**Comment by imfuxiao** [comment]
在开发中，新版本键盘布局从0开始，与1.0完全不同。

**Comment by royccg** [comment]
> 在开发中，新版本键盘布局从0开始，与1.0完全不同。

万分感谢，非常期待

**Comment by imfuxiao** [comment]
2.0.0版本已支持自定义布局。
