### ISSUE TITLE
功能请求：切换到该选项时，颜色背景跟着一起切换

### ISSUE THREAD

**Issue by Anber55** [imfuxiao/Hamster#271]
如题，有的时候会删除自造词，设置了（）作为向左和向右选定词的符号，但是每次都不知道选到了谁，只能数数，希望以后的背景颜色也能跟着选定的词走，更好的确定哪个词应该被删除。Rime可以，iRime和仓好像都不可以，谢谢

**Comment by imfuxiao** [comment]
感谢反馈，目前仓没有添加首选字调整的功能。后面时间空余的话，可以加一下。
