### ISSUE TITLE
如何更改光标位置

### ISSUE THREAD

**Issue by snylonue** [imfuxiao/Hamster#272]
如 rime 的 user guide 所说

> 使用編輯鍵
使用 ←→鍵 定位光標插入點「‸」（或顯示爲「›」），編輯輸入碼。 也可用來縮短後選詞所對應輸入碼的範圍、確認詞句的一部分。
Home、End 鍵 快速跳至句首、句末。
BackSpace、Delete 鍵 分別刪除光標前、後的編碼字符。注意在蘋果鍵盤上前者標註爲 Delete，後者通常是組合鍵 Fn+Delete。
Escape 鍵 清空未完成的輸入。

但查阅按键滑动手势没有发现相关功能

**Comment by imfuxiao** [comment]
感谢反馈。rime的编码区编辑功能目前是不支持。

虚拟键盘上的键位没有那么多，如果支持编辑功能，势必需要添加按键或者添加按键映射。个人觉的反而不利于输入。

另一个，我个人觉的，对编码区域编辑的需求应该是用全拼输入方案，且偏向整句输入的。这种场景下，其实带有云端功能的的输入法，如搜狗等，会更加友好一些。

**Comment by snylonue** [comment]
> 虚拟键盘上的键位没有那么多，如果支持编辑功能，势必需要添加按键或者添加按键映射。个人觉的反而不利于输入。
> 另一个，我个人觉的，对编码区域编辑的需求应该是用全拼输入方案，且偏向整句输入的。这种场景下，其实带有云端功能的的输入法，如搜狗等，会更加友好一些。

我习惯以词语为单位输入的，主要是有时候候选词太多，要翻很久才能翻到单字；而且编辑一次之后再打就更方便
如果可以的话希望加一些滑动手势供自定义

**Comment by wzxmer** [comment]
> > 虚拟键盘上的键位没有那么多，如果支持编辑功能，势必需要添加按键或者添加按键映射。个人觉的反而不利于输入。
> 
> 我习惯以词语为单位输入的，主要是有时候候选词太多，要翻很久才能翻到单字；而且编辑一次之后再打就更方便 如果可以的话希望加一些滑动手势供自定义
> 
> > 另一个，我个人觉的，对编码区域编辑的需求应该是用全拼输入方案，且偏向整句输入的。这种场景下，其实带有云端功能的的输入法，如搜狗等，会更加友好一些。
> 
> 出于隐私等考虑不是很想用这些输入法

相比较输入法的功能，我建议尝试下其它的输入法方案，看你说的喜好，推荐你试试键道 https://github.com/wzxmer/xkjd6-rime  以打词为主

**Comment by imfuxiao** [comment]
仓2.0 支持快捷指令 #SendKeys 发送 up/ down 键，可以达到改变当前高亮候选文字的目的。

**Comment by luochen1990** [comment]
> 仓2.0 支持快捷指令 #SendKeys 发送 up/ down 键，可以达到改变当前高亮候选文字的目的。

求问 iOS 端具体怎么设置？

我尝试通过

键盘布局 -> 中文26键 -> 滑动设置 -> [选中某按键] -> 滑动操作 ->  快捷指令 -> sendKeys() -> 填入 “up” -> 保存

来试图实现向上滑动发送 up键，但是失败了，不知道这里应该如何填写？
