### ISSUE TITLE
bug反馈，上滑换行与点击换行效果不一致

### ISSUE THREAD

**Issue by Anber55** [imfuxiao/Hamster#276]
第一种是【这是上滑换行符实现的换行效果】
第二种是【这是直接点换行键实现的换行效果】

在ToMemo种实现的子字符效果不一样
点击是OK的
上滑的不行的

这不是有什么问题？

**Comment by Anber55** [comment]
视频发到tg群了

**Comment by imfuxiao** [comment]
嗯嗯，看到了。先说下这个暂时无解。

上滑换行使用了\r，是为了满足如微信等app可以在聊天窗口下换行的需求，但\r在window系统是下无效的。

之前使用过\r\n，但会导致退格键需要按两次。

后续解决思路应该还会用\r\n来处理，就是要解决下退格键两次输入的问题。

正在做app的重构和自定义键盘的开发，我看看能否在键盘重构的时候解决掉这个问题。

**Comment by Anber55** [comment]
好的，感谢答疑，问题比较多，见谅

**Comment by groverlynn** [comment]
> 嗯嗯，看到了。先说下这个暂时无解。
> 
> 上滑换行使用了\r，是为了满足如微信等app可以在聊天窗口下换行的需求，但\r在window系统是下无效的。
> 
> 之前使用过\r\n，但会导致退格键需要按两次。
> 
> 后续解决思路应该还会用\r\n来处理，就是要解决下退格键两次输入的问题。
> 
> 正在做app的重构和自定义键盘的开发，我看看能否在键盘重构的时候解决掉这个问题。

U+0085 Next Line （Latin-1／win1252編碼中這個碼位被省略號`…`佔用）
U+2028 Line Separator （相當於shift+enter）
U+2029 Paragraph Separator （相當於enter）

**Comment by imfuxiao** [comment]
> > 嗯嗯，看到了。先说下这个暂时无解。
> > 上滑换行使用了\r，是为了满足如微信等app可以在聊天窗口下换行的需求，但\r在window系统是下无效的。
> > 之前使用过\r\n，但会导致退格键需要按两次。
> > 后续解决思路应该还会用\r\n来处理，就是要解决下退格键两次输入的问题。
> > 正在做app的重构和自定义键盘的开发，我看看能否在键盘重构的时候解决掉这个问题。
> 
> U+0085 Next Line （Latin-1／win1252編碼中這個碼位被省略號`…`佔用） U+2028 Line Separator （相當於shift+enter） U+2029 Paragraph Separator （相當於enter）

可以测试下，如果您反馈的 unicode 可以达到预期效果，可以修改下当前的换行符。
