### ISSUE TITLE
可否更新一下如何加入开发的文档

### ISSUE THREAD

**Issue by cactusnix** [imfuxiao/Hamster#277]
iOS开发新手, 想要启动这个项目, 有些困难, 又需要CocoaPods, 又需要编译, 虽然有一定开发基础, 但是单纯想要更改一些纯代码逻辑部分的内容, 也似乎开始的比较困难.

**Comment by imfuxiao** [comment]
嗯嗯，已注意到这个问题，这是我目前已开始的重构工作的一部分。

最新版本2.0开发会简化这些内容，可以直接上手开发。

请耐心等待。

**Comment by cactusnix** [comment]
嗯嗯 好的 感谢大佬 我耐心等待

**Comment by imfuxiao** [comment]
是的，2.0与现在版本差别很大。

**Comment by imfuxiao** [comment]
抱歉，具体时间点无法确定。
