### ISSUE TITLE
四叶草九宫格拼音部署失败

### ISSUE THREAD

**Issue by debugly** [imfuxiao/Hamster#278]
我在寻找一个九宫格拼音输入法，找到了一个安卓版的  四叶草九宫格拼音方案，部署后没有九宫格，这是哪的问题呢，第一次使用 rime 输入法。
https://github.com/SivanLaai/rime-pure
输入方案是按照这个帖子里写的步骤做的：https://www.laais.cn/posts/projects/rime/installation/
我看到你在 issue 里回复说正在开发九宫格输入法，不知道现在什么进度了，这个四叶草九宫格拼音方案是否有参考价值？

**Comment by imfuxiao** [comment]
因为目前只有全键盘布局，所以是不支持九宫格输入方案的。

我正在开发自定义键盘，开发完了是可以支持九宫格的。还请耐心等待。
