### ISSUE TITLE
方案選單、繁簡轉換、全角半角

### ISSUE THREAD

**Issue by groverlynn** [imfuxiao/Hamster#279]
方案選單（Switch）一旦hotkey設定的與默認不一致就無法識別。（簡單看了一下代碼，似乎是強制改小寫導致librime無法識別）。另外建議打開Switch的menu時直接展開候選欄，因爲根本用不到鍵盤。而switch的caption（默認爲`〔方案選單〕`）不應該當作輸入文字插入，而應該顯示在候選欄當中。建議此時強制採用非內嵌模式。可以通過`dumb`這個option來判斷是否打開了方案選單。

簡繁轉換雖然支持自訂option，但仍只支持`開／關`兩選項的option。而key binding的RIME API是支持多選項的option的。

剩餘兩個全局選項（1）`full_shape`全角半角（全形半形／全寬半寬）、（2）`ascii_punct`（ASCII標點）只能通過switch更改，而且因爲鍵盤的標點被強制改成了非ASCII的標點而不起作用。當輸入方案是`easy_english`等英文方案時也強制使用東亞標點……

**Comment by imfuxiao** [comment]
感谢反馈，非常好的建议，后续版本会依次调整相关功能。
