### ISSUE TITLE
ios17 beta 3 bug

### ISSUE THREAD

**Issue by xy464193** [imfuxiao/Hamster#280]
ios17 beta 3 无法打字

**Comment by imfuxiao** [comment]
Beta版本的问题暂时不能处理，需要等待 iOS17 GA 版本后在修复。

**Comment by tamhaywoo** [comment]
> ios17 beta 3 无法打字

多谢反馈，我暂时不升级iOS beta版本咯

**Comment by HeminWon** [comment]
> Beta版本的问题暂时不能处理，需要等待 iOS17 GA 版本后在修复。

你好，我想帮忙修复iOS17我手机上的相关问题，但是打开工程无法拉取到 Package Dependencies里面的依赖就行编译，请问要如何编译这个工程。

**Comment by imfuxiao** [comment]
> > Beta版本的问题暂时不能处理，需要等待 iOS17 GA 版本后在修复。
> 
> 你好，我想帮忙修复iOS17我手机上的相关问题，但是打开工程无法拉取到 Package Dependencies里面的依赖就行编译，请问要如何编译这个工程。

您好，是项目依赖无法拉取，还是说可以拉取但编译有问题？

一般情况下应该都是 lirrime 编译出现的问题，如果是这里出现的问题，可以手动去 https://github.com/imfuxiao/LibrimeKit 下载已经编译好的 release 版本。然后在尝试看本地是否可以启动模拟器。
