### ISSUE TITLE
用四叶草简体拼音时缺字

### ISSUE THREAD

**Issue by Izumiko** [imfuxiao/Hamster#281]
打不出”帧“字

**Comment by imfuxiao** [comment]
您好，刚看了四叶草的词库文件，帧在词库文件 clover.base.dict.yaml 第 2570 行，拼音为 zheng。

因为四叶草输入方案，我这边是从四叶草的官方 repo 拉去的，您需要去官方的 repo 中提交 issue。

**Comment by Izumiko** [comment]
好的，谢谢
