### ISSUE TITLE
需求建议：增加用户数据上传

### ISSUE THREAD

**Issue by luckykellan** [imfuxiao/Hamster#283]
我在mac和win上使用输入法较多，积累了很多自造词和输入频率。在IOS使用仓输入法并完成输入方案上传以后，用户数据并没有同步

**Comment by imfuxiao** [comment]
您好，可以利用 RIME 的自造词同步功能同步。不过 RIME 自造词同步功能只支持 userdb(二进制)格式词库，tabledb(文本)格式词库不支持。

**Comment by luckykellan** [comment]
您好，感谢回复。请问有相关的博客或者教程吗？刚刚操作没太弄明白...

**Comment by imfuxiao** [comment]
> 您好，感谢回复。请问有相关的博客或者教程吗？刚刚操作没太弄明白...

没有写过专门的教程，之前在有个 issue 中有个测试步骤，您可以参考下。

https://github.com/imfuxiao/Hamster/issues/231#issuecomment-1562159717

**Comment by imfuxiao** [comment]
[同步教程文档](https://github.com/imfuxiao/Hamster/wiki/%E5%90%8C%E6%AD%A5%E6%95%99%E7%A8%8B)
