### ISSUE TITLE
iPad没有切换中英文按键

### ISSUE THREAD

**Issue by yaozhenghangma** [imfuxiao/Hamster#284]
打开了中英文切换按键，但在iPad键盘上没有显示。
![IMG_0773](https://github.com/imfuxiao/Hamster/assets/34626000/48647cc9-35ea-4b4d-b0fc-4dc75e8d6f56)

**Comment by imfuxiao** [comment]
您好，此问题在 PR 273 https://github.com/imfuxiao/Hamster/pull/273 中已修复。

目前在做新的功能重构，没有发布商店版本，请耐心等待。
