### ISSUE TITLE
iPad九宫格数字键盘无法唤起

### ISSUE THREAD

**Issue by yaozhenghangma** [imfuxiao/Hamster#285]
选中了九宫格数字键盘后，还是没有出现九宫格。
![IMG_0774](https://github.com/imfuxiao/Hamster/assets/34626000/006d8618-7c16-4509-b577-3739b178af8d)

**Comment by imfuxiao** [comment]
您好，ipad布局确实没有九宫格。感谢反馈。

**Comment by maogm12** [comment]
iPad只有在浮动键盘才能看到九宫格，不过可以考虑在设置里加个comment。

**Comment by imfuxiao** [comment]
「仓」2.0版本已支持。
