### ISSUE TITLE
需求建议：增加按键滑动手势

### ISSUE THREAD

**Issue by yett1873** [imfuxiao/Hamster#286]
目前在按键滑动手势中，句号`.`、`123↓`、`shift↓`的功能还无法设置 。
尤其希望能够增加对`.`的支持，这样就能将`>`与`<`分别放在`.`和`,`上了！

**Comment by imfuxiao** [comment]
您好，目前 UI 设置不支持这自定义按键的滑动设置。临时方案：您可以通过修改配置文件的方式添加。

可以通过将您的配置文件导出到 iCloud 保存。用文本编辑器打开，如 VSCode等等。参考配置文件中已有的配置，添加您想要相关滑动按键配置。

至于 UI 中直接添加配置的功能，我正在开发中。

**Comment by yett1873** [comment]
你好，已经按照说明配置成功，非常感谢❤️
