### ISSUE TITLE
Please ask when it will be updated.

### ISSUE THREAD

**Issue by DoerLa** [imfuxiao/Hamster#290]
The Great God has recently been hard, we have recently been looking forward to updating, want to know how the update progress is, or if you can come a small update first, thank you

**Comment by imfuxiao** [comment]
最近没有在1.0版本上做小功能，除了有伙伴提交的两个关于 iPad 的适配 PR。所以不准备版本发布。

2.0没有在1.0的基础上开发，有很多技术债需要去补。

新版本也是个人边看书边开发，所以会慢很多，如果一切顺利，预计会在9月份发布2.0的测试版本。

----

I haven't worked on any small features on version 1.x, except for two adaption PRs for iPad submitted by a partner, so I'm not ready for a release. 

2.x version is not developed on the basis of 1.x, and there are a lot of technical debts that need to be filled.

The new version is also developed by individuals while reading books, so it will be much slower, if everything goes well, it is expected that the beta version of 2.0 will be released in September.

**Comment by DoerLa** [comment]
Thank you for the 2.0 version in September

**Comment by noisay** [comment]
> 



> 最近没有在1.0版本上做小功能，除了有伙伴提交的两个关于 iPad 的适配 PR。所以不准备版本发布。
> 
> 2.0没有在1.0的基础上开发，有很多技术债需要去补。
> 
> 新版本也是个人边看书边开发，所以会慢很多，如果一切顺利，预计会在9月份发布2.0的测试版本。
> 
> I haven't worked on any small features on version 1.x, except for two adaption PRs for iPad submitted by a partner, so I'm not ready for a release.
> 
> 2.x version is not developed on the basis of 1.x, and there are a lot of technical debts that need to be filled.
> 
> The new version is also developed by individuals while reading books, so it will be much slower, if everything goes well, it is expected that the beta version of 2.0 will be released in September.

2.0版本会有九宫格输入吗？真的非常非常需要~感谢

**Comment by imfuxiao** [comment]
> > 
> 
> 
> 
> 
> 
> 
> 
> > 最近没有在1.0版本上做小功能，除了有伙伴提交的两个关于 iPad 的适配 PR。所以不准备版本发布。
> 
> > 
> 
> > 2.0没有在1.0的基础上开发，有很多技术债需要去补。
> 
> > 
> 
> > 新版本也是个人边看书边开发，所以会慢很多，如果一切顺利，预计会在9月份发布2.0的测试版本。
> 
> > 
> 
> > I haven't worked on any small features on version 1.x, except for two adaption PRs for iPad submitted by a partner, so I'm not ready for a release.
> 
> > 
> 
> > 2.x version is not developed on the basis of 1.x, and there are a lot of technical debts that need to be filled.
> 
> > 
> 
> > The new version is also developed by individuals while reading books, so it will be much slower, if everything goes well, it is expected that the beta version of 2.0 will be released in September.
> 
> 
> 
> 2.0版本会有九宫格输入吗？真的非常非常需要~感谢

有的，不过九宫格的布局需要对应的输入方案。

**Comment by noisay** [comment]
> > > 
> > 
> > 
> > > 最近没有在1.0版本上做小功能，除了有伙伴提交的两个关于 iPad 的适配 PR。所以不准备版本发布。
> > 
> > 
> > > 
> > 
> > 
> > > 2.0没有在1.0的基础上开发，有很多技术债需要去补。
> > 
> > 
> > > 
> > 
> > 
> > > 新版本也是个人边看书边开发，所以会慢很多，如果一切顺利，预计会在9月份发布2.0的测试版本。
> > 
> > 
> > > 
> > 
> > 
> > > I haven't worked on any small features on version 1.x, except for two adaption PRs for iPad submitted by a partner, so I'm not ready for a release.
> > 
> > 
> > > 
> > 
> > 
> > > 2.x version is not developed on the basis of 1.x, and there are a lot of technical debts that need to be filled.
> > 
> > 
> > > 
> > 
> > 
> > > The new version is also developed by individuals while reading books, so it will be much slower, if everything goes well, it is expected that the beta version of 2.0 will be released in September.
> > 
> > 
> > 2.0版本会有九宫格输入吗？真的非常非常需要~感谢
> 
> 有的，不过九宫格的布局需要对应的输入方案。

意思是九宫格需要专门的输入方案吗？像[https://github.com/iDvel/rime-ice](url)PC端的方案不能直接使用？

**Comment by imfuxiao** [comment]
方案需要做调整，你看雾凇的九宫格也是做了调整的。

**Comment by noisay** [comment]
> 

看到了，没想到我喜爱的两个项目居然有联动，提前感谢两位大佬


<img width="729" alt="image" src="https://github.com/imfuxiao/Hamster/assets/16579487/d6ef7fd8-96c7-4ffe-a21f-0ccbccaa6998">

**Comment by imfuxiao** [comment]
2.0.0版本已上线
