### ISSUE TITLE
 怎么那么就还没有九宫格，我真的是服了

### ISSUE THREAD

**Issue by zhaohai1024** [imfuxiao/Hamster#291]
怎么那么就还没有九宫格，我真的是服了

**Comment by imfuxiao** [comment]
抱歉，我的技术能力太弱了，建议您使用其他输入法。

**Comment by noisay** [comment]
> 怎么那么就还没有九宫格，我真的是服了

不会说话可以不说，欠你的？你是开工资了还是付费了？免费的还要bbll，基本的礼貌都没有
