### ISSUE TITLE
iOS Chrome 地址栏上输入不能清除已选中的地址、且回车也无法覆盖已有内容

### ISSUE THREAD

**Issue by ksqsf** [imfuxiao/Hamster#292]
参见如下复现视频

https://github.com/imfuxiao/Hamster/assets/23358293/e47d10f6-bdbd-4f41-96a6-c21059a56b18

观测行为：输入 "google" 但是并没有覆盖掉地址栏上已有的内容，即使在按下回车之后也没有覆盖，反而是添加到了内容的末尾。

预期行为：在按下第一个 "g" 后，整个地址栏就应该已经被清空，只留下 "g"。（其他输入法均为此行为。）

这是目前的 App Store 最新版本，该问题或已在 2.0 中修复？

**Comment by tamhaywoo** [comment]
嗯，这个情况我也遇到了。我的做法就是X掉之后再输入

**Comment by imfuxiao** [comment]
感谢反馈，这个是已知的问题，在开启内嵌模式是会出现这种情况，iOS 输入法提供的内嵌模式 api 本身的行为就有bug，暂时没有好的处理方式，目前在做2.0的工作，后续有时间会在研究下怎么处理这个问题。

**Comment by tamhaywoo** [comment]
> 感谢反馈，这个是已知的问题，在开启内嵌模式是会出现这种情况，iOS 输入法提供的内嵌模式 api 本身的行为就有bug，暂时没有好的处理方式，目前在做2.0的工作，后续有时间会在研究下怎么处理这个问题。

哦，原来是这样，那我取消掉内嵌模式。Cool

**Comment by groverlynn** [comment]
> 感谢反馈，这个是已知的问题，在开启内嵌模式是会出现这种情况，iOS 输入法提供的内嵌模式 api 本身的行为就有bug，暂时没有好的处理方式，目前在做2.0的工作，后续有时间会在研究下怎么处理这个问题。

`replace(_:withText:)`

**Comment by imfuxiao** [comment]
您好，用最新版本的仓在 Chrome 中测试，没有这个问题了，因此关闭此 issue。如果您还有此问题，可以重新打开此 issue。
