### ISSUE TITLE
显示简繁状态

### ISSUE THREAD

**Issue by tinainsz** [imfuxiao/Hamster#293]
开发者你好，我因为工作需要需要不停切换简体繁体，目前是设置了键盘左下「123」上滑快速切换，因此「123」上方会有一个小小的「繁」提示。
我的困扰是，我不能判断现在键盘处在简体还是繁体的状态，因此每次都需要先打几个字判断，有点麻烦。不知道有没有可能把那个「繁」或者在其他地方，改成显示当下简繁的状态？
谢谢！

**Comment by imfuxiao** [comment]
非常抱歉，这是个一直以来的问题，我暂时没有啥解决方案，因为每个简繁状态是每个输入方案自定义的，也就是你无法通过状态 true/false 判断是繁体还是简体。

回头有时间我在仔细看看 rime 的源码吧。

**Comment by tinainsz** [comment]
好的好的 没事 谢谢你

**Comment by groverlynn** [comment]
> 非常抱歉，这是个一直以来的问题，我暂时没有啥解决方案，因为每个简繁状态是每个输入方案自定义的，也就是你无法通过状态 true/false 判断是繁体还是简体。
> 
> 回头有时间我在仔细看看 rime 的源码吧。

你想得太多了，以自己的思維方式忽略甚至倒轉了大量的代碼和設定邏輯。
每個方案的`switches`下爲每個／組option都可以設定`states`及縮短版的`abbrev`。輸入法不需要理解也不應該試圖理解這些state的語義，照搬就好

**Comment by imfuxiao** [comment]
> > 非常抱歉，这是个一直以来的问题，我暂时没有啥解决方案，因为每个简繁状态是每个输入方案自定义的，也就是你无法通过状态 true/false 判断是繁体还是简体。
> > 回头有时间我在仔细看看 rime 的源码吧。
> 
> 你想得太多了，以自己的思維方式忽略甚至倒轉了大量的代碼和設定邏輯。 每個方案的`switches`下爲每個／組option都可以設定`states`及縮短版的`abbrev`。輸入法不需要理解也不應該試圖理解這些state的語義，照搬就好

感谢，受教了。不过如果用户的简繁的配置中没有配置每个状态对应的值，那么UI如何显示呢?

**Comment by groverlynn** [comment]
> > > 非常抱歉，这是个一直以来的问题，我暂时没有啥解决方案，因为每个简繁状态是每个输入方案自定义的，也就是你无法通过状态 true/false 判断是繁体还是简体。
> > > 回头有时间我在仔细看看 rime 的源码吧。
> > 
> > 
> > 你想得太多了，以自己的思維方式忽略甚至倒轉了大量的代碼和設定邏輯。 每個方案的`switches`下爲每個／組option都可以設定`states`及縮短版的`abbrev`。輸入法不需要理解也不應該試圖理解這些state的語義，照搬就好
> 
> 感谢，受教了。不过如果用户的简繁的配置中没有配置每个状态对应的值，那么UI如何显示呢?

既然用戶要求不顯示那就不顯示啊

**Comment by tywtyw2002** [comment]
如果简繁体是states状态和中英一样，那么全局状态可以通过patch去实现。

相关全局中英问题的讨论
https://github.com/rime/squirrel/issues/145

简单的来说就是输入法前端（hamster）维护一个简繁global的状态，根据规则同步librime 和 global的相关状态。

这个是我实现的global 中英，加了些个人喜好的状态同步，某些情况下中英不切换但是同步。
https://github.com/tywtyw2002/squirrel/commit/4b67732075b89a563283c405d6fb88e6af00ad5c
这个是我参考的实现
https://github.com/rime/squirrel/pull/201

**Comment by imfuxiao** [comment]
2.0新版支持空格显示简繁状态变更。
