### ISSUE TITLE
[Bug] 导入输入法失败

### ISSUE THREAD

**Issue by Seraphli** [imfuxiao/Hamster#295]
通过文件上传功能尝试导入温州话输入法，发现上传到Rime文件夹之后，无法在输入方案里面看到
输入法的仓库在这里
https://github.com/ZWolken/rime-wenzhounese
使用的是release里的压缩包内容
https://github.com/ZWolken/rime-wenzhounese/releases/download/v1.0.0/rime-wenzhounese_v1.0.0.zip

**Comment by DreamAfar** [comment]
你需要在default.custom.yaml文件里面的方案列表，将你导入的方案的名称加入到方案列表后，重新部署

**Comment by Seraphli** [comment]
找到了, 是RIME/build下default.yml文件里的schema
