### ISSUE TITLE
2个建议

### ISSUE THREAD

**Issue by kewell2000** [imfuxiao/Hamster#296]
斗胆向开发者提2个需求：
1.是否有可能实现iOS输入法中的智能纠错输入功能。
2.能否自定义读取手机中rime文件夹的位置。如果可以的话能利用第三方同步软件和macOS同步配置，达到和macOS端相同体验的目的。

**Comment by ksqsf** [comment]
librime 自带一个纠错功能，可以在对应的 translator 下增加 `enable_correction: true` 启用，可以尝试一下。

**Comment by imfuxiao** [comment]
> 斗胆向开发者提2个需求： 1.是否有可能实现iOS输入法中的智能纠错输入功能。 2.能否自定义读取手机中rime文件夹的位置。如果可以的话能利用第三方同步软件和macOS同步配置，达到和macOS端相同体验的目的。

1. 拼音纠错功能在输入方案的配置文件中，需要自己安需求配置。
2. 仓本身是开放配置文件目录的，但由于 iOS 系统的安全设置，键盘需要复制一套一模一样的方案配置到自己的沙盒目录中。所以需要修改完后，在应用内重新部署后才能生效。
