### ISSUE TITLE
请求用仓作为第三方 librime 引擎的前端并自行发布

### ISSUE THREAD

**Issue by tansongchen** [imfuxiao/Hamster#298]
如果手里有一个自己修改过的 librime，可以用 Hamster 作为前端封装一下发布到 App Store 吗？

**Comment by imfuxiao** [comment]
可以，但需要遵守 [GPL-3.0 license](https://github.com/imfuxiao/Hamster/blob/main/LICENSE.txt) 协议。

**Comment by tansongchen** [comment]
@imfuxiao 我最近发现 TestFlight 上的版本已经来到了 3.0，请问 3.0 的源码是放在哪里呢？是否可以开始参与 3.0 的开发了？

**Comment by imfuxiao** [comment]
仓的源码对应商店版本，即每次发布商店版本时，我会推一次代码，TF上的版本对应我的私有库。

目前 2.0 还未发布商店，所以无法参与开发。

**Comment by tansongchen** [comment]
> 仓的源码对应商店版本，即每次发布商店版本时，我会推一次代码，TF上的版本对应我的私有库。
> 
> 目前 2.0 还未发布商店，所以无法参与开发。

好的，那请问目前有预计的 2.0 发布商店的时间吗？如前所述，因为我希望做一个第三方 librime 的前端，因为 1.0 和 2.0 很不一样，所以希望能够基于 2.0 开发

**Comment by imfuxiao** [comment]
> > 仓的源码对应商店版本，即每次发布商店版本时，我会推一次代码，TF上的版本对应我的私有库。
> > 目前 2.0 还未发布商店，所以无法参与开发。
> 
> 好的，那请问目前有预计的 2.0 发布商店的时间吗？如前所述，因为我希望做一个第三方 librime 的前端，因为 1.0 和 2.0 很不一样，所以希望能够基于 2.0 开发

预计 11 月上旬，目前还在测试中，bug比较多，1.0的功能也没全部移植完。

**Comment by imfuxiao** [comment]
> > 仓的源码对应商店版本，即每次发布商店版本时，我会推一次代码，TF上的版本对应我的私有库。
> > 目前 2.0 还未发布商店，所以无法参与开发。
> 
> 好的，那请问目前有预计的 2.0 发布商店的时间吗？如前所述，因为我希望做一个第三方 librime 的前端，因为 1.0 和 2.0 很不一样，所以希望能够基于 2.0 开发

请问后期你是会发布苹果商店么？2.0 的后续版本，我可能会做一些付费功能，比如 WebDAV 这些，这些功能是不会开源的。

**Comment by tansongchen** [comment]
是的，到时候应该会发到苹果商店。没关系，只要基础功能的源码有就可以。

**Comment by imfuxiao** [comment]
> 是的，到时候应该会发到苹果商店。没关系，只要基础功能的源码有就可以。

我建议，如非必要，可以将你想要的功能合并到仓中，不用二次分发。原因有以下几点：

1. 合并进入您想要的功能后，仓的用户群体会更多；
2. 如果分别上架，用户会分流；
3. 维护不方便，如果仓发布新版本，你那边需要合并后在发布，对于 bug 的修复肯定是不及时的。

**Comment by sbxlmdsl** [comment]
> > 是的，到时候应该会发到苹果商店。没关系，只要基础功能的源码有就可以。
> 
> 我建议，如非必要，可以将你想要的功能合并到仓中，不用二次分发。原因有以下几点：
> 
> 1. 合并进入您想要的功能后，仓的用户也会受众使用；
> 2. 如果分别上架，用户会分流；
> 3. 维护不方便，如果仓发布新版本，你那边需要合并后在发布，对于 bug 的修复肯定是不及时的。

因为声笔为了支持以顶功为核心的大量特殊功能，对librime进行了很多特别的定制，已经无法兼容原版的librime，直接并入Hamster会导致很多原生的rime输入方案无法正常使用，所以只能单独发布。

**Comment by imfuxiao** [comment]
> > > 是的，到时候应该会发到苹果商店。没关系，只要基础功能的源码有就可以。
> > 
> > 
> > 我建议，如非必要，可以将你想要的功能合并到仓中，不用二次分发。原因有以下几点：
> > 
> > 1. 合并进入您想要的功能后，仓的用户也会受众使用；
> > 2. 如果分别上架，用户会分流；
> > 3. 维护不方便，如果仓发布新版本，你那边需要合并后在发布，对于 bug 的修复肯定是不及时的。
> 
> 因为声笔为了支持以顶功为核心的大量特殊功能，对librime进行了很多特别的定制，已经无法兼容原版的librime，直接并入Hamster会导致很多原生的rime输入方案无法正常使用，所以只能单独发布。

这两天思考了下，有一种方案可以实现，仓可以内置两个键盘，两个键盘使用不同编译的 librime。其中一个键盘是目前现在的，另一个键盘可以是基于 librime 改造的。

您看这个方案如何？ @sbxlmdsl  @tansongchen

**Comment by imfuxiao** [comment]
2.0.0 版本源码已同步，如果只是因为 librime 的原因，我可以内置两个不同的 librime 的键盘。

个人想法还是不想分裂仓，大家可以一起来开发。

**Comment by isPoto** [comment]
> > > > 是的，到时候应该会发到苹果商店。没关系，只要基础功能的源码有就可以。
> > > 
> > > 
> > > 我建议，如非必要，可以将你想要的功能合并到仓中，不用二次分发。原因有以下几点：
> > > 
> > > 1. 合并进入您想要的功能后，仓的用户也会受众使用；
> > > 2. 如果分别上架，用户会分流；
> > > 3. 维护不方便，如果仓发布新版本，你那边需要合并后在发布，对于 bug 的修复肯定是不及时的。
> > 
> > 
> > 因为声笔为了支持以顶功为核心的大量特殊功能，对librime进行了很多特别的定制，已经无法兼容原版的librime，直接并入Hamster会导致很多原生的rime输入方案无法正常使用，所以只能单独发布。
> 
> 这两天思考了下，有一种方案可以实现，仓可以内置两个键盘，两个键盘使用不同编译的 librime。其中一个键盘是目前现在的，另一个键盘可以是基于 librime 改造的。
> 
> 您看这个方案如何？ @sbxlmdsl @tansongchen

没问题，就这么决定

**Comment by sbxlmdsl** [comment]
> > > > 是的，到时候应该会发到苹果商店。没关系，只要基础功能的源码有就可以。
> > > 
> > > 
> > > 我建议，如非必要，可以将你想要的功能合并到仓中，不用二次分发。原因有以下几点：
> > > 
> > > 1. 合并进入您想要的功能后，仓的用户也会受众使用；
> > > 2. 如果分别上架，用户会分流；
> > > 3. 维护不方便，如果仓发布新版本，你那边需要合并后在发布，对于 bug 的修复肯定是不及时的。
> > 
> > 
> > 因为声笔为了支持以顶功为核心的大量特殊功能，对librime进行了很多特别的定制，已经无法兼容原版的librime，直接并入Hamster会导致很多原生的rime输入方案无法正常使用，所以只能单独发布。
> 
> 这两天思考了下，有一种方案可以实现，仓可以内置两个键盘，两个键盘使用不同编译的 librime。其中一个键盘是目前现在的，另一个键盘可以是基于 librime 改造的。
> 
> 您看这个方案如何？ @sbxlmdsl @tansongchen

那就由您在发布仓的时候，一起内置了吗？我们还需配合什么不？声笔的librime若有更新，和原生的时间又不一致的话，怎么办呢？有办法解决吗？

**Comment by isPoto** [comment]
声笔希望能作为仓的内置方案，缔结长远合作
声笔后续将指定仓为声笔 iOS 的提供者

**Comment by imfuxiao** [comment]
我的设想是，您这边提供改版的 librime，我这边可以把这个改版后的 librime 作为单独的键盘内置到仓中，至于键盘对应的输入方案，也可以内置到仓中，配合这个改版键盘使用。当然一切都需要测试后看效果。

**Comment by sbxlmdsl** [comment]
> 我的设想是，您这边提供改版的 librime，我这边可以把这个改版后的 librime 作为单独的键盘内置到仓中，至于键盘对应的输入方案，也可以内置到仓中，配合这个改版键盘使用。
> 
> 当然现在只是设想，一切都需要后面看测试的效果。

值得一试，需要配合的地方，请及时告知。声笔的librime仓库在https://github.com/sbxlmdsl/librime

**Comment by isPoto** [comment]
> 我的设想是，您这边提供改版的 librime，我这边可以把这个改版后的 librime 作为单独的键盘内置到仓中，至于键盘对应的输入方案，也可以内置到仓中，配合这个改版键盘使用。
> 
> 当然现在只是设想，一切都需要后面看测试的效果。

没问题，@tansongchen 会负责将声笔整合进仓

**Comment by tansongchen** [comment]
> 我的设想是，您这边提供改版的 librime，我这边可以把这个改版后的 librime 作为单独的键盘内置到仓中，至于键盘对应的输入方案，也可以内置到仓中，配合这个改版键盘使用。
> 
> 当然现在只是设想，一切都需要后面看测试的效果。

@imfuxiao 我看了新的 LibrimeKit 的源码，目前似乎只负责将 librime 编译为 framework 了，那我觉得我可以先做用 LibrimeKit 里的脚本编译声笔定制 librime 的工作（可能需要改脚本的一些地方），编译好了之后让它和现在的 LibrimeKit 发布一样的 Frameworks 文件，然后您再把这个 framework 设法集成到 Hamster 的主项目中。

这个分工您看可以吗？

**Comment by imfuxiao** [comment]
> > 我的设想是，您这边提供改版的 librime，我这边可以把这个改版后的 librime 作为单独的键盘内置到仓中，至于键盘对应的输入方案，也可以内置到仓中，配合这个改版键盘使用。
> > 当然现在只是设想，一切都需要后面看测试的效果。
> 
> @imfuxiao 我看了新的 LibrimeKit 的源码，目前似乎只负责将 librime 编译为 framework 了，那我觉得我可以先做用 LibrimeKit 里的脚本编译声笔定制 librime 的工作（可能需要改脚本的一些地方），编译好了之后让它和现在的 LibrimeKit 发布一样的 Frameworks 文件，然后您再把这个 framework 设法集成到 Hamster 的主项目中。
> 
> 这个分工您看可以吗？

可以的，您可以做一个单独发布 Framework 的仓库，我这边从你的 release 中拉取。

**Comment by tansongchen** [comment]
https://github.com/sbxlmdsl/LibrimeKit/releases/tag/0.0.1

定制版 librime 已经能够编译了，因为其他的依赖不用变，所以我这里只上传了 `librime_sbxlm.xcframework`

另外，考虑到后续维护方便，我打算修改一下 Makefile 以及 librimeBuild.sh 脚本，让它能够同时编译原生 librime 以及定制版 librime，然后提交 pull request 到 imfuxiao/LibrimeKit，您审核通过后合并。这样以后只需要从一个仓库的 release 拉取，您看怎么样？

**Comment by imfuxiao** [comment]
> https://github.com/sbxlmdsl/LibrimeKit/releases/tag/0.0.1
> 
> 定制版 librime 已经能够编译了，因为其他的依赖不用变，所以我这里只上传了 `librime_sbxlm.xcframework`
> 
> 另外，考虑到后续维护方便，我打算修改一下 Makefile 以及 librimeBuild.sh 脚本，让它能够同时编译原生 librime 以及定制版 librime，然后提交 pull request 到 imfuxiao/LibrimeKit，您审核通过后合并。这样以后只需要从一个仓库的 release 拉取，您看怎么样？

可以的，很棒~，谢谢。

**Comment by imfuxiao** [comment]
声笔键盘已内置到仓中，大家可以测试下。
 
TF测试版本链接：https://testflight.apple.com/join/6AkRfQYZ
 
开启键盘：在 iOS 系统设置-> 键盘 -> 添加声笔键盘后，需要搭配声笔词库使用。
声笔词库下载：app内-> 输入方案设置-> + -> 开源方案下载 -> 选择声笔输入法（测试）-> 替换并部署。

**Comment by tansongchen** [comment]
非常感谢！我今天测试了一下，librime 部分完全没有问题，不过在候选的显示上，有几个小问题：

1. 三码及以后，候选上的文字出现了一个额外的提示，这个在 mac 版声笔上是没有的；如，输入 sse，mac 版显示

<img width="150" alt="image" src="https://github.com/imfuxiao/Hamster/assets/31927845/6797cf3e-4fc8-41a5-a016-9fb40a14cfc2">

而手机版是

![IMG_378D380C7D87-1](https://github.com/imfuxiao/Hamster/assets/31927845/d3bfd913-b9b0-44f2-a530-faa2255646fa)

不过，上屏的文字是正确的。

2. 四码及以后，可能会出现多个候选，这时候除第一个候选外，应该显示至多 5 个候选，并分别用 a, e, u, i, o 作为索引，如下：

<img width="455" alt="image" src="https://github.com/imfuxiao/Hamster/assets/31927845/69955761-860f-4986-b29a-9fe59cc95d3d">

不过仓目前只能是 1. 2. 3. 4. 这样

![截屏 2023-11-17 09 47 06](https://github.com/imfuxiao/Hamster/assets/31927845/d7711e77-93f3-4010-9ea9-4c1473d63ea9)

**Comment by tansongchen** [comment]
另外，仓输入法现在有什么方法实现「翻页」这个逻辑吗？我试了 `sendKeys(Tab)` 或者 `sendKeys(Page_Down)`，都没有效果。虽然手机输入法一般不翻页，都是直接展开，但是声笔这种固定候选数量的方案需要这个

**Comment by tansongchen** [comment]
main 分支上的代码好像还没有更新，等您有空把实现声笔的这版发上来，我可以一起来调试这些问题

**Comment by imfuxiao** [comment]
1. 问题：四码及以后，可能会出现多个候选，这时候除第一个候选外，应该显示至多 5 个候选，并分别用 a, e, u, i, o 作为索引。

目前仓显示索引，是仓的内部逻辑，您看是否可以通过 lua 脚本实现这个功能，这样，非声笔键盘也可以兼容。

2. 问题：仓输入法现在有什么方法实现「翻页」这个逻辑吗？

目前仓使用的 librime api是下面列出的 api，所以用分页键是不起作用的，

```c
RIME_API Bool RimeCandidateListBegin(RimeSessionId session_id, RimeCandidateListIterator* iterator);
RIME_API Bool RimeCandidateListNext(RimeCandidateListIterator* iterator);
RIME_API void RimeCandidateListEnd(RimeCandidateListIterator* iterator);
RIME_API Bool RimeCandidateListFromIndex(RimeSessionId session_id,
                                         RimeCandidateListIterator* iterator,
                                         int index);
```

分页功能后面我会做改造，会有个开关，即支持上面的api，也可以支持手工翻页，手工翻页会用下面的 api，这个api是支持翻页的。

```c
RIME_API Bool RimeGetContext(RimeSessionId session_id, RimeContext* context);
```

3. 问题：main 分支上的代码好像还没有更新。

这个问题是平时开发我会在私有库中进行，每次发布商店，我会整理 git 的提交记录，rebase 后在 merge 到此仓库的 main 分支。所以 main 分支没有更新。

4. 问题：三码及以后，候选上的文字出现了一个额外的提示，这个在 mac 版声笔上是没有的

这个问题感觉和第2点是一样的，调用api 的不同造成的，估计使用 `getContext` 的 api 获取候选字后，就没有这个问题了。

**Comment by imfuxiao** [comment]
您好，TF 3.0.0（100）版本增加了分页支持，开启方式：键盘设置 -> 候选栏设置 -> 划动分页模式，选择关闭。

我测试后，您反馈的问题：三码及以后，候选上的文字出现了一个额外的提示，已解决。

现在的问题是：四码及以后，可能会出现多个候选，这时候除第一个候选外，应该显示至多 5 个候选，并分别用 a, e, u, i, o 作为索引。

您看是否已 lua 脚本处理？

**Comment by tansongchen** [comment]
感谢，我这边测试额外提示和翻页的问题均已解决。至于候选索引的问题，声笔其实是设置的 `select_keys`，如 `sbjm.schema.yaml` 中有

<img width="547" alt="image" src="https://github.com/imfuxiao/Hamster/assets/31927845/cbca4c6c-cf5d-4c22-8cfd-ee23bba36dd8">

以及

https://github.com/sbxlmdsl/librime/blob/master/src/rime_api.cc#L311

例如，在鼠须管中，无需配置即可实现

<img width="309" alt="image" src="https://github.com/imfuxiao/Hamster/assets/31927845/dd35b995-b408-4648-af70-e0d6934f504c">

因此我的问题实际上是，能否让仓按 Rime 的 `select_keys` 来显示候选索引？

**Comment by tansongchen** [comment]
另外，由于声笔系列码有用到数字符号参与编码的情况，以及翻页和缓冲区编辑的需求，经过这两天的使用我定制了一款键盘布局，

![IMG_12A6143AD28C-1](https://github.com/imfuxiao/Hamster/assets/31927845/7533e926-eb77-45fa-bb32-5a716af82275)

[声笔 47 键仓输入法键盘布局-1118.yaml.zip](https://github.com/imfuxiao/Hamster/files/13405318/47.-1118.yaml.zip)

如果希望这个键盘布局内置的话，是提交 pr 改这个 https://github.com/imfuxiao/Hamster/blob/main/Resources/SharedSupport/hamster.yaml 文件吗？还是做成像开源输入方案下载一样的功能，提交到别的仓库？

**Comment by imfuxiao** [comment]
内置键盘提交 PR 到 hamster 仓库就可以了。

付啸
Email: ***@***.***
________________________________
发件人: Songchen Tan ***@***.***>
发送时间: Monday, November 20, 2023 9:25:06 AM
收件人: imfuxiao/Hamster ***@***.***>
抄送: morse.hsiao ***@***.***>; Mention ***@***.***>
主题: Re: [imfuxiao/Hamster] 请求用仓作为第三方 librime 引擎的前端并自行发布 (Issue #298)


另外，由于声笔系列码有用到数字符号参与编码的情况，以及翻页和缓冲区编辑的需求，经过这两天的使用我定制了一款键盘布局，

[IMG_12A6143AD28C-1]<https://user-images.githubusercontent.com/31927845/284105545-7533e926-eb77-45fa-bb32-5a716af82275.jpeg>

声笔 47 键仓输入法键盘布局-1118.yaml.zip<https://github.com/imfuxiao/Hamster/files/13405318/47.-1118.yaml.zip>

如果希望这个键盘布局内置的话，是提交 pr 改这个 https://github.com/imfuxiao/Hamster/blob/main/Resources/SharedSupport/hamster.yaml 文件吗？还是做成像开源输入方案下载一样的功能，提交到别的仓库？

―

**Comment by imfuxiao** [comment]
> 感谢，我这边测试额外提示和翻页的问题均已解决。至于候选索引的问题，声笔其实是设置的 `select_keys`，如 `sbjm.schema.yaml` 中有
> 
> <img alt="image" width="547" src="https://user-images.githubusercontent.com/31927845/284035887-cbca4c6c-cf5d-4c22-8cfd-ee23bba36dd8.png">
> 以及
> 
> https://github.com/sbxlmdsl/librime/blob/master/src/rime_api.cc#L311
> 
> 例如，在鼠须管中，无需配置即可实现
> 
> <img alt="image" width="309" src="https://user-images.githubusercontent.com/31927845/284036015-dd35b995-b408-4648-af70-e0d6934f504c.png">
> 因此我的问题实际上是，能否让仓按 Rime 的 `select_keys` 来显示候选索引？

您好，我这里查询到 `alternative_select_labels ` 参数是用来控制显示 label 的， 而 `alternative_select_keys ` 参数是用来控制选字的按键的。

显示索引已按照 ``alternative_select_labels ` 参数调整。至于按键选字功能，我这边测试 `sbjm` 不起作用。

**Comment by tansongchen** [comment]
抱歉，之前表述得不是很清楚，我来详细解释一下：

观察原版 librime 的 RimeGetContext 函数（[这里](https://github.com/rime/librime/blob/master/src/rime_api.cc#L277)），是向 context 写入了 `select_keys` 以及 `select_labels`。也就是说，librime 本质上允许动态的 `select_keys` 和 `select_labels`，它们是随着候选一起传给前端的，前端不需要直接从 schema 里读取 `alternative_select_keys`。

比如，鼠须管支持 keys 和 labels 的[动态渲染](https://github.com/rime/squirrel/blob/master/SquirrelInputController.m#L614)。（这里我不太清楚为什么鼠须管是先试图用 keys 初始化候选栏，然后才用 labels，似乎应该是反过来）

所以，我的意思是，能否用类似的逻辑，动态生成 `select_keys` 和 `select_labels`。声笔系列码确实有针对不同码长或者不同首码用不同的 `select_keys` 和 `select_labels` 的情况，算是利用了这种动态特性。

这里比较复杂，涉及的逻辑很多，可以先不着急实现，一起讨论出一个比较通用的解决方案再实现。

**Comment by imfuxiao** [comment]
> 抱歉，之前表述得不是很清楚，我来详细解释一下：
> 
> 观察原版 librime 的 RimeGetContext 函数（[这里](https://github.com/rime/librime/blob/master/src/rime_api.cc#L277)），是向 context 写入了 `select_keys` 以及 `select_labels`。也就是说，librime 本质上允许动态的 `select_keys` 和 `select_labels`，它们是随着候选一起传给前端的，前端不需要直接从 schema 里读取 `alternative_select_keys`。
> 
> 比如，鼠须管支持 keys 和 labels 的[动态渲染](https://github.com/rime/squirrel/blob/master/SquirrelInputController.m#L614)。（这里我不太清楚为什么鼠须管是先试图用 keys 初始化候选栏，然后才用 labels，似乎应该是反过来）
> 
> 所以，我的意思是，能否用类似的逻辑，动态生成 `select_keys` 和 `select_labels`。声笔系列码确实有针对不同码长或者不同首码用不同的 `select_keys` 和 `select_labels` 的情况，算是利用了这种动态特性。
> 
> 这里比较复杂，涉及的逻辑很多，可以先不着急实现，一起讨论出一个比较通用的解决方案再实现。

我看了下 alternative_select_labels ，设定 `alternative_select_labels ` 后，从 context 中获取的 label 确实是 `alternative_select_labels ` 中设置的值。而 `alternative_select_keys` 感觉是给引擎使用的。

**Comment by tansongchen** [comment]
Squirrel 确实是这么写的，但我感觉，似乎这么写和 `alternative_select_labels` 最初被引入的设计矛盾了，这里是引入时的讨论：

https://github.com/rime/librime/issues/57

可以看到，在首帖的配图中，labels 和 keys 都设置了，但是实际上显示的是 labels，[这一楼](https://github.com/rime/librime/issues/57#issuecomment-148278102)的伪代码也证明了这个逻辑。

 @sbxlmdsl 以前发现过其他前端都是按先 labels 后 keys 设计的（比如，[同文](https://github.com/osfans/trime/blob/3399efbe0dcd0c62f9d878d4b7a38f7b1e288ecb/app/src/main/jni/librime_jni/objconv.h#L33)），反而鼠须管是个特例。

所以，目前感觉可以参考同文的实现。

**Comment by imfuxiao** [comment]
👌，同文的代码是 label 优先，select_key 次之，两者都没有，则使用 index 模式，如果没有问题，我就按照同文的逻辑处理了。

**Comment by tansongchen** [comment]
是这样的，那就麻烦您实现了。实现的时候，注意是从 `context` 读取 `context.menu.select_keys` 和 `context.select_labels` 而不是从 schema 读取就好。

（以下是一点细节的补充说明：声笔在首字母声母的情况下 label 是 `aeuio`，但首字母是 `aeiou` 的时候没有 label，也即 context 中获取的内容并不一定总是配置文件中所写的，这或许是一点点小的 hack 吧，但只要所有前端都约定好从 context 中获取，这个生成 labels 的过程就会成为 librime 的实现细节，兼容性就能够得到保证了。）

**Comment by imfuxiao** [comment]
收到，目前配置是从 context 获取。

**Comment by tansongchen** [comment]
@sbxlmdsl 声笔方案一般是怎么发布的？有没有什么办法可以让用户在仓输入法的「开源方案下载」界面自动下载到最新的方案文件

**Comment by sbxlmdsl** [comment]
我不清楚仓对开源方案的要求，是文本文件下载后在手机上进行编译吗？声笔因为数据结构特殊，不能采用这种方式。而且，userdb相当大，编译需要的时间可能很长，有的手机可能还无法正常完成。所以，仓库大都是以userdb的形式存在的。目前声笔只有windows端是内置userdb并一同安装的。其它前端都是让用户手动下载windows包后手动安装或者更新方案。不知道两位对这种情况也没有更好的方式来处理。

**Comment by imfuxiao** [comment]
仓从下个商店版本后，方案都会上传至苹果的 CloudKit 存储，用户可以在仓的 输入方案设置 -> 方案下载 功能中下载。

目前此功能中方案-> “声笔输入法（测试）” 是我用的 windows 下 zip 包上传的，仅是为了测试使用，暂不清楚目前是否和仓的声笔键盘存在某些不兼容的问题。

另外，声笔的方案如需内置到仓中，可以参考 https://github.com/imfuxiao/HamsterInputSchemas 这个项目。

**Comment by tansongchen** [comment]
了解了，会按照 HamsterInputSchema 的要求来编写下载脚本。

@sbxlmdsl 现在声笔的配置文件是有 `rime.lua` 的，需要按 https://github.com/imfuxiao/HamsterInputSchemas 的要求重构一下，然后在 release 里单独发布一个只包含方案的 zip 包即可，方便我在 HamsterInputSchema 的 build.sh 里下载

**Comment by imfuxiao** [comment]
我理解声笔比较特殊，需要搭配声笔键盘使用，所以不会与别的方案共用，就不用调整方案了。

主要还是方案与键盘兼容性测试，还有上传方案的说明。

**Comment by sbxlmdsl** [comment]
> 了解了，会按照 HamsterInputSchema 的要求来编写下载脚本。
> 
> @sbxlmdsl 现在声笔的配置文件是有 `rime.lua` 的，需要按 https://github.com/imfuxiao/HamsterInputSchemas 的要求重构一下，然后在 release 里单独发布一个只包含方案的 zip 包即可，方便我在 HamsterInputSchema 的 build.sh 里下载

好的，我研究一下。

**Comment by sbxlmdsl** [comment]
@imfuxiao @tansongchen 我已经在github的声笔项目中发布了声笔方案压缩包Sbxlm4iOS.231129.zip，见https://github.com/sbxlm/sbxlm.github.io/releases。

**Comment by imfuxiao** [comment]
商店版本 2.1.0 已内置声笔键盘，此 issue 可以关闭了，后续有问题，可以开新的 issue。
