### ISSUE TITLE
流畅度优待优化，按键太小容易误触

### ISSUE THREAD

**Issue by 2428lu** [imfuxiao/Hamster#3]
目前流畅度不太行，开了震动反馈之后就更卡了。ui方面按键过于小，容易误触。候选栏选词有时候点一下就上了，有时候要点几下才能选中想要的词。目前就这些感觉需要优化，大佬加油

**Comment by imfuxiao** [comment]
非常感谢您的反馈, 卡顿问题及UI问题,我会尽快处理.
