### ISSUE TITLE
候选栏选字有时无响应或误触

### ISSUE THREAD

**Issue by imfuxiao** [imfuxiao/Hamster#30]
候选栏选字有时无响应或误触

**Comment by XiaoyuWant** [comment]
这个问题很影响输入，具体表现为选择候选字时，无法成功选中候选字，而是选中了qwer一行中的字母

**Comment by imfuxiao** [comment]
非常抱歉,确实造成很大的困扰,这跟问题我还在处理中,请在耐心等待下.

**Comment by luojiego** [comment]
这个的确是个大问题，现在很影响正常的使用，我最开始以为是我修改了输入方案导致的，我切换成拼写输入法，发现问题是一致的。

**Comment by imfuxiao** [comment]
> 这个的确是个大问题，现在很影响正常的使用，我最开始以为是我修改了输入方案导致的，我切换成拼写输入法，发现问题是一致的。

确实是个大问题, 所以我这几天一直在处理这个问题. 这个问题有点棘手, 还请耐心等待.

**Comment by xlangzhong1** [comment]
> > 这个的确是个大问题，现在很影响正常的使用，我最开始以为是我修改了输入方案导致的，我切换成拼写输入法，发现问题是一致的。
> 
> 
> 
> 确实是个大问题, 所以我这几天一直在处理这个问题. 这个问题有点棘手, 还请耐心等待.

同样遇到这个问题，感觉这个目前最迫切需要解决的问题

**Comment by luojiego** [comment]
@imfuxiao 问题已确认修复，感谢。

**Comment by imfuxiao** [comment]
不客气应该的, 还有其他问题, 还请再次反馈
