### ISSUE TITLE
更新了词库，然后部署就崩溃了。

### ISSUE THREAD

**Issue by Attiv** [imfuxiao/Hamster#303]
更新的比较大，压缩完还38M，有200w 条左右，部署一会就崩溃了

**Comment by Attiv** [comment]
MAC 和安卓上的中文输入法是可以部署成功的

**Comment by imfuxiao** [comment]
啥情况，输入方案的github仓库发我下，我看看。是1.6版本还是1.7的TF版本？

**Comment by Attiv** [comment]
> 

1.7 的tf, 我在tg 上发吧

**Comment by imfuxiao** [comment]
> > 
> 
> 1.7 的tf, 我在tg 上发吧

嗯嗯，可以直接发给我。

**Comment by tamhaywoo** [comment]
也许和设备本身的处理能力有关，我测试过大型词库在iPhone X上部署退出，但在iPad Pro和macOS上部署没有问题。

**Comment by Attiv** [comment]
> 也许和设备本身的处理能力有关，我测试过大型词库在 iPhone X 上部署退出，但在 iPad Pro 和 macOS 上部署没有问题。

确实有这问题，我的词库在7上崩溃，13正常。不过提这个issue 的原因是我打包脚本漏了我新添加的文件，把很多很大的不应该的文件打包进压缩包了。
