### ISSUE TITLE
如何输入tab符号

### ISSUE THREAD

**Issue by Silent-wqh** [imfuxiao/Hamster#304]
因为在配置文件中需要使用tab键，但是我不知道怎么输入，因而只能复制粘贴已有行并修改。
我曾尝试在配置文件中添加输入tab的码，但是部署后不能实现功能。
我在按键滑动手势中添加tab键，但是键盘上显示添加的手势为空并且实际上也无法输入tab。

**Comment by tamhaywoo** [comment]
如果你是用[雾凇拼音](https://github.com/iDvel/rime-ice)的配置文件，那么你可以通过输入`tab`获得 ⇥

**Comment by Silent-wqh** [comment]
> 如果你是用[雾凇拼音](https://github.com/iDvel/rime-ice)的配置文件，那么你可以通过输入`tab`获得 ⇥

我使用的小鹤音形，具体是http://sj.ysupan.com/flypy 里4.挂接音形码路径下的小鹤音形“鼠须管”for macOS.zip 注释说可以用于仓输入法。
在这个配置文件中，我尝试了输入`tab`，无法获得tab

**Comment by tamhaywoo** [comment]
要是图简单，你就直接在用户自定义文件`custom_phrase.txt`里面添加一行呗
⇥ tab

**Comment by Silent-wqh** [comment]
> 要是图简单，你就直接在用户自定义文件`custom_phrase.txt`里面添加一行呗
> ⇥ tab

我在`custom_phrase.txt`里添加没有生效，并且也在`flypy.scheme.yaml`中引用了这个文件。不知道那里出错了。
最后我在`rime.lua`里添加翻译器并在`flypy.scheme.yaml`中引用后可以输入tab键了。
```yaml
engine:
  translators:
    - lua_translator@tab_translator
```
```lua
function tab_translator(input, seg)
   if (input == "otab") then
      local cand = Candidate("tab", seg.start, seg._end, "\t", " ")
      cand.quality = 1
      yield(cand)
   end
end
```

**Comment by DreamAfar** [comment]
等仓2.0版本吧，已经开始TF内测中，有tab键了，可以自定义键盘添加

**Comment by imfuxiao** [comment]
2.0.0版本已上线，可以使用 `symbol("\t")` 或自定义键盘中的 action: tab 来输入 tab 符号。
