### ISSUE TITLE
請問可以考慮加入更多鍵盤自定義嗎？（主要是增加鍵盤）

### ISSUE THREAD

**Issue by Cju-Jyo-Phiung** [imfuxiao/Hamster#305]
rt，我的方案需要用到一排數字鍵(ps.不是註音)，另外ipad pro用默認ipad鍵手感也挺差的，如果能添加pc那種模板就好多了
謝謝大佬Orz

**Comment by imfuxiao** [comment]
您好，目前1.0版本是不支持的。正在开发中的2.0是可以支持自定义键盘的。

**Comment by Cju-Jyo-Phiung** [comment]
wow，謝謝大佬！狠狠期待了😍

**Comment by imfuxiao** [comment]
2.0.0 版本已上线
