### ISSUE TITLE
关于报错处理

### ISSUE THREAD

**Issue by vvveng** [imfuxiao/Hamster#306]
现阶段类似遇到删除已有词库后本地仍能够继续正常使用，但其他设备恢复会导致中文输出异常，缺少一个报错提醒或者用于用户纠错的显示

**Comment by imfuxiao** [comment]
2.0功能稳定后，会增加一个 RIME 的日志处理功能。感谢反馈~

**Comment by imfuxiao** [comment]
RIME 引擎日志记录及检测功能已添加。
