### ISSUE TITLE
关于按键滑动手势的中英文标点问题

### ISSUE THREAD

**Issue by kchen0x** [imfuxiao/Hamster#307]
![IMG_4076D79EC7E0-1](https://github.com/imfuxiao/Hamster/assets/9739009/c6013f78-0357-4388-9298-15b02c9709c6)

如图，我为了方便在某些按键上下滑动上分别配置了英文符号和中文符号，例如：

- 英文标点 .
- 中文标点 。

但是在中文输入状态下，所有的英文标点都会被自动转换成中文标点，导致英文标点没法通过滑动输入。

**Comment by imfuxiao** [comment]
选项中有 processByRIME 把这个选项设置为 false, 另外也可以使用 `symbole` 代替 `character` 选项
