### ISSUE TITLE
2个问题想请教下大佬

### ISSUE THREAD

**Issue by AlexXQJ** [imfuxiao/Hamster#309]
麻烦请教下大佬, 2个问题哈
1. ios端同步的时候 
   ~文件路径是iCloud~dev~fuxiao~app~hamsterapp/Documents,~
   ~在手机上点同步设置~
   ~这时候在macbook上查看iCloud云盘时发现同步数据在Hamster/RimeSync/ 下~
   ~这个文件夹的名字能改吗?~ 

    在其他issues里看到了,是权限问题,  那请问如果MacBook也要同步的话 是不是路径最好也放到Hamster下?

2. ~同步能用onedrive代替吗?在ios上通过"文件"app 也能看到onedrive的文件夹,就是不知道如何获取具体路径~
 如果是权限问题的话 onedrive是不是也没法用了...因为跨应用了?

**Comment by imfuxiao** [comment]
问题1:

**Comment by AlexXQJ** [comment]
> # 问题1:
> 仓输入法 iOS iCloud 目前固定的**根路径**为：`/private/var/mobile/Library/Mobile Documents/iCloud~dev~fuxiao~app~hamsterapp/Documents/` ，子路径可以自定义。
> 
> MacBook也要同步的话 是不是路径最好也放到Hamster下? 是的，否则仓点击重新部署不会同步其他路径下的文件。
> 
> # 问题2
> 目前同步功能只能支持 iCloud, 其他云盘 WebDAV 模式暂不支持。（等2.0功能稳定后，可以添加对其他 WebDAV 的支持）。
> 
> 如果是权限问题的话 onedrive是不是也没法用了...因为跨应用了? 目前版本只能使用 iCloud 同步。iOS端应该是无法跨应用的，因为有权限的限制。

谢谢大佬指点，我把整个macbook配置好的文件夹，上传到手机里，重新部署后输入法变成了朙月拼音 简化字 ，自定义短语也有了，但输入法的词频顺序很奇怪，排在前面的都是生僻字，常用字反而在很后面，这个是我漏了什么操作吗

**Comment by imfuxiao** [comment]
应该是输入方案的问题，仓只是 RIME 的前端，具体排查还需要看 RIME 的输入方案设置。
