### ISSUE TITLE
请问大佬怎么参与2.0内测

### ISSUE THREAD

**Issue by xuqiccr** [imfuxiao/Hamster#310]
非常期待九宫格的布局，请问怎么可以参与2.0内测呢～

**Comment by noisay** [comment]
> 非常期待九宫格的布局，请问怎么可以参与2.0内测呢～

你找找1.x版本里面有没有TestFlight的链接，通过这个可以，我昨天更新了新测试版，但很遗憾，九宫格好像有问题，我切换成九宫格后，只能打出来大写英文字母

**Comment by imfuxiao** [comment]
TF测试链接：https://testflight.apple.com/join/6AkRfQYZ

2.0目前TF版本bug有点多，尝鲜有风险，请一定要注意：备份！！！备份！！！数据无价！！！

九宫格需要对输入方案做配置调整才能使用，目前内置输入方案没有添加九宫格的支持，需要您自行导入输入方案，

这里有我测试使用的配置，您可以参考下，[雾凇输入方案-仓输入法九宫格配置](https://github.com/imfuxiao/rime-ice/blob/main/others/hamster/%E4%B9%9D%E5%AE%AB%E6%A0%BC/rime_ice.custom.yaml)

其他如仓颉键盘，注音键盘都需要配合相应的输入方案才有效。不过仓颉和注音的输入方案在可以在 Squirrel 输入法中提取。

**Comment by xuqiccr** [comment]
[雾凇输入方案-仓输入法九宫格配置](https://github.com/imfuxiao/rime-ice/blob/main/others/hamster/%E4%B9%9D%E5%AE%AB%E6%A0%BC/rime_ice.custom.yaml) 导入rime文件夹后重新部署，好像还是只能输入大写英文字母，我的输入方案勾选的是四叶草，请问是我的使用方式有问题吗

**Comment by imfuxiao** [comment]
抱歉，本地刚才忘提交了，你在重新下载下，记得是整个输入方案，不是只有一个配置文件。连接中的那个配置文件只是对雾凇输入方案的 patch。
下载并上传后选择“雾凇拼音(九宫格)”

**Comment by xuqiccr** [comment]
[如何导入"雾淞拼音输入方案"](https://github.com/imfuxiao/Hamster/wiki/%E5%A6%82%E4%BD%95%E5%AF%BC%E5%85%A5%22%E9%9B%BE%E6%B7%9E%E6%8B%BC%E9%9F%B3%E8%BE%93%E5%85%A5%E6%96%B9%E6%A1%88%22)  按这个教程导入后，方案选择里有雾凇拼音以及各种双拼，但没有雾凇拼音(九宫格)

**Comment by imfuxiao** [comment]
你需要把 https://github.com/imfuxiao/rime-ice/blob/main/others/hamster/%E4%B9%9D%E5%AE%AB%E6%A0%BC/rime_ice.custom.yaml 这个文件放到雾凇的根目录下

**Comment by xuqiccr** [comment]
有了！不过出来的是很小字体的大写英文字母

**Comment by xuqiccr** [comment]
![方案选择界面](https://github.com/imfuxiao/Hamster/assets/24631912/ed4f3f91-92d8-4bed-8f9c-dc0ef1909417)
![打字界面](https://github.com/imfuxiao/Hamster/assets/24631912/4108c336-66b3-45ab-91a4-f51e348fe381)

https://github.com/imfuxiao/Hamster/assets/24631912/f5531676-3bd4-4221-86d0-75d163fcbade

**Comment by imfuxiao** [comment]
这个问题改过么？https://github.com/imfuxiao/rime-ice/blob/main/others/hamster/%E4%B9%9D%E5%AE%AB%E6%A0%BC/rime_ice.custom.yaml

**Comment by xuqiccr** [comment]
没有哎，直接拷贝过去的

**Comment by imfuxiao** [comment]
不应该，直接下载雾凇，把这个文件拷贝到根文件，上传到仓，点击重新部署，选择输入方案，就可以直接使用了，我这边测试是正常的。

你可以把你的输入方案，打成zip上传上来，我做下测试。

**Comment by xuqiccr** [comment]
好，等我下班回去重新搞一次试试，感谢大佬～

**Comment by iDvel** [comment]
我参照作者的示例写好了，已经 push 到雾凇的仓库了，你试试，是个单独的方案，方案选择「雾凇拼音·九宫格」就行了。

**Comment by imfuxiao** [comment]
> 我参照作者的示例写好了，已经 push 到雾凇的仓库了，你试试，是个单独的方案，方案选择「雾凇拼音·九宫格」就行了。

这么快……主要还没有好好测试，不知道那里有坑。

**Comment by iDvel** [comment]
先用上啦~ 再研究研究 🧐
请问一下左侧选择拼音的原理，是不是方案就不能有那些操作 comment 的 Lua 了。

**Comment by imfuxiao** [comment]
很笨的方式，模拟手工退格到模糊拼音前位置，然后替用户输入选择的精确拼音。

**Comment by noisay** [comment]
哈哈哈哈哈哈，两位大佬联动起来了，开心~谢谢两位大佬的付出

**Comment by kchen0x** [comment]
功能还很不稳定，许多功能都还不健全。
暂时无法进行常规使用和测试。先退回正式版了。

**Comment by YorickGu** [comment]
请问有群吗
