### ISSUE TITLE
请问键盘的diy定制的代码教程在哪里，方便给个链接吗

### ISSUE THREAD

**Issue by JanuaryChenMy** [imfuxiao/Hamster#311]
比如ENTER键的样式，我自己设定的，就没有随输入栏的类型儿变化，而自带的中文26键布局，ENTER就会随着变化，或显示换行，或显示send，方便给个教程链接吗？找半天没找到。

**Comment by imfuxiao** [comment]
抱歉，目前按键样式还不能改动。

**Comment by royccg** [comment]
我看见 TF版本的，应该已经可以 自定义键盘了吧，能麻烦 给个自定义的范本或者相关的参考案例吗，谢谢

**Comment by imfuxiao** [comment]
> 我看见 TF版本的，应该已经可以 自定义键盘了吧，能麻烦 给个自定义的范本或者相关的参考案例吗，谢谢

在 wiki 里有文档

**Comment by imfuxiao** [comment]
[自定义键盘布局说明文档](https://github.com/imfuxiao/Hamster/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89%E9%94%AE%E7%9B%98%E5%B8%83%E5%B1%80)
