### ISSUE TITLE
关于隐藏键盘

### ISSUE THREAD

**Issue by JanuaryChenMy** [imfuxiao/Hamster#312]
TF版本。键盘没有隐藏的那个按钮，是我hamster.custom配置问题还是有这个bug？
现在无法手动关闭键盘，一直停留在桌面上

**Comment by imfuxiao** [comment]
解除键盘的按钮没有加到工具栏上，后面会加上去。

**Comment by imfuxiao** [comment]
取消键盘功能已添加
