### ISSUE TITLE
OTA升级16.7后输入法无法使用

### ISSUE THREAD

**Issue by DawnLi-code** [imfuxiao/Hamster#314]
Store和TestFlight版都试过，键盘切换不过去，重置、重新部署也不行

**Comment by imfuxiao** [comment]
使用内置输入方案也无法启动键盘么？

**Comment by DawnLi-code** [comment]
是的，删除后重装，不动任何设置也无法启动键盘。不知道是不是个例，毕竟16.7更新一周了，没看到其他人反馈。

刚更新16.7时用的是TestFlight上一个版本，能输入，但键盘只显示字母，上下划的符号消失了，但实际上下划依然能输入符号。刚好TF又有更新，更新完发觉彻底不能用了。

**Comment by DawnLi-code** [comment]
删除，重启再安装store版后可以用了！

中途还遇到添加键盘后，切换输入法找不到仓输入法的情况，同时app资源库也找不到图标，又重启一次才正常。

谢谢，我关闭这个ISSUES🤝
