### ISSUE TITLE
iOS导入雾凇拼音后，无法启用九宫格

### ISSUE THREAD

**Issue by colinwjd** [imfuxiao/Hamster#315]
![3673188decbc8157213ecd9757f1ae8](https://github.com/imfuxiao/Hamster/assets/7942918/f2f94b6e-8c7a-4f39-9e27-380dc0548598)

**Comment by imfuxiao** [comment]
我看你您的截图是商店版本，商店版本是没有九宫格功能的。目前九宫格功能对应的是在TF的2.0版本，还在测试阶段。

**Comment by colinwjd** [comment]
> 我看你您的截图是商店版本，商店版本是没有九宫格功能的。目前九宫格功能对应的是在TF的2.0版本，还在测试阶段。

好的，期待新版本
