### ISSUE TITLE
custom_phrase不起作用

### ISSUE THREAD

**Issue by Jreen** [imfuxiao/Hamster#317]
忘了说我的机子情况：
13pm,ios16，内测版本
因为我的自定义文件比较多，用9宫格的时候发现没有起到作用

**Comment by imfuxiao** [comment]
您好，麻烦您使用TF最新版本测试下，看问题是否已修复。

**Comment by Sanly** [comment]
不知道我的操作是否正确：我直接修改的“应用文件”下“Rime”文件夹中的“custom_phrase.txt”，然后重新部署，但发现部署后的应用文件和键盘文件中的“custom_phrase.txt”都恢复成默认值。

此外，还有个疑问，“custom_phrase.txt”可以通过“RIME同步”在不同设备上同步吗？
