### ISSUE TITLE
3.0 版本自定义键盘：自定义英文键盘

### ISSUE THREAD

**Issue by shawnwang5** [imfuxiao/Hamster#321]
3.0 版本自定义键盘，能否考虑增加自定义英文键盘的功能呢? 在自定义键盘的布局时，无法指定中英文的模式，导致自定义出来的键盘，始终都只能输入中文。

**Comment by imfuxiao** [comment]
自定义键盘中 Key 的属性中有 Action, 如果是 character 类型默认是经过 rime 引擎处理的，您可以改为 symbol 类型，这个不经过 rime 引擎处理。

**Comment by tamhaywoo** [comment]
哇喔……3.0版本就来了哇

**Comment by imfuxiao** [comment]
> 哇喔……3.0版本就来了哇

TF版本号用的是3.0，对应将来商店版本的2.0，为了 TF 发版本方便，不用等苹果的TF审核。

**Comment by shawnwang5** [comment]
> 自定义键盘中 Key 的属性中有 Action, 如果是 character 类型默认是经过 rime 引擎处理的，您可以改为 symbol 类型，这个不经过 rime 引擎处理。

好的，谢谢。
