### ISSUE TITLE
关于繁简切换

### ISSUE THREAD

**Issue by yepengfan** [imfuxiao/Hamster#323]
开发者您好，非常喜欢这个输入法
目前遇到了一个小问题，请问一下，仓输入法的繁简切换在哪里设置？
目前我的「输入方案」是「小鹤双拼」
在输入功能调整里面的「简繁切换」设置的是「小鹤双拼」
按键滑动手势 选择的是 「123↑ #繁简切换」
然而 滑动切换的时候没反应 请问还有那些需要设置呢？谢谢！

**Comment by imfuxiao** [comment]
您好，Wiki 上有教程，您按着这个试下。

**Comment by yepengfan** [comment]
謝謝 設置好了 我暫時還沒有v2的權限 不過期待正式版！
