### ISSUE TITLE
在部分未适配深色模式的软件中使用键盘时配色不正常

### ISSUE THREAD

**Issue by luozikuan** [imfuxiao/Hamster#325]
我一直开启 iOS 系统的深色模式，使用的仓输入法版本是 3.0.0(22)，在深色模式的软件中显示正常（如微信、知乎等）。

不过在某些未适配深色模式的软件中，键盘是白底白字的，导致按键区看不见内容，如下图，例如淘宝、高德地图。
<p float="left">
<img src="https://github.com/imfuxiao/Hamster/assets/5371065/45a52940-14a1-48ce-a03a-5f34f25d468d" alt="淘宝" width="30%" height="auto">
<img src="https://github.com/imfuxiao/Hamster/assets/5371065/8bac455e-132f-4795-9e40-2b25801947e4" alt="高德地图" width="30%" height="auto">
</p>

但也有某些未适配深色模式的软件中是好的，例如闲鱼
<p float="left">
<img src="https://github.com/imfuxiao/Hamster/assets/5371065/bd44832d-ffad-4014-835c-e8b479ad32b2" alt="闲鱼" width="30%" height="auto">
</p>

而且只有中文键盘有问题，我切换到自定义的英文键盘在所有软件中都是没有问题的
<p float="left">
<img src="https://github.com/imfuxiao/Hamster/assets/5371065/cb2cfada-5649-4a4a-94a6-f51bbd5d415f" alt="高德地图" width="30%" height="auto">
</p>

我的自定义配置文件如下：
[colemak_wubi.zip](https://github.com/imfuxiao/Hamster/files/12876316/colemak_wubi.zip)

**Comment by imfuxiao** [comment]
麻烦测试下 TF 的 24版本，看看是否修复了，我手头没有 iOS 17 真机，部分bug没办法在模拟器中还原，感谢。

**Comment by luozikuan** [comment]
我这边自动更新到 tf 的 25 版本了，经测试，已经都正常了！

**Comment by imfuxiao** [comment]
> 我这边自动更新到 tf 的 25 版本了，经测试，已经都正常了！

感谢反馈。
