### ISSUE TITLE
3.0.0（24）不显示键盘收起图标

### ISSUE THREAD

**Issue by choijck** [imfuxiao/Hamster#326]
如题，ios17.0.3
![WechatIMG37](https://github.com/imfuxiao/Hamster/assets/147698091/90bed199-4663-4236-b983-cc186689ea07)

**Comment by imfuxiao** [comment]
您好，此功能暂未移植到2.0版本，后续添加。

**Comment by imfuxiao** [comment]
键盘取消按键已添加

**Comment by qhjia** [comment]
请问键盘取消按键要在action选项填什么，能麻烦在wiki里加一下吗

**Comment by imfuxiao** [comment]
> 请问键盘取消按键要在action选项填什么，能麻烦在wiki里加一下吗

您好，您指的取消是什么含义，是重新输入么？

**Comment by qhjia** [comment]
就是收起键盘

**Comment by imfuxiao** [comment]
收起键盘没有对应的指令，需要您点下右上角的按钮。如果没有这个按钮，你需要在键盘设置中开启，键盘设置->候选栏设置->显示键盘收起图标。

**Comment by qhjia** [comment]
哦，好的，就是说现在自定义键盘没有办法像系统内置键盘一样加回收键盘的key是吧

**Comment by imfuxiao** [comment]
收起键盘在候选栏上，不占用自定义键盘布局，内置键盘也一样的。不过后面到是可以增加一个收起键盘的指令。

**Comment by qhjia** [comment]
好的，谢谢
