### ISSUE TITLE
自定义键盘高度后 numericNineGrid 界面异常

### ISSUE THREAD

**Issue by luozikuan** [imfuxiao/Hamster#329]
您好，我使用的 testflight 3.0.0(26) 版本，自定义键盘高度后，numericNineGrid 数字九宫格键盘的各键高度不统一，如下图
<p float="left">
  <img src="https://github.com/imfuxiao/Hamster/assets/5371065/9d27dd62-c558-41be-b73a-e52cb2d9860e" width="300" />
  <img src="https://github.com/imfuxiao/Hamster/assets/5371065/12e107ac-4002-4140-979c-a16011f28b61" width="300" /> 
</p>

上图中每行的 rowHeight 自定义值为 52.0
（这个也有个小问题，在 keyboards 下设置 rowHeight 无效，只能在每行上设置）

**Comment by imfuxiao** [comment]
麻烦使用27版本测试下，看是否修复。谢谢~

**Comment by luozikuan** [comment]
> 麻烦使用27版本测试下，看是否修复。谢谢~

试了下，没有修复，现象跟上面报的一样

**Comment by luozikuan** [comment]
试了下 28 版本，numericNineGrid 界面现在是等高的了，不过它的度没有遵循我设置的 52.0 的行高，所以我从自定义的键盘切换到 numericNineGrid 时，键盘会变高一点点。

现在这个状态我觉得已经可以了，这个 issue 我先关闭吧
