### ISSUE TITLE
刚更新1.1.2，发现中文模式下send不能上屏英文

### ISSUE THREAD

**Issue by flay0303** [imfuxiao/Hamster#33]
刚更新1.1.2，发现中文模式下send不能上屏英文了，这是bug还是特性？之前发现上屏英文时会把分隔符比如空格会上屏，这个版本直接不能上屏了，有些不习惯。希望改进，并且能把上屏的分隔符去掉，这样方便中文模式下输入英文。

**Comment by imfuxiao** [comment]
刚查了下, 是我不小心引入了新的bug...我尽快处理...

**Comment by wzxmer** [comment]
可以增加中英的切换按键在空格左边按键里面吗
