### ISSUE TITLE
關扵倉頡和注音佈局的反饋

### ISSUE THREAD

**Issue by PlanetDance19** [imfuxiao/Hamster#331]
字實在太大了，希望能改成像iOS內建輸入法一樣的大小。
現在第三方倉頡好用的不好看，好看的諸如百度捜狗卻又BUG一堆不好用。
希望倉輸入法越來越好
![IMG_0468](https://github.com/imfuxiao/Hamster/assets/99587182/d700eff8-937f-4371-bffb-50ddf81adfe1)

**Comment by gitig** [comment]
希望能对Key的label和KeySwipe的label设置宽度和高度,
我自定义了一个布局, 按倉頡改的, 字母显示的位置偏低, 我想上下居中显示Key的label
, 然后把swipe的label改小一点
![IMG_0005](https://github.com/imfuxiao/Hamster/assets/3177690/43583d96-17a4-4bc5-b2c0-d220961ad382)

**Comment by imfuxiao** [comment]
您好，目前可以通过按键样式调整单个按键的字体大小，也可以通过键盘样式调整整体键盘的字体大小，因此关闭此 issue。
