### ISSUE TITLE
3.0.0(27)的深色模式下按键底圆角

### ISSUE THREAD

**Issue by BrianZR** [imfuxiao/Hamster#332]
![image](https://github.com/imfuxiao/Hamster/assets/144171605/b26a48b2-b2b3-47a5-9f27-06f91747a569)
感觉底圆角显示有点糊

**Comment by imfuxiao** [comment]
感谢反馈，麻烦使用 3.0.0（30）版本在测试下效果。

**Comment by BrianZR** [comment]
![image](https://github.com/imfuxiao/Hamster/assets/144171605/a337bc7c-5f00-4fe8-b9de-2d3f6928c1fa)
OKOK现在好了 作者大大辛苦 希望仓越来越好

**Comment by imfuxiao** [comment]
感谢您的使用~
