### ISSUE TITLE
3.0版九宫格左侧标点符号栏可否支持拼音过滤

### ISSUE THREAD

**Issue by noisay** [imfuxiao/Hamster#333]
就像下图所示两张图一样，这样通过左侧的拼音选择过滤，能够一定程度上加快选字效率
![IMG_4905](https://github.com/imfuxiao/Hamster/assets/16579487/f2bb1fb3-c9c9-410c-b7b5-5a745715c77a)
![IMG_4903](https://github.com/imfuxiao/Hamster/assets/16579487/aa135c80-fbed-49d4-aebd-d262ceeeb291)

**Comment by imfuxiao** [comment]
您好，中文九宫格的拼音候选问题，见 #322 。
