### ISSUE TITLE
关于验证码 tf IOS17

### ISSUE THREAD

**Issue by JanuaryChenMy** [imfuxiao/Hamster#335]
感觉字体有些太窄了，底部还遮挡了一些，看上去像失真的缩略图
![image](https://github.com/imfuxiao/Hamster/assets/42561739/93953d1f-fbe3-4a66-81d9-98c9f1d20ba3)

**Comment by ZZZ7664** [comment]
请问TF版本的邀请码是什么？

**Comment by imfuxiao** [comment]
> 感觉字体有些太窄了，底部还遮挡了一些，看上去像失真的缩略图 ![image](https://user-images.githubusercontent.com/42561739/275971198-93953d1f-fbe3-4a66-81d9-98c9f1d20ba3.png)

您是指验证码上的文字显示么？这个是系统设置的，不是仓键盘设置的。

**Comment by ZZZ7664** [comment]
> > 字体感觉有些太窄了，底部还远了一些，看起来像失真的大概![图像](https://user-images.githubusercontent.com/42561739/275971198-93953d1f-fbe3-4a66-81d9-98c9f1d20ba3.png)
> 
> 您是指验证码上的文字显示么？这是系统设置的，不是仓键盘设置的。

你好，请问我要怎么才能加入测试？

**Comment by ZZZ7664** [comment]
很不好意思再次打扰你，在这里我想说的是我已经找到了

> > 感觉字体有些太窄了，底部还遮挡了一些，看上去像失真的缩略图 ![image](https://user-images.githubusercontent.com/42561739/275971198-93953d1f-fbe3-4a66-81d9-98c9f1d20ba3.png)
> 
> 您是指验证码上的文字显示么？这个是系统设置的，不是仓键盘设置的。

很抱歉再次打扰你，我想说的是我已经找到了

**Comment by imfuxiao** [comment]
TF版本bug多，不稳定，商店版本在TF测试完成的基础上发布。
