### ISSUE TITLE
tf ios17

### ISSUE THREAD

**Issue by JanuaryChenMy** [imfuxiao/Hamster#337]
抖音，系统，均是深色模式，键盘配色突然这样了，自带的26布局，无配色。
![image](https://github.com/imfuxiao/Hamster/assets/42561739/48316b6b-a25b-45d7-b107-122ce60f10ba)

**Comment by imfuxiao** [comment]
TF 32 版本更新了配色设置，为了支持浅色模式和深色模式两种模式切换，修改了配色参数，麻烦您使用 TF 33 版本在测试下。
