### ISSUE TITLE
tf ios17 字乱码

### ISSUE THREAD

**Issue by JanuaryChenMy** [imfuxiao/Hamster#338]
以前好像是不会这样的 不知道是哪个版本开始的
![image](https://github.com/imfuxiao/Hamster/assets/42561739/cba642eb-406f-4387-8ec1-2edd87de8ce1)

**Comment by imfuxiao** [comment]
感觉是输入方案的问题，请问用的什么输入方案？

**Comment by JanuaryChenMy** [comment]
> 感觉是输入方案的问题，请问用的什么输入方案？

是星猫键道的最新版，有30万词库的版本

**Comment by imfuxiao** [comment]
内置星猫没有此问题，个人猜测是词库的文字超过了系统中文字体范围。
