### ISSUE TITLE
关于剪贴板

### ISSUE THREAD

**Issue by JanuaryChenMy** [imfuxiao/Hamster#339]
新增的剪贴的一系列功能太棒了，大佬能不能加个剪贴板的功能呀，市面上好像没有可替代的方案，不知键盘侧能做这个功能吗？文字以及图片的拷贝历史记录。

**Comment by imfuxiao** [comment]
剪贴板这个功能要往深的做，可以做的功能太多了。目前在做商店版本的最后封版，新功能会等2.0商店版本发布后在继续。

**Comment by JanuaryChenMy** [comment]
好的，ios真是没有好的剪贴板，我现在用快捷指令自己写了个剪贴板，简陋的很😂
![image](https://github.com/imfuxiao/Hamster/assets/42561739/86930d7c-4622-4ec1-abd2-3da9d3e2f1b8)

**Comment by DoerLa** [comment]
同样希望有剪贴板功能，可以先来个简单的，后面再做功能，就无敌了

**Comment by Nemophilister** [comment]
爆杀市面上所有输入法，用苹果不就是图个简洁，国产三方，三方键盘整那些花里胡哨的一点用没有，支持作者加油

**Comment by Nemophilister** [comment]
> 好的，ios真是没有好的剪贴板，我现在用快捷指令自己写了个剪贴板，简陋的很😂
> ![image](https://github.com/imfuxiao/Hamster/assets/42561739/86930d7c-4622-4ec1-abd2-3da9d3e2f1b8)

Jsbox啊 Pin taio 都是啊 美区商店搜一下

**Comment by lewoking** [comment]
+1

**Comment by JanuaryChenMy** [comment]
> > 好的，ios真是没有好的剪贴板，我现在用快捷指令自己写了个剪贴板，简陋的很😂
> > ![image](https://github.com/imfuxiao/Hamster/assets/42561739/86930d7c-4622-4ec1-abd2-3da9d3e2f1b8)
> 
> Jsbox啊 Pin taio 都是啊 美区商店搜一下

不行，我这几年试过两次了有，都是因为......好像是无法连续复制？？还是得浮窗挂着？还是什么原因，又都卸载了。

**Comment by AeonWorks** [comment]
剪切板工具是个独立于输入法的功能。国人做的 ToMemo 已经很不错。

**Comment by imfuxiao** [comment]
您好，2.9.0 版本已加入剪贴板功能。
