### ISSUE TITLE
关于键盘的滑动设置

### ISSUE THREAD

**Issue by JanuaryChenMy** [imfuxiao/Hamster#340]
今天更新剪贴功能才开始用这里的ui，有个问题，这里的设置并没有和hamster.custom.yaml联动，那我到底该改哪个...，现在是一半一半

**Comment by JanuaryChenMy** [comment]
是的，又发现个问题：重新部署后，ui侧定义的滑动设置被hamster.custom.yaml覆盖了。

**Comment by imfuxiao** [comment]
hamster.custom.yaml 是用户对配置的补丁，程序不会自己生成这个文件，只是每次部署的时候读取这个文件。

hamster.custom.yaml中的配置优先级最高，其次是同级的 hamster.yaml，最后是内置应用。

如果你是用文件定义程序配置，那么需要每次自己调整 hamster.custom.yaml。否则，hamster.custom.yaml 下的内容会覆盖掉程序内的配置。
