### ISSUE TITLE
符号与英文面板

### ISSUE THREAD

**Issue by JanuaryChenMy** [imfuxiao/Hamster#341]
切换英文→输入英文→点击123→输入.→回到了中文键盘。

默认26布局

**Comment by imfuxiao** [comment]
“键盘设置->符号设置->返回主键盘” 功能下的符号列表中，删除.符号

**Comment by xuehongyanL** [comment]
能否返回“上一个键盘”也就是英文键盘呢？

**Comment by imfuxiao** [comment]
> 能否返回“上一个键盘”也就是英文键盘呢？

没明白您的意思，您可以重新开一个  issue 说明您的问题。
