### ISSUE TITLE
调不出中文

### ISSUE THREAD

**Issue by JanuaryChenMy** [imfuxiao/Hamster#342]
ios17，tf，偶发调不出中文键盘，连按钮都没有，一般是点了输入框弹出的是英文键盘
![image](https://github.com/imfuxiao/Hamster/assets/42561739/bd6ee17b-de1e-4b99-8bbd-6ca520fc98f9)

**Comment by imfuxiao** [comment]
看情况是输入法掉了，系统加载的是系统内置键盘，这个情况在1.0也发生过，可能是键盘crash导致的，看看是否有崩溃的提示，如果有，记得点个发送。

**Comment by iflamma** [comment]
> 看情况是输入法掉了，系统加载的是系统内置键盘，这个情况在1.0也发生过，可能是键盘crash导致的，看看是否有崩溃的提示，如果有，记得点个发送。

2023.11.10 更新的appstore 2.0版本，选择四叶草+九宫格，打不出中文

**Comment by imfuxiao** [comment]
> 2023.11.10 更新的appstore 2.0版本，选择四叶草+九宫格，打不出中文

中文九宫格需要配合支持九宫格的输入方案才能使用，目前雾凇输入方案已支持仓的九宫格键盘，您可以导入雾凇输入方案后，选择“雾凇·九宫格”方案使用。

**Comment by iflamma** [comment]
> > 2023.11.10 更新的appstore 2.0版本，选择四叶草+九宫格，打不出中文
> 
> 中文九宫格需要配合支持九宫格的输入方案才能使用，目前雾凇输入方案已支持仓的九宫格键盘，您可以导入雾凇输入方案后，选择“雾凇·九宫格”方案使用。

谢谢大佬，雾凇导入后重新部署可以使用了
