### ISSUE TITLE
关于键盘默认高度问题

### ISSUE THREAD

**Issue by pointerto** [imfuxiao/Hamster#343]
好像相较于内置键盘低了一些，以那些按键显得小了很多，不知道开发者有没有考虑增加调整高度的功能？

**Comment by 986138497** [comment]
同问

**Comment by imfuxiao** [comment]
您好，是指TF版本还是商店版本？

**Comment by 986138497** [comment]
> 按键显得小了很多，不知道开发者有没有考虑增加调整高度的功能？



> 您好，是指TF版本还是商店版本？

目前用的 tf 版本也是, 后期能增加配置吗

**Comment by imfuxiao** [comment]
您好，关于高度的问题，个人想法是：

1. 内置键盘高度与系统键盘保持一致，
2.  只有行高，没有键盘总体高度，因为不同的行可能需求的高度不一样。

基于以上两点，当前版本（商店及TF版本）都不支持设置键盘高度。

等TF版本上线后，如果有个性化的需求，建议使用自定义键盘来实现。
