### ISSUE TITLE
最新TF版本（38）的几个问题

### ISSUE THREAD

**Issue by chazikai24** [imfuxiao/Hamster#344]
输入方案采用的是雾凇拼音
1.26键UI只有上划的标点符号没有下滑的符号。
2.键盘启用配置，永远只在第一个皮肤上，没法改成其他的皮肤

**Comment by xubai2001** [comment]
> 输入方案采用的是雾凇拼音 1.26键UI只有上划的标点符号没有下滑的符号。 2.键盘启用配置，永远只在第一个皮肤上，没法改成其他的皮肤

1、内置的中文26键需要在键盘布局>滑动设置>按键的滑动方向那里打开 “是否显示文本”

**Comment by chazikai24** [comment]
> > 输入方案采用的是雾凇拼音 1.26键UI只有上划的标点符号没有下滑的符号。 2.键盘启用配置，永远只在第一个皮肤上，没法改成其他的皮肤
> 
> 1、内置的中文26键需要在键盘布局>滑动设置>按键的滑动方向那里打开 “是否显示文本”，也可以编辑hamster.yaml把display: false改成true(有hamster.custom.yaml的话，就在这个里面改)

找到了，在滑动设置里，需要针对每个按键的下划里打开是否显示文本，感谢

**Comment by imfuxiao** [comment]
> 2.键盘启用配置，永远只在第一个皮肤上，没法改成其他的皮肤

问题2可否详细描述下？

**Comment by changzaicl** [comment]
重新copy配色方案到hamster.yaml文件中，就可以了。好像是程序会将配色方案清空

**Comment by S-A9** [comment]
TF兑换吗是多少?

**Comment by imfuxiao** [comment]
您好，请反馈下最新版本是否还存在这个问题。

**Comment by chazikai24** [comment]
> 您好，请反馈下最新版本是否还存在这个问题。

最新版已经没有这个问题了

**Comment by imfuxiao** [comment]
感谢您的反馈
