### ISSUE TITLE
tf版键盘字体问题

### ISSUE THREAD

**Issue by PaPerseller** [imfuxiao/Hamster#345]
若系统设置内设置了加粗字体后键盘字体会自动跟随加粗，但关闭后，键盘字体却仍会停留在粗体，需通过重新配置才能恢复。
同时能否增加默认方案下字体自定义粗细的功能。

**Comment by imfuxiao** [comment]
TF 版本已支持字体设置功能。

注意：需要通过配置文件设置，UI暂不支持。
