### ISSUE TITLE
中英文切换按钮能否像九宫格那样，都放在空格右侧

### ISSUE THREAD

**Issue by imlijq** [imfuxiao/Hamster#347]
最新的 tf 版，3.0.0(41)

我使用的是九宫格布局，切换中英文按钮在空格右侧：

![photo_2023-10-25_14-59-20](https://github.com/imfuxiao/Hamster/assets/19914442/550f264d-cf3c-42df-95fa-28079ebb6261)

点击的时候人的肌肉和潜意识其实已经形成了一个记忆，就是这个中英文切换按钮在这个空侧右侧，也就是更靠近屏幕右侧的位置。

当我点击之后，切换到了英文字母布局，这个按钮却跑到了最左侧，这时我要想切换回九宫格布局，手指就需要往左移动到屏幕最左侧的位置去点击，这就把上一步已经形成的习惯和记忆打乱了。

![photo_2023-10-25_14-59-19](https://github.com/imfuxiao/Hamster/assets/19914442/2275d2e3-c77e-4ba4-92c9-921f7019110c)

不管是习惯右手操作还是左手操作手机，体验上不够顺畅，感觉还是固定在一个位置更好，建议像搜狗输入法一样，统一固定在九宫格布局空格右侧的位置：

![photo_2023-10-25_14-59-17](https://github.com/imfuxiao/Hamster/assets/19914442/0806c73d-158d-4277-97a8-b8855bccdc14)

![photo_2023-10-25_14-59-16](https://github.com/imfuxiao/Hamster/assets/19914442/abb10087-9b5c-46d5-8e0e-789bfdb1fa01)

而且根据上边的第二张截图，英文状态下是没办法直接切换到符号选择布局的，英文状态下只能输入“.”这个符号，那当我在英文布局时要输入一个邮箱，比如 abc@gmail.com ，输入这个@符号，我需要先在英文布局时，点中英文切换按钮切换回九宫格布局，然后再点击符号按钮切换到符号选择布局，输入@之后，还需要返回到九宫格布局，然后再切换到英文输入剩下的 gmail.com。这就很麻烦，所以英文状态下，也是需要一个符号切换按钮存在的。可以从英文->符号，符号->英文，而不是每次都要经过九宫格过渡：英文->九宫格->符号，符号->九宫格->英文。（当然在英文状态下输入符号比如@，最快的方式还是像搜狗这样，将一些常用符号放在字母按钮上，然后通过上滑输出，这样连符号布局都不用切换了）

建议键盘布局多参考下搜狗输入法，毕竟已经做了十几年了，也经过了几千万用户的验证了。

感谢开发者。

**Comment by changzaicl** [comment]
3.0.0（41）26键，候选栏文字显示遮挡问题严重，试了很多次。
换回3.0.0（39）一切正常。虽然3.0.0（39）候选词选项宽度比之前的变大了

**Comment by imfuxiao** [comment]
收到，感谢反馈，我尽快优化下按键布局。

**Comment by changzaicl** [comment]
试了3.0.0（38） → （44）的所有版本，个人感觉（38）的UI最好，具体表现在：
1. 候选栏文字高度适中，现在版本（44）过高。我在hamster.yaml中找不到调整参数。
2. 版本（38）键盘设置中的，候选字体大小、工具栏高度和编码区高度可以找到一个合适值。现在版本（44）总是出现候选词太小的情况。
非常好用，谢谢！

**Comment by skypoc** [comment]
@imlijq 请问您的九宫格是怎么配置的？我选四叶草+九宫格，没办法输出中文

**Comment by imlijq** [comment]
> 收到，感谢反馈，我尽快优化下按键布局。

安装了 tf 3.0.0(51) 之后那个中英文切换按钮都在同一个位置了，谢谢开发者，并且英文布局也有进入符号选择布局的按钮了，但是进入符号选择布局之后，按返回，总是返回到九宫格布局。感觉返回应该是返回上一个布局才是合理的，就是如果从英文进入的符号选择布局，那点返回就是回到英文，从九宫格进入的点返回就是回到九宫格。

**Comment by imlijq** [comment]
> @imlijq 请问您的九宫格是怎么配置的？我选四叶草+九宫格，没办法输出中文

我用的是雾凇拼音，按这个方法操作即可：
https://github.com/imfuxiao/Hamster/wiki/%E5%A6%82%E4%BD%95%E5%AF%BC%E5%85%A5%22%E9%9B%BE%E6%B7%9E%E6%8B%BC%E9%9F%B3%E8%BE%93%E5%85%A5%E6%96%B9%E6%A1%88%22

最后我把“rime-ice/others/Hamster九宫格”目录中的两个 yaml 文件也复制到输入法的 rime 目录了，支持九宫格状态下打出来英文单词。最后选择雾凇拼音输入方案、点重新部署就好了

**Comment by skypoc** [comment]
@imlijq 非常感谢！可以用了。
词频还有点奇怪，应该是需要调教一下

**Comment by skypoc** [comment]
@imlijq 配置完成后没有显示候选拼音，请问是我配置得不对，还是没有完全适配呢？
非常感谢。
![image](https://github.com/imfuxiao/Hamster/assets/68258068/eee07e2a-5ea3-4370-b799-33ca6c478f51)

**Comment by imfuxiao** [comment]
候选拼音功能由于bug，暂时屏蔽了。中文九宫格候选拼音问题 #322 。
