### ISSUE TITLE
关于iPad TF版字母大小

### ISSUE THREAD

**Issue by Sevenyine** [imfuxiao/Hamster#348]
个人感觉iPad上的字母相对整个键盘太小了，希望能自定义一下——（）这样看着有点费眼睛，而且留白也有点多了(*/ω＼*)
感谢！
可能还有一部分原因就是字母粗细（？）反正原生的样子挺舒服的
版本 TestFlight 3.0.0 (41)
对比截图：
![wecom-temp-96519-e87efe3a1d740edf382c7e924b32a7f6](https://github.com/imfuxiao/Hamster/assets/65720409/59af799c-fe50-4f75-ac49-99ddf37fcc3e)
![wecom-temp-105071-4ed5c89b928b1569657fe40c5c647f5d](https://github.com/imfuxiao/Hamster/assets/65720409/5e6a18fa-3fc0-405f-b552-46c61ccecc01)

**Comment by imfuxiao** [comment]
收到，感谢反馈，我尽快优化下。

**Comment by imfuxiao** [comment]
新增键盘设定-字体大小比例参数，可同时放大或缩小按键上全部字体。
