### ISSUE TITLE
空格灵敏度设置消失

### ISSUE THREAD

**Issue by Sevenyine** [imfuxiao/Hamster#350]
Testflight 48版 ipad 无法调节键盘空格横向滑动灵敏度，没有找到这个设置，希望可以加回，感谢！

**Comment by xubai2001** [comment]
swipe/spaceSwipeSensitivity 这个配置项应该是空格滑动的灵敏度，不过我在hamster.yaml以及hamster.custom.yaml均修改为1后，灵敏度依然会很高

**Comment by Sevenyine** [comment]
看见在 3.0.0(69)里添加啦 感谢
