### ISSUE TITLE
扇贝单词中输入界面异常，详见附件

### ISSUE THREAD

**Issue by lovelock** [imfuxiao/Hamster#351]
主要表现为：
1. 切换到英文输入后输入2个字符后自动切换回中文
2. 点删除键后一直播放按键声音，即便退出app也还在响
3. 试了iRime第三方输入法没有类似问题，基本可以排除是扇贝单词的问题

https://github.com/imfuxiao/Hamster/assets/2208731/18b8394d-de02-432f-96cd-a53481b48b53

https://github.com/imfuxiao/Hamster/assets/2208731/5a01da23-84e3-4d38-b26a-57a73ad253f2

**Comment by imfuxiao** [comment]
您好，请反馈下商店 2.1.0 版本后还会出现这个问题么？

**Comment by lovelock** [comment]
现在的现象是写完一个单词，跳转到下一个单词之后，会自动切换回中文。没有别的问题了

**Comment by imfuxiao** [comment]
> 现在的现象是写完一个单词，跳转到下一个单词之后，会自动切换回中文。没有别的问题了

目前键盘的初始状态有两个：一个是输入方案，另一个是键盘布局。

键盘布局每次键盘隐藏重新弹出时，都会返回到设置的键盘布局。而输入方案是可以持久化的，目前折中的方案是：

方案1: 在自定义一个英文输入方案，用来输入英文，这样每次弹出就可以持久保持状态。

方案2: 仓的键盘和系统自带英文键盘，两个键盘之间切换。
