### ISSUE TITLE
输出词语的权重没有持久的保存下来

### ISSUE THREAD

**Issue by imlijq** [imfuxiao/Hamster#352]
最新的 tf 版，3.0.0(51)

我用的雾凇拼音九宫格输入方案，比如我想打出“鉴于”这个词，第一次输的时候“鉴于”在候选词第6的位置，第二次在候选词第2的位置，随着我选中它的次数增多它最后排到了第1个位置。但是我手机做一些其他操作，比如切换到默认的中文、英文、符号输入法之后，最后再切换回来，这个“鉴于”又回到了最开始第6个位置，感觉就是我每次选择的候选词的权重没有保存下来，或者只是临时保存下来了只要做点其他操作就消失了

录屏：

https://github.com/imfuxiao/Hamster/assets/19914442/2dd08468-884c-47ca-9c66-d51db65ebd6c

理想的情况的是像Windows小狼毫那样，将权重持久保存，然后每次点击同步的时候，将这些数据输出到 sync_dir 指定的目录中，然后在 rime_ice.userdb.txt 中就能找到所有打出过的词语和权重

**Comment by skypoc** [comment]
@imlijq 你好，我之前在另一个issues下询问九宫格配置的用户。
为什么您的雾凇配置有拼音候选词呢？作者反馈说目前没有开放这个功能：https://github.com/imfuxiao/Hamster/issues/347#issuecomment-1783991028
我是按照教程导入了雾凇的配置，输入方案是雾凇拼音九宫格
非常感谢

**Comment by imlijq** [comment]
> @imlijq 你好，我之前在另一个issues下询问九宫格配置的用户。 为什么您的雾凇配置有拼音候选词呢？作者反馈说目前没有开放这个功能：[#347 (comment)](https://github.com/imfuxiao/Hamster/issues/347#issuecomment-1783991028) 我是按照教程导入了雾凇的配置，输入方案是雾凇拼音九宫格 非常感谢

我这里出现的不是拼音候选词，点了可能不管用我没太注意，应该就是仓输入法里可以设置显示候选词序号、拼音那里的原因
