### ISSUE TITLE
几个功能建议

### ISSUE THREAD

**Issue by cj233cj** [imfuxiao/Hamster#353]
- 单手键盘功能，最好是覆盖各类自定义方案（9格/全键盘）的全局设置
- 搜狗等词库的导入，能兼容双拼/全拼中英文混输方案最好
- 模糊音
- 双击空格自动添加句号
- 比较明确的分词键设置

**Comment by g6ai** [comment]
这些功能都是Rime配置可以实现的。所以实现这个需求，既可以是提供自定义教程，也可以是做到默认配置中去。op希望哪种方法呢

**Comment by cj233cj** [comment]
> 这些功能都是Rime配置可以实现的。所以实现这个需求，既可以是提供自定义教程，也可以是做到默认配置中去。op希望哪种方法呢

app内能直观切换/设置是最好，或者提供一个配置模板方便普通用户修改

**Comment by justry** [comment]
我也提一个原生输入法自带的一个小功能：在候选栏下滑就能打开全部候选文字，而不用去点候选栏最右侧的下拉小箭头，我猜这个原生小功能很多人都不知道吧。

**Comment by imfuxiao** [comment]
- 双击空格上屏句号
- 分词键设置
后续版本会做优化，因此关闭此 issue。
