### ISSUE TITLE
空格上滑次选和左右滑移动光标同时生效，产生不想要的移动

### ISSUE THREAD

**Issue by qhjia** [imfuxiao/Hamster#355]
用空格上滑进行次选时，会立刻上屏，如果这个操作让所有字符都上屏，让候选栏空掉，而手指还没松开，这时左右移动手指就会让光标也跟着移动。这样就会导致在上滑不正的时候光标错位。
感觉正确的逻辑应该是上滑松手后再上屏，或者就算上屏了仍锁定住不允许左右滑。

**Comment by imfuxiao** [comment]
感谢反馈，您的意见很好。 根据您的意见，我会优化下相关代码。

**Comment by imfuxiao** [comment]
您好，麻烦您测试下 TF 最版本，看是否已修复此问题。

**Comment by qhjia** [comment]
现在上划不会直接上屏，但我发现候选栏有内容的时候空格左右划仍然生效，这和发行版不一样，是新加的feature吗？感觉不是很符合使用习惯，还是像发行版一样，候选栏有内容就不允许移动比较好。
另外我还发现了两个相关的小问题：
1. 上滑的触发角度非常小（体感比发行版小），滑歪了一点就触发不了，感觉可以再调大一点。
2. 我理解的现在空格移动的逻辑是，长按空格一段时间后就进入移动模式，不论手指移动到哪里，就在那个高度留下记录，然后只能在那个高度移动才能移动光标（发行版是不限制高度的）。我觉得稍微长按一段时间空格才能触发移动是合理的，但没必要限制高度，只要进入了移动模式就能在整个键盘范围移动就挺好的。

**Comment by imfuxiao** [comment]
> 现在上划不会直接上屏，但我发现候选栏有内容的时候空格左右划仍然生效，这和发行版不一样，是新加的feature吗？感觉不是很符合使用习惯，还是像发行版一样，候选栏有内容就不允许移动比较好。 另外我还发现了两个相关的小问题：
> 
> 1. 上滑的触发角度非常小（体感比发行版小），滑歪了一点就触发不了，感觉可以再调大一点。
> 2. 我理解的现在空格移动的逻辑是，长按空格一段时间后就进入移动模式，不论手指移动到哪里，就在那个高度留下记录，然后只能在那个高度移动才能移动光标（发行版是不限制高度的）。我觉得稍微长按一段时间空格才能触发移动是合理的，但没必要限制高度，只要进入了移动模式就能在整个键盘范围移动就挺好的。

1. 划动的角度限制是有参数设定的，在 hamster.yaml 中  `swipe` 下 的 `tangentThreshold`，您可以使用配置文件调整此参数。
2. 您说的非常对，目前有一个长按的时间阈值，超过此阈值才会触发长按操作，而空格移动光标就是目前长按触发的。至于您说的高度问题，目前是在划动的过程中，有一个y轴的判定，超过轴一定距离后，就不识别了。
