### ISSUE TITLE
最新的tf版本（65）输入法设置中点击条目程序就会崩溃

### ISSUE THREAD

**Issue by kunpehx** [imfuxiao/Hamster#356]
![image](https://github.com/imfuxiao/Hamster/assets/23466404/de3452b1-ba69-4cde-84b8-bf8c08775b2f)

**Comment by ddqp** [comment]
同样闪退

**Comment by imfuxiao** [comment]
抱歉，65版本做了配置文件格式变动，不兼容之前版本，且没有做升级补丁，于是导致了 Crash。

65 版本已被下线，请升级到 67 版本。
