### ISSUE TITLE
关于hamster.custom.yaml的疑问

### ISSUE THREAD

**Issue by xubai2001** [imfuxiao/Hamster#357]
每次重新部署后，hamster.yaml的内容会合并到hamster.custom.yaml中，在之前数个版本是概率发生，最新的(69)版本中稳定复现，请问这是预期的行为吗？

**Comment by imfuxiao** [comment]
Rime/hamster.yaml 与 Rime/hamster.custom.yaml 是用户自定义配置文件，程序不会修改的。你看看是否有可能其他因素导致的。

**Comment by xubai2001** [comment]
> Rime/hamster.yaml 与 Rime/hamster.custom.yaml 是用户自定义配置文件，程序不会修改的。你看看是否有可能其他因素导致的。

找到原因了，是在最近更新中，发生了合并到custom文件的情况，我最近又刚好开启了icloud同步，致使合并的文件同步到icloud,才导致每次本地修改后自动部署，icloud内的custom文件覆盖了本地文件，谢谢您的回复
