### ISSUE TITLE
关于的“按键滑动手势”的功能建议

### ISSUE THREAD

**Issue by auffry** [imfuxiao/Hamster#359]
1：系统键位方向设置中，滑动方向被锁死，如a↑不能更改为a←或a→，希望后续可以内置到系统设置里，随意更改
2：在滑动“功能”里，希望可以内置一些常用的操作如：复制、粘贴、剪切、全选等功能
再次感谢！

**Comment by imfuxiao** [comment]
> 1：系统键位方向设置中，滑动方向被锁死，如a↑不能更改为a←或a→，希望后续可以内置到系统设置里，随意更改 2：在滑动“功能”里，希望可以内置一些常用的操作如：复制、粘贴、剪切、全选等功能 再次感谢！

1.0的问题会在马上上架的2.0版本解决，敬请期待。
