### ISSUE TITLE
希望首选项和屏幕边缘留一点空隙

### ISSUE THREAD

**Issue by Jmdayou** [imfuxiao/Hamster#36]
希望首选项和屏幕边缘留一点空隙或留下自定义配置参数可进行调整，现在紧贴在屏幕边缘，手机上显示感觉左边的圆角无法完整显示。
![image](https://user-images.githubusercontent.com/130811752/232179149-88e24a27-3415-41b8-81b2-be9e09116264.png)
iPhone默认键盘的空隙如图
<img width="414" alt="image" src="https://user-images.githubusercontent.com/130811752/232179199-c893f064-d28b-4086-8348-160dc0dd2adf.png">

**Comment by imfuxiao** [comment]
谢谢您的反馈, 这个问题已经修正, 预计下个bug修复版本会发布.
