### ISSUE TITLE
表情键盘

### ISSUE THREAD

**Issue by ZZZ7664** [imfuxiao/Hamster#360]
TF 3.0.0（57）  表情键盘没有了嘛  设置快捷键打不开表情了  例如：上滑A键，shortCommand(#emojiKeyboard) 没反应

**Comment by imfuxiao** [comment]
目前 TF 2.0 版本的功能并没有完全覆盖1.0，包括 emoji 键盘，后续会继续移植。

**Comment by ZZZ7664** [comment]
好的 谢谢解答

**Comment by ZZZ7664** [comment]
对了，昨天还是前天是不是刚更新了一下，现在是3.0.0(78) 回车还有回删键上划失效了，目前不清楚是我个人操作问题还是其他问题
