### ISSUE TITLE
关于中英切换的后标点符号不切换的问题

### ISSUE THREAD

**Issue by ZZZ7664** [imfuxiao/Hamster#363]
在之前的商店版中，切换中英后，键盘中的标点符号在上屏时也会相应的进行切换，而现在符号无法跟随整体的切换而切换了，请问这个功能可以加回来吗？

例如：。
e.g. 。 (这个正常应该变成『.』)

**Comment by fqw000** [comment]
如果你尝试设置 `processByRIME: true` 试试呐

**Comment by ZZZ7664** [comment]
请问这个设置在什么位置？

**Comment by ZZZ7664** [comment]
之前设置的符号都是通过RIME处理的

**Comment by stepbackdunk** [comment]
遇到了一样的问题

**Comment by imfuxiao** [comment]
按键上的划动符号，您可以在`键盘设置`->`键盘布局`->`中文26键`-> `划动设置`，设置对应的符号。

如果想让符号由 rime 引擎处理，将输入符号转为其他符号，则选择字符类型，且开启`由 rime 引擎处理` 选项。

如果不想让 rime 引擎处理，就是想输入什么，输出是什么，可以选择 `符号` 类型，并输入自己的符号。
