### ISSUE TITLE
启动 2.0 之后不断的显示「初次启动，需要编译输入」然后「导入数据异常」

### ISSUE THREAD

**Issue by BrainKu** [imfuxiao/Hamster#364]
如标题所示，看到 v2 上也有类似的反馈：[基于 Rime 的 iOS 仓输入法更新 2.0 版本了，自定义键盘布局上线 - V2EX](https://www.v2ex.com/t/990492#;)

我这边是刚卸载重装了仓输入法，系统是 iOS 16.6.1

<img src="https://github.com/imfuxiao/Hamster/assets/6072202/43418c48-1188-4d6b-a0f5-ed0a600c9634" width="300">
<img src="https://github.com/imfuxiao/Hamster/assets/6072202/8b03f9be-0722-4f4d-8c74-af4d690dd78c" width="300">

**Comment by imfuxiao** [comment]
抱歉，我还在排查问题中，

麻烦您在系统设置中的仓的设置界面变更下存储位置，然后在试下。

![image](https://github.com/imfuxiao/Hamster/assets/6482586/010f6d86-5a9d-41e2-81f9-daab14a14e46)

**Comment by imfuxiao** [comment]
感谢您的反馈，问题已找到，预计 2.0.1 版本修复，
