### ISSUE TITLE
微信中，向空输入框里输入汉字的时候“发送”的按钮会变大一下。

### ISSUE THREAD

**Issue by mvpwanhao** [imfuxiao/Hamster#366]
https://github.com/imfuxiao/Hamster/assets/68336164/e9e3b3dc-5aed-4fa1-9284-24e1b58dc245

就第一次输入文字的时候会闪，只要输入框里面有字就不会这样闪了。
试了一下，换成原生的输入法就不会出现这个现象。
===
输入法版本：2.0.0（4）
iOS版本：17.0.3
微信：8.0.43

**Comment by DawnLi-code** [comment]
2.0.1
17.1.1
8.0.43
同样情况，本来以为是微信故意的🤣

**Comment by chouxiang99** [comment]
设置里面又一个嵌入的设置，把嵌入的设置关了，就不会有变化了
