### ISSUE TITLE
您好，2.0.1版键盘按键内字母大小明显变大

### ISSUE THREAD

**Issue by 1786928717** [imfuxiao/Hamster#369]
2.0.1版明显比之前1.x版本好很多，界面变得明显流畅与节能，对开发者表示衷心感谢。
但是相比起1.x版本与ios原生键盘，2.0.1明显按键字母变大了很多（26键拼音、仓颉、9键）
而且小写字母变成了大写字母，看着更大，略不舒适。
这个可以自己改吗，还是开发者会在后续版本中修复呢。
（机型13mini，系统iOS16.1.2(20B110)，软件2.0.1）
![微信圖片_20231110195406](https://github.com/imfuxiao/Hamster/assets/118802767/1a869412-5c3b-4843-bc1a-3ec756241b43)

**Comment by imfuxiao** [comment]
您好，感谢您的反馈，在后续的开发计划中，会有按键级别样式调整，到时会有字体大小的调整。

至于主键盘大写字母的问题，这是个新需求，我看看后续怎么安排调整。

**Comment by 1786928717** [comment]
感谢，很好的软件，已在App Store推荐，会持续关注后续更新。
