### ISSUE TITLE
升级2.0.1以后，下划动文本不显示

### ISSUE THREAD

**Issue by DawnLi-code** [imfuxiao/Hamster#370]
App Store版本2.0.1
iPhone 15
iOS17.1.1 

删除旧版，重启手机，安装store版本，默认设置，键盘皮肤只显示上划的文本，不显示下划的文本。

键盘设置里的“关闭划动显示文本”开关有效，打开以后上下划动文本都不显示。

**Comment by imfuxiao** [comment]
抱歉，默认配置下，下划是不显示的，您可以在 键盘布局 -> 中文26键，点击 > 进入设置，在划动设置部分，开启下划显示，同时您也可以对每个键的上下左右划动自定义调整。

**Comment by DawnLi-code** [comment]
谢谢，可以显示了。藏的有点深了，我反反复复翻了软件设置，没想到在那里面😂。然后点了20多次，都打开了。
