### ISSUE TITLE
注音键盘字体描边不一致

### ISSUE THREAD

**Issue by kanwakyuudai** [imfuxiao/Hamster#371]
![截圖 2023-11-10 22 57 49 jpeg](https://github.com/imfuxiao/Hamster/assets/17743934/66ec2508-410e-44c7-80a3-6d540f0b33b9)

另外希望候选栏可以加一个emoji功能

**Comment by imfuxiao** [comment]
收到，感谢您的反馈。

emoji 键盘后续会开发的，字体不一致的问题，我查下原因。
