### ISSUE TITLE
可調鍵面字體大小、鍵面響應大小寫切換

### ISSUE THREAD

**Issue by LEOYoon-Tsaw** [imfuxiao/Hamster#372]
非常感謝作者製作的倉輸入法，終於有一個好用的iOS輸入法了！
只是我有兩個建議：
1. 可調鍵面字體大小，默認字號西文合適，但中文（如用倉頡鍵盤）則感到字太大了；
2. 大小寫切換在鍵面上反映爲加粗，但並不直觀，希望能分別設置大小寫狀態下的鍵面，默認則可用A、a

**Comment by imfuxiao** [comment]
嗯嗯，感谢您的反馈，后续版本会做优化。

**Comment by imfuxiao** [comment]
您好，

1. 字体大小的问题：目前版本字体大小可以在「键盘配色」中调整，也可使用单个的「按键样式」去调整。
2. 大小写加粗的问题，新版本已无此问题。另外您可以使用自定义字体来修改默认键盘字体。

因此关闭此 issue，如您还有相关问题，可重新打开此 issue。
