### ISSUE TITLE
iOS端最新更新问题

### ISSUE THREAD

**Issue by 971230** [imfuxiao/Hamster#374]
本人一直使用的是默认的仓输入法，APPStore下载下来就没有更改任何东西，一直使用的还习惯的。最近的一次更新，直接大变样，默认的26键文本从小写变大写，没有了下滑文本显示，中英文切换被隐藏，用中文状态敲击字母再直接点击中英文切换按键不能直接变英文了，总之改了好多。是我设置的问题可以更改回来么？还是这款软件打算永久使用这样的方案了
![1](https://github.com/imfuxiao/Hamster/assets/37500200/0c6eddb4-0703-41b8-a4d2-f01d6644bdbd)
![2](https://github.com/imfuxiao/Hamster/assets/37500200/eaa735c3-2c3c-43cf-bf6d-94d3d76e1d4b)

**Comment by DawnLi-code** [comment]
多看下软件设置，空格键两边符号默认可能关着，还有下划文本显示要到 键盘布局 -> 中文26键，点击 > 进入设置 里打开。

**Comment by 971230** [comment]
这个空格键两边符号开关我知道找半天了，试了很多按键，真的好像没有啊

**Comment by imfuxiao** [comment]
在键盘设置 -> 键盘布局 -> 中文26键，点击 > 进入设置页面。里面有空格两侧按钮的设置。

如果需要对两侧按钮添加上下划动，在划动设置中，点+，选择添加字符或者符号字符。这两个的区别是根据你添加空格两侧的符号是否经过 RIME处理而决定的，如果你在空格两侧添加的符号，选择经过RIME处理，那么就选择字符（由RIME处理），否则选择符号字符。

**Comment by 971230** [comment]
虽然我知道这次的更新可能再也回不去了，但是仍然感谢各位的耐心解答，由衷感谢大家的的付出。谢谢
