### ISSUE TITLE
请问是否支持如下方式自定义动作

### ISSUE THREAD

**Issue by shuxiao9058** [imfuxiao/Hamster#375]
如图片所示，长按弹出可选项。。。

![IMG_9982](https://github.com/imfuxiao/Hamster/assets/3312525/475ffab7-02bb-4e81-9eb8-ae94cffad6e3)

**Comment by imfuxiao** [comment]
抱歉，目前暂不支持，不过此功能在后续开发计划中。

**Comment by shuxiao9058** [comment]
赞，希望能够增加自默认的符号键盘。。。习惯了默认的键盘，不太习惯九宫格和分类符号键盘。

**Comment by imfuxiao** [comment]
嗯嗯，这里后面也会做调整。

**Comment by Nemophilister** [comment]
对上下左右滑动输入不同字符，跟iOS自带键盘一样那真的绝了![正在上传 282250982...]

**Comment by Nemophilister** [comment]
![image](https://github.com/imfuxiao/Hamster/assets/136904652/a5332e57-6952-49cc-9198-8e1f33832adc)

**Comment by iT-Boyer** [comment]
ios最新版本，划动符号无法使用，长按不放大显示，划动无效果

**Comment by Nemophilister** [comment]
> ios最新版本，划动符号无法使用，长按不放大显示，划动无效果

我的17.2 正常啊
