### ISSUE TITLE
重新部署后iCloud上的文件没有覆盖本地文件

### ISSUE THREAD

**Issue by jhongyu** [imfuxiao/Hamster#376]
问题如标题所示，现在用的是 TF 的最新版本

iCloud 文件
![IMG_111F3E6EBA21-1](https://github.com/imfuxiao/Hamster/assets/48473551/4e24fe91-87af-4b4c-aec2-4691838c21e2)    

键盘文件
![IMG_E64F46B92DB9-1](https://github.com/imfuxiao/Hamster/assets/48473551/cdb374ee-8fc5-4434-b678-371770d82f81)   

应用文件
![IMG_37F536A174A1-1](https://github.com/imfuxiao/Hamster/assets/48473551/43d2370b-057f-4542-b457-58bc809cbe2e)

**Comment by imfuxiao** [comment]
您好，iCloud 与 手机是单向的，即开启 iCloud 后，每次部署使用 iCloud 中的文件覆盖本地文件。

如果需要将本地文件复制或覆盖到 iCloud 中，需要主动点击 iCloud同步 中的 “拷贝应用文件至iCloud” 按钮

**Comment by jhongyu** [comment]
我这边是重新部署之后 iCloud 没有覆盖本地文件，或者说是没有全部覆盖，可以看到 `rime_ice.custom.yaml` 的时间是对的上的，但是 `my_custom_phrase.txt` 的时间和内容都对不上

**Comment by jhongyu** [comment]
打开“部署时覆盖键盘词库文件”选项之后解决了，应该是因为 `my_custom_phrase` 是自定义的词库文件，所以关闭这个选项的时候没有覆盖
