### ISSUE TITLE
  需求原求的旧键盘布局

### ISSUE THREAD

**Issue by giddence** [imfuxiao/Hamster#377]
习惯了之前的键盘UI布局，即原生的键盘UI，希望加个键盘样式的选项，能继续用原来的UI。

旧的UI布局点左下角的“123”之后，按键从26键分布的字母变为26键分布数字和符号，样式没变。

![IMG_9015](https://github.com/imfuxiao/Hamster/assets/70460481/63465dd0-977c-43cb-8f85-1deba817580d)
![IMG_9016](https://github.com/imfuxiao/Hamster/assets/70460481/1ab601c4-c06e-4755-a1eb-b0d2122cd656)

新的UI布局点左下角的“123”之后，按键从26键分布的字母变成9键分布的数字，样式变化太大，看起来很别扭。符号页面同理。
![IMG_9018](https://github.com/imfuxiao/Hamster/assets/70460481/590fdc09-69f6-40cf-903d-747f068ce795)
![IMG_9019](https://github.com/imfuxiao/Hamster/assets/70460481/b642720e-e3db-49fd-aec7-98a4fe600f6f)
![IMG_9020](https://github.com/imfuxiao/Hamster/assets/70460481/b760608e-ca7c-45b0-bfb9-3f782311f18f)

**Comment by burndown** [comment]
我也有这个需求，创建了自己的键盘布局，但是不知道怎么在主键盘里引用。。

**Comment by imfuxiao** [comment]
收到，感谢反馈，1.0的布局，后续会加个相关开关，让大家自由选择。

**Comment by imfuxiao** [comment]
> 我也有这个需求，创建了自己的键盘布局，但是不知道怎么在主键盘里引用。。

主键盘的按键的动作（action）是固定的，没办法引入自定义的动作，除非你用多个自定义键盘。相互切换。

**Comment by burndown** [comment]
> > 我也有这个需求，创建了自己的键盘布局，但是不知道怎么在主键盘里引用。。
> 
> 主键盘的按键的动作（action）是固定的，没办法引入自定义的动作，除非你用多个自定义键盘。相互切换。

我找到了，通过在线工具自定义一个数字符号键盘，布局跟原生键盘一样，然后再自定义一个拼音键盘，在拼音键盘对应位置引用刚才自定义的数字符号键盘，这样就可以了. 
一位老哥共享给我他的自定义键盘。
[hamster.custom.zip](https://github.com/imfuxiao/Hamster/files/13345399/hamster.custom.zip)

**Comment by imfuxiao** [comment]
商店版本 2.1.0 可以关闭分类符号键盘及数字九宫格键盘。关闭后就是原生键盘布局。
