### ISSUE TITLE
请问如何修改键盘上的字母大小写显示？

### ISSUE THREAD

**Issue by qinghuannn** [imfuxiao/Hamster#378]
如图，新版本更新后，默认的键盘字母都是大写，与之前的逻辑不一样，有点难受。但没找到在哪个位置可以修改大小写的显示。

![微信图片_20231111234226](https://github.com/imfuxiao/Hamster/assets/24269148/eb81e3e9-c41c-4d6b-b848-c3f415999f1a)

**Comment by 971230** [comment]
默认的布局改不了，作者直接默认的大写，要么自己自定义键盘布局

**Comment by qinghuannn** [comment]
> 默认的布局改不了，作者直接默认的大写，要么自己自定义键盘布局

请问是直接修改SahredSupport/hamster.yaml是吗

**Comment by ofzo** [comment]
可以提供配置项吗@imfuxiao

**Comment by 971230** [comment]
> > 默认的布局改不了，作者直接默认的大写，要么自己自定义键盘布局
> 
> 请问是直接修改SahredSupport/hamster.yaml是吗

这个只是参考，里面有内置的仓颉和注音的自定义键盘，对比着来(自定义键盘布局好像不能显示上下划字符，好像)

**Comment by qinghuannn** [comment]
我知道了，在Rime目录下添加hamster.custom.yaml进行自定义。另外如果发现自定义的内容没有被载入，则需要重新界面设置，再载入

**Comment by imfuxiao** [comment]
抱歉，我看很多人反馈希望默认键盘可以显示小写，基于大家的需求，后续版本会加个开关设置。

**Comment by imfuxiao** [comment]
商店版本 2.1.0 已实现中文26键大小写显示功能。
