### ISSUE TITLE
请问应如何部署hamster.yaml?

### ISSUE THREAD

**Issue by yett1873** [imfuxiao/Hamster#379]
无论把自定义的hamster.yaml放在Rime/还是Rime/build/下，重新部署时都会被覆盖为在app内手动修改的版本。请问在哪里能看到相关教程呢？

**Comment by qinghuannn** [comment]
在Rime目录下添加hamster.custom.yaml进行自定义。另外如果发现自定义的内容没有被载入，则需要重新界面设置，再载入。
参考：https://github.com/imfuxiao/Hamster/issues/378#issuecomment-1809504541

**Comment by yett1873** [comment]
感谢回复！请问“重新界面设置，再载入。”是指的重新部署吗？
我将Rime/hamster.custom.yaml导入hamster的目录下，然后点击重新部署，反复多次也不成功。其它的词典文件能够正常部署，但自定义设置始终会被默认设置覆盖。
最后我替换了shared support中的hamster.yaml，再重新部署，就成功了。
我的设备是14pro,ios 17.0.3，hamster 2.0.1。

**Comment by imfuxiao** [comment]
> 感谢回复！请问“重新界面设置，再载入。”是指的重新部署吗？ 我将Rime/hamster.custom.yaml导入hamster的目录下，然后点击重新部署，反复多次也不成功。其它的词典文件能够正常部署，但自定义设置始终会被默认设置覆盖。 最后我替换了shared support中的hamster.yaml，再重新部署，就成功了。 我的设备是14pro,ios 17.0.3，hamster 2.0.1。

您好，如果您在 UI 上设置某个设置，那么通过配置文件（hamster.custom.yaml）修改相同的设置，就会冲突。这个时候已 UI 上的设置为准。

如果想让配置文件中的配置项生效，就还原在 UI 上所做的设置，操作方法是点击：关于 -> 重置界面设置。

**Comment by yett1873** [comment]
> 您好，如果您在 UI 上设置某个设置，那么通过配置文件（hamster.custom.yaml）修改相同的设置，就会冲突。这个时候已 UI 上的设置为准。
> 
> 如果想让配置文件中的配置项生效，就还原在 UI 上所做的设置，操作方法是点击：关于 -> 重置界面设置。

终于成功了，原来是在关于里，谢谢。
另外，玩了一会儿才发现需要在设置里allow full access才能用剪贴版功能，感觉可以小字在选项旁提示一下记得开权限。
❤️再次感谢开发这么好用的软件！

**Comment by imfuxiao** [comment]
嗯嗯，收到，感谢您的反馈。
