### ISSUE TITLE
请求增加自带五笔输入方案

### ISSUE THREAD

**Issue by xlangzhong1** [imfuxiao/Hamster#38]
基于版权问题，现已经可以内置86五笔 or 98五笔方案了

**Comment by imfuxiao** [comment]
您好, 很高兴收到您的反馈. 请问您可否提供 86五笔 or 98五笔的 rime输入方案的地址. 谢谢

**Comment by copuzzle** [comment]
哈哈，作为一个多年的老五笔输入法用户感觉这个86五笔极点码表方案不错: 
https://github.com/KyleBing/rime-wubi86-jidian

**Comment by copuzzle** [comment]
> 您好, 很高兴收到您的反馈. 请问您可否提供 86五笔 or 98五笔的 rime输入方案的地址. 谢谢

哈哈，作为一个多年的老五笔输入法用户感觉这个86五笔极点码表方案不错:
https://github.com/KyleBing/rime-wubi86-jidian

ps: 看了 issue 的还不少，如果作者有想法让大家PR一起协作的话，可以创建 todo list 出来，这样有兴趣的人可以一起来完善这个项目

**Comment by imfuxiao** [comment]
> > 您好, 很高兴收到您的反馈. 请问您可否提供 86五笔 or 98五笔的 rime输入方案的地址. 谢谢
> 
> 哈哈，作为一个多年的老五笔输入法用户感觉这个86五笔极点码表方案不错: https://github.com/KyleBing/rime-wubi86-jidian
> 
> ps: 看了 issue 的还不少，如果作者有想法让大家PR一起协作的话，可以创建 todo list 出来，这样有兴趣的人可以一起来完善这个项目

好想法, 我考虑下怎么整理下TODO LIST.

**Comment by luojiego** [comment]
> 基于版权问题，现已经可以内置86五笔 or 98五笔方案了

@copuzzle 提供的方案也是我在 Mac 和 Windows 使用的方案，部署简单，你可以尝试一下。借助局域网上传配置，然后部署，就能使用五笔使用法了。

**Comment by imfuxiao** [comment]
五笔方案预计 1.3.0 版本内置, 五笔方案源: https://github.com/networm/Rime
