### ISSUE TITLE
升级到最新版本后，雾凇全拼九宫格模式无法使用

### ISSUE THREAD

**Issue by iamlaom** [imfuxiao/Hamster#381]
升级到2.0.1之后，配置雾凇拼音，使用26键模式输入很流畅，但是使用九宫格方式无法显示中文候选词，截图如下。

![IMG_3558](https://github.com/imfuxiao/Hamster/assets/42690537/7fb259b6-3c49-46f3-9cd0-c1232cc9f90c)
![IMG_3557](https://github.com/imfuxiao/Hamster/assets/42690537/7380d762-9000-4679-8a3d-69e96814648c)

**Comment by wenLiangcan** [comment]
九宫格模式双拼也用不了，不过因为是第一次使用不确定以前是不是支持的

**Comment by RunYou** [comment]
重新再导入一次雾凇输入法就行了，选雾凇九宫格

**Comment by msn1983aa** [comment]
确实导入雾凇后选择九宫格，左侧无法显候选拼音了还是一排标点符号，导致无法很好的使用了，暂时回到了系统输入法。

**Comment by imfuxiao** [comment]
感谢反馈，目前九宫格的拼音候选功能还有bug，所以上线前把九宫格拼音候选功能屏蔽了，后续解决问题后会上线的。

九宫格双拼也是一样的道理，需要对应的输入方案配置的支持才可以，目前适配的是全拼模式，等候选拼音功能上线后，会考虑做双拼的九宫格方案。

**Comment by iamlaom** [comment]
多谢大佬！期待更新，加油！
