### ISSUE TITLE
2.0以后 键盘配色不能用rime 配置了吗？

### ISSUE THREAD

**Issue by SeongBrave** [imfuxiao/Hamster#382]
<img width="432" alt="image" src="https://github.com/imfuxiao/Hamster/assets/10784393/9c9f7ed5-5f91-4839-8a9c-65d8ca4c363d">
这块的配置可以自定义吗？之前rime中的配置无法生效了吗？

**Comment by imfuxiao** [comment]
您好，2.0版本的配色增加了很多参数，1.0之前内置的配色需要调整后才能使用。

您可以参考配色文档，https://github.com/imfuxiao/Hamster/wiki/%E9%85%8D%E8%89%B2%E8%AF%B4%E6%98%8E

把你想要的配置，按照 方案管理 -> 应用文件 -> SharedSupport -> hamster.yaml 文件中的配色格式，添加下您的新配色，并将修改后的文件存放在 应用文件 -> Rime 下。

配置文件除了可以使用  hamster.yaml 也可以使用 hamster.custom.yaml ,文件的区别与 rime 中的 default.yaml 和 default.custom.yaml 逻辑相同。

**Comment by jlm346383101** [comment]
请问，中/英切换按钮的颜色在哪改？button_front_color改不了这个
<img width="429" alt="微信图片_20231121001615" src="https://github.com/imfuxiao/Hamster/assets/2649880/23817bf3-d82e-4807-b274-68291fd238d3">
