### ISSUE TITLE
2.0.1版本无法使用小鹤双拼的编码辅助功能

### ISSUE THREAD

**Issue by AeonWorks** [imfuxiao/Hamster#383]
1.0 时代可以。通过输入 ` 可模糊不记得的拼音字母或形码，每输入一次表示一个模糊编码。相当有用。

配置没有变化，将之前配置复制到 2.0，没有效果。

**Comment by AeonWorks** [comment]
如果需要贴出配置文件，可以贴出来。

**Comment by AeonWorks** [comment]
[flypy.schema.zip](https://github.com/imfuxiao/Hamster/files/13327460/flypy.schema.zip)

应该是这个配置文件，并不确定。

**Comment by imfuxiao** [comment]
默认a 键上划是 `，可以达到你想要的效果。

如果你使用的是空格两边的自定义按键，请开启对应的“由RIME处理”选项开关。

**Comment by AeonWorks** [comment]
感谢回复。我已经把默认的都盖了。我已经把 ` 配置到 z 键上了，没有效果。请问还需要什么操作么？

空格两边的自定义按键，我已经开启由 RIME 处理了。

**Comment by AeonWorks** [comment]
把 ` 配置为 a 上划就可以。我可以先这么用。

**Comment by AeonWorks** [comment]
再想请教一下，配置到 a 上划后功能可以实现，但没有编码提示，请问如何开启？ @imfuxiao

**Comment by AeonWorks** [comment]
搞定了，开启 显示候选文字 Comment 即可。
