### ISSUE TITLE
从1.x升级到2.x后，键盘下滑字符不显示，只显示上划字符。

### ISSUE THREAD

**Issue by tarkky** [imfuxiao/Hamster#388]
升级到新版后。如题，下滑字符不显示，是需要重置么？
另外，支付宝捐了你20天的煎饼果子。哈哈。
![20231113_011605000_iOS](https://github.com/imfuxiao/Hamster/assets/19773978/bc180543-5820-46d0-8182-e8f1f647e8a4)

**Comment by tamhaywoo** [comment]
这个问题我遇到过，需要进入键盘设置，把26个字母的下滑开关开启

**Comment by 971230** [comment]
现在需要键盘布局里面，中文26键里面，划动设置一个一个点开显示的

**Comment by tarkky** [comment]
@tamhaywoo  @971230 谢谢二位。找到了。搞定了。不过建议作者能否设个一键开关将26个字母一次打开？ 谢谢

**Comment by 971230** [comment]
新版本更新难免出很多疑问点，还是不急包容一些，后续更新反馈一下就行了，想要的功能说一下，项目组会考虑的

**Comment by imfuxiao** [comment]
> @tamhaywoo @971230 谢谢二位。找到了。搞定了。不过建议作者能否设个一键开关将26个字母一次打开？ 谢谢

收到，感觉大家还是想把上下划动都显示出来，后续我会把内置的上下划动都显示出来。
