### ISSUE TITLE
打不出么字

### ISSUE THREAD

**Issue by RunYou** [imfuxiao/Hamster#389]
![image](https://github.com/imfuxiao/Hamster/assets/43163474/0506194d-4dfa-42f7-998f-2efde9cbbed3)![image](https://github.com/imfuxiao/Hamster/assets/43163474/300b4246-b4e1-4e18-9256-4940eca562a2)
第一个问题，九宫格打不出me字
第二个问题，主题选择跟随系统，夜间从黑色切到白色app，显示有问题，需要按一下符号，再返回才好

**Comment by imfuxiao** [comment]
感谢您的反馈，
1. 问题1: me 么字不出，是因为目前九宫格不支持候选拼音，me被引擎中的词库候选字优显示，候选栏默认只出100字，导致后面的字都显示不出来了，这个算是一个问题吧，我后面会做优化。
2. 问题2，感觉是您的配色问题，请参考[配色说明文档](https://github.com/imfuxiao/Hamster/wiki/%E9%85%8D%E8%89%B2%E8%AF%B4%E6%98%8E)，修改按键文字颜色参数。

**Comment by RunYou** [comment]
> 感谢您的反馈，
> 1. 问题1: me 么字不出，是因为目前九宫格不支持候选拼音，me被引擎中的词库候选字优显示，候选栏默认只出100字，导致后面的字都显示不出来了，这个算是一个问题吧，我后面会做优化。
> 2. 问题2，感觉是您的配色问题，请参考[配色说明文档](https://github.com/imfuxiao/Hamster/wiki/%E9%85%8D%E8%89%B2%E8%AF%B4%E6%98%8E)，修改按键文字颜色参数。

感谢您的解答。问题2，我一开始就禁用了配色，这个问题还是存在。

**Comment by imfuxiao** [comment]
> > 感谢您的反馈，
> > 
> > 1. 问题1: me 么字不出，是因为目前九宫格不支持候选拼音，me被引擎中的词库候选字优显示，候选栏默认只出100字，导致后面的字都显示不出来了，这个算是一个问题吧，我后面会做优化。
> > 2. 问题2，感觉是您的配色问题，请参考[配色说明文档](https://github.com/imfuxiao/Hamster/wiki/%E9%85%8D%E8%89%B2%E8%AF%B4%E6%98%8E)，修改按键文字颜色参数。
> 
> 感谢您的解答。问题2，我一开始就禁用了配色，这个问题还是存在。

收到，我在排查下。

**Comment by imfuxiao** [comment]
问题2 确认是 Bug，预计下个版本发布修复，感谢您的反馈。

**Comment by iDvel** [comment]
> 第一个问题，九宫格打不出me字

@imfuxiao  是我把你的代码做了如下修改导致的：
```diff
-    - derive/[abc]/A/
+    - derive/a/A/
+    - derive/[bc].+/A/
-    - derive/[def]/D/
+    - derive/e/D/
+    - derive/[df].+/D/
-    - derive/[mno]/M/
+    - derive/o/M/
+    - derive/[mn].+/M/
```
按 2、3、6 只出 a e o，无法响应其他的拼音，九宫格用户一般习惯了按 3 出「的」。
修改后可以了，但是按下 64 期望的是 ne 和 me，实际给出了很多 n'd m'd m'f 等简拼的词组。

折腾半天各种尝试，改了一个凑合能用 https://github.com/iDvel/rime-ice/commit/db2375b0d9dba21247da4e5dd58c3d36c56c2b5a

**Comment by RunYou** [comment]
> 问题2 确认是 Bug，预计下个版本发布修复，感谢您的反馈。

您好，另有一个问题和建议
问题，字库比较少的话，去哪里添加字?比如现在26键，雾凇拼音下，我打不出“汯”字，我想把这个字，添加进字库，应该去哪个文件夹添加?感谢
建议，能否增加一下26键拼音误触的识别?比如“增加”两字，拼音zengjia很容易碰错打成zenhjia，或者右下角的bn按键更容易误触，比如neng打成nebg
期待您能在下个版本把9宫格选拼音加上，感谢您做出这款优秀的输入法app
