### ISSUE TITLE
可否集成雾凇拼音

### ISSUE THREAD

**Issue by tamhaywoo** [imfuxiao/Hamster#39]
首先感谢你的开发，为我们多了一个好用的iOS平台输入法
目前[iDvel](https://github.com/iDvel)的[雾凇拼音](https://github.com/iDvel/rime-ice)一直处于更新状态，对于词库等方面也有很多优化，不知道是否可以将雾凇拼音集成到仓输入法中去呢？

**Comment by imfuxiao** [comment]
您好, 很高兴收到您的反馈, 方案很好. 可以内置到后续版本中. 谢谢

**Comment by imfuxiao** [comment]
> ## 您好, 很高兴收到您的反馈, 方案很好. ~可以内置到后续版本中~. 谢谢
> 抱歉, 考虑再三, 不能将此方案内置到App中. 因为此方案在持续更新, 更适合自己手动上传到app中的方式, 这样可以作者的版本保持一致, 如果内置到app中, app内置版本将来会低于作者的版本.

抱歉 @tamhaywoo

**Comment by tamhaywoo** [comment]
我已经解决这个问题了，谢谢。

**Comment by imfuxiao** [comment]
雾淞拼音输入方案使用
1. git clone https://github.com/iDvel/rime-ice
2. App打开输入方案上传, 点击启动
3. 局域网浏览器打开手机IP后, 进入"Rime"文件夹, 全选并删除.
4. 将rime-ice下文件全选, 拖拽到浏览器中, 注意: 这里当前位置是Rime文件夹下
5. 点击App主页面重新部署按钮, 等待部署完成.
6. 完毕, 可以使用了.

**Comment by wd** [comment]
> 抱歉, 考虑再三, 不能将此方案内置到App中. 因为此方案在持续更新, 更适合自己手动上传到app中的方式, 这样可以作者的版本保持一致, 如果内置到app中, app内置版本将来会低于作者的版本.

作者更新其实一般就是一些词库的更新，滞后一些没啥。即使在 Mac 上面使用，也没几个用户会不停去更新的。
集成进去主要是可以方便懒的折腾的用户。你可以在每次 build 新版本的时候自动更新到最新的放到 app 里面。

不过对于这些内置的方案，用户如何自定义可能是个问题。不清楚是不是只放 `*.custom.yaml`  就可以。
