### ISSUE TITLE
通过文件备份/导出上划下划的功能取消了吗？

### ISSUE THREAD

**Issue by pointerto** [imfuxiao/Hamster#394]
之前备份了.plist文件，但是好像没在2.0中找到导入入口

**Comment by imfuxiao** [comment]
您好，1.0升级2.0的时候会自动将1.0的划动转为2.0的划动，可能下划部分没有显示出来，您可以在 键盘设置 -> 键盘布局 -> 中文26键，点击 > 符号或者左划，进入设置页面，在划动设置的中，将按键的下划显示开关打开。
