### ISSUE TITLE
26键，字母键上方的的数字和符号是怎么输入的？

### ISSUE THREAD

**Issue by KevinLeung007** [imfuxiao/Hamster#395]
没找到教程

**Comment by qinghuannn** [comment]
https://lost-melody.github.io/hamster-tools

**Comment by imfuxiao** [comment]
您好，原生内置的中文26键的上下划动设置，在 键盘设置 -> 键盘布局 -> 中文26键，点击 “>” 符号或者向左划，进入设置页面，里面有划动设置。
