### ISSUE TITLE
关于通过RIME处理

### ISSUE THREAD

**Issue by pointerto** [imfuxiao/Hamster#396]
在上划下划里设置之后也没有调出输入方案的设置，而是直接上屏

**Comment by pointerto** [comment]
目前只有A键设置的划动动作可以生效，其他都不行，都是直接上屏

**Comment by imfuxiao** [comment]
您好，有个 processByRIME 的选项，如果是 false 则表示不经过 RIME 引擎，直接上屏。true 则表示经过 RIME 引擎。

您可参考 [自定义键盘布局教程](https://github.com/imfuxiao/Hamster/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89%E9%94%AE%E7%9B%98%E5%B8%83%E5%B1%80)
