### ISSUE TITLE
地球图标（用于切换输入法）太扁了

### ISSUE THREAD

**Issue by yanjingsong** [imfuxiao/Hamster#398]
和原生的相比，有点扁，所以对强迫症患者有些难受。
![IMG_0651](https://github.com/imfuxiao/Hamster/assets/62985472/952f9b85-cc1e-496b-b86a-9a89a40d11d4)

**Comment by imfuxiao** [comment]
抱歉，此问题会在下个版本修复。

**Comment by g6ai** [comment]
我也遇到这个问题，谢谢op，谢谢作者的工作

**Comment by imfuxiao** [comment]
商店2.1.0版本已修复此问题。
