### ISSUE TITLE
候选字过多造成卡顿问题

### ISSUE THREAD

**Issue by imfuxiao** [imfuxiao/Hamster#4]
目前调用librime的api获取候选字是没有做分页, 一次性获取的全部候选字. 这样做的目的是: 

1. 开发简单(对不起, 我懒了)
2. 对使用者也友好, 不用类似PC上的分页.

目前看来以上决定是错误的, 按照目前反馈, 体验不好, 使用者出现卡顿. 对于使用像小鹤音形这种4码成一字的输入方案, 候选字不多, 所以没有出现卡顿. 而当有的输入方案的候选字过多, 比如上千的候选字, UI卡顿严重.

个人能想到的最好的解决方案是: 分页. 类似当候选栏滚动到最右端时, 再次调用librimeAPI, 获取第二页的候选字. 

理想很好, 现实是**这个开发有点复杂(我还是懒了)**. 所以目前临时解决方案, 先设置一个最大获取候选字数量. 每次以这个数量获取候选字.

终级的分页方案等有时间了在开发吧.

**Comment by wzxmer** [comment]
补充一个相关问题，顶功的时候，会吞掉一个字母，比如：bkrjfv，bkrj会打出比如，f会把比如上屏，然后f会被吞，只剩下v
