### ISSUE TITLE
中英下的键盘布局跳变

### ISSUE THREAD

**Issue by xiaoxchou** [imfuxiao/Hamster#401]
1.开启“符号”键和“中英切换”键的前提下，进行中英切换，会出现最左下角的“数字”键与“符号”键在不同的语言下位置是对调着变化的
2.建议按键声音可以调整大小

**Comment by imfuxiao** [comment]
收到，感谢反馈，后面会优化下您说的问题。

**Comment by imfuxiao** [comment]
1. TF 最新版本按键音已可调整
2. 符号键/中英切换键已固定位置。
