### ISSUE TITLE
自定義上下左右滑動輸入，十次有九次無法記憶

### ISSUE THREAD

**Issue by groverlynn** [imfuxiao/Hamster#402]
任何不按順序的設定都會無法記錄。即使看似記錄了，實際根本沒有寫入配置文件（猜測是把無數配置放到同一個文件的關係）。平均5分鐘才能設定好一個按鍵，太可怕了……
 而且UI設計也反常理，下拉三角居然無法下拉……反而文字才能下拉……

**Comment by sunznx** [comment]
我觉得你可以花半小时研究一下这个工具，然后导入自定义键盘布局。我就是这样做的。
https://lost-melody.github.io/hamster-tools

**Comment by groverlynn** [comment]
> 您好，没有明白您反馈的问题，可否明确说明下你是在那个功能下，怎么操作，产生了什么样的bug。

自定義鍵盤佈局中的划動設置

**Comment by groverlynn** [comment]
盲猜跟你的yaml數據結構有關。你用了大量的列表，但都沒有key，所以應當是遍歷然後比對某個子項來判斷的是吧？這樣效率低了2階，機讀人讀都累。還沒寫入上一個設定項，就要寫入下一個設定項。如果把那個子項當成父項的key應該能解決問題。

**Comment by imfuxiao** [comment]
> 盲猜跟你的yaml數據結構有關。你用了大量的列表，但都沒有key，所以應當是遍歷然後比對某個子項來判斷的是吧？這樣效率低了2階，機讀人讀都累。還沒寫入上一個設定項，就要寫入下一個設定項。如果把那個子項當成父項的key應該能解決問題。

并不是您说的原因，您可以看代码中的实现。

**Comment by groverlynn** [comment]
> > 盲猜跟你的yaml數據結構有關。你用了大量的列表，但都沒有key，所以應當是遍歷然後比對某個子項來判斷的是吧？這樣效率低了2階，機讀人讀都累。還沒寫入上一個設定項，就要寫入下一個設定項。如果把那個子項當成父項的key應該能解決問題。
> 
> 并不是您说的原因，您可以看代码中的实现。

有幾例是諸如#等字符被直接當成代碼了
