### ISSUE TITLE
installation.yaml文件重置需要重新修改的问题

### ISSUE THREAD

**Issue by vvveng** [imfuxiao/Hamster#403]
把同步路径做一个配置项，rime 同步时，自动把这个配置项写的文件里。

**Comment by g6ai** [comment]
我有一个类似的想法：可否在iCloud向应用同步`RIME`文件夹（点击重新部署）时，区分不同设备的installation_id（写入对应设备的installation.yaml版本）？

感觉OP的建议比我上面的想法更合理。

**Comment by imfuxiao** [comment]
商店版本 2.7.0 已支持在界面中修改 installation.yaml 中的参数。
