### ISSUE TITLE
构建过程中需要 SharedSupport.zip，但 InputSchemaBuild.sh 脚本未更新

### ISSUE THREAD

**Issue by tansongchen** [imfuxiao/Hamster#404]
编译过程报错 `Hamster/Resources/SharedSupport/SharedSupport.zip: No such file or directory`，查看了一下 Makefile 好像需要 make schema，但 InputSchemaBuild.sh 中指向的 v2.0 branch 并不存在

**Comment by imfuxiao** [comment]
抱歉，内置方案以后都会迁移 CloudKit 存储，所以这里做了功能变更。

**Comment by tansongchen** [comment]
那现在应该如何成功编译运行仓的项目呢？目前我这里的情况就是因为没有这个 SharedSupport 所以编译运行不了

**Comment by imfuxiao** [comment]
您好，我把v2.0分支推上去了，您在本地重新执行下 `make schema`， 注意内置方案有点多，网络不好的情况下会出现异常。

**Comment by tansongchen** [comment]
感谢，有了这个之后终于可以成功运行了，环境是 iOS 15 模拟器（M2 Rosetta 模式，有点慢，但可以接受）。不过我还不大熟悉仓的代码结构，直接开始做 librime-sbxlm 的桥接可能还做不了，您可以先给我指派几个简单的小 issue 练练手。

**Comment by imfuxiao** [comment]
> 感谢，有了这个之后终于可以成功运行了，环境是 iOS 15 模拟器（M2 Rosetta 模式，有点慢，但可以接受）。不过我还不大熟悉仓的代码结构，直接开始做 librime-sbxlm 的桥接可能还做不了，您可以先给我指派几个简单的小 issue 练练手。

您好，这部分工作我正在做，因为牵扯的地方太多了，很多地方都是直接调用 RIME 的api，全部需要重构。

我邮箱是 morse.hsiao@gmail.com，您方便的话发邮件到我邮箱，我们私下方便沟通。
