### ISSUE TITLE
是否可以使用系统输入法切换输入法

### ISSUE THREAD

**Issue by ofzo** [imfuxiao/Hamster#405]
首先感谢作者辛苦的付出。
对于全面屏（大部分应该都是了）底部已留有大块的空白空间，并且带有一个输入法切换器，是否可以将
Hamster的输入法切换也放置在这里，这样可以节省键盘的盘面空间，而且切换输入法是个比较底频率的操作，如果能放在角落里应该会更好
![IMG_560940CE348A-1](https://github.com/imfuxiao/Hamster/assets/18000037/7c763b4c-aead-4713-9fee-c068e88f20f3)

**Comment by imfuxiao** [comment]
您好，您的建议很好，但是地球图标/麦克风图标区域是系统管理区域，程序是无法调整的。

您红色框部分，是显示系统键盘的部分，只能显示具体的键盘，目前仓只有一个键盘，即您看到的仓输入法。

如果您不希望键盘上显示中英切换键，您可以使用上下划动的方式切换，比如默认 e 键的下划是切换英文键盘。

**Comment by ofzo** [comment]
> 您好，您的建议很好，但是地球图标/麦克风图标区域是系统管理区域，程序是无法调整的。
> 
> 
> 
> 您红色框部分，是显示系统键盘的部分，只能显示具体的键盘，目前仓只有一个键盘，即您看到的仓输入法。
> 
> 
> 
> 如果您不希望键盘上显示中英切换键，您可以使用上下划动的方式切换，比如默认 e 键的下划是切换英文键盘。

那是否可以通过向系统动态注册多个输入法来实现呢

**Comment by imfuxiao** [comment]
可以有多个键盘，但是没必要，多个键盘之间切换会有卡顿的。

**Comment by ofzo** [comment]
> 可以有多个键盘，但是没必要，多个键盘之间切换会有卡顿的。

https://github.com/imfuxiao/Hamster/assets/18000037/f41c9c26-07f3-4169-93f2-5a83e41a8ed0
我刚刚测试了一下, 感觉这个过程在可接受范围内

**Comment by imfuxiao** [comment]
这是因为你切换的是系统输入法，系统输入法不会被杀进程，三方输入是会的。

**Comment by ofzo** [comment]
> 这是因为你切换的是系统输入法，系统输入法不会被杀进程，三方输入是会的。

明白了,感谢感谢
