### ISSUE TITLE
请求增加一个导入系统短语的功能

### ISSUE THREAD

**Issue by stepbackdunk** [imfuxiao/Hamster#407]
可以参考微信输入法
可以快速输入邮箱或者手机号，很方便!
加上这个功能就可以主力使用了，感谢🙏
![IMG_7816](https://github.com/imfuxiao/Hamster/assets/70123022/58fb5b2a-d1f4-45c7-ad21-17fcf8224dd4)
![Uploading IMG_7817.png…]()

**Comment by imfuxiao** [comment]
收到，感谢反馈，这个功能有做规划，后续会开发。

**Comment by imfuxiao** [comment]
您好，此功能已规划到「剪切板」功能中，因此关闭此 issue，感谢您的反馈。
