### ISSUE TITLE
目前已经支持hamster.custom.yaml覆盖的形式了,可否增加高级用法禁用UI配置形式呢?

### ISSUE THREAD

**Issue by cactusnix** [imfuxiao/Hamster#408]
背景: 已经在hamster.custom.yaml覆盖了一些配置选择,但是UI界面仍然可以调整这些配置选项,最后就不知道配置了哪些了.
期望: 配置文件优先级是最高无法被UI覆盖的.

**Comment by imfuxiao** [comment]
您好，UI的设置优先级是最高的，因为UI是最便捷的，对开箱即用是友好的。

如果您希望用配置文件设置，可以通过关于页面的两个功能，“重置界面设置”和“导出界面设置”功能来完成。

**Comment by cactusnix** [comment]
按照关于页面的解释,重置页面设置仅仅重置keyboard(yaml文件的节点)下面的配置吧. 像toolbar,general,rime的设置都不会被重置回hamster.custom.yaml的配置.目前测试下来是这样.

**Comment by imfuxiao** [comment]
页面上不是说“重置通过界面修改的配置项”，就是你在UI上操作修改的配置项。与配置文件无关。

**Comment by cactusnix** [comment]
那目前RIME的overrideDictFiles的true和false,无法被这个功能重置回配置文件的修改诶.

**Comment by imfuxiao** [comment]
你是否在界面上修改这个配置呢？

**Comment by cactusnix** [comment]
1. hamster.custom.yaml的patch成false
2. 界面调整成true
3. 点击关于中的重置按钮 界面上并未调整成false 退出软件后台重新进入也是如此
4. 这个时候重新部署一下rime 界面变成false

**Comment by imfuxiao** [comment]
收到，显示的问题可能是页面的bug.

配置文件的中的配置项，需要重新部署才能生效，这是对的。
