### ISSUE TITLE
键盘内距和边距问题

### ISSUE THREAD

**Issue by qhjia** [imfuxiao/Hamster#409]
1.键盘的边距没办法独立于内距调节，由其是左右内距调整合适了左右边距就会很小。
2.横屏和竖屏用的是一套参数，希望能分开。

**Comment by qhjia** [comment]
上面是系统键盘，下面是我自定义的rime键盘，左右内距差不多，但边距差很多。
![ios_keyboard](https://github.com/imfuxiao/Hamster/assets/75422228/a85fbdd8-fe0f-44cd-940d-1df594b9d298)
![rime_keyboard](https://github.com/imfuxiao/Hamster/assets/75422228/22c9ce32-3b0c-4938-b7d7-63d5d1a18875)

**Comment by qhjia** [comment]
研究了一下，左右边距可以靠加占位符解决，但如果能直接调应该会更优雅一点

**Comment by cactusnix** [comment]
也许buttonInsets这个配置项可以解决你的问题.
详见: https://github.com/imfuxiao/Hamster/wiki/自定义键盘布局

**Comment by RunYou** [comment]
> 也许buttonInsets这个配置项可以解决你的问题.
> 
> 详见: https://github.com/imfuxiao/Hamster/wiki/自定义键盘布局

请问，我用lost-melody 开发的自定义键盘工具搞了个键盘布局，然后要怎么使用呢？是要写成 yaml 文件么？怎么导入到配置中呢？

**Comment by qhjia** [comment]
> 也许buttonInsets这个配置项可以解决你的问题. 详见: [https://github.com/imfuxiao/Hamster/wiki/自定义键盘布局](https://github.com/imfuxiao/Hamster/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89%E9%94%AE%E7%9B%98%E5%B8%83%E5%B1%80)

我说的内距指的就是这个buttonInsets，如果想调大边距自然会让内距变大

**Comment by qhjia** [comment]
> > 也许buttonInsets这个配置项可以解决你的问题.
> > 详见: [https://github.com/imfuxiao/Hamster/wiki/自定义键盘布局](https://github.com/imfuxiao/Hamster/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89%E9%94%AE%E7%9B%98%E5%B8%83%E5%B1%80)
> 
> 请问，我用lost-melody 开发的自定义键盘工具搞了个键盘布局，然后要怎么使用呢？是要写成 yaml 文件么？怎么导入到配置中呢？

导出布局文件传到手机里，在键盘布局里右上角的+号里添加
