### ISSUE TITLE
日志过大问题

### ISSUE THREAD

**Issue by weearc** [imfuxiao/Hamster#410]
新版本似乎持续记录日志到存储，经过几天使用单次日志最大已经到10MB上下，持续记录但并不处理可能会有爆内存的问题，可否提供选项或开关关闭日志。

**Comment by imfuxiao** [comment]
您好，日志只有 app 内部的重新部署和同步功能，两个RIME的功能会记录日志，而且只记录改过程的日志。其余时间是不记录日志的。
另外日志最多保持 10 个文件，不会更多。

所以我很诧异，您的单次日志怎么会有 10 MB，因为重新部署和同步两个过程很短暂。

**Comment by weearc** [comment]
> 您好，日志只有 app 内部的重新部署和同步功能，两个RIME的功能会记录日志，而且只记录这个过程中的日志。其余时间是不记录日志的。 另外日志最多保持 10 个文件，不会更多。
> 
> 所以我很诧异，您的单次日志怎么会有 10 MB，因为重新部署和同步两个过程很短暂。

出现这个问题时候在测试多个自己整理的大词库，本身体积都相当大且数量多。可能确实会影响日志大小。如果日志数量始终可控的话就放心了，多谢解释
