### ISSUE TITLE
单手模式无法开启

### ISSUE THREAD

**Issue by xenowei** [imfuxiao/Hamster#412]
iOS版本：17.1.1，iPhone 13，软件版本：20.1(1)
已在键盘上设置了划动动作触发左右手模式，但都无法触发。

**Comment by imfuxiao** [comment]
抱歉，1.0的功能还没有移植完，下个版本会将不可用的指令先屏蔽，后续移植完毕后在开放。

**Comment by imfuxiao** [comment]
单手模式已支持，可通过快捷指令切换。
