### ISSUE TITLE
怎样让符号键盘和数字九宫格返回最近使用的键盘(而不是主键盘)？

### ISSUE THREAD

**Issue by xuehongyanL** [imfuxiao/Hamster#413]
我自定义了两个键盘 分别为“chinese14”和“english26”
我在“chinese14”键盘中设置了切换键 keyboardType(custom(english26))
在“english26”中设置了keyboardType(numericNineGrid)
我在设置中设置键盘布局为“自定义-chinese14”

期望的情形：
“切换英文→切换数字九宫格→输入123→点击返回→回到英文键盘”

实际情形：
“切换英文→切换数字九宫格→输入123→点击返回→回到中文键盘”

将“numericNineGrid”换成“classifySymbolic”同理

**Comment by imfuxiao** [comment]
感谢您的反馈，后续会做优化。

**Comment by imfuxiao** [comment]
TF 119 版本已处理完成，商店下个版本会同步发布。
