### ISSUE TITLE
关于键盘振动的一个细节问题

### ISSUE THREAD

**Issue by shinyypig** [imfuxiao/Hamster#416]
当前的版本 https://github.com/imfuxiao/Hamster/releases/tag/2.0.1 ，在删除字符时会一直振动，即便所有字符都被删除了。

不过原生键盘会在删除了所有字符后停止振动，不太熟悉iOS开发，不知道能不能实现在没有字符可以删除时不再振动这一功能。

**Comment by imfuxiao** [comment]
您好，看您的描述，您的问题是否为，即使手指不再按删除键了，震动依然存在。如果是这样的现象，就应该是bug了。

**Comment by shinyypig** [comment]
您好，并不是，手指一直是按着删除键的。但是原生键盘会检测输入框是否存在可以删除的字符，如果没有就不会振动。目前仓输入法并不会检测，只要按着删除键就会一直振动。

**Comment by imfuxiao** [comment]
收到，明白了，感谢您的反馈，后面会优化下。

**Comment by imfuxiao** [comment]
> 您好，并不是，手指一直是按着删除键的。但是原生键盘会检测输入框是否存在可以删除的字符，如果没有就不会振动。目前仓输入法并不会检测，只要按着删除键就会一直振动。

你好，我用系统内置键盘测试，短信界面，无字的时候也是会触发震动的。

我想了下，按键按下时的反馈应该与上下文无关，因为反馈是本身就是用来提示我按这个键了，而无关是否有内容。

**Comment by shinyypig** [comment]
是的，只要按了就会有反馈。不过，长按有区别，内置键盘在长按删除键如果没有内容可以删除，后续不会有振动了。但是仓输入法，在长按时，无论是否有可删除的内容，都会持续振动，这样的振动反馈其实是不合理的。

**Comment by imfuxiao** [comment]
收到，TF 104 版本已优化。
