### ISSUE TITLE
希望height为0，可以隐藏行

### ISSUE THREAD

**Issue by leisure365** [imfuxiao/Hamster#417]
目前最新版，width为0已经可以隐藏按键了，但height为0却不可以隐藏整行。
        希望可以在设置height为0时，能隐藏整行。这样可以更方便和灵活的设置竖屏和横屏的不同按键布局。
        望采纳，谢谢！

**Comment by imfuxiao** [comment]
您好，可否提供下您的自定义键盘配置，方便我进行测试。

**Comment by leisure365** [comment]
你好，打扰了。之前回复的那个邮件中的键盘测试文件中，第一行的横排行高忘改为0了，这个附件是重修改了第一行横排行高为0的。感谢！











在 2023-11-21 10:08:44，"morse.hsiao" ***@***.***> 写道：

您好，可否提供下您的自定义键盘配置，方便我进行测试。

**Comment by imfuxiao** [comment]
您好，邮件中没有看到附件。麻烦您重新发送下。

**Comment by leisure365** [comment]
[您好,为防止附件看不到,再加个蓝奏链接:
https://leisure.lanzouj.com/iWYom1fhs8qb
[测试键盘.zip](https://github.com/imfuxiao/Hamster/files/13422388/default.zip)

**Comment by imfuxiao** [comment]
TF 104 版本已优化

**Comment by leisure365** [comment]
好的，谢谢！辛苦了，我来试试。
