### ISSUE TITLE
建议优化：当前仓多次导入部署后，占用空间会增大

### ISSUE THREAD

**Issue by Jmdayou** [imfuxiao/Hamster#418]
感谢大佬的辛勤开发

如题，即使是同一个方案，在多次导入删除后，相同的文件占用iOS的空间却越来越大。

举例：
假设首次部署后软件占用空间是100mb，再进行如下操作后，文件体积会变大：
1、完全删除原方案（键盘和应用中Rime下所有文件）
2、导入新方案并再次完全删除
3、再次导入原方案
结果：软件占用空间变成150mb或更高。

**Comment by imfuxiao** [comment]
您好，麻烦提供下您的导入方式。

**Comment by Jmdayou** [comment]
比如，我通过仓的开源方案下载导入一个方案，部署后完全删除后（所有Rime下文件，包括键盘及应用），再用icloud部署我原来的方案，此时仓的占用空间会变大，按理说同样的文件部署后应该是相同大小。

**Comment by Jmdayou** [comment]
> 您好，麻烦提供下您的导入方式。

我测试的时候是使用声笔输入法（测试） 和我的原方案进行对比，  我的原方案在完全删除内置方案后部署的大小为100mb（文稿与数据），删除后通过内置的开源方案导入声笔输入法（测试）后是337mb（文稿与数据），当我再次删除部署成我自己的方案时，文稿数据变成了160mb。如果多次操作，这个空间也会再次增加，每次增加约60mb。

**Comment by SunDD4** [comment]
我也遇到过这样的问题，只要多次删除方案，再重新添加，部署后会体积越来越大，我的一度达到过900M

**Comment by groverlynn** [comment]
> > 您好，麻烦提供下您的导入方式。
> 
> 我测试的时候是使用声笔输入法（测试） 和我的原方案进行对比， 我的原方案在完全删除内置方案后部署的大小为100mb（文稿与数据），删除后通过内置的开源方案导入声笔输入法（测试）后是337mb（文稿与数据），当我再次删除部署成我自己的方案时，文稿数据变成了160mb。如果多次操作，这个空间也会再次增加，每次增加约60mb。

主要是辭典正查反查的二進制文件。
但是每一個文件可能被複製4次，加上衝突版本，至多可能有6個副本。

**Comment by groverlynn** [comment]
> 比如，我通过仓的开源方案下载导入一个方案，部署后完全删除后（所有Rime下文件，包括键盘及应用），再用icloud部署我原来的方案，此时仓的占用空间会变大，按理说同样的文件部署后应该是相同大小。

差異應該正好是佔用icloud的空間

**Comment by imfuxiao** [comment]
新版本已无此问题，如还有问题，在重新打开此问题。
