### ISSUE TITLE
iphone14 pro max-ios16.2：只有主屏搜索框等调出仓输入法，其他位置包括APP内都调不出仓输入法【已解决】

### ISSUE THREAD

**Issue by fqw000** [imfuxiao/Hamster#42]
iphone14 pro max-ios16.2：只有主屏搜索框等调出仓输入法，其他位置包括APP内都调不出仓输入法
设置里键盘只保留仓输入法一个输入法也不行。

临时解决方案：
设备重启
设置里修改视图大小实现Respring也可以

**Comment by gowinder** [comment]
iphone 11 pro max ios 16.4.1同样的情况，改字体大小可以出来一次，再改一次后就怎么改也没有了
