### ISSUE TITLE
iOS仓输入法调用

### ISSUE THREAD

**Issue by kentback** [imfuxiao/Hamster#420]
安装以后，系统设置添加了输入法，但是按地球无法调用输入法

**Comment by imfuxiao** [comment]
您好，麻烦尝试以下方式：
1. 检查系统键盘中是否已经存在添加的仓输入法
2. 把不能打开的应用从后台关闭，并重新打开，看是否可以打开键盘
3. 尝试重启手机后，看是否可以打开键盘

**Comment by kefengzhang** [comment]
> 安装以后，系统设置添加了输入法，但是按地球无法调用输入法

你这个问题我这边有重现,重启手机后解决了
