### ISSUE TITLE
參數命名

### ISSUE THREAD

**Issue by groverlynn** [imfuxiao/Hamster#421]
配色方案 color scheme （而不是schema）
輸入方案 schema （rime故意選了不同的拼寫避免typo）

文字顏色（前景色）是foreground color（對應background color背景色），從來沒有用front color的。front（與behind相對）會被誤認爲是mask之類的。

九宮格鍵盤是ten key，而不是nine grid（因爲實際上是十二宮，十個主鍵）。所謂26鍵鍵盤也不存在，至少算上空格27鍵吧？何況數量並不能區分鍵盤佈局。移動端的全鍵盤主要有QWERTY、QWERTZ、AZERTY。

按鍵鍵名（鍵帽）是keyCap，鍵值是keyCode，對應字符（第一層、無修飾鍵）是keyChar。如果用key value，這個key就不是按鍵，而是dictionary的key及其對應的value

標點是punctuation，符號才是symbol。rime默認是給標點貼punct tag，且設定爲punct type。不過這些都被符號鍵盤閹割了，以至於聯想預測也無法實現了。

內嵌輸入rime本身就有相應參數，是inline_preedit（內嵌顯示編輯區）和inline_candidate（內嵌顯示首選）

候選項是candidate，可分成label text comment三部分。candidate word不僅不準確（候選項一般是詞組而非單字，語句流輸入法的候選項甚至往往是句），也分不清是text還是comment。這組稱呼在rime對應commitText、commitComment等操作

**Comment by g6ai** [comment]
感觉很多是iRime留下来的坏翻译，等到app成熟稳定了可以专门讨论处理一下。（已经比iRime好多了）

**Comment by imfuxiao** [comment]
1. 配色方案中的 fornt 相关参数，已改为 foreground, 
2. 配置文件中的 candidate word 已改为 cnadidate text。
3. 键盘的命名不做变动，与搜狗，百度等输入法的键盘名保持一致。
4. 保留 symbol 命名，相关功能并不只是为了输入标点，也可以输入 emoji 等。

**Comment by jimmy54** [comment]
> 感觉很多是iRime留下来的坏翻译，等到app成熟稳定了可以专门讨论处理一下。（已经比iRime好多了）

躺枪

**Comment by imfuxiao** [comment]
> > 感觉很多是iRime留下来的坏翻译，等到app成熟稳定了可以专门讨论处理一下。（已经比iRime好多了）
> 
> 躺枪

大佬来了~
