### ISSUE TITLE
竖屏width为0，横屏width不为0时，在“备忘录”中横屏中，这些键不显示

### ISSUE THREAD

**Issue by leisure365** [imfuxiao/Hamster#422]
键盘布局文件中横竖布局相同显示没有问题。
        如标题——竖屏width为0，横屏width不为0时，在视频全屏播放发送弹幕时是正常显示的。
        但在“iOS备忘录”的横屏中，这些键基本不显示。
        其中，4套横竖布局不同（width竖为0，横不为0）的键盘只有1套是正常的。
（1）只有这套布局是正常的
![声笔47·横对称-1](https://github.com/imfuxiao/Hamster/assets/128219182/de7ee4ff-c0bc-4274-bd3c-c26f29810bc6)
![声笔47·横对称-2](https://github.com/imfuxiao/Hamster/assets/128219182/c8a24558-3ae6-424a-ad44-8196584f4074)
![声笔47·横对称-4](https://github.com/imfuxiao/Hamster/assets/128219182/35d8088c-7515-4a19-89d7-9d839b0de4f8)
(2)其他布局不正常（以其中1套展示）
![声笔trime-1](https://github.com/imfuxiao/Hamster/assets/128219182/8121cdb8-a293-4e14-931e-481a3b7e6159)
![声笔trime-2](https://github.com/imfuxiao/Hamster/assets/128219182/3b992d82-2f76-4d4e-8d3c-c28bf35dd943)
![声笔trime-3【备忘录】](https://github.com/imfuxiao/Hamster/assets/128219182/cdf7ef0a-e70a-41d4-bfe5-d6e34930d4c6)
（3）横竖布局不同的键盘截图，及键盘布局文件全部放在压缩包了。

[声笔键盘.zip](https://github.com/imfuxiao/Hamster/files/13448931/default.zip)
谢谢！

**Comment by imfuxiao** [comment]
您好，商店版本的 width = 0 或 height = 0 的 bug 是没有修复的，我在 TF 最新版本测试显示是正常的，麻烦您使用 TF 版本测试。

TF 测试链接：https://testflight.apple.com/join/6AkRfQYZ

**Comment by leisure365** [comment]
测试了，备忘录里还是不行。
![版本号](https://github.com/imfuxiao/Hamster/assets/128219182/acd8d09c-5666-48f3-bfad-13d413fc470d)
![版本号02](https://github.com/imfuxiao/Hamster/assets/128219182/534b57d8-7752-46c6-bd97-dd7cc4ab2d0f)

**Comment by imfuxiao** [comment]
抱歉，我没看出来，备忘录的问题是啥问题。

**Comment by imfuxiao** [comment]
您好，麻烦使用 TF 113 版本测试下。
另外，我看你的配置文件，键盘声笔34，第3569行，配置 action: none 的宽度有问题。

**Comment by leisure365** [comment]
感谢，已经可以了。
