### ISSUE TITLE
目前是无法定义单个按键的背景颜色(暂时没找到文档)

### ISSUE THREAD

**Issue by cactusnix** [imfuxiao/Hamster#425]
需求背景: 想要让自己的自定义键盘布局,能够实现和原生键盘一样的发送按钮的颜色和普通字母按键颜色是不一致的.
PS: 补充一个需求场景,期望能够按钮文字是动态的,就和默认值大小写锁定的功能一样

**Comment by imfuxiao** [comment]
嗯嗯，感谢反馈，此功能在开发计划内。不过会晚一些在开发，近期的版本还是在维护基础功能，键盘稳定性的开发上。

**Comment by imfuxiao** [comment]
键盘模型中的「按键样式」已支持此功能，可查阅：[文档](https://ihsiao.com/apps/hamster/docs/CustomKeyboard.html#keyboard-%E6%A8%A1%E5%9E%8B)。
