### ISSUE TITLE
TF 唤起键盘时第一排会跳，好几个版本这样了

### ISSUE THREAD

**Issue by BrianZR** [imfuxiao/Hamster#429]
https://github.com/imfuxiao/Hamster/assets/144171605/8dcbb796-1fa1-4c0a-b79e-2ae480213834

录屏录不出来，拍了个视频

**Comment by imfuxiao** [comment]
抱歉，麻烦使用最新的 TF 版本试下。

**Comment by BrianZR** [comment]
112没有出现这样的问题 感谢大佬 大佬注意护肝
