### ISSUE TITLE
希望小写字母按键的字母可以居中显示

### ISSUE THREAD

**Issue by Jmdayou** [imfuxiao/Hamster#430]
如图，当前tf版本的仓小写键盘的字母有些偏下

仓tf（111）：

<img width="414" alt="image" src="https://github.com/imfuxiao/Hamster/assets/130811752/e15f58d3-ed2a-47a2-a98c-7d3f9a3d0182">

系统原生：
<img width="414" alt="image" src="https://github.com/imfuxiao/Hamster/assets/130811752/6023aab4-d116-4ae3-84b7-0e38568594d8">

**Comment by imfuxiao** [comment]
您好，目前键盘在原生字体的模式下，小写是会居中的，自定义字体可能会有所偏差。因此关闭此 issue。
