### ISSUE TITLE
iOS上下划符号自动上屏

### ISSUE THREAD

**Issue by DJ975** [imfuxiao/Hamster#433]
我使用的国际音标输入法要用很多符号键辅助输入，如`a` `f` `.` `.`显示候选项`ä`。最近设置一台新设备的仓输入法，在从另一台正常使用的设备中将输入法文件复制过来。

在新设备中出现的错误情况是，上下划动时的一切符号会直接上屏，但，非上下划的符号则处理正常，例如若启用默认为`.`的空格右侧按键，`a` `f` `c上划` `c上划`直接上屏为`af..`，但`a` `f` `.` `.`（点击空格右侧按键输入`.`）正常显示未上屏的候选项`ä`。

两个设备的划动设置里的滑动操作全按默认，都是character（由Rime处理）而非symbol（不由Rime处理）。

**Comment by imfuxiao** [comment]
滑动设置中有个 processByRIME  的开关，如果不想直接上屏，可以打开此开关。

**Comment by DJ975** [comment]
> 滑动设置中有个 processByRIME  的开关，如果不想直接上屏，可以打开此开关。

是指键盘设置＞键盘布局＞滑动设置中各个按键可以单独设置的滑动操作是“字符（由RIME处理）”还是“符号字符（不由RIME处理）”吗？

所有的滑动操作都是设置为”字符”的。

**Comment by imfuxiao** [comment]
每个划动选项面有个processByRime 的开关，把这个开关打开。

Thanks & Best Regards

***@***.******@***.***>


From: DJ975 ***@***.***>
Date: Thursday, November 30, 2023 at 02:29
To: imfuxiao/Hamster ***@***.***>
Cc: morse.hsiao ***@***.***>, Comment ***@***.***>
Subject: Re: [imfuxiao/Hamster] iOS上下划符号自动上屏 (Issue #433)

滑动设置中有个 processByRIME 的开关，如果不想直接上屏，可以打开此开关。

是指键盘设置＞键盘布局＞滑动设置中各个按键可以单独设置的滑动操作是“字符（由RIME处理）”还是“符号字符（不由RIME处理）”吗？

所有的滑动操作都是设置为”字符”的。

―
