### ISSUE TITLE
某些网站登录时，输入法键盘不会触发自动填充

### ISSUE THREAD

**Issue by DawnLi-code** [imfuxiao/Hamster#436]
系统iOS17.1.1
输入法store版本2.0.1
iOS打开自动填充: 设置 - 密码 - 密码选项 - 打开 自动填充密码，并选择使用的密码管理工具。然后在登录的网页和部分app时即可使用自动填充功能。

正常情况下，打开需要输入密码的网页，系统键盘会触发自动填充，点击，然后面容ID验证即可自动填充账号密码。

发现使用本输入法键盘，在一些账号密码分两页(Google、EpicGames等)依次输入的时候，不会触发自动填充，截图有和系统键盘的对比。

![IMG_4401](https://github.com/imfuxiao/Hamster/assets/19859737/8f9099ea-307a-4a66-a7ce-9b88f00d3a1a)
![IMG_4402](https://github.com/imfuxiao/Hamster/assets/19859737/db384c67-5143-43b1-b43f-601e12bd8e49)
![IMG_4394](https://github.com/imfuxiao/Hamster/assets/19859737/cafa8952-24dd-45af-ac96-68cc1d4d7081)

在一些账号密码为一页(qq邮箱、GitHub)的情况下是能触发自动填充的，即使没触发，点击密码输入框，因为会自动切换到系统键盘，也能使用自动填充。

![IMG_4400](https://github.com/imfuxiao/Hamster/assets/19859737/c96a350b-99e8-482f-b40d-033946d40a3f)

**Comment by imfuxiao** [comment]
您好，iOS 安全限制，三方键盘是不会触发自动填充系统中已保存的账户信息的。

**Comment by DawnLi-code** [comment]
收到，原来如此。一直是使用系统输入法，没用过第三方所以不清楚，抱歉。
