### ISSUE TITLE
切换emojis键盘问题

### ISSUE THREAD

**Issue by laivn** [imfuxiao/Hamster#437]
自己配置的键盘切换emojis键盘没有显示，请问需要特殊配置吗？
![IMG_4338](https://github.com/imfuxiao/Hamster/assets/2081110/cc0e8e7d-4080-4d1b-8bb5-54ac737a2ff5)
![IMG_4339](https://github.com/imfuxiao/Hamster/assets/2081110/9316986c-219f-4570-a2ff-b0e9c64e9315)

**Comment by imfuxiao** [comment]
emoji键盘还未开发，相关问题见 #360

**Comment by imfuxiao** [comment]
抱歉，TF测试群已经不在加新人了，有问题可以给我发邮件，或者Github上提 issue.

后续在仓的功能完善后，我会建个QQ讨论群。
