### ISSUE TITLE
设置同步问题

### ISSUE THREAD

**Issue by kewell2000** [imfuxiao/Hamster#438]
在macOS系统上我用的是RIME输入法，自定义短语和用词频率等在设置中可以通过某些同步app同步到ios端，但iOS上仓输入法无法自定义读取iOS上app位置的同步过来的设置文件，导致macOS和iOS端的设置无法同步。
能否做到指定读取iOS端RIME文件夹？

**Comment by imfuxiao** [comment]
您好，可以参考 wiki 中的[同步教程](https://github.com/imfuxiao/Hamster/wiki/%E5%90%8C%E6%AD%A5%E6%95%99%E7%A8%8B)。
