### ISSUE TITLE
请教自定义配色的问题

### ISSUE THREAD

**Issue by MKingWang** [imfuxiao/Hamster#439]
作者你好，感且提供ios端的rime输入法。想请教一下，要如何增加仓的配色方案？  我把squirrel.yaml导入或者改成Hamster.yaml都无法识别

**Comment by imfuxiao** [comment]
您好，配置文件请命名为 `hamster.yaml` 或者 `hamster.custom.yaml` 两种。两个区别与 rime 的方式相同。

注意：暂不支持 rime 中的特殊的 yaml 语法，只支持通用的 yaml 语法。

您可以把您的配置增加到上述的文件中，案例参考可以使用 SharedSupport 目录下 `hamster.yaml` 文件。

配色参数说明，可以查阅 wiki 中的 [配色说明文档](https://github.com/imfuxiao/Hamster/wiki/%E9%85%8D%E8%89%B2%E8%AF%B4%E6%98%8E)
