### ISSUE TITLE
应用占用太多空间

### ISSUE THREAD

**Issue by ofzo** [imfuxiao/Hamster#440]
![20231128-222214](https://github.com/imfuxiao/Hamster/assets/18000037/475aaea6-8053-417d-b568-251beb832376)
![IMG_45EDAF14EC8A-1](https://github.com/imfuxiao/Hamster/assets/18000037/3a0af515-a83a-46b9-a427-7d6e09744a10)
我的配置文件只有 30+ Mb, 但在手机上占用了一个G的空间

**Comment by imfuxiao** [comment]
您好，占用空间的问题有以下几个原因：

1. 商店版本的 2.0.1 内置了多个输入方案，都在 SharedSupport 目录下，会占用一定的空间。
2. iOS 安全限制，键盘不能直接访问仓主体应用目录下的文件，所以仓会把输入方案复制一份到公共区域供键盘访问，所以会多一倍。
3. 当键盘没有开启完全访问权限时，对公共区域没有写权限，这种情况下，键盘会把公共区域下的文件复制到自己的沙箱环境下。体积又多了一倍。

综上，体积可能会变为三倍。所以看着占用了很多空间。

这个问题已经在 TF 版本中做过优化，商店版本也会在近期发布，请您在新版本发布在关注下这个问题。

**Comment by imfuxiao** [comment]
> 但是好像还是不对，3倍的话，也就是100Mb, 算上主题程序大概也就是200+Mb, 可这个占用了一个G
> 
> 另外SharedSupport下内置的输入方案是否可以删除呢

您好，2.1.0 版本已对存储空间进行了优化，麻烦您反馈下是否还存在问题。

**Comment by ofzo** [comment]
> > 但是好像还是不对，3倍的话，也就是100Mb, 算上主题程序大概也就是200+Mb, 可这个占用了一个G
> 
> > 
> 
> > 另外SharedSupport下内置的输入方案是否可以删除呢
> 
> 
> 
> 您好，2.1.0 版本已对存储空间进行了优化，麻烦您反馈下是否还存在问题。

嗯嗯,现在看起来300+正常了,辛苦了,感谢
