### ISSUE TITLE
版本更新之后，自己的配置文件丢失

### ISSUE THREAD

**Issue by chouxiang99** [imfuxiao/Hamster#441]
当前时间是2023年12月5日 09:15，我看商店里面仓输入法16小时之前更新了，我设置的应用自动更新，也不知道啥时候更新了，然后昨天感觉输入法怪怪的，今天上班看了一下，发现之前的配置文件都不在了，就感觉仓输入法恢复了出场设置，现在手机的仓输入法版本我看了一下是1.9

**Comment by imfuxiao** [comment]
抱歉，2.0 版本与 1.0 版本是不兼容的，所以在升级 2.0 后，1.0 的部分配置项可能不存在了。您可能需要按照 2.0 的配置项在重新配置下。

**Comment by chouxiang99** [comment]
> 抱歉，2.0 版本与 1.0 版本是不兼容的，所以在升级 2.0 后，1.0 的部分配置项可能不存在了。您可能需要按照 2.0 的配置项在重新配置下。

原来如此，那我重新配置一下就好了  今日上班摸鱼任务+1 哈哈哈哈  感谢解答~
