### ISSUE TITLE
把mac上的文件全量拷贝到iphone上，重新部署，报错

### ISSUE THREAD

**Issue by chouxiang99** [imfuxiao/Hamster#443]
不好意思，又来打扰了，之前1.0的时候，我的操作是，通过wifi传输文件，删除iphone的rime文件夹内容，然后把mac的rime文件夹内容全量拷贝到iphone部署即可
但是昨天更新之后，我今天早上同样的方式，把mac 的文件夹全量拷贝到iphone，包括build文件夹，在iphone点击重新部署，提示报错，但输入已经可以正常使用了
我查看了日志报错内容，如下

配置构建错误：
E20231205 10:41:01.540109 1585001 config_component.cc:247] error building config: luna_pinyin.schema
字典编译失败：
E20231205 10:41:01.544975 1585001 deployment_tasks.cc:372] dictionary 'luna_pinyin' failed to compile.

之前遇到过类似的问题是因为iphone的build文件夹中没有luna_pinyin.schema文件，但我今天特地确认了，存在luna_pinyin.schema文件，所以还需要麻烦 帮忙看看是啥原因导致的

<img width="718" alt="image" src="https://github.com/imfuxiao/Hamster/assets/45085951/82184197-f806-4bbf-92e3-c7f291ae80d0">
![image](https://github.com/imfuxiao/Hamster/assets/45085951/8cd87d1c-5426-487a-b433-961152acb399)

最后附一下iphone的rime文件夹内容以及log文件
![image](https://github.com/imfuxiao/Hamster/assets/45085951/be87ed5e-79a7-452f-b7c4-b2a9b8769396)
[20231205-104554.log](https://github.com/imfuxiao/Hamster/files/13554518/20231205-104554.log)

**Comment by chouxiang99** [comment]
少了一张iphone build文件夹存在luna_pinyin.schema的截图的截图
![image](https://github.com/imfuxiao/Hamster/assets/45085951/ea3a275c-ca70-448a-9271-ba4e1441fe84)

**Comment by chouxiang99** [comment]
然后目前在iphone部署，会部署成功，也可以正常使用，但是会提示存在异常
![image](https://github.com/imfuxiao/Hamster/assets/45085951/afb5a295-6834-4e22-a2e8-29c5bf9723b7)

**Comment by imfuxiao** [comment]
build下是不需要存放 yaml 文件的，这里的文件都是 rime 编译后的文件，你的词库文件应该放在 Rime 路径下。

**Comment by imfuxiao** [comment]
另外如果 mac 上是可以的，那么你可以先把 Rime 目录下文件清空了，然后在把 mac 下的文件全量复制到 Rime 目录下。

**Comment by chouxiang99** [comment]
> 另外如果 mac 上是可以的，那么你可以先把 Rime 目录下文件清空了，然后在把 mac 下的文件全量复制到 Rime 目录下。

1. 我试了一下删除mac里面的build文件夹中的所有yaml文件，重新部署之后重新在build文件夹生成了，所以这个应该没啥关系

2. 我在mac上是可以正常部署的，然后清空iphone 的rime目录，把mac下的全量拷贝到rime目录下（包含所有文件以及文件夹），依然是上面两个错误
一个是配置构建错误
E20231205 11:08:02.376956 1604083 config_component.cc:247] error building config: luna_pinyin.schema
一个是字典编译失败
E20231205 11:08:02.380813 1604083 deployment_tasks.cc:372] dictionary 'luna_pinyin' failed to compile.

具体的日志文件如下
[20231205-110802.log](https://github.com/imfuxiao/Hamster/files/13554661/20231205-110802.log)

**Comment by chouxiang99** [comment]
捣鼓了一中午，发现是因为缺少了luna_pinyin.dict.yaml，但mac上，不需要这个文件，也可以正常部署并使用，并且没有报错提示

**Comment by imfuxiao** [comment]
mac 上的 Squirrel 内置了 luna 方案。考虑到应用体积原因，仓是不内置这些方案的。

错误显示的问题：您上面的日志截图错误信息已经很明显了。
