### ISSUE TITLE
iOS，更新应用会丢失自定义方案

### ISSUE THREAD

**Issue by FurryWolfX** [imfuxiao/Hamster#444]
iOS，更新应用会丢失自定义方案
软件备份里面的东西也消失了，又得花时间重新配置，关键积累的词库也丢了，很难受

**Comment by changzaicl** [comment]
我这边倒是有备份，但是之前的方法（拷贝键盘词库文件至应用），在2.1版本中，无法实现目的。

**Comment by FurryWolfX** [comment]
> 我这边倒是有备份，但是之前的方法（拷贝键盘词库文件至应用），在2.1版本中，无法实现目的。 我找到原因了，“打开仓输入法，在 RIME 功能下，关闭“部署时覆盖键盘词库文件”开关。” https://github.com/imfuxiao/Hamster/wiki/%E5%90%8C%E6%AD%A5%E6%95%99%E7%A8%8B

不是这个问题，更新后像全新安装的一样，啥都没了，我是自己制作的输入方案

**Comment by weaming** [comment]
我也有这个现象

**Comment by imfuxiao** [comment]
您好，更新并不会删除文件，可能是相关参数或者功能做了调整，您可以重新部署一下，在尝试使用。

**Comment by FurryWolfX** [comment]
已从iCloud恢复之前的备份，但不是最新的，以后得勤备份了

**Comment by weaming** [comment]
之前局域网 WiFi上传进去的词库不见了

**Comment by qinghuannn** [comment]
同，很多文件都没了。。。

**Comment by ethereal-faith** [comment]
更新之后方案全没了，之前的四叶草也变成了雾凇

**Comment by imfuxiao** [comment]
从 2.1.0 版本后，仓只内置雾凇输入方案。SharedSupport 不在存放内置方案。原来内置方案已迁移至苹果的 CloudKit 云端存储，有需要的可以从云端下载。在`输入方案设置 -> 点击 + -> 方案下载`功能中。
