### ISSUE TITLE
中文文件名称乱码

### ISSUE THREAD

**Issue by weaming** [imfuxiao/Hamster#445]
<img width="291" alt="image" src="https://github.com/imfuxiao/Hamster/assets/10275711/0a809375-b4cf-4997-b379-98463085b594">

**Comment by imfuxiao** [comment]
收到，感谢反馈。

**Comment by imfuxiao** [comment]
TF 167 已修复

**Comment by imfuxiao** [comment]
> 这个乱码在 1.11.0 又出现了

在哪显示乱码的，麻烦您详细说明下，谢谢。

**Comment by weaming** [comment]
app  内『方案文件管理』，或者 输入方案上传里，浏览器里显示，下下来也是。

**Comment by imfuxiao** [comment]
> app 内『方案文件管理』，或者 输入方案上传里，浏览器里显示，下下来也是。

我这里测试不会，截图看看。

**Comment by weaming** [comment]
![IMG_0421](https://github.com/imfuxiao/Hamster/assets/10275711/dccb993e-c032-4fa5-952d-d3b839d2a718)

**Comment by imfuxiao** [comment]
看你的文件时间是好早之前的了，不是最新的。乱码是因为 zip 解压的问题，麻烦更新最新版本。

![image](https://github.com/imfuxiao/Hamster/assets/6482586/ad388905-4826-469f-935a-84ce08479cf4)

**Comment by weaming** [comment]
怎么更新这个， app  版本最新了

**Comment by imfuxiao** [comment]
> 怎么更新这个， app 版本最新了

如果 app 是最新版本，那么你看到的乱码就是之前有 bug 的版本首次解压生成的，后续升级也不会覆盖这些文件。

这些文件只是内置方案中的提供文件，所幸这些文件不影响你的正常使用，你可以忽略它。

如果你觉的看着碍眼，也可以删除它们，记得从乱码的父级文件删除。

如果你的方案文件中没有什么需要备份的东西，比如自己的词库之类的，也可以使用 rime 中的重置功能重置。

**Comment by imfuxiao** [comment]
> 我卸载重新安装可以了，只是又要我重新上传自己的文件

囧，这些文件也不影响你的使用，可以完全忽略的。

**Comment by weaming** [comment]
只是我需要跟踪这些文件，同时备份自己的文件
