### ISSUE TITLE
版本 2.1.0  找不到地方添加自定义配色方案了

### ISSUE THREAD

**Issue by weaming** [imfuxiao/Hamster#446]

**Comment by imfuxiao** [comment]
需要将配色添加到 hamster.yaml 或者 hamster.custom.yaml 文件中，可以参考默认配置文件 SharedSupport/hamster.yaml 文件。

配置参数参考配色说明文档。https://github.com/imfuxiao/Hamster/wiki/%E9%85%8D%E8%89%B2%E8%AF%B4%E6%98%8E

**Comment by jlm346383101** [comment]
[
![IMG_1269](https://github.com/imfuxiao/Hamster/assets/2649880/4ad359f2-ecd0-4aa3-8730-554a2085576e)
](url)
右下角“换行”左边按键上的label看不见了(我设置黑底色的原因)

**Comment by imfuxiao** [comment]
收到，感谢反馈。

**Comment by imfuxiao** [comment]
中英切换图片已可跟随配色调整颜色。
