### ISSUE TITLE
版本 2.1.0 按键震动失效

### ISSUE THREAD

**Issue by weaming** [imfuxiao/Hamster#447]
不知道是不是我个人的问题

**Comment by imfuxiao** [comment]
您好，现在已经是 2.1.0 版本了。

**Comment by weaming** [comment]
看错了，1.9.0 是  RIME  版本，已更新标题

**Comment by imfuxiao** [comment]
请检查键盘是否开启完全访问权限，如果开启了，还是没有震动，建议先关闭，然后重启手机，然后在开启。

**Comment by weaming** [comment]
开启完全访问后恢复。
是不是更新就会重置这个开关？

**Comment by imfuxiao** [comment]
> 开启完全访问后恢复。 是不是更新就会重置这个开关？

应该是系统的原因，仓自身是不会调整这个开关的。
