### ISSUE TITLE
[Bugs] 

### ISSUE THREAD

**Issue by groverlynn** [imfuxiao/Hamster#448]
「分類符號鍵盤」無法關閉。選擇關閉「分類符號鍵盤」的效果是啓用主鍵盤的第二層和第三層。
九宮格鍵盤只能直接輸出數字，且是主鍵盤數字而非小鍵盤九宮格數字。選擇ascii模式會跳轉ascii的qwerty鍵盤且錯誤顯示成中文qwerty鍵盤。左欄符合均無法由rime處理，也無法自定義非常重要的分詞鍵等。
默認不顯示候選項編號，但卻沒有屏蔽用編號選詞的功能。選項若不帶編用於號，原本的選項鍵就理應可以用作直接輸入。

另外，app內的文本編輯器，在調整完選擇範圍且選擇範圍較大的時候不會彈出浮動控制條（複製剪切等命令），而喚起該控制條的唯一方法是點選已選範圍，而點選已選範圍的結果是取消選擇……於是陷入了無限循環……
「應用」、「鍵盤」兩者有何區別根本未有説明，加上icloud一式三份佔空間不説，優先級（誰覆蓋誰）特別混亂，若是再做一次同步，一不小心文件量翻倍，全是衝突……

**Comment by imfuxiao** [comment]
您好，

1. 分类符号无法关闭。

我这里测试是可以关闭，关闭后，显示类似原生输入法方案符号键盘。

2. 九宮格鍵盤只能直接輸出數字，且是主鍵盤數字而非小鍵盤九宮格數字。

您说的九宫格是指键盘布局中的中文九宫格么？这个是用来做中文九键输入的，需要搭配雾凇输入方案使用。不存在全键盘盘的副键盘数字键的问题。

3. app内文本编辑器目前只是简单的编辑功能，重量级的编辑功能，请使用专业编辑器App 进行编辑文件。例如：iOS 的 Textastic 应用，可以直接编辑仓下文件。

4. 应用文件 与 键盘文件的区别

应用文件是指仓app内沙盒环境下 Document 目录下文件。放在这个目录就是为了开放仓内的 rime 文件，方便使用 iOS 内置的 File 应用管理文件，同时也方便使用外部编辑器，如上面说得 Textastic 应用编辑文件。

键盘文件指键盘使用的文件。因为 iOS 安全显示，键盘应用无法直接访问仓 App 内沙盒目录的文件。所以需要将应用文件复制一份给键盘使用。

如果不使用自造词功能，那么键盘文件与应用文件是完全一样的，没有区别。所以编辑的时候请编辑应用文件下的文件，编辑完成后，使用 rime 的重新部署功能，会重新复制。


目前仓的功能还不完善，所以没有专门写说明文档，后面会做补充。
