### ISSUE TITLE
希望雾凇拼音-九宫格能支持模糊音

### ISSUE THREAD

**Issue by gbinhe** [imfuxiao/Hamster#450]
在雾凇拼音里面设置了模糊音，但对九宫格模式无效，在九宫格文件里面没找到模糊音设置。

**Comment by imfuxiao** [comment]
您好，九宫格为啥还要支持模糊音呢，如果支持模糊音，会导致候选更多，不利于候选字筛选。

**Comment by noisay** [comment]
> 在雾凇拼音里面设置了模糊音，但对九宫格模式无效，在九宫格文件里面没找到模糊音设置。

雾凇拼音最近更新的配置文件中，有一个t9.schema.yaml，你在那里面按照PC上一样改模糊音就可以了。

**Comment by noisay** [comment]
> 您好，九宫格为啥还要支持模糊音呢，如果支持模糊音，会导致候选更多，不利于候选字筛选。

俺们南方人nl不分的啦

**Comment by gbinhe** [comment]
> > 在雾凇拼音里面设置了模糊音，但对九宫格模式无效，在九宫格文件里面没找到模糊音设置。
> 
> 雾凇拼音最近更新的配置文件中，有一个t9.schema.yaml，你在那里面按照PC上一样改模糊音就可以了。

多谢，把t9.schema.yaml里面候选拼音的小写字母编码改了下，现在可以了
