### ISSUE TITLE
希望能关闭九宫格上滑输入数字的功能

### ISSUE THREAD

**Issue by skypoc** [imfuxiao/Hamster#453]
上滑输入数字非常容易误触，而且在连打的情况下会导致输入按键丢失

**Comment by imfuxiao** [comment]
您好，可以通过自定义配置文件调整这个配置。

方式1:

1. 您可以通过 iOS 内置应用，将手机目录下的仓输入法下的`SharedSupport`目录下 `hamster.yaml`文件复制到 `Rime`目录下
2. 通过仓的文件管理功能，打开`应用文件`下 `Rime`目录的 `hamster.yaml` 文件（即上一步复制的文件）
3. 修改 `swipe` 下 `keyboardSwipe`的内容为：
```yaml
swipe:
  keyboardSwipe: []
```
4. 重新部署


方式2:

1. 新建hamster.custom.yaml 文件，文件内容为
```yaml
patch
  swipe:
    keyboardSwipe: []
```
2. 通过 `WiFi上传功能`，将文件存放至 `Rime` 目录下
3. 点击重新部署。

**Comment by skypoc** [comment]
非常感谢

**Comment by xuqiccr** [comment]
请问您起作用了吗，我两个方案都试了一下，都没有生效
