### ISSUE TITLE
雾凇输入法自定义emoji重新部署以后会直接重置成原来的

### ISSUE THREAD

**Issue by keaidu** [imfuxiao/Hamster#455]

**Comment by keaidu** [comment]
时间关键词改完保存重新部署以后还是老样子没变化。
![Uploading IMG_4523.png…]()

**Comment by imfuxiao** [comment]
配置文件不应该去修改 `键盘文件` 下的内容。如果不使用自造词功能，`键盘文件`只是`应用文件`的一个复制品，所以您在`键盘文件`下做的改动，在重新部署后，都会被`应用文件`下的文件所替换。

如果您关闭了 `RIME -> 部署时覆盖键盘词库文件`，那么重新部署时，会先用`键盘文件`下的`*.text`或者`*.userdb`文件覆盖`应用文件`。这是为了保留键盘生成的自造词。
