### ISSUE TITLE
能否保持中英文状态或者键盘布局的选择

### ISSUE THREAD

**Issue by qhjia** [imfuxiao/Hamster#456]
我想完全脱离ios系统的英文键盘，只使用仓输入法满足中英文输入需求，但现在遇到一个问题，我没有办法让键盘保持住英文的状态。无论是用中英文切换键，还是切换到英文的键盘布局，在收起键盘再打开后都会切换回中文状态。目前我能做到的就只有在app中切换键盘布局才能做到保持英文状态。
所以我想问一下有没有什么办法可以在键盘中用一个按键就做到长期的切换中英文，而不用进入app设置。比如用脚本更改配置文件中reset的值之类的方法？

**Comment by imfuxiao** [comment]
两种方式。

方式1: 键盘布局切换，适用与中英布局想有区别的情况，中文一套键盘布局，英文一套键盘布局，可以在自定义布局中的某个按键上设置两套布局的切换。

优点：键盘可以有所区别，英文键盘下可以配置 rime 的英文输入方案。

方式2: ASCII状态切换，适用于中英布局相同的情况。通过快捷指令 `#中英切换` 修改 ascii_mode 状态值，从而达到输入英文的需求。

优点：简单。缺点：无法挂载英文输入方案。

**Comment by qhjia** [comment]
您好，我的意思是没有保持住中英文状态，就是说如果我的主输入法是中文，我不论用哪种您说的方法，暂时切换到了英文，将键盘收起后再重新打开都会回到主键盘，没办法像在小地球里切换了英文一样长期保持。

**Comment by imfuxiao** [comment]
> 您好，我的意思是没有保持住中英文状态，就是说如果我的主输入法是中文，我不论用哪种您说的方法，暂时切换到了英文，将键盘收起后再重新打开都会回到主键盘，没办法像在小地球里切换了英文一样长期保持。

目前可以通过输入方案切换来实现，配置一个英文输入方案，英文输入方案可以挂载英文词典。不需要切换键盘，需要输入英文时，切换到英文输入方案就可以了。

而且切换的方案状态是会保存的。

**Comment by qhjia** [comment]
谢谢，这种方法确实可以实现我的需求。
另外，我发现“加载文字显示输入方案名”和“长显显示输入方案名”有冲突，刚加载新方案时有时会重叠显示，有时会保留上个输入方案名。

**Comment by imfuxiao** [comment]
> 谢谢，这种方法确实可以实现我的需求。 另外，我发现“加载文字显示输入方案名”和“长显显示输入方案名”有冲突，刚加载新方案时有时会重叠显示，有时会保留上个输入方案名。

感谢反馈， TF 140 以后的版本已修复此问题，商店版本等 2.2.0 修复。

**Comment by qhjia** [comment]
好的。另外请问testflight现在是不能再加入了吗，我用之前的链接已经加不了。

**Comment by imfuxiao** [comment]
是的，目前TF链接已经关闭， TF 的人数已经上千了，帮助测试已经足够了。

**Comment by qhjia** [comment]
好的，感谢耐心解答
