### ISSUE TITLE
九宫格无法输入中文

### ISSUE THREAD

**Issue by warmso** [imfuxiao/Hamster#457]
无论使用App的默认配置文件还是mac端的rime配置 切换为九宫格键盘之后 输入的都是数字 无法输入中文

iOS 17.1.2

**Comment by warmso** [comment]
hi:

	我是设置了 雾凇输入方案·九宫格 也还是输入后全是数字 截图如下：
	试过了所有能设置的方案都无效

	需要提供log文件吗
	

￼￼

**Comment by imfuxiao** [comment]
是内置的雾凇方案么？您的雾凇可能版本不是最新的。您可以使用 rime 的重置功能，使用内置的雾凇方案。

**Comment by warmso** [comment]
hi：
	解决了 谢谢！
