### ISSUE TITLE
自定义的英文键盘是否可以挂载英文词库，从而完成单词联想？

### ISSUE THREAD

**Issue by Pansamore** [imfuxiao/Hamster#458]
如果可以的话，请问具体该如何操作？

**Comment by imfuxiao** [comment]
不可以，内置英文键盘下是没有 rime 引擎的，即输入什么，就输出什么。

建议您配置一个英文输入方案。如 https://github.com/sdadonkey/rime-english 。

通过输入方案切换，来完成英文词库挂载。
