### ISSUE TITLE
几个快捷指令无法生效使用

### ISSUE THREAD

**Issue by jlm346383101** [imfuxiao/Hamster#459]
1、#配色切换: 在设置里面启用配色后，再将z键下滑设置成配色切换，但是不生效，需要如何设置才能使用?
![IMG_1273](https://github.com/imfuxiao/Hamster/assets/2649880/79b3dd2b-11c7-4437-9c57-bc212c220fce)
![IMG_1272](https://github.com/imfuxiao/Hamster/assets/2649880/e0e9da47-d140-40e2-9013-35a65db15b9e)
2、#换行: 在右下角的“enter”上将上划、下划、左划均设置为该指令后不生效(不显示文本、无法换行)。但是设置在z键能生效(显示文本、换行成功)。→→→→→我在微信输入框测试的。
3、希望增加一个快捷指令→全选。
感谢!!!

**Comment by imfuxiao** [comment]
您好，部分快捷指令是1.0版本的功能，目前2.0还未完全把1.0的功能迁移完毕。还请耐心等待。

另外，中英切换图标的 icon 的问题，我想想办法处理，感谢您的反馈。

**Comment by jlm346383101** [comment]
好的，大佬，感谢回复。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "imfuxiao/Hamster"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月8日(星期五) 晚上11:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [imfuxiao/Hamster] 几个快捷指令无法生效使用 (Issue #459)





 
您好，部分快捷指令是1.0版本的功能，目前2.0还未完全把1.0的功能迁移完毕。还请耐心等待。
 
另外，中英切换图标的 icon 的问题，我想想办法处理，感谢您的反馈。

**Comment by imfuxiao** [comment]
快捷指令已经可以使用了。icon 的问题也已经处理。
