### ISSUE TITLE
需求~删除键~向左滑动快速删除

### ISSUE THREAD

**Issue by androidcn** [imfuxiao/Hamster#46]
需求~删除键~向左滑动快速删除

输入法误触很严重，无法正常使用

iPhone13ProMax
15.1.1

**Comment by imfuxiao** [comment]
抱歉, 误触的问题还在处理中(#30 ), 我会尽快修复.

**Comment by imfuxiao** [comment]
> > 抱歉, 误触的问题还在处理中(#30 ), 我会尽快修复.
> 
> 求加快，删除键 向左快速删除

收到, 不过最近还是先优先确保bug修复. 请理解~

**Comment by imfuxiao** [comment]
快速删除编码区功能已上线，默认绑定在删除键的左滑手势中。
