### ISSUE TITLE
怎么导入界面设置

### ISSUE THREAD

**Issue by tamhaywoo** [imfuxiao/Hamster#461]
如题，在关于页面中，有导出界面设置，目前不知道怎么导入界面设置文件。

**Comment by imfuxiao** [comment]
抱歉，目前没有直接导入 `hamster.yaml` `hamster.custom.yaml` 的功能。

目前可以通过以下方式进行：
方式1. 通过 Files 应用复制文件到手机本地的仓输入法下 `Rime` 目录中
方式2: 通过仓的 `WiFi 上传功能`将文件上传至 `Rime` 目录下

**Comment by tamhaywoo** [comment]
好的，那也是有解决方案的。谢谢呢

**Comment by tamhaywoo** [comment]
需要注意把文件名修改下：
将默认导出的键盘配置文件`hamster.app.yaml`更改为`hamster.yaml`
