### ISSUE TITLE
「自定义键盘配置文件加载失败」，能提供具体的报错信息吗？

### ISSUE THREAD

**Issue by ccomac** [imfuxiao/Hamster#462]
作者您好，2.2 在 TF 发布以后自定义键盘描述文件的语法大改，我按照新的 Wiki 内容修改原有的配置之后就反复提示「自定义键盘配置文件加载失败」，然而程序不会告知用户到底是哪里出现了问题，导致想要修改也无从下手，不知是否可以在加载失败的时候给出具体的信息，这样才能进行针对性的修改，不然的话对于普通用户来说自定义键盘布局的这个功能使用起来实在是有点困难了（我只能通过逐一测试按键的方式来找到到底是哪个键的配置有问题），谢谢。

**Comment by chea08** [comment]
[20231214-235211.log](https://github.com/imfuxiao/Hamster/files/13679380/20231214-235211.log)

**Comment by groverlynn** [comment]
> [20231214-235211.log](https://github.com/imfuxiao/Hamster/files/13679380/20231214-235211.log)

log沒有錯誤日誌。打開shared裏面編譯後的默認的hamster.app.yaml，lint瘋狂報錯，從都到尾全是紅的，list的縮進全是錯的……

**Comment by imfuxiao** [comment]
> > [20231214-235211.log](https://github.com/imfuxiao/Hamster/files/13679380/20231214-235211.log)
> 
> log沒有錯誤日誌。打開shared裏面編譯後的默認的hamster.app.yaml，lint瘋狂報錯，從都到尾全是紅的，list的縮進全是錯的……

rime只会编译 `hamster.yaml` 和 `hamster.custom.yaml` 文件，且编译后的文件会合并到 `Rime/build/hamster.yaml`。所以不知道你描述的问题是什么？

**Comment by imfuxiao** [comment]
> 作者您好，2.2 在 TF 发布以后自定义键盘描述文件的语法大改，我按照新的 Wiki 内容修改原有的配置之后就反复提示「自定义键盘配置文件加载失败」，然而程序不会告知用户到底是哪里出现了问题，导致想要修改也无从下手，不知是否可以在加载失败的时候给出具体的信息，这样才能进行针对性的修改，不然的话对于普通用户来说自定义键盘布局的这个功能使用起来实在是有点困难了（我只能通过逐一测试按键的方式来找到到底是哪个键的配置有问题），谢谢。

您好，TF（150）版本后增加了 yaml 文件的错误信息，可以定位到具体 Ymal 文件中那个节点出的问题，错误信息在日志的最后一行。

**Comment by imfuxiao** [comment]
> > 作者您好，2.2 在 TF 发布以后自定义键盘描述文件的语法大改，我按照新的 Wiki 内容修改原有的配置之后就反复提示「自定义键盘配置文件加载失败」，然而程序不会告知用户到底是哪里出现了问题，导致想要修改也无从下手，不知是否可以在加载失败的时候给出具体的信息，这样才能进行针对性的修改，不然的话对于普通用户来说自定义键盘布局的这个功能使用起来实在是有点困难了（我只能通过逐一测试按键的方式来找到到底是哪个键的配置有问题），谢谢。
> 
> 您好，TF（150）版本后增加了 yaml 文件的错误信息，可以定位到具体 Ymal 文件中那个节点出的问题，错误信息在日志的最后一行。

RIME 重新部署有两种错误：

错误1: RIME 引擎部署时，由 RIME 生成的异常，这部分会在 RIME 部署中报出，或者 RIME 部署结束后，检测 RIME 输出的日志中的异常报出。如果是日志中的异常，屏幕顶部会有一个 Banner 弹出。日志中可通过开头 `E` 加时间关键字搜索，如`E2023`。

错误2: RIME 阶段完毕后，仓会读取 `Rime/build/hamster.yaml` 文件。序列化（可以理解为解析配置文件）为仓内部的模型，已识别具体的配置内容。在序列化的过程中，如果 `hamster.yaml` 文件符合 yaml 的语法规范，但不符合仓定义的模型，就会报错。

举例，`action: test` 这个符合 yaml 的语法，但不符合仓的模型，序列化时就会报错。

目前大部分错误都是这种类型，因为仓在 TF 145 后模型变了，旧的配置在序列化时就会报错。

目前 TF 150 版本后，会将序列化时生成的异常，追加到 RIME 部署时生成的日志中，所以直接看最后一行就可以了，里面有 yaml 文件中具体那个节点出的错。

> 注意：这里的 yaml 文件是 rime 编译后生成的 `Rime/build/hamster.yaml` 文件，需要自己在找到对应的原始配置文件中，比如用`__include`指令导入的文件。

举例：

![image](https://github.com/imfuxiao/Hamster/assets/6482586/3304d3bf-b54c-4e7a-93f6-57ec663d2c9e)

上面日志中显示，在`Rime/build/hamster.yaml`文件中的 `keyboards` 节点下 `Index 0` (因为 keybords 是数组类型，index 0 表示第一个元素)，`rows`节点下的`Index 0`（同上，rows 也是数组类型，Index 0 表示第一个元素）。`keys`节点下 `index 8`（同上，keys 也是数组类型，index 8 表示第 9 个元素），`action`异常。

![image](https://github.com/imfuxiao/Hamster/assets/6482586/b6c8fbad-cadd-4dac-a875-18377aee432e)


上图是错误日志对应 `Rime/build/hamster.yaml` 文件。可以看到`action`对应的值是 `{keys: "Control+Shift+e"}` ，这个配置符合 yaml 语法规范，Rime 可以正常编译，但不符合仓的模型，所以报错。
