### ISSUE TITLE
tf build137切换输入方案后，空格上显示的还是上一个方案的名称

### ISSUE THREAD

**Issue by ywyself** [imfuxiao/Hamster#463]
tf build 137 版本，自定义键盘。

在键盘中切换输入方案后，空格上显示的仍然是上一个方案的名字，实际上方案已经切换了。重新呼出键盘，会显示正确的名称
![image](https://github.com/imfuxiao/Hamster/assets/27804899/f7710cb1-5393-4baf-af2f-0ba656bd7b77)
![image](https://github.com/imfuxiao/Hamster/assets/27804899/7cc520bf-8573-426d-a37b-e6f870ed947c)

**Comment by imfuxiao** [comment]
您好，感谢反馈，预计 TF 版本 140 后面的版本修复。

**Comment by ywyself** [comment]
@imfuxiao 您好，感谢付出。 我遇到了另一个问题，在深色模式下，弹出数字键盘，样式不太对，浅色模式是正常的。

![image](https://github.com/imfuxiao/Hamster/assets/27804899/d48a9f76-8d3b-42f5-a2c6-b3db6984f3e0)

**Comment by imfuxiao** [comment]
TF 新版本以修复，如有问题，麻烦您重新反馈。
