### ISSUE TITLE
仓的配置文件问题

### ISSUE THREAD

**Issue by JanuaryChenMy** [imfuxiao/Hamster#465]
新版本更新后，我把键盘自带的配置文件直接复制到了icloud里，改了一下过滤和候选大小，但是是无效的，请问是什么原因？

**Comment by imfuxiao** [comment]
您好，TF 137 版本后调整自定义布局及配置文件中的一些参数格式。TF 的 app 里有说明。

自定义布局目前可以通过: https://lost-melody.github.io/hamster-tools 网页工具转为新版格式。

其他参数需要手工修改。
