### ISSUE TITLE
关于英文键盘自动关闭候选栏的问题

### ISSUE THREAD

**Issue by JanuaryChenMy** [imfuxiao/Hamster#467]
英文是不需要候选栏的吧？可以给个方法，让切换自带英文键盘或自定义键盘时，可选关闭候选栏吗(或调整高度为0)？
![image](https://github.com/imfuxiao/Hamster/assets/42561739/52d645bd-95a6-4e99-8bcc-59a1c4868db9)

**Comment by imfuxiao** [comment]
抱歉，目前候选栏不能跟随键盘环境自动调节，只能始终保持设置状态。
