### ISSUE TITLE
请问这个参数是在哪里调

### ISSUE THREAD

**Issue by ZZZ7664** [imfuxiao/Hamster#468]
![image](https://github.com/imfuxiao/Hamster/assets/103173090/06094261-7902-489a-b945-836afa361a65)

**Comment by ZZZ7664** [comment]
这个是旧版的，新版的直接恢复默认了，而且恢复备份也不可用![image](https://github.com/imfuxiao/Hamster/assets/103173090/e27a865f-9f4a-4de2-9d06-9df5f148bdab)

**Comment by imfuxiao** [comment]
您好，在配置文件中调整，如果您使用 UI界面设置，可以不用理会。

**Comment by ZZZ7664** [comment]
好的，谢谢解答> 您好，在配置文件中调整，如果您使用 UI界面设置，可以不用理会。
