### ISSUE TITLE
数据读取异常

### ISSUE THREAD

**Issue by 971230** [imfuxiao/Hamster#472]
好久没有动过仓的配置了，今天莫名其妙的调不出来输入法，重新部署提示异常，是bug还是我哪里问题。主要是我很久什么都没有动了，都是正常使用的，就很莫名其妙。
![微信图片_20231223140532](https://github.com/imfuxiao/Hamster/assets/37500200/73b69269-9635-42c9-91cd-c80a0f439ae3)
[20231223-140656.log](https://github.com/imfuxiao/Hamster/files/13758184/20231223-140656.log)

**Comment by 971230** [comment]
看了一下应该是版本更新到2.2之后的文件格式不兼容的问题，还是想反馈一下能不能兼容之前的版本的自定义文件，哪怕是一个版本更新，这样就不至于软件一更新输入法就崩了。

**Comment by xy464193** [comment]
我刚更新后，也是报相同的错，没找到解决方法，卸载仓输入法后，重新上传数据，再布署就可以了。
