### ISSUE TITLE
升级到最新版, 数据读取错误, 文件在此,可以下载查看

### ISSUE THREAD

**Issue by 986138497** [imfuxiao/Hamster#473]
[hamster.custom.zip](https://github.com/imfuxiao/Hamster/files/13758285/hamster.custom.zip)
升级到最新版, 数据读取错误 .之前都是可以的

**Comment by datacruiser** [comment]
RIME重置，然后重新上传配置文件再重新部署就好了

**Comment by 986138497** [comment]
> RIME重置，然后重新上传配置文件再重新部署就好了

不行哦,我试了

**Comment by 986138497** [comment]
> RIME重置，然后重新上传配置文件再重新部署就好了

我是从 AppStore 下载的, 不知道作者改了啥, 我看了 issus, 很多都遇到了这个问题

**Comment by datacruiser** [comment]
> > RIME重置，然后重新上传配置文件再重新部署就好了
> 
> 我是从 AppStore 下载的, 不知道作者改了啥, 我看了 issus, 很多都遇到了这个问题

我也是从appstore 更新了一下，然后将RIME重置以后，重新上传了文件 重新部署成功

**Comment by imfuxiao** [comment]
> [hamster.custom.zip](https://github.com/imfuxiao/Hamster/files/13758285/hamster.custom.zip) 升级到最新版, 数据读取错误 .之前都是可以的

自定义键盘模型已从 2.2.0 调整了，您配置文件中的还是旧版。请转为最新模型。参考 wiki 中的「自定义键盘」。

另外配置文件中有些参数也需要调整，如 `Keyboard` 已改为 `keyboard` 等等
