### ISSUE TITLE
破坏性升级还是有点影响体验的

### ISSUE THREAD

**Issue by unexpectedxx** [imfuxiao/Hamster#475]

**Comment by imfuxiao** [comment]
抱歉，前期设计错误产生的问题，必须调整模型。后续尽量不这样粗暴处理了。

**Comment by Pansamore** [comment]
> 抱歉，前期设计错误产生的问题，必须调整模型。后续尽量不这样粗暴处理了。

如果可以，希望可以在readme里写一下更新的内容，这样我们更新前可以提前准备。

**Comment by FurryWolfX** [comment]
这是我第三次因为升级导致输入法崩掉，这对我这种使用了大量自定义方案的人非常的崩溃

**Comment by FurryWolfX** [comment]
更新2.2.0之后userdb无法同步了

**Comment by trusun** [comment]
我是第二次升级, 第二次崩掉, 卸载了, 受不了这个刺激了

**Comment by kefengzhang** [comment]
还好我的修改比较少...只修改了拼音模糊输入且电脑上有备份,呵呵

**Comment by sunznx** [comment]
> 这次更新之后发现userdb无法同步了

现在是不是还是无法同步，我也发现了这个问题。不知道是自己的配置问题还是 bug。
另外，配置那里的【部署时覆盖键盘词库文件】是什么意思？

**Comment by trusun** [comment]
跟你说一下我的解决方案吧, 卸载后没忍住重装上了, 重装后就不报错了, 开同步再次报错, 
再次卸载重装, 重装后上传icloud, 重新配置重新部署, 同步等一切都正常了.

**Comment by sunznx** [comment]
> 跟你说一下我的解决方案吧, 卸载后没忍住重装上了, 重装后就不报错了, 开同步再次报错, 再次卸载重装, 重装后上传icloud, 重新配置重新部署, 同步等一切都正常了.

我也是卸载重装了，但是词库还是有问题。

**Comment by imfuxiao** [comment]
> > 这次更新之后发现userdb无法同步了
> 
> 现在是不是还是无法同步，我也发现了这个问题。不知道是自己的配置问题还是 bug。 另外，配置那里的【部署时覆盖键盘词库文件】是什么意思？

检查是否为键盘开启「完全访问权限」

**Comment by sunznx** [comment]
> > > 这次更新之后发现userdb无法同步了
> > 
> > 
> > 现在是不是还是无法同步，我也发现了这个问题。不知道是自己的配置问题还是 bug。 另外，配置那里的【部署时覆盖键盘词库文件】是什么意思？
> 
> 检查是否为键盘开启「完全访问权限」

确实，因为我是卸载重装的，没开启这个【完全访问权限】

**Comment by Silent-wqh** [comment]
新手在升级前好不容易搞好了小鹤音形，结果升级后崩掉了，到现在都没继续使用仓输入法了🥹

**Comment by kefengzhang** [comment]
> 新手在升级前好不容易搞好了小鹤音形，结果升级后崩掉了，到现在都没继续使用仓输入法了🥹

表示同情,下次可以试试用电脑备份好配制文件..个人感觉仓输入法还是很好用的,因为我的mac就是用的鼠须管输入法,都是一条线的,之前研究过,所以很认同rime相关的输入法

**Comment by imfuxiao** [comment]
非常抱歉给各位带来不好的体验，后续升级我会认真处理，尽量做到向下兼容。

此 issue 先关闭，后续如果有新的问题，可以提交新的 issue.
