### ISSUE TITLE
升级到2.2.0，userdb文件无法同步

### ISSUE THREAD

**Issue by FurryWolfX** [imfuxiao/Hamster#476]
升级到2.2.0，userdb文件无法同步。一开始以为是我自定义方案的问题，后来重置默认配置，执行同步，发现在sync文件夹中没有产生userdb文件

**Comment by cactusnix** [comment]
重置后有重新处理installation.yaml里面的sync_dir配置吗?

**Comment by FurryWolfX** [comment]
> 重置后有重新处理installation.yaml里面的sync_dir配置吗?

没有

**Comment by cactusnix** [comment]
> > 重置后有重新处理installation.yaml里面的sync_dir配置吗?
> 
> 
> 
> 没有

需要配置了才能正确展示 可以了解一下wiki文档里面关于同步的那些
