### ISSUE TITLE
配置文件无法部署

### ISSUE THREAD

**Issue by yett1873** [imfuxiao/Hamster#479]
作者你好，更新最新版本后部署多次还是无法载入配置文件，描述一下尝试的过程，不知道是哪里做错了，烦请指正：
## 步骤
1. 新建hamster.custom.yaml, 复制粘贴[hamster.yaml 配置文件说明（alpha） · imfuxiao/Hamster Wiki](https://github.com/imfuxiao/Hamster/wiki/hamster.yaml-%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E8%AF%B4%E6%98%8E%EF%BC%88alpha%EF%BC%89)并微调，保存在本地仓输入法下 Rime/中
2. 按照 #379 中的方法重置界面设置并重新部署
3. 结果：对工具栏的修改等没有成功载入
4. 使用[倉輸入法·工具 · Lost Melody](https://lost-melody.github.io/hamster-tools)导出配色文件和布局文件并命名为`keyboards-yett.yaml`和`colorSchemas-blue.yaml`，保存在本地仓输入法下 Rime/中
5. 在hamster.custom.yaml的对应处换上这两个文件名，如图![image](https://github.com/imfuxiao/Hamster/assets/75569851/277a065c-7f24-41f9-8c2e-ee78ae814938) ![image](https://github.com/imfuxiao/Hamster/assets/75569851/1829d364-fb4d-494f-b923-abb1f0f8f17a) 
6. 重复2
7. 结果：无论是对工具栏的修改等，还是配色和布局，都没有成功载入
8. 尝试把配色和布局复制粘贴在hamster.custom.yaml中，如图 ![image](https://github.com/imfuxiao/Hamster/assets/75569851/301075ed-0473-48fd-b521-5ceb72a070bd) ![image](https://github.com/imfuxiao/Hamster/assets/75569851/f76e9b23-d113-4c2d-89ee-9adc9ae69b57)
10. 重复2
11. 结果：无论是对工具栏的修改等，还是配色和布局，都没有成功载入

**Comment by cactusnix** [comment]
keyboards里面的action格式已经不是这样的了, 是{ character: { char: 1 } }, 这次是个破坏性升级, 所以需要处理.

**Comment by yett1873** [comment]
> keyboards里面的action格式已经不是这样的了, 是{ character: { char: 1 } }, 这次是个破坏性升级, 所以需要处理.

感谢回复，已经改过来了。不过即便没有自定义键盘，直接复制粘贴[hamster.yaml 配置文件说明（alpha） · imfuxiao/Hamster Wiki](https://github.com/imfuxiao/Hamster/wiki/hamster.yaml-%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E8%AF%B4%E6%98%8E%EF%BC%88alpha%EF%BC%89)，只调整字体大小，也依旧无法载入

**Comment by cactusnix** [comment]
> > keyboards里面的action格式已经不是这样的了, 是{ character: { char: 1 } }, 这次是个破坏性升级, 所以需要处理.
> 
> 感谢回复，已经改过来了。不过即便没有自定义键盘，直接复制粘贴[hamster.yaml 配置文件说明（alpha） · imfuxiao/Hamster Wiki](https://github.com/imfuxiao/Hamster/wiki/hamster.yaml-%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E8%AF%B4%E6%98%8E%EF%BC%88alpha%EF%BC%89)，只调整字体大小，也依旧无法载入

你需要将文件先命名成hamster.custom.yaml, 遵循rime规范, 然后在里面使用patch打补丁的形式才可以的.
![Uploading Screen Shot 2023-12-25 at 11.32.59.png…]()

**Comment by yett1873** [comment]
> 你需要将文件先命名成hamster.custom.yaml, 遵循rime规范, 然后在里面使用patch打补丁的形式才可以的.

谢谢！终于解决了。我一直是把文件命名为hamster.custom.yaml的，但是没加patch，是这个原因导致的。
