### ISSUE TITLE
需求：增加WebDAV方式或iCloud方式同步字库

### ISSUE THREAD

**Issue by imShire** [imfuxiao/Hamster#48]
需求：增加WebDAV方式或iCloud方式同步字库

**Comment by dovil** [comment]
Rime的同步字库还是很重要的，辛苦添加

**Comment by MiracleXYZ** [comment]
+1 for iCloud sync

**Comment by imfuxiao** [comment]
大家好, WebDAV 的需求需要具体描述下. 是想同步到类似坚果云的云盘需求么?

**Comment by zhuce128** [comment]
+1 for iCloud sync！

**Comment by tarkky** [comment]
> 大家好, WebDAV 的需求需要具体描述下. 是想同步到类似坚果云的云盘需求么?

个人建议，如果加同步的话，最好别只加icloud，最好将onedrive和dropbox的都加上，当然可以一步一步来，先易后难。

**Comment by DreamAfar** [comment]
> 大家好, WebDAV 的需求需要具体描述下. 是想同步到类似坚果云的云盘需求么?

我猜他们说的iCloud和WebDAV同步，一个是同步方案配置和词库文件还有一个是同步拼音方案下，日常打字积累的用户词库，同步后可以同步pc、Mac、iOS、安卓多个设置之间积累的词库，保持一致。
（我目前公司电脑和个人电脑就是通过坚果云的WebDAV自动同步个人用户词库和配置，手动点击、或设置个自动计划就会同步部署。）

WebDAV还有个功能可以将手机当成服务器，在电脑的文件管理器或软件连接上，可以直接上传方案文件和编辑配置文件，iRime上现在就有这两个功能，修改自定义键盘布局和配置起来很方便，电脑上编辑完，手机点部署就可以了。

**Comment by rainrdx** [comment]
同支持。希望作者能增加用户词库同步功能。我自己用onedrive。但是一个一个网盘实现也很辛苦。有什么都行。多谢作者。

**Comment by derek0x** [comment]
增加WebDAV方式

**Comment by imfuxiao** [comment]
感谢大家的支持，目前App支持浏览器上传输入方案。iCloud同步会尽快推出。

**Comment by imfuxiao** [comment]
现在可以通过iOS分享功能及输入方案中右上角“+”功能导入zip包形式导入输入方案。

**Comment by imfuxiao** [comment]
很好的建议，目前正在做重构和自定义键盘的功能。等完成这部分功能后，可以着手这部分功能开发。
