### ISSUE TITLE
自动升级后自定义键盘布局消失

### ISSUE THREAD

**Issue by leoleoasd** [imfuxiao/Hamster#480]
如题

**Comment by cactusnix** [comment]
这次升级是个破坏性升级,自定义键盘的yaml模型格式变了,需要参考一下wiki里面的进行调整,action:{character: {char: "q"}}

**Comment by leoleoasd** [comment]
这个完全可以升级的时候自动改一下的啊....

**Comment by cactusnix** [comment]
可能有一些读写权限上的问题或者是没有考虑到吧, 这个输入法目前还处于前期迭代期间, 加上作者以及一些参与者应该都是自己的业余时间, 确实可能会出现这种情况, 希望后续他们考虑一下, 尽量避免吧, 还是感谢他们的辛勤付出, 我们也多给他们一些包容.

**Comment by kefengzhang** [comment]
我是删除app,然后重新安装,重新配制来解决这个问题的

**Comment by imfuxiao** [comment]
您好，此问题与 #475 是一样的，都是因为自定义布局的 yaml 格式变更导致的，破坏性升级确实体验不好，以后我尽量注意这个问题。
