### ISSUE TITLE
键盘布局页面错误

### ISSUE THREAD

**Issue by bingo982426** [imfuxiao/Hamster#482]
进入键盘布局--->中文26键--->滑动设置，选中一个随便点击，然后退出到滑动设置列表，页面显示不正确，需要重新退出软件再进入
![IMG_4158](https://github.com/imfuxiao/Hamster/assets/19426679/df4a79a4-a7b6-4d0e-9fe7-2f95ab72f463)

**Comment by imfuxiao** [comment]
您好，麻烦提供 iOS 版本信息，看能的截图，像是越狱了，不清楚是否有影响。

**Comment by bingo982426** [comment]
> 您好，麻烦提供 iOS 版本信息，看能的截图，像是越狱了，不清楚是否有影响。

抱歉，才看见，iPhone 13 Pro Max ，版本15.1.1

**Comment by bingo982426** [comment]
> 您好，麻烦提供 iOS 版本信息，看能的截图，像是越狱了，不清楚是否有影响。

是越狱设备
