### ISSUE TITLE
建议App本身不带任何输入法

### ISSUE THREAD

**Issue by cactusnix** [imfuxiao/Hamster#483]
浏览相关issues发现其实内置输入法方案已经在CloudKit里面存储,可以通过+来进行下载和使用,那么出于对于脏数据的考虑,是否可以下载后就不内置任何输入法,用户自己通过添加的方式追加,这样可以保证文件目录是干净,后续升级用户也只需要重新添加并替换自己的输入法,现在文件目录时常出现混乱,比如我通过zip包的形式导入,浏览查看仍然会有很多不需要的文件存在.

**Comment by imfuxiao** [comment]
> 浏览相关issues发现其实内置输入法方案已经在CloudKit里面存储,可以通过+来进行下载和使用,那么出于对于脏数据的考虑,是否可以下载后就不内置任何输入法,用户自己通过添加的方式追加,这样可以保证文件目录是干净,后续升级用户也只需要重新添加并替换自己的输入法,现在文件目录时常出现混乱,比如我通过zip包的形式导入,浏览查看仍然会有很多不需要的文件存在.

不内置任何输入方案，对新手用户是不友好的，所以需要一个支持基础功能的输入方案。

目前输入方案都是存储在 `Rime` 目录中，如果您不需要内置方案，可以先把 `Rime` 目录删除，删除后在使用 zip 方式导入，那么就是纯净的。

**Comment by cactusnix** [comment]
> > 浏览相关issues发现其实内置输入法方案已经在CloudKit里面存储,可以通过+来进行下载和使用,那么出于对于脏数据的考虑,是否可以下载后就不内置任何输入法,用户自己通过添加的方式追加,这样可以保证文件目录是干净,后续升级用户也只需要重新添加并替换自己的输入法,现在文件目录时常出现混乱,比如我通过zip包的形式导入,浏览查看仍然会有很多不需要的文件存在.
> 
> 不内置任何输入方案，对新手用户是不友好的，所以需要一个支持基础功能的输入方案。
> 
> 目前输入方案都是存储在 `Rime` 目录中，如果您不需要内置方案，可以先把 `Rime` 目录删除，删除后在使用 zip 方式导入，那么就是纯净的。

能明白这么做的原因,  主要是考虑到哪怕是新手从右上角仅仅添加自己想要的输入法似乎也是比较友好的, 这样也能减少应用的体积, 减少与高级用户导入自己输入法的冲突. 
内置的话, 大部分也是新手不需要的输入法, 按需添加似乎更加有选择性一点. 
当然是我个人的一些看法哈, 可能新手用户不是我这样的想法, 仅供参考.

**Comment by imfuxiao** [comment]
嗯嗯，非常理解您说的意思。目前app的安装包体积已经很小了，不到 50 MB的大小。所以体积已经不是问题了。另外如上面所说，内置输入方案已经从 SharedSupport 目录转移至 Rime 目录，且只内置了一个输入方案。原先的其他内置输入方案已全部迁移到 CloudKit 存储了。

如果想删除内置方案，只需要删除 `Rime` 目录就可以了，很方便的。

**Comment by cactusnix** [comment]
嗯嗯 明白了🫡
