### ISSUE TITLE
能否提供一个低版本ipad的安装文件

### ISSUE THREAD

**Issue by blackhole889** [imfuxiao/Hamster#486]
现在需要ios是15以上才能使用仓，我的ipad比较老，是12.5，能否提供一个低版本ios的仓的安装文件。

**Comment by imfuxiao** [comment]
抱歉，不可以，因为 UI 布局依赖一些高版本的 api。所以目前最低支持版本为 15 版本。

如果有动手能力的化，也可以往下降版本，但需要做一些的 patch 代码。
