### ISSUE TITLE
IOS 端原词库中没有但是上过屏词组记忆和排序问题

### ISSUE THREAD

**Issue by datacruiser** [imfuxiao/Hamster#488]
mac 端和 IOS端都是同样的配置，采用小鹤双拼的输入方案，配置文件如下：
[double_pinyin_flypy.custom.yaml.zip](https://github.com/imfuxiao/Hamster/files/13767944/double_pinyin_flypy.custom.yaml.zip)

不过比较奇怪的一点是 对于 原来词库里面没有但是上屏过的词组，在mac端 当我下次再次输入相同的词组的时候 这些上过屏的词组会 自动计入自定义词库并且在待上屏的候选词排序靠前，比如我输入一个人的名字并上屏以后，当我第二次输入的时候他在候选排序里面靠前。

但是在IOS端，对于未在词库里面但是上过屏的词组，但你第二次输入的时候仿佛没有任何变化，比如我输入我的名字，第一次输入和第二次输入体验是一样的，我用小鹤双拼输入两个字母，每次都需要我一个字一个字的选。

不知道大家有没有遇到这样的情况，是不是我在IOS端的app 里面哪里的设置有问题还是什么情况？

**Comment by imfuxiao** [comment]
检查键盘是否开启完全访问权限，如果没有开启，请开启在尝试。

**Comment by datacruiser** [comment]
> 检查键盘是否开启完全访问权限，如果没有开启，请开启在尝试。

原来如此，感谢～！
