### ISSUE TITLE
升级之后，小鹤双拼的自定义短语无法生效

### ISSUE THREAD

**Issue by zilonghe** [imfuxiao/Hamster#490]
应该只需要创建一个custom_phrase_double.txt就ok了吧？重新部署后无法生效。

[custom_phrase_double.txt](https://github.com/imfuxiao/Hamster/files/13775126/custom_phrase_double.txt)

**Comment by cactusnix** [comment]
原因可能如下:
1. 文件的名字应该是custom_phrase.txt
2. 可能软件的rime设置页面打开了部署时覆盖词库

**Comment by cactusnix** [comment]
3. 可能没有在系统设置中开启键盘的完全访问权限
