### ISSUE TITLE
雾凇拼音吞字错误

### ISSUE THREAD

**Issue by seepage3000** [imfuxiao/Hamster#491]
仓输入法2.2.0，输入方案是默认的雾凇拼音26键盘。
今天想打“原来土豆丝”，先输入“原来”，当输入“土豆丝”到对话框，自动删除了“来”，变成“原土豆丝”。类似这个情况之前在2.0的版本也出现过，可惜不能复现，也没有录屏。
请问是误操作了什么吗？
![bug](https://github.com/imfuxiao/Hamster/assets/51148924/2849ce9d-aaef-4731-8b46-2d0535b67c25)

**Comment by imfuxiao** [comment]
是否开启了「内嵌」模式，如果开启了「内嵌」，麻烦先关闭「内嵌」然后在测试下。
