### ISSUE TITLE
现在全选功能可以实现吗？

### ISSUE THREAD

**Issue by JanuaryChenMy** [imfuxiao/Hamster#493]
如题，试了sendkey是不好用，有方法可以实现吗？

**Comment by imfuxiao** [comment]
目前没有「全选」快捷指令。

「全选」功能依赖苹果的 api，目前存在 bug，所以暂不提供此功能。

**Comment by BrianZR** [comment]
之后会支持吗> 目前没有「全选」快捷指令。
> 
> 
> 
> 「全选」功能依赖苹果的 api，目前存在 bug，所以暂不提供此功能。

**Comment by imfuxiao** [comment]
目前TF 版本已支持全选指令，但因系统 api 限制，全选可能会出现部分全选的问题。
