### ISSUE TITLE
自定义键盘布局：无法选择和使用

### ISSUE THREAD

**Issue by shawnwang5** [imfuxiao/Hamster#494]
### 主配置：
![image](https://github.com/imfuxiao/Hamster/assets/12855876/372a6f85-bd3e-415f-b558-e1b2962c008c)

### 键盘布局配置：
[hamster_keyboards.yaml.txt](https://github.com/imfuxiao/Hamster/files/13800321/hamster_keyboards.yaml.txt)

### 环境：
![b25604aed2232e871d2ff1ad8e43be1](https://github.com/imfuxiao/Hamster/assets/12855876/1e68adc4-00b4-4dbe-b4da-d1bb365b1983)

### 结果：
![b89b9a66021bc92ce72ec577beac14e](https://github.com/imfuxiao/Hamster/assets/12855876/44c0cf5a-cabd-47b3-baee-cf3c532d2847)

**Comment by imfuxiao** [comment]
我测试是可以的，测试方法如下：

1. 新建 `hamster.custom.yaml`，文件内容如下：

```yaml
patch:
  keyboards:
    __include: hamster_keyboards/keyboards
```

2. 上传 `hamster_keyboards.yaml`文件，文件内容是你提供的文件。
3. 将两个文件复制到 `Rime` 目录下。
4. 重新部署后，即可看到你定义的`中文`键盘了。

如果您还是看不到，请点击`关于`-> `重置界面设置`，然后在查看是否能看到你定义的键盘。

为什么会存在这种情况，请查阅「仓」的操作手册：[配置文件的优先级](https://ihsiao.com/apps/hamster/docs/AppSettings.html#%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E7%9A%84%E4%BC%98%E5%85%88%E7%BA%A7)

**Comment by shawnwang5** [comment]
> 我测试是可以的，测试方法如下：
> 
> 1. 新建 `hamster.custom.yaml`，文件内容如下：
> 
> ```yaml
> patch:
>   keyboards:
>     __include: hamster_keyboards/keyboards
> ```
> 
> 2. 上传 `hamster_keyboards.yaml`文件，文件内容是你提供的文件。
> 3. 将两个文件复制到 `Rime` 目录下。
> 4. 重新部署后，即可看到你定义的`中文`键盘了。
> 
> 如果您还是看不到，请点击`关于`-> `重置界面设置`，然后在查看是否能看到你定义的键盘。
> 
> 为什么会存在这种情况，请查阅「仓」的操作手册：[配置文件的优先级](https://ihsiao.com/apps/hamster/docs/AppSettings.html#%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E7%9A%84%E4%BC%98%E5%85%88%E7%BA%A7)

重置UI界面设置之后，点击重新部署，出现了异常。异常如下图：

![IMG_9485](https://github.com/imfuxiao/Hamster/assets/12855876/cb52b048-e0d4-4548-bb93-f2930069d214)

**Comment by imfuxiao** [comment]
看错误应该是输入方案的问题，请检查日志中以“E”开头的错误日志

**Comment by shawnwang5** [comment]
> 看错误应该是输入方案的问题，请检查日志中以“E”开头的错误日志

好的，我查查。谢谢。
