### ISSUE TITLE
"左侧符号列表由 RIME 处理 "开关Rime的配置

### ISSUE THREAD

**Issue by SeongBrave** [imfuxiao/Hamster#495]
<img width="441" alt="image" src="https://github.com/imfuxiao/Hamster/assets/10784393/5adf8036-5397-4bbf-af77-562376654a0a">
如上图这个开关，然后在rime 中需要怎么配置吗有相关文档吗？

**Comment by imfuxiao** [comment]
不需要在 RIME 中做配置，「左侧符号列表」指数字九宫最左侧可以上下划动的的符号列表，列表内容可以在你截图的「符号列表」标签栏处增/删/改。

在开启截图红框选项后，点击的符号会经过  RIME 引擎，否则直接上屏。

**Comment by SeongBrave** [comment]
多谢回复啊，我想左侧符号做配置文件维护现在支持吗？ 目前app内也可以，想把这些统一到一个类似rime-ice下处理呢，这样就不用在app内一个一个的添加呢

**Comment by imfuxiao** [comment]
请查阅 SharedSupport 文件夹下 hamster.yaml 文件，里面有 `symbolsOfGridOfNumericKeyboard` 参数，对应九宫格左侧符号列表。

**Comment by SeongBrave** [comment]
@imfuxiao 多谢了，还有个问题，就是我自定义一个patch 文件（Hamster.custom.yaml）,是不是app和自动加载这个文件呢，文件内容类似
<img width="554" alt="image" src="https://github.com/imfuxiao/Hamster/assets/10784393/ddee613a-28a7-462d-ba98-21f975b140f5">
但是好像没有生效

**Comment by imfuxiao** [comment]
是 `hamster.custom.yaml`，小写。
