### ISSUE TITLE
TestFlight 129 升级后无法使用的错误

### ISSUE THREAD

**Issue by aetherwu** [imfuxiao/Hamster#496]
iOS 16.6.1
iPhone 12 Pro

从 TF129 升级到更高版本以后，配置界面显示错误。

1、中文键盘配置无法选中
2、键盘配置可以打开，但之前的所有配置消失
3、输入法可以激活，但所有自定义滑动无法使用
![IMG_7807](https://github.com/imfuxiao/Hamster/assets/1645472/10de1079-9409-4d57-bd02-3fe88731e09f)
![IMG_7806](https://github.com/imfuxiao/Hamster/assets/1645472/d481b6ab-fcad-4720-85e0-083b894dd8f2)

4、升级到更新版本，重新部署失效。
![IMG_7808](https://github.com/imfuxiao/Hamster/assets/1645472/791e70f1-6bce-43a8-bded-6f04e3cd6280)

5、恢复使用步骤：
- 降级到 TF 129
- 删除 Wifi 方案上传里的 rime/shared support 两个文件夹
- 重新上传本地配置或者 icloud drive/ hamster 中的老配置（前提是没有被覆盖过）

6、关于自定义键盘的升级说明：
- 因为 rime 文件很多，很繁杂，导致 rime 有很多重复配置项目（分布在不同文件），虽然尝试过，但无法完成操作要求。

**Comment by imfuxiao** [comment]
您好，与 #475 问题相同，自定义键盘布局的模型变更导致的，因此关闭此 issue。

**Comment by aetherwu** [comment]
> 您好，与 #475 问题相同，自定义键盘布局的模型变更导致的，因此关闭此 issue。

全部删除重装 App Store 版本了。
配置只好重新来过。
