### ISSUE TITLE
关于单个按钮的颜色设置

### ISSUE THREAD

**Issue by JanuaryChenMy** [imfuxiao/Hamster#497]
我使用了那个仓的diy自定义键盘的网站工具，设定了单个键盘的颜色，可是无效，翻了下wiki也没有说明，现在是否有这个功能？
![image](https://github.com/imfuxiao/Hamster/assets/42561739/fa523c62-77e8-43da-8ff5-77a73a4c38fe)
![image](https://github.com/imfuxiao/Hamster/assets/42561739/6c8f30ee-4905-4d6a-9b3b-b5d8e23e4e09)

**Comment by imfuxiao** [comment]
TF版本 157 版本后新增功能，请查阅 TF 发版说明。

**Comment by JanuaryChenMy** [comment]
> TF版本 157 版本后新增功能，请查阅 TF 发版说明。

目前最新的是155呀![image](https://github.com/imfuxiao/Hamster/assets/42561739/d6300021-5cf7-45cb-a958-489af60d1ddd)

**Comment by imfuxiao** [comment]
beta测试组目前是 155 版本。alpha 版本会提前更新测试，测试没有问题在转 beta 测试。

**Comment by JanuaryChenMy** [comment]
> beta测试组目前是 155 版本。alpha 测试组会提前更新测试，测试没有问题在转 beta 测试。

现在还可以加入alpha测试吗？方便的话麻烦发下邀请链接🙏

**Comment by imfuxiao** [comment]
alpha 版本不适合日常使用，bug多，新功能体验还是等 beta 版本吧。

**Comment by JanuaryChenMy** [comment]
> alpha 版本不适合日常使用，bug多，新功能体验还是等 beta 版本吧。

好的

**Comment by JanuaryChenMy** [comment]
> alpha 版本不适合日常使用，bug多，新功能体验还是等 beta 版本吧。

bate大概什么时候更新157呢

**Comment by byicer** [comment]
@JanuaryChenMy 请问键盘文件可以分享吗?很漂亮!

**Comment by JanuaryChenMy** [comment]
> @JanuaryChenMy 请问键盘文件可以分享吗?很漂亮!

邮箱

**Comment by byicer** [comment]
byicer@live.com

**Comment by JanuaryChenMy** [comment]
> byicer@live.com @JanuaryChenMy 

已发
