### ISSUE TITLE
重新部署：未能读取数据，因为数据缺失。

### ISSUE THREAD

**Issue by shawnwang5** [imfuxiao/Hamster#498]
现状如图所示：
![25234f5e418b5c255acd99543cc2a75](https://github.com/imfuxiao/Hamster/assets/12855876/ffbc456e-cd9b-4d63-aa07-c541522cb6c2)

问题排查：
查阅了日志文件，日志文件中没有“E”开头的数据内容。没观察到明显报错。部署不成功。

自定义键盘文件：
[hamster_keyboards.yaml.txt](https://github.com/imfuxiao/Hamster/files/13807524/hamster_keyboards.yaml.txt)

**Comment by imfuxiao** [comment]
您好，与 #475 的问题相同，因此关闭此 issue。
