### ISSUE TITLE
键盘类型切换键显示空白

### ISSUE THREAD

**Issue by lixing0016** [imfuxiao/Hamster#50]
最新版bug！不知其他大佬有没有碰到
![IMG_2340](https://user-images.githubusercontent.com/56327827/232371419-3f18d218-7d84-4e48-8a15-b30662de77e2.JPEG)

**Comment by imfuxiao** [comment]
刚测试发现, 有部分用户需要卸载后重新安装才能显示空白按键的问题.

**Comment by lixing0016** [comment]
![IMG_2342](https://user-images.githubusercontent.com/56327827/232644019-729320df-1445-45fb-af6a-4b010d536a20.JPEG)

**Comment by lixing0016** [comment]
已升级到最新版本1.1.4

**Comment by imfuxiao** [comment]
> 已升级到最新版本1.1.4

收到, 我正在处理. 感谢反馈

**Comment by imfuxiao** [comment]
目前在未遇到此种情况，如果大家在遇到，我在修复。
