### ISSUE TITLE
关于键内上/下滑字体的大小、方案绑定布局的需求

### ISSUE THREAD

**Issue by tianhao** [imfuxiao/Hamster#500]
用了2天，挺好用的，为开发点赞！

不过目前我遇到以下几个问题，希望功能上能加强

需求（需求程度从高到低）：
1. 上/下滑的字太小颜色也不明显看不清，我看单键的剩余空间是够的，希望能设置上/下滑字的大小、颜色；
2. 输入方法跟键盘布局绑定，切方案时把布局一起切换掉，比如切到9宫格方案键盘布局也切到对应的9宫格；
3. 还是上下滑，中文方案的上下滑用中文符号，切英文时延用上下滑，但是中文符号换成英文符号，目前的问题是，换成英文后就没有上下滑了，还要切键盘找符号输入。

**Comment by gfgkmn** [comment]
2.3.0似乎已经可以支持字体大小设置了，就是不知道怎么方便的修改，说了是个样式参数，不过目前使用内置26键盘，只想改划动字体大小
