### ISSUE TITLE
关于震动

### ISSUE THREAD

**Issue by JanuaryChenMy** [imfuxiao/Hamster#501]
震动的触感反馈有种说不上来的感觉，是迟钝几毫秒？还是马达不对，不如原生键盘的手感脆亮，包括按键音也是，不明亮

**Comment by imfuxiao** [comment]
收到，感谢反馈。

**Comment by BTBMan** [comment]
目前感觉还是有这个问题，声音和震动的体验不是很好，没有原生键盘来的舒服，有一点点延迟感，声音的比原版要小很多。
