### ISSUE TITLE
项目依赖 GCDWebServer 不存在

### ISSUE THREAD

**Issue by SeongBrave** [imfuxiao/Hamster#503]
工程依赖地址 https://github.com/JacobHearst/GCDWebServer 好像不存在了

**Comment by imfuxiao** [comment]
已改为：https://github.com/imfuxiao/GCDWebServer

**Comment by SeongBrave** [comment]
现在main分支还是之前的，要跑咱的项目是再的项目再哪个分支呢？

**Comment by imfuxiao** [comment]
只需要替换项目地址，其他不需要改

**Comment by SeongBrave** [comment]
嗯嗯，多谢回复啊，现在又报错了,<img width="407" alt="image" src="https://github.com/imfuxiao/Hamster/assets/10784393/7819ea0d-a891-4730-beec-31d7e3a20456">  我是在 LibrimeKit 下载的然后解压到Frameworks目录的

**Comment by imfuxiao** [comment]
请下载对应版本的 LibrimeKit 。https://github.com/imfuxiao/Hamster/blob/main/librimeFramework.sh

里面有对应版本信息，或者执行`make framework`

**Comment by SeongBrave** [comment]
嗯嗯 多谢

**Comment by imfuxiao** [comment]
我的错，2.1.1 版本被我删除了（github的免费空间只有 500 MB，快用完了），先手动下载 [2.2.1](https://github.com/imfuxiao/LibrimeKit/releases/tag/2.2.1) 或者 2.3.0 也可以。

**Comment by SeongBrave** [comment]
我下载了2.2.1 好像还是报错了 
<img width="423" alt="image" src="https://github.com/imfuxiao/Hamster/assets/10784393/5089bb72-2501-4e61-81ba-26ea24a2fc63">

**Comment by imfuxiao** [comment]
看 XCode 的详细错误，这个看不出来是什么问题。

**Comment by SeongBrave** [comment]
<img width="783" alt="image" src="https://github.com/imfuxiao/Hamster/assets/10784393/309d6284-f871-47cb-a452-8a85a4239697">

**Comment by imfuxiao** [comment]
<img width="1216" alt="image" src="https://github.com/imfuxiao/Hamster/assets/6482586/35b33275-8e3f-4ceb-9f19-4ea038564957">

应该是这个函数在 2.1.1 版本中没有编译进去，你在试下 2.3.0 版本。

**Comment by SeongBrave** [comment]
太感谢了，终于包起来了😂，不过不是最新的，相对TF版本有点旧
