### ISSUE TITLE
iPadOS 候选栏bug

### ISSUE THREAD

**Issue by liuchanghuaX1** [imfuxiao/Hamster#505]
![image](https://github.com/imfuxiao/Hamster/assets/40064819/7a71cafb-ee25-4b52-9c08-e69f90130767)![image](https://github.com/imfuxiao/Hamster/assets/40064819/ed872a55-8612-43d5-acdc-69662e82618e)
如图所示，iPad版仓输入多显示了标题栏，重置也没用。iPad设备为iPad Air 5，iPad OS版本为14.2。

**Comment by imfuxiao** [comment]
非仓的问题，此标题栏是系统的功能。感谢您的反馈。
