### ISSUE TITLE
如何在仓中输入特殊字符开头的自定义符号

### ISSUE THREAD

**Issue by kphxcodes** [imfuxiao/Hamster#506]
在macOS中定义以`/fh`开头的特殊符号，在仓中输入特殊符号就直接上屏。有什么办法可以解决这个问题吗?

![CleanShot 2024-01-08 at 13 16 31@2x](https://github.com/imfuxiao/Hamster/assets/155599810/74fde2b3-bf6a-4c6e-a780-67ea5829fd46)

**Comment by imfuxiao** [comment]
看您的需求：是需要将 `/fh` 发送给 RIME 引擎，然后由 RIME 提供特殊符号的候选。

这种输入目前可以有两种方式：

方式一：通过 `sendKeys` 指令，发送 `/ + f + h` 指令给 RIME 引擎。
方式二：定义自定义按键或自定义按键的划动，action 请定义为具体的 `character `。

具体可以查阅文档：[自定义键盘](https://ihsiao.com/apps/hamster/docs/CustomKeyboard.html) 中的 action 选项。
