### ISSUE TITLE
挂载词库后报错

### ISSUE THREAD

**Issue by Pansamore** [imfuxiao/Hamster#508]
在rime_ice.dict.yaml中挂载mydict.yaml词库，重新部署显示成功，但是log报错
![IMG_0923](https://github.com/imfuxiao/Hamster/assets/121852996/b8b5bba5-c4f4-4a66-a34d-32bbc8506a98)
![IMG_0924](https://github.com/imfuxiao/Hamster/assets/121852996/0b65736e-94b3-4b2c-bd24-9438c7801ee0)
![IMG_0925](https://github.com/imfuxiao/Hamster/assets/121852996/b9cb558f-648d-4995-b2a5-d58c6db35cee)

**Comment by imfuxiao** [comment]
建议在 PC 上改造好后在移植到「仓」中。
