### ISSUE TITLE
申请内置方案的问题

### ISSUE THREAD

**Issue by speedcell4** [imfuxiao/Hamster#512]
您好, 非常感谢开发这么好用的输入法. 

我现在有个自己编写的方言输入法方案, 请问可以申请内置么. 
现在还在开发阶段, 预计半年后才能出第一个正式版本, 目前只是提前咨询一下. 

如果可以内置的话, 那另外还有个问题是我后续更新这个方案还需要再提交 PR 么, 还是说用户点了重新部署之后输入法就会自动到我的 repo 下载最新的方案?

**Comment by imfuxiao** [comment]
您好，考虑到 App 体积问题，目前内置方案只有「雾凇输入方案」，其余方案已全部迁移到苹果的「 CloudKit」中存储。用户可以联网下载。

如果您想将自己的方案上传到「仓」的「CloudKit」中，供用户下载使用，那么可以根据项目[HamsterInputSchemas](https://github.com/imfuxiao/HamsterInputSchemas)的说明来操作。

> 注意：项目「HamsterInputSchemas」只是临时方案，后续会有变动。

**Comment by speedcell4** [comment]
感谢~
