### ISSUE TITLE
长按字母后弹出气泡的背景色修改

### ISSUE THREAD

**Issue by changzaicl** [imfuxiao/Hamster#515]
现在好像是透明的，在https://lost-melody.github.io/hamster-tools 试了各种参数，还是不行。只想不透明，不要和后面的键盘字母重叠就行。谢谢

**Comment by imfuxiao** [comment]
您好，感谢您的反馈。

TF 版本键盘配色有添加参数 `button_bubble_back_color`：按键气泡颜色（可选），为空时使用 button_back_color 作为气泡颜色，长按 Action 的背景色等同此颜色。

如果您使用的是商店版本，需要等待下个版本。

**Comment by changzaicl** [comment]
好的。谢谢！
