### ISSUE TITLE
启用“键盘设置/不规则显示滑动文本”后带有特殊功能的回车键文字漂移

### ISSUE THREAD

**Issue by SkyYkb** [imfuxiao/Hamster#516]
如图，无特殊功能时显示正常：

![image](https://github.com/imfuxiao/Hamster/assets/44992049/b04d9c7a-572e-4ee6-b548-89786bfee9f1)

带有诸如“搜索”等功能的回车键文字会有漂移：

![image](https://github.com/imfuxiao/Hamster/assets/44992049/75bbbe40-2f2d-4e77-b05c-2ffdd0386dd0)

**Comment by imfuxiao** [comment]
感谢您的反馈，此问题 TF 版本已修复，商店版本下个版本修复。
