### ISSUE TITLE
有人测试了和其他输入法对比吗

### ISSUE THREAD

**Issue by sunznx** [imfuxiao/Hamster#517]
主要是占用内存方面的问题

**Comment by sunznx** [comment]
> 个人意见: 没有意义。iOS 对第三方键盘本身就有内存限制大小，上限 77 MB。

好像有时候在打字的时候，Hamster 会出不来，要重新唤醒，我以为是我词库太大的问题。
77MB 但是我的词库好像都不止这么大。

**Comment by imfuxiao** [comment]
1. 应用使用的内存大小与词库自身的大小不是一个概念，例如：某数据库中数据有 PB 大小，也不是将全部数据都加载到内存中的。
2. 「仓」键盘无法加载，原因太多了，可能是「仓」本身的 bug 导致，也可能是系统 bug。
