### ISSUE TITLE
可以想办法根据我选择的结果词将该词的优先级调高吗?

### ISSUE THREAD

**Issue by kefengzhang** [imfuxiao/Hamster#518]
如题,我希望一些我常用的词随着我的日常使用,越来越前

**Comment by imfuxiao** [comment]
这个是输入方案的设置，比如「雾凇」输入方案，它的词频会根据使用调整。

**Comment by frodobaggi** [comment]
遇到问题同上，macOS Squirrel 同样的配置文件部署，词频选择是没问题的。但手机上每次打同样的一组词都是需要像第一次输入时翻页去找，这个不知道怎么配置？

**Comment by DawnLi-code** [comment]
同问题，使用的雾凇，Mac下正常，iOS升级后不会自动调频了

**Comment by imfuxiao** [comment]
> 同问题，使用的雾凇，Mac下正常，iOS升级后不会自动调频了

请检查键盘的完全访问权限是否打开？

**Comment by DawnLi-code** [comment]
> > ~~同问题，使用的雾凇，Mac下正常，iOS升级后不会自动调频了~~
> 
> 请检查键盘的完全访问权限是否打开？

恢复正常，不知道什么时候权限被关闭了🤷‍♂️

**Comment by kefengzhang** [comment]
刚才确认也是因为没有打开完全访问权限
