### ISSUE TITLE
custom_phrase无法设置

### ISSUE THREAD

**Issue by Sanly** [imfuxiao/Hamster#520]
iPhone 14 Pro Max
iOS：17.2.1
仓：2.3.0

不知道我的操作是否正确：我直接修改的“应用文件”下“Rime”文件夹中的“custom_phrase.txt”，然后重新部署，但发现部署后的应用文件和键盘文件中的“custom_phrase.txt”都恢复成默认值。

此外，还有个疑问，“custom_phrase.txt”可以通过“RIME同步”在不同设备上同步吗？

**Comment by imfuxiao** [comment]
1. 检查「RIME」->「部署时覆盖词库文件」选项
2. 不支持，因为「RIME同步」只支持 userdb 类型词库。（[手册](https://ihsiao.com/apps/hamster/docs/Sync.html)中有说明）

**Comment by Sanly** [comment]
我整理一下思路：

1. “RIME同步”只支持 userdb 类型词库，我用的雾凇拼音的配置，搜了一下“db_class”，只看到在“custom_phrase”项下有这个参数，显示为“stabledb”，在配置文件夹中的“rime_ice.userdb”中有二进制文件，因此词库应该是userdb 类型？
2. 由于需要同步自造词，因此应该使用“RIME同步”，按照手册需要关闭「部署时覆盖键盘词库文件」选项。
3. 关闭「部署时覆盖键盘词库文件」选项后无法使用“custom_phrase.txt”，因此在部署“custom_phrase.txt”前先要打开「部署时覆盖键盘词库文件」选项。
4. 之后再使用“RIME同步”功能同步自造词时，需要再关闭「部署时覆盖键盘词库文件」选项。
5. 因此“custom_phrase.txt”和自造词无法在同一设置下完成同步和部署。

不知道上述理解是否准确？
