### ISSUE TITLE
兄弟，非常感谢，也非常钦佩。

### ISSUE THREAD

**Issue by tarkky** [imfuxiao/Hamster#53]
有意付费使用。或者给你捐款。可否放一下捐款连接。

**Comment by stephenchou888** [comment]
麻烦作者贴个捐款，另外谢谢作者的辛苦，还有希望增加9宫格，感谢了。

**Comment by imfuxiao** [comment]
非常感谢二位, 好的应用也离不开大家不断使用, 不断的反馈.

现在应用还不完善, 有很多问题需要调整. 暂时就不贴了. 

等大家用的满意了, 我在放连接.

再次感谢~

**Comment by DawnLi-code** [comment]
加油！

**Comment by luojiego** [comment]
加油，我抽空也学习一下如何 App 的开发，看能不能帮上忙。

**Comment by tarkky** [comment]
> 非常感谢二位, 好的应用也离不开大家不断使用, 不断的反馈.
> 
> 现在应用还不完善, 有很多问题需要调整. 暂时就不贴了.
> 
> 等大家用的满意了, 我在放连接.
> 
> 再次感谢~

没关系，既然不想收费，可以先弄个捐款，有能力的可以帮助一下。自愿的原则。不寒碜。

**Comment by imfuxiao** [comment]
> 加油，我抽空也学习一下如何 App 的开发，看能不能帮上忙。

欢迎入坑~

**Comment by tarkky** [comment]
另外问一下：很喜欢你的默认配置，键盘，上下划等等，请问，可以迁移到android的trime上面么？谢谢

**Comment by imfuxiao** [comment]
> > 非常感谢二位, 好的应用也离不开大家不断使用, 不断的反馈.
> > 现在应用还不完善, 有很多问题需要调整. 暂时就不贴了.
> > 等大家用的满意了, 我在放连接.
> > 再次感谢~
> 
> 没关系，既然不想收费，可以先弄个捐款，有能力的可以帮助一下。自愿的原则。不寒碜。

谢谢, 那我抽空搞一个, 感谢支持~

**Comment by tarkky** [comment]
> > > 非常感谢二位, 好的应用也离不开大家不断使用, 不断的反馈.
> > > 现在应用还不完善, 有很多问题需要调整. 暂时就不贴了.
> > > 等大家用的满意了, 我在放连接.
> > > 再次感谢~
> > 
> > 
> > 没关系，既然不想收费，可以先弄个捐款，有能力的可以帮助一下。自愿的原则。不寒碜。
> 
> 谢谢, 那我抽空搞一个, 感谢支持~

谢谢你的付出，这是你应得的。

**Comment by imfuxiao** [comment]
> 另外问一下：很喜欢你的默认配置，键盘，上下划等等，请问，可以迁移到android的trime上面么？谢谢

trime默认是支持的, 我这个就是学习trime.

**Comment by tarkky** [comment]
> > 另外问一下：很喜欢你的默认配置，键盘，上下划等等，请问，可以迁移到android的trime上面么？谢谢
> 
> trime默认是支持的, 我这个就是学习trime.

最新版的trime是配置是空的，需要自己弄上去，字典，输入法我知道，但是键盘和上下划就不知道怎么弄了，有什么简单的办法直接复制过去么？

**Comment by tarkky** [comment]
我自己先试试，有具体问题再过来问你。谢谢。

**Comment by imfuxiao** [comment]
> 



> > > 另外问一下：很喜欢你的默认配置，键盘，上下划等等，请问，可以迁移到android的trime上面么？谢谢
> > 
> > 
> > trime默认是支持的, 我这个就是学习trime.
> 
> 最新版的trime是配置是空的，需要自己弄上去，字典，输入法我知道，但是键盘和上下划就不知道怎么弄了，有什么简单的办法直接复制过去么？

上下滑动不行, 需要自己的App自己来. 我这个上下滑动是学习落格的.

**Comment by tarkky** [comment]
> > 
> 
> > > > 另外问一下：很喜欢你的默认配置，键盘，上下划等等，请问，可以迁移到android的trime上面么？谢谢
> > > 
> > > 
> > > trime默认是支持的, 我这个就是学习trime.
> > 
> > 
> > 最新版的trime是配置是空的，需要自己弄上去，字典，输入法我知道，但是键盘和上下划就不知道怎么弄了，有什么简单的办法直接复制过去么？
> 
> 上下滑动不行, 需要自己的App自己来. 我这个上下滑动是学习落格的.
啊，希望你能把这个输入法做成跨平台的。到时候我android，pc上面全用你的方案。哈哈。
