### ISSUE TITLE
将 switches 定义的选项放置在无输入码时的候选栏显示

### ISSUE THREAD

**Issue by tansongchen** [imfuxiao/Hamster#532]
我在阅读 issue 时发现了这个：

https://github.com/imfuxiao/Hamster/issues/133

似乎已经有人实现了在候选栏里显示各个选项，但是似乎后来没有采用这个设计。个人认为，目前无输入码时候选栏比较空，放这些选项可以把空间利用起来，还能简化中英切换、简繁切换的逻辑（现在需要用户手动设置简繁切换的选项名，但是如果都显示出来的话用户在输入界面选择即可），也便于和同文保持一致。

如果没有意见的话，我可以着手来实现这个功能。

**Comment by imfuxiao** [comment]
新年好，关于工具栏是有开发计划的，类似微信输入法的交互。

https://github.com/imfuxiao/Hamster/assets/6482586/299fccae-fe9c-401d-866b-77a3306dbfeb

**Comment by imfuxiao** [comment]
您好，目前新版本已支持候选栏编辑，因此关闭此 Issue。

**Comment by tansongchen** [comment]
非常棒，已经用上了。
