### ISSUE TITLE
数字参与编码、数字顶屏

### ISSUE THREAD

**Issue by tansongchen** [imfuxiao/Hamster#533]
目前，若一个键的 action 是

```js
{ character: { char: '2' } }
```

则当数字参与编码时，输入这个数字并未使其追加到当前的输入码，而是数字直接上屏，输入码不变。另外，当使用 alternative_select_keys 时，数字应当具有顶屏功能，但是目前也不能够顶屏，行为和刚才描述的一样。

同样一份配置文件，鼠须管上是可以正确执行以上两种逻辑的。请问可能的问题在哪里？

**Comment by imfuxiao** [comment]
是否可以顶码上屏，在『仓』中是根据 rime 的状态处理的，主要是下面截屏的逻辑。
![image](https://github.com/imfuxiao/Hamster/assets/6482586/c51265db-54ea-464a-b4e4-bd68825d6399)
![image](https://github.com/imfuxiao/Hamster/assets/6482586/e45e1264-28ea-4a61-a5bb-3ad1a1a78897)

**Comment by imfuxiao** [comment]
action 为 character 时，还有一个 processByRIME 的选项，默认是 true ，表示这个字符会发送给 RIME 引擎。
