### ISSUE TITLE
自定义输入方案净出生僻字

### ISSUE THREAD

**Issue by DJ975** [imfuxiao/Hamster#534]
导入了自定义输入方案，中古汉语全拼，结果候选字完全没有“常用字”的概念了，例如输入“不”的声母+“可”的带调全拼，出来的是这种东西：
![image](https://github.com/imfuxiao/Hamster/assets/91820827/fde84c24-2d01-43c8-8c20-acefb580074d)

使用的方案类似https://github.com/biopolyhedron/rime-middle-chinese 中的dict和schema文件

试过开完全访问，没有效果

**Comment by ksqsf** [comment]
可能是因为仓没有自带 essay.txt

https://github.com/rime/librime/blob/49c7298b/src/rime/dict/dict_settings.cc#L60

**Comment by liangkaichun** [comment]
我也遇到类似问题，感觉上是某些filter没有生效
