### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by HopeBill** [imfuxiao/Hamster#535]
拉取代码 通过: make framework 报以下错误怎么解决
gzip: unknown compression format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
make: *** [framework] Error 2

**Comment by imfuxiao** [comment]
抱歉，因 Github 可用空间不足，删除了一些旧的 release 包。

您可修改 `make framework` 脚本文件 `librimeFramework.sh` 第 `14` 行，将版本号改为最新的 `2.4.2`。如下：

```sh
...
# 下载依赖的 librime framework
LibrimeKitVersion="2.4.2"
...
```

**Comment by HopeBill** [comment]
非常感谢 ,按照您说的已解决 但是又遇到新的问题，如图：
![1](https://github.com/imfuxiao/Hamster/assets/17613633/9c667194-d8a8-4d91-99be-1dbab7202356)
其中GCDWebServer这个库已找不到，另外两个“ librime”、“ librimeRIME”都是提示二进制目标文件无法映射到预期名称的工作中

**Comment by imfuxiao** [comment]
GCDWebServer 的 SPM 库被作者删除了，现已换为：`https://github.com/imfuxiao/GCDWebServer.git`，请手工修改下。
如下：

```swift
    .package(url: "https://github.com/imfuxiao/GCDWebServer.git", exact: "3.5.5"),
```
