### ISSUE TITLE
仓九宫格，自定义数字词组，上屏乱码

### ISSUE THREAD

**Issue by Nothend** [imfuxiao/Hamster#538]
仓九宫格模式下，顺利可以唤起自定义词组了。汉字英文都可以正常显示。但是如果自定义词组是一串数字，比如身份证，唤起的时候显示正常，点击上文本框的时候却是乱码。如视频损失。

https://github.com/imfuxiao/Hamster/assets/73117056/e2e12497-accc-4d01-b84e-bdaba61b83fe

**Comment by Nothend** [comment]
又仔细看了一下，就是数字40675219685453849 进入文本框的时候变成了g0mpja1wmtjgjdtgw。其中“4”对应键位的第一个字母“G”，其他依次类推。不知为何如此。求解答，谢谢

**Comment by Nothend** [comment]
根据其他人提醒，九宫格中文模式下，键入“sj”动态日期也同样存在问题，数字会变成所在键位的首字母。

**Comment by imfuxiao** [comment]
> 大佬， #573 这个bug 这次最新版，修改好了。但是本bug又出现了，大佬看看这两个bug感觉像跷跷板一样。感谢。 @imfuxiao

收到，感谢反馈

**Comment by imfuxiao** [comment]
我记得这个 bug 目前已经修正了，麻烦您反馈下，谢谢。
