### ISSUE TITLE
〖建议〗能否使用第三方字体显示生僻字

### ISSUE THREAD

**Issue by youxixiaoziqq** [imfuxiao/Hamster#541]
ios系统下对生僻字的显示经常会出现❓，是否能支持用一个第三方字体（如MiSans L3）来显示生僻字，将该字体连同方案一并部署到输入珐？

**Comment by ZiGmaX809** [comment]
> 已经有了，可以看看帮助手册添加字体文件并部署

麻烦帮忙指个路，我找了好久没找到

**Comment by chca2** [comment]
> > 已经有了，可以看看帮助手册添加字体文件并部署
> 
> 麻烦帮忙指个路，我找了好久没找到

https://ihsiao.com/apps/hamster/docs/

**Comment by imfuxiao** [comment]
新版已支持字体功能，感谢您的反馈。
