### ISSUE TITLE
请问如何关闭键盘上的符号标记？

### ISSUE THREAD

**Issue by iTvX** [imfuxiao/Hamster#544]
比较喜欢简洁的键盘，目前非常喜欢这款输入法，唯独不喜欢键盘上*每个字母的符号**，显得键盘很凌乱，请问有办法删除吗？或者自己配置文件也可以，求解决。谢谢

**Comment by imfuxiao** [comment]
如截图选项所示:
![image](https://github.com/imfuxiao/Hamster/assets/6482586/1424ecef-cf3a-45b7-9717-a2840a72d5a1)

**Comment by imfuxiao** [comment]
非常感谢您的支持~
