### ISSUE TITLE
能够完整显示一页候选的某种扩展候选窗

### ISSUE THREAD

**Issue by tansongchen** [imfuxiao/Hamster#545]
现在有一个分页显示候选的选项，但是有可能出现选项在一行内无法显示完全，需要滑动才能显示完全的情况。

对于某些输入方案来说，会存在「最好能一次性看完一页候选」的需求，比如声笔在 4 码时的 5 个候选需要分别用 aeuio 选择，或者 092 五笔的一简十重。如果能一次性看完一页候选，就不需要通过滑动的方式来翻看，不用打断输入过程。

在同文输入法上，有一个悬浮窗模式，可以装下不止一行的候选

![IMG_7849](https://github.com/imfuxiao/Hamster/assets/31927845/d06d7f32-d30f-44a8-8019-8472c5b63922)

不知道仓输入法能否也实现类似效果？

**Comment by imfuxiao** [comment]
可以的，我后面优化下。

**Comment by Marksusu** [comment]
候选项、候选序号和候选 comment 三者，如果能在候选栏里各占一行就好了。
候选项在中间，序号、 comment 分列在候选项上、下方。
这样能节省屏幕宽度。

**Comment by imfuxiao** [comment]
> 候选项、候选序号和候选 comment 三者，如果能在候选栏里各占一行就好了。 候选项在中间，序号、 comment 分列在候选项上、下方。 这样能节省屏幕宽度。

最近在重构这里的UI，这个确实可以节省宽度，但我咋觉的不太美观，您有什么可以美化的想法么？

**Comment by imfuxiao** [comment]
![image](https://github.com/user-attachments/assets/69adee9f-cd1e-40cb-9c13-827c076b9f38)

这是候选项、候选序号和候选 comment 三者各占一行的初步效果

**Comment by tansongchen** [comment]
目前这个不太美观，可能主要是因为上下的内容都比较少，候选序号一般不会太长，占一行感觉浪费了。也许可以内容一行、序号和 comment 共用上面一行，这样接近同文的设计

**Comment by imfuxiao** [comment]
https://github.com/user-attachments/assets/4606b154-f267-4040-91d4-473e3632e851

动态调整候选栏高度

**Comment by imfuxiao** [comment]
> 目前这个不太美观，可能主要是因为上下的内容都比较少，候选序号一般不会太长，占一行感觉浪费了。也许可以内容一行、序号和 comment 共用上面一行，这样接近同文的设计

我还是觉的三个元素在一行显示会好看些，如果宽度超出屏幕，则自动拉高候选栏，显示换行后的内容。

**Comment by Marksusu** [comment]
> > 候选项、候选序号和候选 comment 三者，如果能在候选栏里各占一行就好了。 候选项在中间，序号、 comment 分列在候选项上、下方。 这样能节省屏幕宽度。
> 
> 最近在重构这里的UI，这个确实可以节省宽度，但我咋觉的不太美观，你有什么可以美化的想法么？

哈哈哈，谢谢你的回复，非常感谢你能重视我的个人化提议。

这个……美、美不美也不是绝对的，每个人在这里显示的东西也不完全一样。

如果让我使用自定义功能，我则只需要显示 comment 和候选词这两行就够了。

当我把候选字体大小调整到“正好能显示一个单字和九个二级简码对应的双字词”时， `qwertyuiop` 按键上面就有 `1-0` ，这就正好是序号了。

而我用 comment 的场景就仅限反查编码和词频，编码是固定的四位字母，词频是固定的三位数字，我只要把字体大小调整到跟双字词（此时候选中出现的词通常是双字词）等宽时，上下两栏中内容就相当饱满和一致了，这样的组合也就十分美观了。

并且，通常情况下，我基本都不会在意候选区的样子，选中之后就会被记忆的习惯所抛弃了（脑子君它就是这么渣），我只是在使用二级简码双字词时才会用足所有 10 个选项，一旦哪天把这 10 个都记牢了，就连这个也不用再看了。

有点奇怪是吧？


:)

**Comment by Marksusu** [comment]
> 目前这个不太美观，可能主要是因为上下的内容都比较少，候选序号一般不会太长，占一行感觉浪费了。也许可以内容一行、序号和 comment 共用上面一行，这样接近同文的设计

![image](https://github.com/user-attachments/assets/07da9fa2-ef40-4d4b-9425-d2e4f2df0852)

同文的确值得参考。
我的同文是这样的，调了字体大小，且用了上角标字体

**Comment by imfuxiao** [comment]
发布测试版后，自适应高度的候选栏大家反馈并不好，因为 iOS 的特性，候选栏无法做到悬浮，所以候选栏高度变化，导致键盘上方高度跳动，影响打字体验。

目前我已撤回自适应高度的功能，改为原来的横向划动，但是候选栏会做成两行，候选字占一行，序号与 comment 信息共用一行。

效果如下：

![image](https://github.com/user-attachments/assets/ce0049db-5fb0-4c08-856a-0a12b14e762d)

**Comment by Marksusu** [comment]
> 发布测试版后，自适应高度的候选栏大家反馈并不好，因为 iOS 的特性，候选栏无法做到悬浮，所以候选栏高度变化，导致键盘上方高度跳动，影响打字体验。
> 
> 
> 
> 目前我已撤回自适应高度的功能，改为原来的横向划动，但是候选栏会做成两行，候选字占一行，序号与 comment 信息共用一行。
> 
> 
> 
> 效果如下：
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/ce0049db-5fb0-4c08-856a-0a12b14e762d)
> 
> 

这个好，节省宽度又整洁

**Comment by Marksusu** [comment]
![image](https://github.com/user-attachments/assets/fdeabb78-55c1-40cc-b03a-4b132d8d5cab)
完美！
谢谢大佬～

**Comment by imfuxiao** [comment]
先关闭此 issue，后续如有其他问题，请新建 issue。
