### ISSUE TITLE
feature request  是否能自定义输入方案排序

### ISSUE THREAD

**Issue by aristotll** [imfuxiao/Hamster#546]
当前我只能去掉我主输入法之外的输入化，不然刚进来都会用其他输入法。

**Comment by imfuxiao** [comment]
我后面优化下，目前解决方案是：在键盘进入使用`#方案切换`指令，进入方案选择列表，选择一下您的方案，后面再次启动时就是选择的方案了。

**Comment by imfuxiao** [comment]
您好，此功能已支持，感谢您的反馈。
