### ISSUE TITLE
请问如何备份仓输入法的配置

### ISSUE THREAD

**Issue by iTvX** [imfuxiao/Hamster#547]
不是备份rime配置，是备份仓输入法的配置。

我目前已经通过icloud选项，把rime和sharedsupport file传到了icloud，但是经过我的发现，云端的rime可以成功的导入到本地，云端的sharedsupport也可以成功导入。但是实际配置并没有发生变化。

也就是说，我实际改变了file中的仓输入法yaml文件，但是实际没有变化。请问是怎么回事呢？如何优雅的在云端同步我所有设备仓输入法的配置信息呢？最好可以同步布局这些一起同步了。

感谢输入法作者，已捐赠以表感谢。

**Comment by imfuxiao** [comment]
您好，非常感谢您的支持。

关于您的问题，您可以参考操作手册中的[「应用配置」](https://ihsiao.com/apps/hamster/docs/AppSettings.html#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6)部分。
