### ISSUE TITLE
九宫格的“符号”如何修改默认选项？

### ISSUE THREAD

**Issue by Nothend** [imfuxiao/Hamster#548]
九宫格的“符号”如何修改默认选项？我新装仓输入法用九宫格或者26键，符号的默认状态都是中文，如何设置为“常用”呢？感谢！！！
![IMG_9080](https://github.com/imfuxiao/Hamster/assets/73117056/1df098b5-f5f1-417a-8792-9b2f9abd29c3)

**Comment by imfuxiao** [comment]
您好，目前默认的符号列表不支持自定义。「常用」列表中的符号是历史使用记录。

后面我看看如何调整为自定义。

**Comment by Nothend** [comment]
> 您好，目前默认的符号列表不支持自定义。「常用」列表中的符号是历史使用记录。
> 
> 后面我看看如何调整为自定义。

感谢你的回复！我的意思是：按下符号键之后，默认是停留在“常用”这个菜单选项。但是目前我一直是停留在“中文”这个菜单选项上，新装了一台ipad也是如此，但是我看其他人说默认就是“常用”菜单选项，是不是这个可以设置？

**Comment by Nothend** [comment]
https://github.com/imfuxiao/Hamster/assets/73117056/11547514-0d02-403b-b16e-8adb4c885aef

可能是我表述的不清楚，视频清楚一点

**Comment by Nothend** [comment]
> 应该是跟键盘有关系，内置中文键盘点击进入就是「中文」符号列表，内置英文键盘点击进入就是「英文」符号列表。其他键盘点击进入就是「默认」符号列表。

明白了谢谢

**Comment by Lion176** [comment]
我也遇到同样的问题：按下符号键之后，默认是停留在“中文”符号菜单，我希望它停留在“常用”符号菜单，有没有办法设置？

**Comment by imfuxiao** [comment]
> 我也遇到同样的问题：按下符号键之后，默认是停留在“中文”符号菜单，我希望它停留在“常用”符号菜单，有没有办法设置？

目前是不可以的，只有「自定义键盘」点击搬入符号键盘是「常用」列表。
