### ISSUE TITLE
如何设置18键双键

### ISSUE THREAD

**Issue by pinoLingo** [imfuxiao/Hamster#549]
现在使用的是18键的键盘，W 和 E 在一个键位上，但是配置 character 只支持单个字符，按下时仅会输入 w 字符，请问下如何设置按下 WE 键后输入 we 两个字符。感谢！！
<img width="394" alt="image" src="https://github.com/imfuxiao/Hamster/assets/51288409/3623b812-1afc-4487-a82d-c1bf008325ff">

**Comment by royccg** [comment]
可以参考 我的库中的 [theme+方案](https://github.com/royccg/gedao17_ios_rime/tree/159c395042239ecc6b167c1064e6e941bedf7984/theme%2B%E6%96%B9%E6%A1%88)，中17键的 "gedao_custom.yaml"和"gedao.schema.yaml"
![image](https://github.com/imfuxiao/Hamster/assets/44716144/0431eb46-22ba-463f-ac2a-ad1960696b0e)
18键的话，应该有很多可以直接用的 别人的方案的，建议多看看 [rime的关于自定义的内容](https://github.com/LEOYoon-Tsaw/Rime_collections/blob/ffd92d26f17f425a77a872ed753336483fb9c6d3/Rime_description.md)
