### ISSUE TITLE
开启触感后开关飞了

### ISSUE THREAD

**Issue by HinataKato** [imfuxiao/Hamster#55]
设备是SE Gen 1，改了6的分辨率（SE的分辨率应该也会）
![IMG_20230417_165126_988](https://user-images.githubusercontent.com/57648531/232434834-49715f33-bae0-4668-857d-252466c86c81.PNG)

**Comment by Attiv** [comment]
7 的布局是乱的，没有保存

**Comment by imfuxiao** [comment]
iOS14.2 问题复现.
