### ISSUE TITLE
在编码区渲染脱字符，并有区别地显示作文中和作文外的编码

### ISSUE THREAD

**Issue by tansongchen** [imfuxiao/Hamster#550]
在鼠须管上，例如输入 4 个音节然后定位到第 2 个音节的时候的效果是

<img width="434" alt="image" src="https://github.com/imfuxiao/Hamster/assets/31927845/da5cfee9-35b9-42ed-a6e4-cfbc10a44561">

但是在仓上，由于没有脱字符以及颜色上的区别显示，较难判断出当前作文包括哪些编码

![截屏 2024-03-09 22 08 33](https://github.com/imfuxiao/Hamster/assets/31927845/45505b93-cdc8-4578-9956-450c9a6fe380)

**Comment by imfuxiao** [comment]
脱字符支持功能已在商店版本 2.4.0 / TF 版本中支持。但有些限制：脱字符只支持工具栏显示，开启「内嵌模式」后不在显示；

调整脱字符位置，可以通过 `sendKeys` 指令发送 `left` 或 `right` 键。
