### ISSUE TITLE
九宫格键盘下如何自定义置顶候选项

### ISSUE THREAD

**Issue by relaxjfy** [imfuxiao/Hamster#552]
九宫格输入时，比如我想打“了”字，输入“l”出来的置顶是“了”，默认是“来”，custom_phrase.txt中针对的好像是26键，请问要如何实现呢
![0313](https://github.com/imfuxiao/Hamster/assets/55477124/bb1a7fc1-d844-4391-b39b-1b410da04fe0)

**Comment by imfuxiao** [comment]
目前内置九宫格使用的是「雾凇·九宫格」方案，您可以看下「雾凇·九宫格」的配置文件，里面有中文注释说明。

**Comment by relaxjfy** [comment]
> 目前内置九宫格使用的是「雾凇·九宫格」方案，您可以看下「雾凇·九宫格」的配置文件，里面有中文注释说明。

是t9.schema.yaml这个吗
![0313-1](https://github.com/imfuxiao/Hamster/assets/55477124/5460de9b-407a-43e4-9b2b-37579f6b5a38)
![0313-2](https://github.com/imfuxiao/Hamster/assets/55477124/d36471e7-13db-46bf-ab44-5f8a166ec09e)
![0313-3](https://github.com/imfuxiao/Hamster/assets/55477124/99d710a0-2c96-490a-8bc9-807aee9c90da)

**Comment by relaxjfy** [comment]
貌似可以了，在 custom_phrase.txt改了下顺序重新部署
