### ISSUE TITLE
默认九宫格的空格键无法上滑输入“0”

### ISSUE THREAD

**Issue by liu7526539** [imfuxiao/Hamster#553]
你好，在默认仓.九宫格的空格键无法上滑输入“0”，想找配置文件自己添加但没有找到。或者是否可以在后期的版本中添加上去

**Comment by imfuxiao** [comment]
见手册[「内置键盘中文九宫格如何自定义按键划动配置」](https://ihsiao.com/apps/hamster/docs/Questions.html#%E5%86%85%E7%BD%AE%E9%94%AE%E7%9B%98%E4%B8%AD%E6%96%87%E4%B9%9D%E5%AE%AB%E6%A0%BC%E5%A6%82%E4%BD%95%E8%87%AA%E5%AE%9A%E4%B9%89%E6%8C%89%E9%94%AE%E5%88%92%E5%8A%A8%E9%85%8D%E7%BD%AE)

**Comment by liu7526539** [comment]
解决了，谢谢🙏
