### ISSUE TITLE
在ios 17.3.1 下无法打出汉字

### ISSUE THREAD

**Issue by chinesewebman** [imfuxiao/Hamster#554]
九宫格点击之后都是出123456789这样的数字，语音输入倒是正常能出汉字。

**Comment by imfuxiao** [comment]
见手册「[中文九宫格无法打字只能输入数字」](https://ihsiao.com/apps/hamster/docs/Questions.html#%E4%B8%AD%E6%96%87%E4%B9%9D%E5%AE%AB%E6%A0%BC%E6%97%A0%E6%B3%95%E6%89%93%E5%AD%97%E5%8F%AA%E8%83%BD%E8%BE%93%E5%85%A5%E6%95%B0%E5%AD%97)

**Comment by imfuxiao** [comment]
看不到你的截图，请在输入方案中只勾选「九宫格」，另外键盘请勾选「九宫格」，然后在测试。

**Comment by chinesewebman** [comment]
果然解决了，多谢！发自我的指尖在 2024年3月13日，20:25，morse.hsiao ***@***.***> 写道：﻿
看不到你的截图，请在输入方案中只勾选「九宫格」，另外键盘请勾选「九宫格」，然后在测试。
