### ISSUE TITLE
默认模式下只修改键盘布局为九宫格无法拼音输入

### ISSUE THREAD

**Issue by sosoyososo** [imfuxiao/Hamster#555]
https://github.com/imfuxiao/Hamster/assets/1425019/771b4b70-e8a4-4a1e-8a1f-20474de6e99d

app store 下载后只勾选了中文九键,只输出了数字没有中文候选

**Comment by imfuxiao** [comment]
就手册「[中文九宫格无法打字只能输入数字」](https://ihsiao.com/apps/hamster/docs/Questions.html#%E4%B8%AD%E6%96%87%E4%B9%9D%E5%AE%AB%E6%A0%BC%E6%97%A0%E6%B3%95%E6%89%93%E5%AD%97%E5%8F%AA%E8%83%BD%E8%BE%93%E5%85%A5%E6%95%B0%E5%AD%97)

**Comment by sosoyososo** [comment]
问题确实解决了，也是我没去看文档导致的。

不过如果有可能还是建议为每个布局关联一个默认可用的输入方案，毕竟像我这样受到安利来开箱使用的多，真的一点点看完文档的少，也有助于你app store评分。

哈哈哈，一点小建议哈，也不一定对。
