### ISSUE TITLE
设置 `- action: { shortcutCommand: {sendKeys: { keys: "Escape" }} }`和相关block配置 无法生效

### ISSUE THREAD

**Issue by sci-42ver** [imfuxiao/Hamster#556]
为了方便在身边没有电脑的时候临时做些配置文件修改，我使用 [`ivim`](https://www.reddit.com/r/ipad/comments/17q7pza/comment/k8as3ql/?utm_source=share&utm_medium=web2x&context=3) 编辑文件以及文件夹 (APP自带的无搜索以及其他功能，不太方便)，其经常需要用到esc按键。

于是，我尝试使用 `action: { shortcutCommand: {sendKeys: { keys: "Escape" }} }`，但是没有效果 (`processByRIME: false/true`均如此)。
```javascript
...
              - action: { shortcutCommand: {sendKeys: { keys: "BackSpace" }} }
                label: "BackSpace"
                display: true
                processByRIME: false
                direction: down
```

但是，“Control+p” 配合 `processByRIME: true` 以及 `default.yaml` 的 `- { when: composing, accept: Control+p, send: Up }` 是有效的。

接着我使用 `ish` 查看按键情况:
```bash
$ read -n 1 bs; printf %s "$bs" | xxd # 手按默认的Backspace按键
00000000: 7f                                       . # 和 linux Console 编码一样 https://man7.org/linux/man-pages/man4/console_codes.4.html
$ read -n 1 bs; printf %s "$bs" | xxd # 使用`keys: "BackSpace"` 和 `processByRIME: false/true` 两种情况
# 没有反应 于是按enter
00000000: 0d                                       . # 此应该是对应 enter 的编码 基于上处linux console编码
```
以上说明 `sendKeys` 和 实际按键 可能有些区别 (比如上面的 Backspace)。

Q:
请问是否有办法映射Escape按键到action功能上? 以上问题是否是有可能 `Hamster` 成功发送了key，但是 `ish/ivim` 部分按键可能仅支持其内部的 `Esc/Ctrl` 按键 而 不支持外部的接口 (不太了解 ios 开发，此仅为猜测)?

**Comment by imfuxiao** [comment]
1. 目前 `Escape` 在代码中映射为 `esc`或`ESC`，我随后在加一个 `Escape`;
2. `sendKey`指令必须经过 RIME 处理，且需要配合 `default .yaml`中的 `key_binder` 配置一起使用的，不然是不会有效果。

在 iSH 应用中，我测试过，不起作用。貌似组合键 ctrl 或 esc 键都需要应用工具栏中提供的按键来处理。

**Comment by sci-42ver** [comment]
好的 谢谢。

对于2，可以问下 `processByRIME: false` 应用场景么 (是否仅用于 `character/symbol` )?

**Comment by imfuxiao** [comment]
> 好的 谢谢。
> 
> 对于2，可以问下 `processByRIME: false` 应用场景么 (是否仅用于 `character/symbol` )?

对的，目前主要是对 character 类型的控制，其他类型此选项不起作用。
