### ISSUE TITLE
强迫症患者提出的问题

### ISSUE THREAD

**Issue by kooleelee** [imfuxiao/Hamster#557]
感谢作者，输入法非常好用，提个强迫症患者的问题😂

核心问题：能否只通过App的界面设置，配置出和iOS原生输入法一致的布局和功能？

当前设置：使用雾凇拼音，启用内嵌模式、工具栏高度设为45、滑动文本显示关闭、禁用数字九宫格和分类符号键盘、中文26键显示大写字母关闭

具体表现：
1. 按键整体和原生输入法的高度不一致，导致切换中英文时会跳动（见下图，左边仓输入法，右边iOS原生）
2. 26键的数字符号键盘，无法通过长按输入更多符号（原生的长按非常方便）
3. 键盘上的字体，在滑动文本显示关闭后，偏小
4. 缺少回车键的判断逻辑，输入框为空时发送按钮没有disable（见下图，左边仓输入法，右边iOS原生）
5. 中文模式下输入一半的内容，切换英文后会清空，而没有上屏
6. 中文下的Emoji按钮还挺方便的，能加上就好了

![左仓输入法右原生](https://github.com/imfuxiao/Hamster/assets/32923434/090046ed-201c-41c6-95ae-42c6811386b8)

**Comment by derek0x** [comment]
你可以通过rowheight，keywidth，自行调整
