### ISSUE TITLE
Ipad 上配置键盘布局划动设置时闪退

### ISSUE THREAD

**Issue by dyphire** [imfuxiao/Hamster#559]
如题，ipad 上最新版本输入法中在键盘布局里进行划动设置指定划动操作时，点击快捷指令或切换键盘的操作都会立即闪退。ios 手机上没有这个问题

**Comment by imfuxiao** [comment]
感谢您的反馈，预计下个版本修复。

**Comment by dyphire** [comment]
最新的商店版已修复该问题
