### ISSUE TITLE
双击空格出句号

### ISSUE THREAD

**Issue by imfuxiao** [imfuxiao/Hamster#56]
需求描述: 希望可以双击空格出句号.

**Comment by DawnLi-code** [comment]
个人觉得意义不大
一、空格两边已经能自定义句号或者其它符号了
二、也有输入一句空两三格的时候

**Comment by tingting-d** [comment]
个人觉得这个没有必要，在输入功能调整设置里可以自定义空格左右的按键，在此处按照自己的习惯设置更方便。

**Comment by imfuxiao** [comment]
此功能暂时不考虑。放在项目的feature中，或许未来会做。
