### ISSUE TITLE
反馈一下使用九键输入的一些问题

### ISSUE THREAD

**Issue by limelisest** [imfuxiao/Hamster#561]
1.重码的优先级问题，就比如我按3，默认显示的是'e'，但是我想要他默认的是'd'，记住按一下3就能打'的'这个字，同理还有打74366的时候我希望他出来的是'什么'shen'm，但是实际上给出来的是'切莫'qie'mo

2.因为用的九键所以对于英文键盘的联想是有一定需求的，希望加上这个功能

ps:后续会不会考虑九宫格滑动输入之类的功能

整体用起来还是很不错的，拿来当主力输入法了（已赞助一杯瑞幸

**Comment by imfuxiao** [comment]
您好，感谢您的支持。

问题2：需要调整雾凇·九宫格输入方案配置，在 `t9.schema.yaml` 第 50 行，

```yaml
    # - table_translator@melt_eng     # 英文输入
    # 改为，注意空格缩进
    - table_translator@melt_eng     # 英文输入
```

问题1：九宫格输入方案目前还不完善，后续会优化。

**Comment by limelisest** [comment]
> 您好，感谢您的支持。
> 
> 问题2：需要调整雾凇·九宫格输入方案配置，在 `t9.schema.yaml` 第 50 行，
> 
> ```yaml
>     # - table_translator@melt_eng     # 英文输入
>     # 改为，注意空格缩进
>     - table_translator@melt_eng     # 英文输入
> ```
> 
> 问题1：九宫格输入方案目前还不完善，后续会优化。

我又观察了下大概发现了问题所在
当一个键包含a/o/e这三个可以单独成字的韵母时候，他就会停止联想其他声母的字词
比如点2的时候只会联想a而不会联想b*,c*，3和6的e和o同理。
