### ISSUE TITLE
EXC_BAD_ACCESS (code=1, address=0x8)

### ISSUE THREAD

**Issue by HopeBill** [imfuxiao/Hamster#562]
我尝试引入自己的项目中，当我输入相应字符时总是在相同位置报一下错误:EXC_BAD_ACCESS (code=1, address=0x8)，是在调用的时候需要注意什么问题吗

![1](https://github.com/imfuxiao/Hamster/assets/17613633/6ceccbc1-b8b2-4400-8499-8cdb7b8db355)

**Comment by tigerace207** [comment]
请问最后是怎么解决的呢？
