### ISSUE TITLE
alpha204版本下，app内设置的内容保存在哪个文件了

### ISSUE THREAD

**Issue by chca2** [imfuxiao/Hamster#565]
比如说按键滑动设置这些，官方wiki提到了app设置内容和hamster.yaml的区别和优先级，但是没有说app设置项保存去哪里了。有看到wiki说sharedsupport存放了默认的设置文件，但在rime或sharedsupport都没有发现保存有app设置项的文件。
p.s:我用的alpha204版本，方案为小鹤音形，iCloud同步设置。

**Comment by imfuxiao** [comment]
您好，所谓 App 设置，指通过 UI 界面生成的设置，这些设置是在应用内部存储，并没已文件的形式暴露出来。

**Comment by chca2** [comment]
> 您好，所谓 App 设置，指通过 UI 界面生成的设置，这些设置是在应用内部存储，并没已文件的形式暴露出来。

感谢回复，那么需要追加设置（如增加微信皮肤）时候，只能使用放置hamster.yaml在rime的做法吗，但这样又会存在需要比对ap设置项和yaml定义值，很容易冲突后不生效，是否有好的做法？
