### ISSUE TITLE
iPad上布局bug

### ISSUE THREAD

**Issue by chca2** [imfuxiao/Hamster#566]
如图，没有设置中英切换键但还是出现且位置奇怪，此外设置了空格键左右按键也没有显示。![image](https://github.com/imfuxiao/Hamster/assets/65901120/aa00bd6c-0cfb-4e86-9164-4eebaaf34c09)

**Comment by imfuxiao** [comment]
抱歉，iPad 上的键盘，后面会做优化。感谢您的反馈。

**Comment by imfuxiao** [comment]
商店 2.7.0 已优化，感谢您的反馈。

**Comment by chca2** [comment]
> 商店 2.7.0 已优化，感谢您的反馈。

![EB053354-0471-4F98-B6EF-6CE4D56469A1_4_5005_c](https://github.com/user-attachments/assets/df09681a-e35d-48ce-ac20-ea64f0145ef1)
付佬，不确定是否已修复，我使用的iOS 18，商店2.7.0版本。
如图的中英文按钮还是在左边，另外也请看看双数字按钮、额外增加的逗号句号、左上和右上的tab和删除键位置是否正常。
当然，上述问题并不影响使用。也并非最优先问题。

**Comment by imfuxiao** [comment]
是正常的，iPad 上的布局是参考系统键盘中的布局。

**Comment by nullptrx** [comment]
请问如何在”中文26键“的基础上自定义ipad键盘？a和z在ipad上对齐了，希望m右移一格，键盘设置中的“显示逗号按键”开关无效。
