### ISSUE TITLE
自带方案“极点五笔”单字模式出错

### ISSUE THREAD

**Issue by xlangzhong1** [imfuxiao/Hamster#567]
设备：iPhone 15pro  IOS17.4.1
问题描述：以[极点五笔方案](https://github.com/KyleBing/rime-wubi86-jidian) 自带文档设置单字教程操作，出现无法出字的情况，如下图
![image](https://github.com/imfuxiao/Hamster/assets/59363725/7c7fc474-e1c2-4776-83d8-b439a6c591ff)

尝试解决：重装app，重装方案无效
复现方法：

1. 新设备下载仓输入法后，点击“输入方案设置”--“+”--“方案下载”--“五笔86--极点方案”--替换并部属
2. 现测试打字，完全正常
3. 返回app，进入文件管理，打开应用文件：wubi86_jidian.schema.yaml，将图示两行前的“#”删掉并重新部属，如图：
![image](https://github.com/imfuxiao/Hamster/assets/59363725/c3eabd0a-dc36-48cb-88e9-c57a73c70df5)
4. 测试打字，会出现问题描述中的情况。

经群友测试更改，也发现同样问题，应当是属bug，操作改单字教程完全按极点五笔方案进行，其它未有改动

**Comment by derek0x** [comment]
确实有bug，单字无法出汉字

**Comment by imfuxiao** [comment]
是方案的问题，已提交 PR。服务端我已重新上传，请重新下载此方案。
