### ISSUE TITLE
提点小建议

### ISSUE THREAD

**Issue by lianyis** [imfuxiao/Hamster#57]
1，添加英文键盘和切换键。另外英文键盘可以直接上屏，不需要候选栏。当然也可以做一个开关。
2，滑行输入。
3，支持T9模式。

**Comment by imfuxiao** [comment]
很高兴收到您的反馈. 
1. 中英文切换按键的功能正在开发, 应该这一两天就会发布. 关联 #22
2. 滑行输入这个功能没有. 后续考虑看是否添加此功能.
3. 九宫格功能在需求列表中, 后续开发. 关联 #52
