### ISSUE TITLE
商店版 2.4.0 及 TF 214 九宫格只能输入数字

### ISSUE THREAD

**Issue by g6ai** [imfuxiao/Hamster#571]
不仅用我的配置只能输入数字，为了测试我进行了RIME重置，选择了“雾凇拼音·九宫格”输入方案和“中文９键”键盘布局，依然只能输入数字。

**Comment by imfuxiao** [comment]
感谢反馈，应该是内置的雾凇方案有点问题。

临时解决方案：「输入方案设置」->  右上角 「+」-> 「方案下载」，点击「雾凇拼音」，选择「替换并部署」。

注意：使用中文九宫格，需要在输入方案中选择「仓·九宫格」（只包含一个输入方案），另外键盘布局选择「中文9键」。

**Comment by g6ai** [comment]
谢谢仓老师，以上方法成功解决问题（为什么Dvel的t9.schema.yaml里称呼您为仓老师而不是付老师）

**Comment by imfuxiao** [comment]
> 谢谢仓老师，以上方法成功解决问题（为什么Dvel的t9.schema.yaml里称呼您为仓老师而不是付老师）

😭，请不要这样称呼我，仓输入法的英文是 Hamster，是仓鼠。

**Comment by g6ai** [comment]
测试证实TF 215已修复本issue
