### ISSUE TITLE
2.4.0版九宫格“v”符号上屏无法使用

### ISSUE THREAD

**Issue by Nothend** [imfuxiao/Hamster#573]
之前版本的九宫格可以通过字母v进行符号上屏。比如星座，在九宫格中键入vxz就能显示星座的符号。到最新的版本选定字母时会吃掉前面的字母。

https://github.com/imfuxiao/Hamster/assets/73117056/5fef7f22-e707-42ac-8108-62c221f58633

**Comment by imfuxiao** [comment]
商店版本已修复此问题，因此关闭此 issue。后续如果在有问题，麻烦提交新的 issue。
