### ISSUE TITLE
長按輸入列時，位於中心的鍵長按後可能輸入不了最右/最左側的字元

### ISSUE THREAD

**Issue by Ostrichbeta** [imfuxiao/Hamster#574]
長按輸入時，如果長按列太長，又是從中間開始時，可能會出現按不到另一側的情況。

比如下方數字長按輸入的對比：
![image](https://github.com/imfuxiao/Hamster/assets/25266479/f28f6c24-c8e6-4a45-a87a-88907171ff86)
倉中，數字5是由中間按下的，但是由於螢幕的長度，滑到最右側最多也只能滑到 「(5)」處。

而系統內帶的輸入法（此處以注音輸入法為例），則是將開始位置置中，這樣往左往右都可以滑到：
![image](https://github.com/imfuxiao/Hamster/assets/25266479/d418e3d2-43a7-456d-bc39-e626670efc58)

**Comment by imfuxiao** [comment]
感谢您的反馈，TF版本在优化长按气泡样式时，已处理了此问题。
