### ISSUE TITLE
长按action汽泡样式优化

### ISSUE THREAD

**Issue by derek0x** [imfuxiao/Hamster#575]
![IMG_1068](https://github.com/imfuxiao/Hamster/assets/18011180/c59a9f54-1716-404c-b1e1-c924792dbb2a)
![IMG_1118](https://github.com/imfuxiao/Hamster/assets/18011180/64bc8cd6-9114-4c11-a104-b1e81f3f3033)

**Comment by derek0x** [comment]
仓老师懂我意思

**Comment by imfuxiao** [comment]
感谢您的反馈，TF 3.0.0（224）已优化长按气泡样式。
