### ISSUE TITLE
划动设置切换中文九宫格键盘异常

### ISSUE THREAD

**Issue by 1wingedangel** [imfuxiao/Hamster#576]
版本是 TF215。
在键盘布局 - 中文26键 - 划动设置，设置任意按键的上划，划动操作是 切换键盘 - 中文九宫格键盘，此时划动操作显示的是 keyboardType(chineseNumeric) 。

实际进行上划操作时并没有切换到中文九宫格键盘，而是全键盘版本的数字键盘。

**Comment by imfuxiao** [comment]
您好，商店版本与TF版本已修正此文题，因此关闭此 issue。如果您的问题仍为解决，可以重新打开此 issue。
