### ISSUE TITLE
最近想到的一些问题和建议

### ISSUE THREAD

**Issue by Anber55** [imfuxiao/Hamster#578]
可能的问题：
1、全选后点击文本立马删除，不知道是不是问题 
2、全选后进行复制、剪切无效
https://github.com/imfuxiao/Hamster/assets/117334130/f9810e17-fe5e-400d-a55b-60b5e1ec8452
3、将键盘的最后一行的最左侧按键宽度变大，这一行其他按键的宽度变小，使得这一行宽度总和为1，导致了之前正常的长按显示现在被拉的很长，超出屏幕范围（和之前正常的配置对比过，只有这一点发生改变）
![IMG_0755](https://github.com/imfuxiao/Hamster/assets/117334130/6e79cac7-1c4b-44c3-af4f-506127dc99f2)

建议：
1、键盘工具栏现在很多工具，是否支持排序
2、希望将未点击时的键盘字符颜色与长按后的字符颜色分开设置
![IMG_0754](https://github.com/imfuxiao/Hamster/assets/117334130/9de78ce1-6565-4e52-89e1-7ad3dc67b9f2)
![IMG_0755 2](https://github.com/imfuxiao/Hamster/assets/117334130/9d6de680-7347-4a16-9334-ff23af0807c1)
3、键盘上方左侧和右侧的功能键是否能配色
![IMG_0757](https://github.com/imfuxiao/Hamster/assets/117334130/5726ae4e-2378-4052-acd9-7723c77bc284)
4、可以像iRime一样，官方配置一个通用的键盘布局配色，让新手使用起来更易上手，QQ群很多人都在求配色布局

**Comment by imfuxiao** [comment]
感谢反馈。

1. 全选后点击文本立马删除。这个不是问题，内嵌模式下输入，点击选择字符，也会出现这个问题。
2. 这是个问题，TF 下个版本会修复。
3. 长按视图后面会做优化，后面一起处理。

建议：
1. 键盘工具栏现在很多工具，是否支持排序。不打算做排序，因为工具栏最多只可以添加 6 个按键，完全可以通过点击「晃动」动画的按键以删除，并选择添加新的按键。用这种方式处理排序的问题。
2. 此问题应该也是长按优化的一部分。
3. 键盘上方左侧和右侧的功能键是否能配色。优先级不搞，暂时不会做调整。目前可以通过「键盘配色」调整，好像与键盘文字颜色是一致的。
4. 这个问题见仁见智。仓默认已系统原生键盘配色为主，我平时也是这样使用的。内置的键盘配色有两个，可以打开初步使用。
