### ISSUE TITLE
"Payload too large" error occurs during file upload

### ISSUE THREAD

**Issue by MiracleXYZ** [imfuxiao/Hamster#58]
I am using rime-ice and the `build/rime_ice.table.bin` file is taking up 70MB. However, whenever I try to upload it to my phone, I receive an error message stating that the size limit has been exceeded:

<img width="313" alt="image" src="https://user-images.githubusercontent.com/30370926/232525655-01d91b83-dda6-4d9a-95ac-73bcb254052f.png">

Is there any way to increase the size limit?

**Comment by imfuxiao** [comment]
> I am using rime-ice and the `build/rime_ice.table.bin` file is taking up 70MB. However, whenever I try to upload it to my phone, I receive an error message stating that the size limit has been exceeded:
> 
> 
> 
> <img width="313" alt="image" src="https://user-images.githubusercontent.com/30370926/232525655-01d91b83-dda6-4d9a-95ac-73bcb254052f.png">
> 
> 
> 
> Is there any way to increase the size limit?

您好, 文件上传功能在iOS侧开启了http服务,此服务有限制request的body的最大字节数, 目前设置为60MB.

做此限制的目的是, iOS系统对app内存的使用有大小限制, 超过了会被kill. 另外我也没有想到会有这么大的词库. 

方便提供下您的输入方案么, 我测试下如果没有问题, 我把限制提高些.

**Comment by MiracleXYZ** [comment]
我在用雾凇拼音： https://github.com/iDvel/rime-ice

**Comment by flay0303** [comment]
> 我在用雾凇拼音： https://github.com/iDvel/rime-ice
> 
> ---
> 
> 我是用 plum 配置的，看起来如果直接手动安装的话，不需要这个大词库文件（？）

build下面的字库bin文件是编译生成的，是不需要复制过去的。把几个dict文件放进去就行了。

**Comment by imfuxiao** [comment]
雾淞拼音输入方案使用
1. git clone https://github.com/iDvel/rime-ice
2. App打开输入方案上传, 点击启动
3. 局域网浏览器打开手机IP后, 进入"Rime"文件夹, 全选并删除.
4. 将rime-ice下文件全选, 拖拽到浏览器中, 注意: 这里当前位置是Rime文件夹下
5. 点击App主页面重新部署按钮, 等待部署完成.
6. 完毕, 可以使用了.
