### ISSUE TITLE
无法内购

### ISSUE THREAD

**Issue by cactusnix** [imfuxiao/Hamster#582]
美区账号无法进行支付 并不确定是否是账号的原因 点击购买卡在唤醒的过程中

**Comment by imfuxiao** [comment]
应该是可以的，我用美区账号测试过，是可以购买的。

麻烦重新在试下，看看是否是网络的问题。

也可以发邮件给我，我发您内购兑换码。

**Comment by cactusnix** [comment]
> 应该是可以的，我用美区账号测试过，是可以购买的。
> 
> 
> 
> 麻烦重新在试下，看看是否是网络的问题。
> 
> 
> 
> 也可以发邮件给我，我发您内购兑换码。

可以了，已经购买了，原因是走了代理。
