### ISSUE TITLE
关于添加GitHub Issue Template的建议

### ISSUE THREAD

**Issue by 971230** [imfuxiao/Hamster#583]
就是建议添加一些模板，规范一下Issue的提交
![image](https://github.com/imfuxiao/Hamster/assets/37500200/e160ff08-0d21-4ee1-994e-fd54c4e8a4e4)
![image](https://github.com/imfuxiao/Hamster/assets/37500200/9d97d2c0-fbf6-4b11-8083-42d251f36e51)
好处就是提交的更加规范，对issue进行分类，节省开发者交流的时间，让作者(们)更专注于issue问题本身，感觉目前咱项目有一些issue确实不是具体的问题，是可以通关类似的方式过滤掉的，还有一些重复的问题也是一样的，参考其他项目，如图
![image](https://github.com/imfuxiao/Hamster/assets/37500200/0c33c677-f7ba-4f69-90c1-42c8b2f464b7)
不知道作者忙不忙，提个小建议🫰🫰🫰🫰🫰

**Comment by imfuxiao** [comment]
您好，非常好的建议，我已添加此功能。
