### ISSUE TITLE
「Bug」打开纠错功能（enable_correction: true)之后，键入部分拼音会导致输入法崩溃。

### ISSUE THREAD

**Issue by xymeng16** [imfuxiao/Hamster#589]
**Bug的详细描述**
打开内置的纠错功能（enable_correction: true)之后，键入部分拼音会导致输入法崩溃。

**Bug 的复现过程**
1. 设置*.schema.yaml中的
```yaml
translator: 
  enable_correction: true
```
2. 重新部署；
3. 键入ha/ma/se等拼音（注意，不要在键入这些拼音之前输入其他拼音，当这些拼音不作为起始编码时，不会触发此bug）；
4. 输入法即刻崩溃。
**您的预期行为**
输入法应该正常运行并给出相应的字词。

**屏幕截图/视频**
<video src="https://github.com/imfuxiao/Hamster/assets/21276508/0f4a3394-c9b2-410c-b344-52982c926e20" controls></video>

**设备信息**
 -  iOS 版本：如 17.4.1
 -  仓输入法版本：商店版 2.4.1 

**其他**
默认的雾凇拼音以及我个人fork的[薄荷拼音](https://github.com/xymeng16/oh-my-rime)均可复现此bug

**Comment by xymeng16** [comment]
顺道提一嘴，Pro中的WebDAV没看懂怎么用，希望作者或多或少能给点指引：）

**Comment by imfuxiao** [comment]
> 顺道提一嘴，Pro中的WebDAV没看懂怎么用，希望作者或多或少能给点指引：）

WebDAV 目前还是处于实验功能，目前已发现不少问题，后面会逐步完善。等功能稳定了会出文档。感谢反馈。

**Comment by imfuxiao** [comment]
经测试，此问题是 librime 更新到 1.11.0 后出现的问题。我回退到  librime 1.10.0 版本后正常。

**Comment by xymeng16** [comment]
> 经测试，此问题是 librime 更新到 1.11.0 后出现的。我回退到 librime 1.10.0 版本后测试正常。
> 
> librime 的问题需要上游 librime 进行修复。

收到，感谢🙏

请问您有无在librime侧提出相关issue？如果您那边有更多的调试信息/日志，方便的话麻烦在那边开一个issue。如果没有更多信息，我可以直接把这个issue复制过去。

另外如果可以的话最好在App Store的版本也回退一下，或者给个TF的名额在TF侧回退，没有这个纠错功能打字还是有些费劲:)

> > 顺道提一嘴，Pro中的WebDAV没看懂怎么用，希望作者或多或少能给点指引：）
> 
> WebDAV 目前还是处于实验功能，目前已发现不少问题，后面会逐步完善。等功能稳定了会出文档。感谢反馈。

辛苦，希望可以实现（手动的）双向同步，这样能解决Google Drive或者其他网盘的配置没法方便的在iOS上同步这个问题。（通过一些方法把这些网盘挂成WebDAV解决）

**Comment by imfuxiao** [comment]
我还没有仔细看这个问题在 librime 的具体问题点是啥，只是看到 enable_correction 选项的相关代码在 1.11.0 版本与 1.10.0 版本之间做过改动。等我有空了看看可否修复 librime 的问题，所以暂时没有对 librime 库提交 issue。
---
WebDAV 目前是还是实验功能，还有一些问题需要处理。

**Comment by fxliang** [comment]
rime/librime#863 已修复了

**Comment by imfuxiao** [comment]
> [rime/librime#863](https://github.com/rime/librime/pull/863) 已修复了

librime 没有发布 release，「仓」依赖 librime 的 release 版本。

**Comment by fxliang** [comment]
> > [rime/librime#863](https://github.com/rime/librime/pull/863) 已修复了
> 
> librime 没有发布 release，「仓」依赖 librime 的 release 版本。

很快就会了

**Comment by imfuxiao** [comment]
> > > [rime/librime#863](https://github.com/rime/librime/pull/863) 已修复了
> > 
> > 
> > librime 没有发布 release，「仓」依赖 librime 的 release 版本。
> 
> 很快就会了

嗯嗯，librime 发布后我会更新看看。

**Comment by fxliang** [comment]
> > > > [rime/librime#863](https://github.com/rime/librime/pull/863) 已修复了
> > > 
> > > 
> > > librime 没有发布 release，「仓」依赖 librime 的 release 版本。
> > 
> > 
> > 很快就会了
> 
> 嗯嗯，librime 发布后我会更新看看。

1.11.2 released https://github.com/rime/librime/releases/tag/1.11.2

**Comment by imfuxiao** [comment]
> > > > > [rime/librime#863](https://github.com/rime/librime/pull/863) 已修复了
> > > > 
> > > > 
> > > > librime 没有发布 release，「仓」依赖 librime 的 release 版本。
> > > 
> > > 
> > > 很快就会了
> > 
> > 
> > 嗯嗯，librime 发布后我会更新看看。
> 
> 1.11.2 released https://github.com/rime/librime/releases/tag/1.11.2

收到，我去搞搞

**Comment by imfuxiao** [comment]
商店版本已发布，librime 已升级至 1.11.2，测试不会在崩溃了，如有问题，请可以重新打开此 issue。
