### ISSUE TITLE
输入符号提供其他输入方式。

### ISSUE THREAD

**Issue by weearc** [imfuxiao/Hamster#59]
感谢菊苣的付出，现在终于有个完全开源的iOS 的rime了。实际使用的时候发现输入符号和数字是支持直接上划的，这个确实很好，不过也想请求一下其他的实现方式，比如类似gboard的长按展开上划可输入的符号组然后手指按住并滑动选择符号。目前虽然打开气泡并上划能实现类似效果但对于默认不开启气泡的人和不熟悉直接上划的不太友好。请求添加长按选择的方式，此方式在实现上可能有办法兼容上划的实现。

**Comment by imfuxiao** [comment]
感谢您的反馈.

想法很赞, 我会考虑下如何加入此功能.

**Comment by imfuxiao** [comment]
关联 #24 ，通过符号键盘实现。
