### ISSUE TITLE
「Feature」是否可能增加“强制使用配置文件”或“应用内设置”的选项

### ISSUE THREAD

**Issue by chca2** [imfuxiao/Hamster#591]
**您的功能请求是否与某些问题有关？请描述**
iPhone配置文件、iCloud配置文件和应用内设置，冲突时无法使hamster配置文件生效。相信许多用家都碰到过类似问题，如果增加选项会解决两者差异。

**描述您想要的解决方案**
增加“强制使用配置文件”或“应用内设置”的选项。

**描述您考虑过的替代方案**
无

**其他**
无

**Comment by imfuxiao** [comment]
「应用界面设置」与「配置文件设置」是两种方式，所以必然会出现冲突。

仓目前的逻辑是通过优先级来解决：界面设置 > 配置文件 > 默认配置项。

对于普通用户来说，界面设置就够用了，常用的选项，界面点点就可以用了。

复杂的靠配置文件的设置，那么就用配置文件就可以了。

而且「关于」中也有界面设置选项的「重置」与「导出」，也能满足需求。

所以强制使用「配置文件」或者强制使用「界面设置」的需求，我个人认为是没有必要。
