### ISSUE TITLE
问题 后续是否仍会开源？

### ISSUE THREAD

**Issue by cactusnix** [imfuxiao/Hamster#592]
如题

**Comment by imfuxiao** [comment]
抱歉，之前没有同步代码的原因，是因为在申请「软著」中，到今年二月底的时候，软著才申请下来。

目前没有同步的原因，是我还没有想清楚，后面 Hamster 如何运作下去。

2.0 发布了打赏码，2.4版本上线了 Pro 模块，也是想让 Hamster 更好维持下去，目前状态来看有点难。

**Comment by cactusnix** [comment]
> 抱歉，之前没有同步代码的原因，是因为在申请「软著」中，到今年二月底的时候，软著才申请下来。
> 
> 
> 
> 目前没有同步的原因，是我还没有想清楚，后面 Hamster 如何运作下去。
> 
> 
> 
> 2.0 发布了打赏码，2.4版本上线了 Pro 模块，也是想让 Hamster 更好维持下去，目前状态来看有点难。

可以理解，目标都是希望产品更加好，已经支持，也尊重你的选择。

**Comment by mirtlecn** [comment]
大概对付费这个改动是没有必要太犹豫的。

在苹果生态下开发，本身就给 Apple 交钱，没公司支持，还要倒贴时间是不值当的。

不少 iOS 应用都同时保持开源和订阅制或者买断，运行了几年了也没有大问题。毕竟有壁垒在那。

担心开源后被二次开发上架维权繁琐，私有也不是不能接受。毕竟这个项目本事就很优秀。也许不少人都会支持。

只是说，似乎看来这个项目目前还是gpl 协议，如果后续还采用这个协议，分发必须附带对应的源码。

如果没有 gpl 其他库的话，如果以后私有，可能要以后的版本改个协议，做个声明之类
