### ISSUE TITLE
空格双击句号+快捷指令

### ISSUE THREAD

**Issue by Anber55** [imfuxiao/Hamster#595]
**您的功能请求是否与某些问题有关？请描述**
我希望利用空格双击取代我的句号键，但是有几点想看看能不能实现：
①前面无字符的情况下输入句号，有的时候会用到（几个点表示无奈）
②计算器lua，无法双击空格产生小数点

希望快捷指令增加：重置（测试会经常重置，有了这个快捷指令就能完全自动化了）+WebDAV同步（我是用来在Mac上检测自造词）

**描述您想要的解决方案**
如上

**描述您考虑过的替代方案**
没有

**其他**
没有

**Comment by imfuxiao** [comment]
- ①前面无字符的情况下输入句号，有的时候会用到（几个点表示无奈）

这个需求不应该是双击空格去实现的事情，如果有用户需要多输入几个空格，来进行缩进，就很容易发生空格变为句号的问题。所以其他输入法也是只有光标在候选字后面且没有任何间隔的情况下，双击才会出现句号。我想理由也是一样的。

- ②计算器lua，无法双击空格产生小数点

双击空格的场景设计是为了断句使用。不适用你说的场景，建议使用上划/长按/切数字键盘去完成小数点的输入。


- 快捷指令添加：重置，WebDAV同步。

重置是危险操作，不考虑提供快捷指令。WebDAV同步目前是实验功能，暂不考虑。
