### ISSUE TITLE
希望候选栏支持多行

### ISSUE THREAD

**Issue by Dieken** [imfuxiao/Hamster#596]
**您的功能请求是否与某些问题有关？请描述**

手机上屏幕很窄，经常一行不够显示词组候选，滑动选择不太方便。

**描述您想要的解决方案**

希望候选栏可以显示多行，至少两行。

**描述您考虑过的替代方案**

无。

**其他**

无。

**Comment by imfuxiao** [comment]
您好，您的需求与 #545 相同，因此关闭此 issue。如有任何关于此 issue 的补充说明，可在 #545 中回复。
