### ISSUE TITLE
魔然方案同步词库失败

### ISSUE THREAD

**Issue by jdjxk** [imfuxiao/Hamster#599]
**Bug的详细描述**
自 2.4.0 版本后，采用魔然方案时，同步提示异常，2.4.1 仍存在此问题，2.4.0 版本更新前使用一切正常
查看日志发现 moran 数据库提示只读，而 moran-english 正常备份

**Bug 的复现过程**
重现此 Bug 的步骤：
1. 选用魔然方案
2. 点击 Rime 同步
3. 日志异常

**您的预期行为**
正常同步

**屏幕截图/视频**
如果可能，请添加截图或视频以帮助解释您的问题。

**设备信息（请填写以下信息）：**
 -  iOS 版本：如 17.4.1
 -  仓输入法版本：商店版 2.4.1

**其他**
日志节选
I20240416 09:33:30.066046 0x16df0f000 user_dict_manager.cc:213] synchronizing 2 user dicts.
I20240416 09:33:30.066049 0x16df0f000 user_dict_manager.cc:179] synchronize user dict 'moran'.
E20240416 09:33:30.066434 0x16df0f000 level_db.cc:273] Error opening db 'moran' read-only.
E20240416 09:33:30.068575 0x16df0f000 user_dict_manager.cc:204] error backing up user dict 'moran'.
I20240416 09:33:30.068597 0x16df0f000 user_dict_manager.cc:179] synchronize user dict 'moran_english'.
I20240416 09:33:30.122105 0x16df0f000 user_db.cc:115] backing up userdb 'moran_english' to /var/mobile/Containers/Data/Application/196AC6A2-195E-44FE-AB4F-ADD121428DFB/Documents/Rime/sync/35e1e7d1-b914-4ad7-a0fe-099a54a68132/moran_english.userdb.txt
I20240416 09:33:30.122114 0x16df0f000 tsv.cc:62] writing tsv file: /var/mobile/Containers/Data/Application/196AC6A2-195E-44FE-AB4F-ADD121428DFB/Documents/Rime/sync/35e1e7d1-b914-4ad7-a0fe-099a54a68132/moran_english.userdb.txt
I20240416 09:33:30.122490 0x16df0f000 level_db.cc:284] closed db 'moran_english'.
E20240416 09:33:30.122498 0x16df0f000 user_dict_manager.cc:220] failed synchronizing 1/2 user dicts.
I20240416 09:33:30.122516 0x16df0f000 deployer.cc:96] 3 tasks ran: 2 success, 1 failure.
I20240416 09:33:30.122654 0x16dbc7000 level_db.cc:284] closed db 'moran'.

**Comment by jdjxk** [comment]
已找到解决方法：
添加一个其他方案重新部署后成功同步，再换回魔然方案使用，比较繁琐

**Comment by imfuxiao** [comment]
看您的日志错误在这里：
```
E20240416 09:33:30.066434 0x16df0f000 level_db.cc:273] Error opening db 'moran' read-only.
E20240416 09:33:30.068575 0x16df0f000 user_dict_manager.cc:204] error backing up user dict 'moran'.
```

- 可以尝试着给键盘一个完全访问权限试试
- 还可以检查下同步的路径是否有写权限

**Comment by jdjxk** [comment]
已授予完全访问权限，路径的话改为iCloud目录，问题依旧

**Comment by jdjxk** [comment]
2.6.0更新后同步恢复正常，请知悉
