### ISSUE TITLE
候选栏候选字无法完全显示.

### ISSUE THREAD

**Issue by Attiv** [imfuxiao/Hamster#60]
![image](https://user-images.githubusercontent.com/15698129/232632413-7390049c-a2d3-4ce8-84c2-cd3c616f0b45.jpeg)
![image](https://user-images.githubusercontent.com/15698129/232632435-0f872431-c710-4a8a-89a5-644dbadfd7e8.jpeg)

**Comment by xudonlee** [comment]
那个数字键盘切换按钮显示空白的我的也没修复，估计是部分机型没适配

**Comment by Attiv** [comment]
我的是13

**Comment by imfuxiao** [comment]
> 那个数字键盘切换按钮显示空白的我的也没修复，估计是部分机型没适配

卸载重新安装测试下

**Comment by imfuxiao** [comment]
候选栏改了控件, 有一个宽度计算. 是这里有了问题, 我今天在修改下. 应该明天会出一个版本.

@Attiv 麻烦提供下具体机型, 另外您的输入方案是用的xkjd6吗? 我需要测试下

**Comment by Attiv** [comment]
> 候选栏改了控件, 有一个宽度计算. 是这里有了问题, 我今天在修改下. 应该明天会出一个版本.
> 
> 
> 
> @Attiv 麻烦提供下具体机型, 另外您的输入方案是用的xkjd6吗? 我需要测试下

是的，用的xkjd6，手机是13

**Comment by imfuxiao** [comment]
收到, 谢谢

**Comment by DreamAfar** [comment]
不单是键道6输入方案有问题，其他方案的都有问题，只要显示候选编码，并且编码长的就会被省略一部分不显示。
![image](https://user-images.githubusercontent.com/69999980/232640609-b9d93f73-1e52-465b-afa0-75e9b51a82aa.jpeg)

![image](https://user-images.githubusercontent.com/69999980/232640625-d19d4eb6-a09e-47b0-8d15-25e60ade0b20.jpeg)

**Comment by imfuxiao** [comment]
> 不单是键道6输入方案有问题，其他方案的都有问题，只要显示候选编码，并且编码长的就会被省略一部分不显示。 ![image](https://user-images.githubusercontent.com/69999980/232640609-b9d93f73-1e52-465b-afa0-75e9b51a82aa.jpeg)
> 
> ![image](https://user-images.githubusercontent.com/69999980/232640625-d19d4eb6-a09e-47b0-8d15-25e60ade0b20.jpeg)

收到, 感谢反馈. 这个问题是昨天在发布候选栏误触无反应引入的, 我今天会修改, 预计最快明天可以发布一个版本.
