### ISSUE TITLE
「Feature」优化九宫格数字键盘气泡过大

### ISSUE THREAD

**Issue by Lion176** [imfuxiao/Hamster#601]
**您的功能请求是否与某些问题有关？请描述**
简明扼要地描述问题所在。
![IMG_8384](https://github.com/imfuxiao/Hamster/assets/97778001/34b7d211-3925-45ae-80a9-ba0ef270d57b)
![IMG_8385](https://github.com/imfuxiao/Hamster/assets/97778001/e58b3748-a6f0-47e2-a5ed-175632036345)
九宫格数字键盘气泡过大，建议优化调整一下尺寸。
**描述您想要的解决方案**
简明扼要地描述您希望发生的结果。

**描述您考虑过的替代方案**
简明扼要地描述您考虑过的任何替代解决方案或功能。

**其他**
在此处添加有关功能请求的任何其他上下文或截图或视频等等。

**Comment by imfuxiao** [comment]
目前气泡显示逻辑已调整，九宫格按键已不在显示气泡了。
