### ISSUE TITLE
「Feature」支持指定自定义数字键盘，代替内置数字键盘

### ISSUE THREAD

**Issue by Jmdayou** [imfuxiao/Hamster#603]
**您的功能请求是否与某些问题有关？请描述**
在闹钟、记账软件等需要输入数字的场景，使用仓会调用内置的数字键盘，而非自定义键盘中的数字键盘

**描述您想要的解决方案**
希望可以指定自定义键盘为数字键盘，在相关场景内调用指定的键盘

**描述您考虑过的替代方案**
无

**其他**
无

**Comment by imfuxiao** [comment]
商店版本新增：defaultNumericKeyboard 参数，默认为 numericNineGrid，即内置数字键盘，您可以将值改为您自己的数字键盘。
