### ISSUE TITLE
「Feature」

### ISSUE THREAD

**Issue by gtnndgit** [imfuxiao/Hamster#604]
**您的功能请求是否与某些问题有关？请描述**
1、中文九宫格布局中，左侧的符号逗号”，“、问号”？“、句号”。“、感叹号”！“和顿号”、“在按键内不居中啊（逼死强迫症），翻了一下午文档也没找到在哪里可以修改这个。
2、还有默认的九宫格布局能不能把键盘布局文件分享下，想在此基础上修改下。看了下目前按键内字体大小还不能调整希望添加下这个功能。
3、工具栏字标移动、中英切换的logo文件可以修改吗？

**Comment by imfuxiao** [comment]
您好，

问题1：不同的字体，全角和半角显示是不同的，如果想要全角符号居中，请保持默认字体样式。
问题2：目前自定义布局不支持跨行功能，所以中文九宫格的布局是内置布局，无法已配置文件的形式导出。
问题3：目前图标都是使用 iOS 内置 SF Symbol ，无法修改。
