### ISSUE TITLE
工具栏各个栏目点击后双击震动

### ISSUE THREAD

**Issue by dyg777** [imfuxiao/Hamster#605]
**Bug的详细描述**
工具栏各个栏目点击后双击震动

**您的预期行为**
简明扼要地描述您期望得到的结果。
![0d9046a838a1694ee171ad55c82a8321](https://github.com/imfuxiao/Hamster/assets/109892355/e0f9c6b6-bdb9-4b81-922e-be89e07b9a0d)

**屏幕截图/视频**
如果可能，请添加截图或视频以帮助解释您的问题。

**设备信息（请填写以下信息）：**
 -  iOS 版本：如 17.5
 -  仓输入法版本： TF 3.0.0（247）

**其他**

在此添加有关该 bug 的任何其他信息。

**Comment by imfuxiao** [comment]
商店版本 2.5.0 / TF 3.0.0(251) 已修复此问题。
