### ISSUE TITLE
商店版仓输入法2.5.0版本，文本换行的情况下全选有BUG

### ISSUE THREAD

**Issue by LokChunYu** [imfuxiao/Hamster#606]
**Bug的详细描述**
文本输入后，在换行的情况下，#全选 的快捷方式会遗漏首一到两个字，并且把前面的文本顶乱。如视频。

**Bug 的复现过程**
重现此 Bug 的步骤：
**屏幕截图/视频**
https://github.com/imfuxiao/Hamster/assets/18650603/8416eaad-b6ad-4834-b136-c4eaefa84d5f

**设备信息（请填写以下信息）：**
 -  iOS 版本：如 17.4.1，iPhone12 max pro
 -  仓输入法版本：商店版 2.5.0

**Comment by imfuxiao** [comment]
iOS 系统中并未提供 `全选` 相关 api，目前使用的 api 只能获取文本光标前后的**有限**文字，且是部分文字，如果存在英文句号、换行等情况，系统的 api 也会截断。所以此问题非 bug。

感谢您的反馈。

**Comment by LokChunYu** [comment]
感谢大佬回答。辛苦！
