### ISSUE TITLE
「Feature」期待工具栏的符号有所区别和变化

### ISSUE THREAD

**Issue by LokChunYu** [imfuxiao/Hamster#607]
![iShot_2024-04-22_17 19 42](https://github.com/imfuxiao/Hamster/assets/18650603/8ab81f0b-988b-4087-8114-d8c43fed8385)
工具栏符号现在已经有点击颜色变化，但是不明显。希望对工具栏的符号在切换状态下有所区别，特别是“中英文切换”和“简繁切换”这两个需求，比如
1、“中英文切换”在中文状态下，无底色，切换英文状态下有底色，并且符号由“字”变成“A”；
2、“简繁切换”在简体状态下，无底色，切换繁体状态下有底色。

**Comment by imfuxiao** [comment]
TF 3.0.0 （262）已优化，商店下个版本发布

**Comment by LokChunYu** [comment]
非常感谢大佬的辛苦！

**Comment by imfuxiao** [comment]
商店版本已发布，如有问题，请可以重新打开。
