### ISSUE TITLE
「Bug」雾凇拼音无法使用中文9键，历史issue里的解决方案都无效

### ISSUE THREAD

**Issue by chsenc** [imfuxiao/Hamster#608]
**Bug的详细描述**
雾凇拼音无法使用中文9键

**Bug 的复现过程**
下午在商店里下载了2.4版本，打开输入法方案中没有雾凇拼音九宫格方案，只有雾凇拼音和仓九宫格方案，默认的雾凇拼音方案使用拼音9键只能输入数字，使用仓九宫格方案也无效，重置rime，卸载软件重新下载都没用。

**您的预期行为**
在雾凇拼音方案下使用中文9键

**屏幕截图/视频**
如果可能，请添加截图或视频以帮助解释您的问题。

**设备信息（请填写以下信息）：**
 -  iOS 版本：17.4.1
 -  仓输入法版本：商店版 2.4.1 /2.5.0
![9e6cfbb10a9cc7e448dae42ea0d3a4b](https://github.com/imfuxiao/Hamster/assets/62168575/3c058541-0a3f-49c7-b266-52f9d92bf0d2)
![9ed018b5be91ea3f32137ec622941a3](https://github.com/imfuxiao/Hamster/assets/62168575/5297a382-ad67-4ce7-be97-5a7b036683d7)

**其他**

在此添加有关该 bug 的任何其他信息。

**Comment by imfuxiao** [comment]
这个不是bug，雾凇拼音对应26键布局，九宫格布局请选择「仓·九宫格」
