### ISSUE TITLE
「Bug」使用顶字上屏功能时（四码定长方案），开启内嵌模式，第五个编码无法显示，需要输入第六个编码才能显示新的编码

### ISSUE THREAD

**Issue by Jmdayou** [imfuxiao/Hamster#610]
**Bug的详细描述**
使用顶字上屏功能时（四码定长方案），开启内嵌模式，第五个编码无法显示，需要输入第六个编码才能显示新的编码
实际测试，关闭内嵌模式也是同样的效果

**Bug 的复现过程**
我要连续输入两个「测试」（编码kosp），正常情况下我输入kosp，再输入下一个字母k时，会将测试两字上屏，编码区会变成k。
当前版本，只输入一个字母k时，测试两字会上屏，但字母k无法显示，继续输入o时，显示出ko

**您的预期行为**
希望顶字时，可以正常显示出顶字后的第一个字母

**屏幕截图/视频**
顶字上屏后，要输入ko才显示编码，只输入k时不显示（即第五码不显示）
<img width="414" alt="image" src="https://github.com/imfuxiao/Hamster/assets/130811752/8bce710d-6394-4ef8-b984-33a5f9ab68f2">

**设备信息（请填写以下信息）：**
 -  iOS 版本：如 17.5
 -  仓输入法版本：TF 3.0.0（251）

**其他**

在此添加有关该 bug 的任何其他信息。

**Comment by imfuxiao** [comment]
麻烦提供下您测试的方案

**Comment by Jmdayou** [comment]
[tiger.zip](https://github.com/imfuxiao/Hamster/files/15064335/tiger.zip)
选择虎码官方词库，「测试」的编码是kosp

**Comment by imfuxiao** [comment]
您好，刚发布了 TF 253 版本，麻烦看看是否已修复。

**Comment by Jmdayou** [comment]
测试了一下，仍然是一样的问题，候选栏可以显示候选，但编码无法显示。
<img width="414" alt="image" src="https://github.com/imfuxiao/Hamster/assets/130811752/8a2e026a-643a-4b5b-88e0-e6b0fd1044b6">

**Comment by imfuxiao** [comment]
你是不是开启内嵌模式了？

**Comment by Jmdayou** [comment]
关了内嵌，试了一下。非内嵌模式下是正常的，开启之后就和上面一样无法正常显示编码了，感谢。

**Comment by Jmdayou** [comment]
256已正常，大佬神速，感谢！
