### ISSUE TITLE
「Bug」2.5.0商店版本一定概率丢失上下划符号

### ISSUE THREAD

**Issue by chca2** [imfuxiao/Hamster#611]
**Bug的详细描述**
2.5.0商店版本一定概率丢失上下划符号

**Bug 的复现过程**
呼出键盘时候，如果重新部署（使用的hamster.yaml）则正常。

**您的预期行为**
希望修复

**屏幕截图/视频**
无

**设备信息（请填写以下信息）：**
 -  iOS 版本：17.4.1
 -  仓输入法版本：商店版 2.5.0

**其他**

在此添加有关该 bug 的任何其他信息。

**Comment by imfuxiao** [comment]
您好，麻烦使用 TF 256 版本测试，看是否已经修复。

**Comment by chca2** [comment]
> 您好，麻烦使用 TF 256 版本测试，看是否已经修复。

OK，目前测试没有复现了，明天再试试没问题我就关闭此issue。
