### ISSUE TITLE
「Bug」状态栏中的工具栏消失

### ISSUE THREAD

**Issue by dyg777** [imfuxiao/Hamster#612]
**Bug的详细描述**
状态栏中的工具栏消失

**Bug 的复现过程**
重现此 Bug 的步骤：

https://github.com/imfuxiao/Hamster/assets/109892355/dc5ca760-da07-4256-821e-32661be83e20

**屏幕截图/视频**
如果可能，请添加截图或视频以帮助解释您的问题。

**设备信息（请填写以下信息）：**
 -  iOS 版本：如 17.5
 -  仓输入法版本： TF 3.0.0（253）

**Comment by imfuxiao** [comment]
麻烦使用 TF 256 版本测试，看是否已经修复次问题。

**Comment by dyg777** [comment]
已修复，感谢
