### ISSUE TITLE
「Bug」切换大写模式后，上下划动字符丢失

### ISSUE THREAD

**Issue by Jason0asdjia** [imfuxiao/Hamster#613]
**Bug的详细描述**
如题

**屏幕截图/视频**
![image](https://github.com/imfuxiao/Hamster/assets/24503086/0af281da-0384-4c97-bc3e-247b86a75fd0)

![image](https://github.com/imfuxiao/Hamster/assets/24503086/70077837-6d8c-4854-b24f-f0990bc78502)

**设备信息（请填写以下信息）：**
 -  iOS 版本：17.3
 -  仓输入法版本：商店版 2.5.0

**Comment by cv2wx** [comment]
更新后同样有该问题，必须通过切换输入法的方式解决。

**Comment by cv2wx** [comment]
补充：不切换大写字母模式也有可能随机触发，表现为在小写字母界面下仍然无法使用划动输入。
![screenshot](https://github.com/imfuxiao/Hamster/assets/69333371/4169bd86-6f67-4ce7-b5f2-b2f836954558)

**Comment by imfuxiao** [comment]
TF 3.0.0 （262）已优化，商店下个版本发布

**Comment by cv2wx** [comment]
> TF 3.0.0 （262）已优化，商店下个版本发布

感谢！请问何时能够更新😂

**Comment by imfuxiao** [comment]
快了，临上线前，群里测试发现有个bug，等bug处理完会发布一版。

**Comment by cv2wx** [comment]
> 快了，临上线前，群里测试发现有个bug，等bug处理完会发布一版。

辛苦了！

**Comment by imfuxiao** [comment]
商店版本已发布，此 Bug 已修复，如有问题，请可以重新打开。

**Comment by cv2wx** [comment]
经测试无法复现
再次感谢
