### ISSUE TITLE
「Bug」不能记忆单手键盘设置

### ISSUE THREAD

**Issue by cj233cj** [imfuxiao/Hamster#614]
**Bug的详细描述**
此前在自定义键盘中定义了“M右滑”切换为右侧单手键盘，切换过一次后再次呼出输入法会保持上次单手键盘状态，2.51（1）版本升级后不同app间或者不同输入法间呼出会重置为全屏键盘，需要再次手动切换

**您的预期行为**
呼出键盘时保持上次状态

**屏幕截图/视频**
略

**设备信息（请填写以下信息）：**
 -  iOS 版本： 17.3
 -  仓输入法版本：商店版 2.51（20240423升级）

**Comment by imfuxiao** [comment]
TF 3.0.0 （262）已优化，商店下个版本发布

**Comment by imfuxiao** [comment]
商店版本已发布，此 Bug 已修复，如有问题，请可以重新打开。
