### ISSUE TITLE
九宫格键盘布局自定义长按滑动不生效

### ISSUE THREAD

**Issue by 1wingedangel** [imfuxiao/Hamster#615]
**Bug的详细描述**
按照说明文档写了 `hamster.custom.yaml` 重新部署之后，依然无法在九宫格键盘布局进行自定义的长按和滑动操作。

**Bug 的复现过程**
重现此 Bug 的步骤：
1. 把说明文档中的代码贴到 hamster.custom.yaml 并上传到应用的 RIME 文件夹。
2. 重新部署
3. 切换输入方案为雾凇拼音九宫格、键盘布局为中文九宫格
4. 对 space 进行上滑操作，没有效果；对1进行长按操作，没有效果。

**您的预期行为**
自定义的长按和滑动操作生效

**设备信息（请填写以下信息）：**
 -  iOS 版本：如 17.4.1
 -  仓输入法版本：TF 3.0.0（256）

**其他**

使用的 hamster.custom.yaml 文件 [hamster.custom.zip](https://github.com/imfuxiao/Hamster/files/15088611/hamster.custom.zip)

另外我也发现键盘文件中 build/hamster.yaml 里有反映 patch 的信息，至少说明这个hamster.custom.yaml 是已经应用上去了的。

**Comment by imfuxiao** [comment]
您好，我这里按您的配置文件测试是正常的。以下是测试截屏，您的配置文件只配置了 “@/.” 键的长按。


https://github.com/imfuxiao/Hamster/assets/6482586/83ca57e6-0539-40ea-a61a-0ebc6c13f7f8


如果您还是无法正常使用，建议先重置，然后在将您的配置文件放到 Rime 目录下，然后重新部署看看。

**Comment by 1wingedangel** [comment]
尝试重置了一下仓输入法，果然就能正常反映了。但是有些界面配置不想再花时间折腾，我还是研究一下怎么把其他配置写到 `hamster.custom.yaml` 里去吧。感谢开发者的回答。
