### ISSUE TITLE
「Bug」无法成功部署凇鹤拼音方案

### ISSUE THREAD

**Issue by suibianzai** [imfuxiao/Hamster#616]
**Bug的详细描述**
开发者好，最近刚入坑，配置上遇到了问题：
有一个在雾凇拼音基础上增加了小鹤拼音的方案，叫[凇鹤拼音](https://github.com/kchen0x/rime-crane)，我把这个方案的文件下载下来后，按照说明，先把rime文件夹清空，然后导入除others和read me以外的所有文件，点重新部署，app提示“未能读取数据，因为它的格式不正确”见下图

**您的预期行为**
请问是我哪一步操作有问题？还是其他的原因？。

**屏幕截图/视频**
![IMG_16D7AB92376B-1](https://github.com/imfuxiao/Hamster/assets/42022663/e4451ad4-fd79-453d-857b-987c8b583019)

**设备信息（请填写以下信息）：**
 -  iOS 版本：如 15.4.1
 -  仓输入法版本：商店版 2.5.1(1)

**Comment by imfuxiao** [comment]
请提供您的部署包，即 Rime 目录下的文件。

**Comment by imfuxiao** [comment]
您好，我看了你上面说的方案[凇鹤拼音](https://github.com/kchen0x/rime-crane)。

发现这个方案中含有 `hamster.yaml` 文件，此文件是「仓输入法」使用的配置文件，而这个文件中的配置语法是「仓」历史版本中的配置语法，与目前版本是不兼容的。所以会报错。

建议您删除`hamster.yaml`。

**Comment by suibianzai** [comment]
> 您好，我看了你上面说的方案[凇鹤拼音](https://github.com/kchen0x/rime-crane)。
> 
> 发现这个方案中含有 `hamster.yaml` 文件，此文件是「仓输入法」使用的配置文件，而这个文件中的配置语法是「仓」历史版本中的配置语法，与目前版本是不兼容的。所以会报错。
> 
> 建议您删除`hamster.yaml`。

删除hamster.yaml之后就成功了，感谢~🙏🏻
