### ISSUE TITLE
「Feature」建议单手键盘的切换左右手和恢复全尺寸键盘的按键和键盘之间设置一点死区

### ISSUE THREAD

**Issue by cachalot2000** [imfuxiao/Hamster#618]
我是重度单手使用者。
单手用多了发现经常误触左右手切换和恢复全键盘。

举例：
我是左手键盘，所以切换左右手的按键在字母p的右边。
因为单手，所以p是大拇指能够到的最远距离，这个按键往往在单手按的时候无法非常精确的按到。
于是会超出一些碰到左右手切换键的范围，于是键盘切换成了右手键盘。
在我的使用场景下这个误触还是非常频繁的。基本每天都要按到3，4次。

另一个场景就是点击发送时候误触到全尺寸键盘按键，键盘恢复成了全尺寸。

可能的解决方法思考：
因为切换左右手键的使用频率其实非常低（一个人设置一次就行了，不知道有没人左右互搏的），恢复全尺寸键盘也不是非常常用的键位，当需要使用的时候也是能接受专门去按一下的。
所以个人认为可以在键盘和左右手键及全尺寸键中间设置个死区，将这两个键位的可触碰区域远离键盘一些，这样就不会在按键超出键盘范围时误触到这两个键位了。
而如果要用到这两个键位，即使是触碰范围很小，因为用到的机会实在不多，双手精确操作也是完全能接受的。

谢谢

**Comment by imfuxiao** [comment]
TF 3.0.0 （262）已优化，商店下个版本发布

**Comment by cachalot2000** [comment]
能给一个tf资格么，上一个3月1过期了。然后遇到单手键盘bug，现在无法正常使用了，据说tf已经修复

**Comment by imfuxiao** [comment]
> 能给一个tf资格么，上一个3月1过期了。然后遇到单手键盘bug，现在无法正常使用了，据说tf已经修复

给我的邮箱发邮件，邮件内容请附上您的 Apple 账号。

**Comment by cachalot2000** [comment]
收到

**Comment by imfuxiao** [comment]
商店版本已发布，如有问题，请可以重新打开。
