### ISSUE TITLE
「Feature」字体粗细跟随系统设置

### ISSUE THREAD

**Issue by KFERMercer** [imfuxiao/Hamster#619]
建议：在未配置使用其他字体的情况下，键盘字体粗细跟随系统设置。

描述：在当前版本中，无论系统字体粗细键盘都为细体，在使用粗体字体的设备上略显违和。

我考虑过的替代方案：配置使用系统自带的其他粗体字体，但是由于与系统字体有差异所以更加违和。

希望您百忙之中可以考虑一下这个建议，谢谢😊

**最后感谢本项目，正是有了您的无私奉献才有了如此好用的输入法🙇‍**

**Comment by imfuxiao** [comment]
TF 3.0.0 （262）已优化，商店下个版本发布

**Comment by KFERMercer** [comment]
兄弟是真的敬业
