### ISSUE TITLE
功能建议，候选栏下拉键

### ISSUE THREAD

**Issue by Ricadre** [imfuxiao/Hamster#62]
![WechatIMG225](https://user-images.githubusercontent.com/3013056/232644585-bef4be44-75aa-4e0d-864a-86e6aa6e4a20.jpeg)
![WechatIMG226](https://user-images.githubusercontent.com/3013056/232644587-4fd2b106-0b8f-4967-8660-2832b408f7f6.jpeg)
可否在候选栏加入下拉键，展开更多候选字。

**Comment by Ricadre** [comment]
另外左下角切换键依然是空白，目前还未尝试卸载重装，候选字的背景框颜色不太突出，可否和原生键盘一样，另外可否实现内嵌编码呢？感谢大佬！

**Comment by imfuxiao** [comment]
非常抱歉, 左下角切换键依然是空白的问题, 我正在处理. 

提议很好, 后续会添加此功能.
