### ISSUE TITLE
「Feature」调整侯选词的界面的排版（字体大小/每页显示数量……）

### ISSUE THREAD

**Issue by suibianzai** [imfuxiao/Hamster#620]
**您的功能请求是否与某些问题有关？请描述**
请问是否能调整侯选词的字体大小/每行显示数量？目前的侯选词太小了，在车上打字，经常因为摇晃看不清楚，对视力也不友好。

**描述您想要的解决方案**
是否可以自定义侯选词排版，比如字号、字词与字词之间的间隔之类的，或者说自定义每页显示的侯选词数量，或者直接改宽敞一点，现在感觉又小又挤。而且作为双拼用户，常用的侯选词就那么几个，不太用得着翻页。

**描述您考虑过的替代方案**
下图第一张是ios自带的双拼侯选词界面，第二张是仓输入法的，可以看到很明显的对比，系统自带的排版更舒服，对眼睛也更友好，至少对我来说😢

**其他**
![IMG_4636](https://github.com/imfuxiao/Hamster/assets/42022663/9d1ed39f-5a85-44bb-acdb-b651ef18776c)![IMG_4635](https://github.com/imfuxiao/Hamster/assets/42022663/053486ea-87b8-4149-bd4a-c72d21ff11d3)

**Comment by imfuxiao** [comment]
TF 3.0.0 （262）已优化，商店下个版本发布

**Comment by suibianzai** [comment]
> TF 3.0.0 （262）已优化，商店下个版本发布

感谢感谢~

**Comment by imfuxiao** [comment]
商店版本已发布，如有问题，请可以重新打开。
