### ISSUE TITLE
「Bug」通过SWITCHER切换中英/繁简状态，工具栏文字不会跟随变动；空格显示option_state失效

### ISSUE THREAD

**Issue by Jmdayou** [imfuxiao/Hamster#621]
**Bug的详细描述**
1、259版本更新了中英/繁简切换工具栏，可以动态显示状态，但如果直接通过SWITCHER切换中英/繁简状态，工具栏文字不会跟随变动。
2、如果通过switcher切换且也点击了中英/繁简状态切换，那么之后通过switcher切换其他选项，如表情开关，空格上显示状态变动会失效（option_State）

**Bug 的复现过程**
使用switcher切换中英/繁简状态

**您的预期行为**
1、工具栏的中英/繁简状态会跟随实际的状态显示，不管是通过工具栏操作或switcher/快捷按键操作
2、空格显示option_state能正常工作

**屏幕截图/视频**
如果可能，请添加截图或视频以帮助解释您的问题。

**设备信息（请填写以下信息）：**
 -  iOS 版本：如 17.5
 -  仓输入法版本：TF259

**其他**

在此添加有关该 bug 的任何其他信息。

**Comment by imfuxiao** [comment]
TF 3.0.0 262 已优化，商店下个版本发布

**Comment by Jmdayou** [comment]
感谢，目前测试了一下，中英/繁简状态已经可以正常切换显示。 
但是空格显示state现在除了中英/繁简状态正常显示之外，表情、输入方案名称等其他状态在切换时无法显示。
复现操作：在任意界面点击一下工具栏的中英或繁简切换，再次通过switcher的方式开关其他状态，此时空格无法显示其他状态的开关。
