### ISSUE TITLE
「Bug」震动功能不起作用

### ISSUE THREAD

**Issue by leenux9527** [imfuxiao/Hamster#622]
**Bug的详细描述**
已开启按键震动，但实际输入时并没有震动

**Bug 的复现过程**
重现此 Bug 的步骤：
1. 按键震动-开、震动强度-强、微调震动强度-1.0、系统完全访问权限-已授权
2. 打开微信，输入任意字符
3. 手机没有任何震动

**您的预期行为**
在输入字符时，手机震动

**屏幕截图/视频**
无

**设备信息（请填写以下信息）：**
 -  iOS 版本：17.3.1
 -  仓输入法版本：商店版 2.5.1(1)

**其他**
无

**Comment by imfuxiao** [comment]
开启震动需要开启键盘的「完全访问权限」，你在震动开关下面，点说明文字处，可以跳转系统设置的地方，试试看。

**Comment by leenux9527** [comment]
我反复确认，设置已经全都打开了，但还是没有震动
<img width="823" alt="image" src="https://github.com/imfuxiao/Hamster/assets/26673510/66b26e90-1f21-4f95-8898-a25ebffffcfe">

**Comment by imfuxiao** [comment]
麻烦提供下您的 iOS 版本，还有手机型号，谢谢。

**Comment by leenux9527** [comment]
iPhone型号：iPhone14 Pro
iOS 版本：17.3.1
仓输入法版本：商店版 2.5.1(1)

**Comment by imfuxiao** [comment]
查看 iOS 系统设置 -> 声音与触感 -> 系统触感反馈 ，需要打开此选项。

**Comment by leenux9527** [comment]
> 查看 iOS 系统设置 -> 声音与触感 -> 系统触感反馈 ，需要打开此选项。

这下正常了，非常感谢
