### ISSUE TITLE
「Bug」TF 270字体设置失效

### ISSUE THREAD

**Issue by Jmdayou** [imfuxiao/Hamster#624]
**Bug的详细描述**
字体设置失效，在自定义字体界面已添加小米生僻字字体，正常情况下生僻字可以显示，但目前无法显示。如：𰻝𰻝面biángbiángmiàn 无法显示

**Bug 的复现过程**

**您的预期行为**
可以正常调用自定义字体显示生僻字

**屏幕截图/视频**
<img width="414" alt="image" src="https://github.com/imfuxiao/Hamster/assets/130811752/bbaa976d-2fff-4df3-b508-6dda718921bf">

**设备信息（请填写以下信息）：**
 -  iOS 版本：17.5
 -  仓输入法版本：TF 270

**其他**

在此添加有关该 bug 的任何其他信息。

**Comment by imfuxiao** [comment]
麻烦提供下字体文件，或者字体文件的下载地址。

**Comment by Jmdayou** [comment]
感谢
