### ISSUE TITLE
「Bug」部分APP无法调出仓输入法

### ISSUE THREAD

**Issue by suibianzai** [imfuxiao/Hamster#625]
**Bug的详细描述**
中信证券的搜索框里面不能使用仓输入法，其他系统自带输入法没有问题。
中信银行、兴业证券的app没有这个问题。不知道是不是中信证券app本身的问题，它这个输入框确实长得有点不一样。

**屏幕截图/视频**
中信证券：
![IMG_4647](https://github.com/imfuxiao/Hamster/assets/42022663/bb237ce8-6784-491d-89aa-191f374e626c)
兴业证券：
![IMG_4648](https://github.com/imfuxiao/Hamster/assets/42022663/f580fd0e-0bda-47fa-9d9a-1abe577e3001)
中信银行：
![IMG_4649](https://github.com/imfuxiao/Hamster/assets/42022663/8d4937e4-e036-49ab-95f8-a44708375186)

**设备信息（请填写以下信息）：**
 -  iOS 版本：如 15.4.1
 -  仓输入法版本：商店版 2.5.1

**Comment by imfuxiao** [comment]
您好，这个不是 bug，iOS 上的应用可以「禁用」第三方输入法。

**Comment by suibianzai** [comment]
> 您好，这个不是 bug，iOS 上的应用可以「禁用」第三方输入法。

了解 谢谢
