### ISSUE TITLE
咨询一下，默认的中文26键，长按弹出的气泡中的符号在哪更改？

### ISSUE THREAD

**Issue by lianyis** [imfuxiao/Hamster#626]
比如，我在划动设置中，将M键的上划改成问号，下划改成斜杠。但是长按M的时候，气泡中除了小写m和大写M外，还有一个默认的省略号，而不是我修改完的问号和斜杠。而QWER这些按键我修改后，长按的气泡中又显示成我修改的符号了。不知是bug，还是我设置的不对？

**Comment by imfuxiao** [comment]
看您的描述，您更改的是上下划动配置，而非长按配置。长按配置可参考 `SharedSupport/hamster-swipe.yaml`配置
