### ISSUE TITLE
當icloud文件不在本地時，會出現文件錯誤

### ISSUE THREAD

**Issue by kit1858644** [imfuxiao/Hamster#628]
當icloud上的文件不在本地，重新部署下載到應用文件裡的文件都是".xxxx.icloud"格式。

需要自行到file上下載文件再按同重新部署

**Comment by Tspm1eca** [comment]
再試了一下，這個問題讓RIME同步和iCloud同步都同步不了

**Comment by imfuxiao** [comment]
TF 280 已优化 iCloud 同步逻辑
