### ISSUE TITLE
「Feature」 期待 label 支持 SF Symbols

### ISSUE THREAD

**Issue by Nicked639** [imfuxiao/Hamster#631]
**您的功能请求是否与某些问题有关？请描述**
简明扼要地描述问题所在。

对于描述快捷指令的 label，目前 emoji 以及字体符号的选择并不多，希望能加入 SF Symbols 的支持，扩展键盘划动字符以及长按后的 label 表现力。

**Comment by imfuxiao** [comment]
商店版本 2.7.0 已支持此功能。
