### ISSUE TITLE
「Feature」为shift分词按键能增加个选项

### ISSUE THREAD

**Issue by chca2** [imfuxiao/Hamster#632]
**您的功能请求是否与某些问题有关？请描述**
测试版的shift分词按键能增加个选项吗，小鹤音形使用的`而不是'

**描述您想要的解决方案**
测试版的shift分词按键能增加个选项吗，小鹤音形使用的`而不是'

**描述您考虑过的替代方案**
简明扼要地描述您考虑过的任何替代解决方案或功能。

**其他**
在此处添加有关功能请求的任何其他上下文或截图或视频等等。

**Comment by imfuxiao** [comment]
您好，Shifft 分词功能就只是分词。比如 「xian」 可以是先的拼音，但是我想打「西安」，就需要分词 「xi'an」。

在小鹤音形中，「`」符号是反查符，非分词符号，您可以将「`」映射到其他按键的上下划动中触发。

**Comment by chca2** [comment]
好的，了解
