### ISSUE TITLE
「Bug」快捷键设置清空后，在主动换行的情形下，清空动作删除不完全

### ISSUE THREAD

**Issue by LokChunYu** [imfuxiao/Hamster#634]
**Bug的详细描述**
快捷键设置清空后，在主动换行的情形下，清空动作删除不完全

**Bug 的复现过程**
重现此 Bug 的步骤：
1、输入文本，如果是自然换行，清空动作可以全部删除；
2、输入文本，如果是主动换行，清空动作总会留几个字删除不了，删除不完全。
（请见视频）

**屏幕截图/视频**

https://github.com/imfuxiao/Hamster/assets/18650603/a5c49858-648d-43c2-b85d-ecadf3732726

**设备信息（请填写以下信息）：**
 -  iOS 版本：如 17.4.1
 -  仓输入法版本：商店版 2.5.1

**Comment by imfuxiao** [comment]
您好，这是因为 iOS 键盘相关 API 的问题。系统对于「换行」等符号会做分隔，导致拿不到全部的上下文。

此问题与「全选」在「换行」存在的情况下，无法完全选中是一样的。

暂时无解。

**Comment by LokChunYu** [comment]
谢谢老大回复，果然和「全选」问题一样，系统限制🤣

**Comment by imfuxiao** [comment]
也不算是系统限制吧，系统目前提供给第三方使用的的键盘相关功能接口，功能不多，也不够完全，目前只能这样凑合。
