### ISSUE TITLE
输入首个字母，候选框不显示文字

### ISSUE THREAD

**Issue by hkzcz** [imfuxiao/Hamster#636]
**Bug的详细描述**
首次输入不能显示，第一键第一个字母的候选字。

**Bug 的复现过程**
重现此 Bug 的步骤：
1. 首次启动键盘输入第一个字母时
2. 第一个字母的编码不能显示，但按空格可以上屏首选。

**您的预期行为**
简明扼要地描述您期望得到的结果。

**屏幕截图/视频**
如果可能，请添加截图或视频以帮助解释您的问题。

**设备信息（请填写以下信息）：**
 -  iOS 版本：如 17.4.1
 -  仓输入法版本：商店版 2.6.0 和 TF 3.0.0（277）都有这个问题。

**其他**

在此添加有关该 bug 的任何其他信息。

**Comment by imfuxiao** [comment]
方便的话，用「仓」内置的备份功能，打一个备份包，然后发给我。

**Comment by imfuxiao** [comment]
已确认此 Bug，TF 下个版本会修复。
