### ISSUE TITLE
「Feature」可自定义长按按键的反应

### ISSUE THREAD

**Issue by Jiang10086** [imfuxiao/Hamster#637]
**您的功能请求是否与某些问题有关？请描述**
现在好像无法自定义长按字母出现的字符，想能够自定义。比如说默认状态下长按「k」可以得到「“」，但是有时候想打单引号，要去符号表里翻有些不方便。这点iOS默认键盘就做得很好

**描述您想要的解决方案**
自定义长按操作

**描述您考虑过的替代方案**
简明扼要地描述您考虑过的任何替代解决方案或功能。

**其他**
在此处添加有关功能请求的任何其他上下文或截图或视频等等。

**Comment by Jiang10086** [comment]
还有个应用场景是长按打出带声调的字母

**Comment by wxmbaci** [comment]
长按是可以配置的，文档上有.
````
callout:
- action: { shortcutCommand: "#上个输入方案" }
````
可以通过 hamster.custom.yaml 进行配置。
[CustomKeyboard](https://ihsiao.com/apps/hamster/docs/CustomKeyboard.html#key-%E6%A8%A1%E5%9E%8B)

**Comment by Jiang10086** [comment]
> 长按是可以配置的，文档上有.
> 
> ```
> callout:
> - action: { shortcutCommand: "#上个输入方案" }
> ```
> 
> 可以通过 hamster.custom.yaml 进行配置。 [CustomKeyboard](https://ihsiao.com/apps/hamster/docs/CustomKeyboard.html#key-%E6%A8%A1%E5%9E%8B)

谢谢你，我会尝试的
