### ISSUE TITLE
「Feature」上划/下划输入支持英文

### ISSUE THREAD

**Issue by Jiang10086** [imfuxiao/Hamster#638]
**您的功能请求是否与某些问题有关？请描述**
比如，默认状态下能通过上划「N」键快捷输入「！」字符，但是英文状态下无法这样做

**描述您想要的解决方案**
英文也能上划输入符号，而不仅仅是数字

**描述您考虑过的替代方案**
简明扼要地描述您考虑过的任何替代解决方案或功能。

**其他**
在此处添加有关功能请求的任何其他上下文或截图或视频等等。

**Comment by imfuxiao** [comment]
英文键盘下可以自定义设置划动符号。请参考设置文档：[内置英文键盘如何自定义按键划动与长按](https://ihsiao.com/apps/hamster/docs/Questions.html#%E5%86%85%E7%BD%AE%E8%8B%B1%E6%96%87%E9%94%AE%E7%9B%98%E5%A6%82%E4%BD%95%E8%87%AA%E5%AE%9A%E4%B9%89%E6%8C%89%E9%94%AE%E5%88%92%E5%8A%A8%E4%B8%8E%E9%95%BF%E6%8C%89)
