### ISSUE TITLE
「Bug」使用了小鹤双拼，部分侯选字会出现缺失的情况，仅显示一个框框里面带有问号。

### ISSUE THREAD

**Issue by J02Octo** [imfuxiao/Hamster#639]
**Bug的详细描述**
简明扼要地描述这个 Bug 是什么，如

**Bug 的复现过程**
重现此 Bug 的步骤：
1. 打开 '...'
2. 点击 '....'
3. 看到 ... 异常。

**您的预期行为**
简明扼要地描述您期望得到的结果。

**屏幕截图/视频**
如果可能，请添加截图或视频以帮助解释您的问题。

**设备信息（请填写以下信息）：**
 -  iOS 版本：如 17.0.3
 -  仓输入法版本：商店版 2.4.1 或 TF 3.0.0（122）

**其他**

在此添加有关该 bug 的任何其他信息。

**Comment by xubai2001** [comment]
苹果系统字体不支持，可以在仓的字体设置中添加一个支持较大字集的字体，不过也只能在输入法上看看
