### ISSUE TITLE
「Bug」重新部署后无法正常打出拼音

### ISSUE THREAD

**Issue by Kosette** [imfuxiao/Hamster#641]
**Bug的详细描述**
同步更新了雾凇拼音的最新文件，重新部署后无法正常打出拼音，且重置无效，具体表现见图片。

**Bug 的复现过程**
重现此 Bug 的步骤：
偶发bug，未能复现。卸载重装后恢复正常。

**您的预期行为**
正常拼写

**屏幕截图/视频**
![image](https://github.com/imfuxiao/Hamster/assets/35268640/3726d38f-bbe7-4366-af81-071fa7f86e31)

**设备信息（请填写以下信息）：**
 -  17.4.1
 -  仓输入法版本：商店版 1.11.2

**其他**

**Comment by imfuxiao** [comment]
> 仓输入法版本：商店版 1.11.2

**Comment by imfuxiao** [comment]
我这边测试内置的雾凇是正常的。

----

商店版本升级会比较 SharedSupport 文件夹下 的相关配置，如果你对此文件夹下的文件作了调整，是会被覆盖的。

**Comment by imfuxiao** [comment]
应该是您的配置文件的问题，而非雾凇的问题。

----
「将来可能支持更方便的导入导出点划设置吗？」

如果你是用内置设置功能调整的划动配置，那么在「关于」中有一个「导出界面设置」，导出后可以搭配 hamster.custom.yaml 文件使用。

如果你是通过自定义配置文件调整划动配置，那么你直接备份你的配置文件就可以了。
