### ISSUE TITLE
仓输入法下部署雾凇，custom_phrase自定义词库好像无效

### ISSUE THREAD

**Issue by ccharname** [imfuxiao/Hamster#642]
每次修改custom_phrase文件，部署后恢复成原样，请问什么原因

**Comment by ccharname** [comment]
对于26键有效，部署后custom_phrase文件的修改能够保持并生效。看来是九宫格的问题。

**Comment by ccharname** [comment]
custom_phrase在九宫格键盘无效

**Comment by imfuxiao** [comment]
> custom_phrase在九宫格键盘无效

雾凇九宫格方案用的是：[# 自定义短语：custom_phrase_t9.txt](https://github.com/iDvel/rime-ice/blob/98d18b74df12e9995be2942ad518cd340e1b33e8/t9.schema.yaml#L63)

**Comment by ccharname** [comment]
感谢回复，我试试

**Comment by ccharname** [comment]
> > custom_phrase在九宫格键盘无效
> 
> 雾凇九宫格方案用的是：[# 自定义短语：custom_phrase_t9.txt](https://github.com/iDvel/rime-ice/blob/98d18b74df12e9995be2942ad518cd340e1b33e8/t9.schema.yaml#L63)

确认custom_phrase_t9.txt有效。但还有一点问题，t9自定义短语触发的条件可能是跟26键不太一样，比如：ppp三个字母自定义了一个短语，26键是直接按三次P键后触发短语；t9按三次（PQRS）键，形成的字母也是ppp，但是不会触发短语。可能是因为t9按三次（PQRS）键，第一次按是s，第二次按是pp，第三次按是ppp。我不知道说清楚了没有。

**Comment by imfuxiao** [comment]
九键的方案的原理是键盘发送的数字，由 RIME 将数字还原成拼音，然后与方案的码表进行匹配。

比如：你按键盘的 `ABC` 键，是发送 1 到 rime 中，rime在根据方案中的转换规则在转换为字母（a/b/c 模糊匹配），然后匹配方案的码表。

按你例子，按三次 `PQRS` 键，是发送了三次 7 到 rime 中。你看雾凇 [t9.schema.yaml](https://github.com/iDvel/rime-ice/blob/d934ea14097f14d88e17690152f5d9c286b68747/t9.schema.yaml#L89) 中转换规则，是穷举了所有拼音的组合，而三个 7 并没有与之对应的拼音转换规则，所以输入的三个 7 还是三个 7，于是无法匹配你在 `custom_phrase_t9.txt` 设置的短语。

方法1: 修改你的 custom_phrase_t9.txt 中的词库，将编码对应为正确的拼音，或者无效的数字，比如三个 777。

方法2: 调整  [t9.schema.yaml](https://github.com/iDvel/rime-ice/blob/d934ea14097f14d88e17690152f5d9c286b68747/t9.schema.yaml#L89)  中的转换策略，此方法我没有测试过，理论是可行的。

**Comment by ccharname** [comment]
谢谢，说的非常详细了
