### ISSUE TITLE
「Feature」允许修改英文键盘布局

### ISSUE THREAD

**Issue by 0xFFFFFA** [imfuxiao/Hamster#643]
**您的功能请求是否与某些问题有关？请描述**
某些键盘左下切换到英文键盘后需要在右下角切回中文键盘，容易误触

**描述您想要的解决方案**
允许调整英文键盘布局

**描述您考虑过的替代方案**
右侧切换键盘，需要适应

**其他**
在此处添加有关功能请求的任何其他上下文或截图或视频等等。

**Comment by imfuxiao** [comment]
内置英文布局可以自定义划动和长按，其他不能自定义。

可以参考文档：[内置英文键盘如何自定义按键划动与长按](https://ihsiao.com/apps/hamster/docs/Questions.html#%E5%86%85%E7%BD%AE%E8%8B%B1%E6%96%87%E9%94%AE%E7%9B%98%E5%A6%82%E4%BD%95%E8%87%AA%E5%AE%9A%E4%B9%89%E6%8C%89%E9%94%AE%E5%88%92%E5%8A%A8%E4%B8%8E%E9%95%BF%E6%8C%89)
