### ISSUE TITLE
「Feature」为librime添加插件librime-charcode

### ISSUE THREAD

**Issue by thelastlin** [imfuxiao/Hamster#647]
**概述**
部分输入方案需要使用 [rime/librime-charcode](https://github.com/rime/librime-charcode) 过滤字符编码。
当前版本中的librime中的`charset_filter`仅作为占位实现，无法指定过滤字符编码。

ref:
https://github.com/rime/librime/blob/6b1b41f53cd7fb8cd605c65cfb1e8d5c780f1308/src/rime/gear/charset_filter.cc#L107C20-L107C76

**解决方案**
在编译librime时添加插件[rime/librime-charcode](https://github.com/rime/librime-charcode) 。
这一插件直接依赖于 `Boost::locale`。

**Comment by imfuxiao** [comment]
之前尝试增加过这个插件，但是增加后会导致编译的体积增大不少，所以不打算支持此插件。

见：https://github.com/imfuxiao/LibrimeKit/issues/3
