### ISSUE TITLE
输入过的词无记录和频次调整，例如个人姓名反复输入也无法出现在候选框

### ISSUE THREAD

**Issue by dqylyln** [imfuxiao/Hamster#649]
**Bug的详细描述**
输入过的词不会记录和频词调整，常用词语反复输入都无法直接出现在候选栏，只能一个一个字来选字组词。曾经以为是个人配置文件问题，尝试重置软件所有配置，用软件默认输入方案配置也是同样问题，即便开启了多端设备同步，也确保了rime_ice.userdb.txt 文件中有常用词，但是还是无法出现在候选栏。感觉像是设备同步后，APP 获取rime_ice.userdb.txt文件后没有应用一样。

**Bug 的复现过程**
1.反复输入个人常用词，无法进入候选栏，每次都要一个一个字选。
2.开启设备同步mac 和win 都可以同步userdb.txt文件，并且将userdb.txt 里的词快速匹配出现在候选栏，但是唯独ios 设备不行。尝试确认icloud app 同步目录的userdb.txt 中有对应的词语。

**您的预期行为**
希望能更mac 和win  的输入法一样，对于反复输入的个人词语会记录，快速出现在候选栏中，并且能修复多设备同步词库文件没有应用的went

**屏幕截图/视频**

**设备信息（请填写以下信息）：**
 -  iOS 版本：17.5.1
 -  仓输入法版本：商店版本 1.11.2

**其他**
设备型号: iphone 12 pm
输入发方案: 雾凇拼音

**Comment by imfuxiao** [comment]
检查键盘的「完全访问权限」是否开启，不开启键盘没有写权限，无法记录词频。

**Comment by dqylyln** [comment]
感谢！，果然是这个低级问题， 刚开启了完全访问，已经可以记录输入过的频词了。
另外还有个疑问，就算没有开启「完全访问权限] 键盘无法记录频次，但是对应词语已经通过mac 平台同步好，并且确保出现在icloud 中Hamster对应同步的文件userdb.txt 中，但是为什么 Hamsterapp 没有去使用呢？

**Comment by imfuxiao** [comment]
检查 RIME 下的「部署时覆盖词库文件」选项，是否没有关闭，多平台同步需要关闭此选项。

**Comment by dqylyln** [comment]
> 检查 RIME 下的「部署时覆盖词库文件」选项，是否没有关闭，多平台同步需要关闭此选项。

感谢，问题都解决了，有点傻没有第一时间去找close 的issues ，直接重新提了个issues，建议把这些常见问题，增加到APP的注意事项里，代码仓库reademe 里也可以加下。

**Comment by dqylyln** [comment]
其实APP 的键盘设置里，可以增加一个选项，记录输入频词的开关，点击直接跳转对应的ios设置中的 「完全访问权限」，引导用户打开。
