### ISSUE TITLE
「Feature」工具栏上面能否增加快速粘贴剪贴板内容的快捷操作

### ISSUE THREAD

**Issue by zeroskylian** [imfuxiao/Hamster#652]
这两天用这很不错，已购入 pro 版本。希望能增加更多便捷操作，比如工具栏上面快速粘贴剪贴板内容

**Comment by zeroskylian** [comment]
同时反馈个问题工具栏上面的中英文切换和键盘上面的中英文切换不同步，而且状态栏上面的按钮如果设置为英文，键盘上的的中英文切换按钮就无效了

**Comment by imfuxiao** [comment]
> 同时反馈个问题工具栏上面的中英文切换和键盘上面的中英文切换不同步，而且状态栏上面的按钮如果设置为英文，键盘上的的中英文切换按钮就无效了

键盘中的中英是切换键盘，而工具栏上的中英是切换 RIME 的中英状态。两个是不一样的。

有的使用场景中，可能不需要切换键盘，比如：本身就是中文26键，那么只需要切换 RIME 的「中英」状态即可。

但有些场景是需要切换键盘的，比如：中文九键下想输入英文，就需要切换键盘。

所以您可以根据自己的使用场景来定。如果不需要切换键盘，可以把键盘按键的中英键关闭掉，只保留工具栏上的中英切换。

----

剪贴板功能以在规划中，后面版本迭代会开发的。

**Comment by zeroskylian** [comment]
> > 同时反馈个问题工具栏上面的中英文切换和键盘上面的中英文切换不同步，而且状态栏上面的按钮如果设置为英文，键盘上的的中英文切换按钮就无效了
> 
> 键盘中的中英是切换键盘，而工具栏上的中英是切换 RIME 的中英状态。两个是不一样的。
> 
> 有的使用场景中，可能不需要切换键盘，比如：本身就是中文26键，那么只需要切换 RIME 的「中英」状态即可。
> 
> 但有些场景是需要切换键盘的，比如：中文九键下想输入英文，就需要切换键盘。
> 
> 所以您可以根据自己的使用场景来定。如果不需要切换键盘，可以把键盘按键的中英键关闭掉，只保留工具栏上的中英切换。
> 
> 剪贴板功能以在规划中，后面版本迭代会开发的。

哦哦，谢谢回答，了解了。还有能问下能改键盘上面字母的字重吗，我看了下文档只有设置字体大小

**Comment by imfuxiao** [comment]
字重可以通过字体来处理，默认键盘使用的 light 字体，可以通过自定义字体功能，设置为 blod 字体等等。

**Comment by zeroskylian** [comment]
多谢！
