### ISSUE TITLE
「Bug」一进入app就无限处于部署中的状态

### ISSUE THREAD

**Issue by qhjia** [imfuxiao/Hamster#653]
**Bug的详细描述**
一进入app，就显示“RIME部署中，请稍候……”，无限转圈，没有办法进行任何操作，杀掉app重开也没用，没法详细判断具体是由什么原因导致的，但是输入法还是可以正常使用的，最近两个多月没进过app，推测可能有什么配置文件在更新后不兼容导致不能正常部署。

**期望的效果**
在没法正常部署的情况下停止部署，而不是卡住

**屏幕截图**
![IMG_0637](https://github.com/imfuxiao/Hamster/assets/75422228/4585d272-7cac-4bc5-8b09-f13a68a2613e)

**设备信息：**
 -  iOS 版本：17.5.1
 -  仓输入法版本：商店版 2.6.1(1)

**Comment by imfuxiao** [comment]
您好，新版在重新部署时，如开启「iCloud」选项，会强制同步本地与服务端文件。如果您的网络出现了问题，可能会导致此问题。

解决方案：

1. 检测网络，是否与苹果 iCloud 服务通信正常。
2. 使用内置 Files 文件，检测 iCloud 文件夹下的「Hamster」文件夹，是否存在未下载文件，如果存在，请自己手工下载。
3. 以上两种如无法解决，先将 iCloud 下 「Hamster」文件夹备份，备份后删除。然后在打开「仓」

**Comment by qhjia** [comment]
谢谢，手动下载后正常了

**Comment by imfuxiao** [comment]
商店版本 2.7.0 修复。
