### ISSUE TITLE
「Bug」iPadOS running iOS app

### ISSUE THREAD

**Issue by iphoting** [imfuxiao/Hamster#655]
**Bug的详细描述**
Please refer to screenshot: 
![image](https://github.com/imfuxiao/Hamster/assets/109854/4dabf1f3-4090-473f-a98b-5c90c224f873)

**您的预期行为**
The spacing between keys should be smaller, more similar to stock keyboard. 

**设备信息（请填写以下信息）：**
 -  iPadOS 版本：如 17.5.1
 -  仓输入法版本：商店版 2.6.1

**Comment by imfuxiao** [comment]
商店版本 2.7.0 对 iPad 键盘做了优化。
