### ISSUE TITLE
「Bug」使用五笔・拼音输入法无法保存自造词

### ISSUE THREAD

**Issue by dallaslu** [imfuxiao/Hamster#657]
**Bug的详细描述**
使用五笔・拼音输入法时，例如键入 rvyomqswb，候选词「热风枪」后有太极图标。但再次键入 rmsw 后，并没有「热风枪」候选。

**Bug 的复现过程**
根据 https://dallas.lu/using-wubi-pinyin-in-hamster/ 中描述的步骤，添加了输入法方案。具体配置文件见 https://github.com/dallaslu/rime-wubi-pinyin

**您的预期行为**
自造词能够保存。

**设备信息（请填写以下信息）：**
 -  iOS 版本：17.3
 -  仓输入法版本：商店版 1.11.2

**Comment by imfuxiao** [comment]
您好，请检查键盘是否开启了「完全访问」权限。

**Comment by dallaslu** [comment]
在系统设置中，打开 仓输入法->键盘->完全访问 的开关后，问题解决。
