### ISSUE TITLE
输入文字出现重复

### ISSUE THREAD

**Issue by a-w-1806** [imfuxiao/Hamster#658]
**Bug的详细描述**
在偶尔情况下，输入会出现重复情况。例如，输入“一二”会导致“一二一二”进入文本框。

**Bug 的复现过程**
目前不清楚如何复现。

**您的预期行为**
不再重复

**屏幕截图/视频**

**设备信息（请填写以下信息）：**
 -  iOS 版本：如 17.5.1
 -  仓输入法版本：商店版 2.6.1

**其他**

方案为小鹤双拼

**Comment by imfuxiao** [comment]
感谢您的反馈，此问题已在 TF 版本中修复，商店版本需在等等。

**Comment by imfuxiao** [comment]
商店版本已发布 2.7.0 版本。
