### ISSUE TITLE
「Bug」仓九宫在输入的过程中，按发送键上屏的是数字，期望是拼音

### ISSUE THREAD

**Issue by wxmbaci** [imfuxiao/Hamster#659]
**Bug的详细描述**
仓九宫在输入的过程中，不选候选词的情况，按发送键上屏的是数字，期望是拼音

**Bug 的复现过程**
重现此 Bug 的步骤：
1. 打开需要输入的场景
2. 按键输入，不选候选词，点击发送/换行
3. 看到  上屏的是数字，不是候选的拼音

**您的预期行为**
期望可以增加配置选项，按换行的时候，出候选词、或者拼音。

**屏幕截图/视频**

https://github.com/imfuxiao/Hamster/assets/16020511/9721b5af-fbc4-4b0c-9d3e-b13ce5c29c8a

**设备信息（请填写以下信息）：**
 -  iOS 版本： 17.5.1
 -  仓输入法版本：商店版 2.6.1(1) 

**其他**

在此添加有关该 bug 的任何其他信息。

**Comment by imfuxiao** [comment]
您好，我这边测试是正常的。

测试使用字体为 v1.330 版本中 LXGWWenKai-Bold.ttf， 下载地址：https://github.com/lxgw/LxgwWenKai/releases/tag/v1.330


测试视频如下：


https://github.com/imfuxiao/Hamster/assets/6482586/9fdd0e44-33a9-4027-97e5-6a86096a1290

**Comment by wxmbaci** [comment]
> 您好，我这边测试是正常的。
> 
> 测试使用字体为 v1.330 版本中 LXGWWenKai-Bold.ttf， 下载地址：https://github.com/lxgw/LxgwWenKai/releases/tag/v1.330
> 
> 测试视频如下：
> 
>  RPReplay_Final1718902683.MP4

辛苦使用九宫格的键盘试试呢？我刚测试26键可以，九宫格不行。

**Comment by imfuxiao** [comment]
> > 您好，我这边测试是正常的。
> > 测试使用字体为 v1.330 版本中 LXGWWenKai-Bold.ttf， 下载地址：https://github.com/lxgw/LxgwWenKai/releases/tag/v1.330
> > 测试视频如下：
> > RPReplay_Final1718902683.MP4
> 
> 辛苦使用九宫格的键盘试试呢？我刚测试26键可以，九宫格不行。

抱歉，消息回复错了，九键上屏数字的问题，在 TF 版本已修复，商店版本需要等等。

**Comment by imfuxiao** [comment]
商店版本已发布 2.7.0 ，如您测试没有问题，可以关闭此 issue。

**Comment by wxmbaci** [comment]
> 商店版本已发布 2.7.0 ，如您测试没有问题，可以关闭此 issue。

已经可以了，辛苦啦
