### ISSUE TITLE
「Feature」是否考虑在输入法中引用SF Symbols。

### ISSUE THREAD

**Issue by kunpehx** [imfuxiao/Hamster#660]
在定义按键时需求自定义图标，苹果官方的[SF Symbols ](https://developer.apple.com/sf-symbols/)图标丰富，可以满足自定义的需求。是否考虑集成？

**Comment by imfuxiao** [comment]
感谢您的建议，TF 版本已实现此功能，商店版本需要在等等。

**Comment by imfuxiao** [comment]
可能你不在 alpha 测试组中，请耐心等待。

```yaml
TF版本更新3.0.0（299） - alpha 测试组

- feat: 自定义键盘支持 SF Symbol 图标。
```
