### ISSUE TITLE
「功能」请问这能在android上应用吗？

### ISSUE THREAD

**Issue by owzweb** [imfuxiao/Hamster#662]
您好，我找了很久也没有找到你的私信，用了你项目在ios端，无论是在界面上，输入体验上，词语准确性方面等感觉真的很棒，只是还有点小遗憾，只有ios端，

**Comment by imfuxiao** [comment]
「仓输入法」只是 RIME 的前端，除了UI，所有的功能都是基于 RIME 的 api，所以在 Andriod 上的选择很多的，比如同文和小企鹅等。

**Comment by owzweb** [comment]
首页非常感谢大神能在百忙之中抽空回我的信息，由于开源android又是基于9宫格拼音输入法的，基本是没有（最少目前我是没有找到），现在的卡点在于，在用户连续输入的时候，很想知道底层是如何把这些拼音拆分去查的，我留意到大神你写的仓输入法上有好多个词库，不知道底层是如何加载这些词库
&nbsp;


215921352
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年7月1日(星期一) 晚上7:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [imfuxiao/Hamster] 「功能」请问这能在android上应用吗？ (Issue #662)














 
「仓输入法」只是 RIME 的前端，除了UI，所有的功能都是基于 RIME 的 api，所以在 Andriod 上的选择很多的，比如同文和小企鹅等。

**Comment by bandengzex** [comment]
librime提供了api了，只是其他Android平台输入法都没用上

**Comment by bandengzex** [comment]
[https://github.com/rime/librime/pull/771](url)

**Comment by owzweb** [comment]
大神您好，又来叨扰您了，下载了你的源码运行后，发现长按某个字母无法弹出气泡显示多个字母或符号并选择，不知道是不是设置不对，还是其它问题。望大神帮忙指点一二，不胜感激

**Comment by imfuxiao** [comment]
> 大神您好，又来叨扰您了，下载了你的源码运行后，发现长按某个字母无法弹出气泡显示多个字母或符号并选择，不知道是不是设置不对，还是其它问题。望大神帮忙指点一二，不胜感激

您好，目前本仓库代码只同步到商店版本的 2.1.0，之后版本的代码没有同步，所以会有差异。

**Comment by owzweb** [comment]
嗯嗯，不知道这个后续是否会考虑同步？还是作为收费项？

**Comment by imfuxiao** [comment]
> 嗯嗯，不知道这个后续是否会考虑同步？还是作为收费项？

目前不会同步，后面是否会同步，看收入情况而定，毕竟还是要吃饭的。

**Comment by owzweb** [comment]
嗯，理解，大神，不知道能否指点下，要实现这一效果要如果处理呢？（不知道提的是否有点过份了）
&nbsp;


215921352
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年8月12日(星期一) 下午5:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [imfuxiao/Hamster] 「功能」请问这能在android上应用吗？ (Issue #662)





  
嗯嗯，不知道这个后续是否会考虑同步？还是作为收费项？
  
目前不会同步，后面是否会同步，看收入情况而定，毕竟还是要吃饭的。
 
&mdash;

**Comment by imfuxiao** [comment]
这个需要在目前的 UITouch 中添加对长按的处理，当长按时间到达阈值时，去绘制长按的UIView。在绘制 UIView 时，根据对按键的长按配置，生成 UIView 上显示的具体内容。大致流程是这样。
