### ISSUE TITLE
新下载的仓输入法，使用默认的雾凇方案，点击部署按钮后，同步时没有userdb.txt文件

### ISSUE THREAD

**Issue by Oliveira-Lee** [imfuxiao/Hamster#663]
新下载的仓输入法，使用默认的雾凇方案后
点击部署按钮后，并没有生成userdb文件夹，然后在同步时没有userdb.txt文件
后面卸载重装几次之后，才有一次能够看到userdb的文件夹

 -  iOS 版本：17.0.3
 -  仓输入法版本：商店版 2.4.1

**Comment by Oliveira-Lee** [comment]
呃，一般会部署很久，要好几分钟才行

**Comment by tamhaywoo** [comment]
没有通过输入文字的行为就没有这个文件，所以重新部署之后没有出现这个文件是正常情况。

**Comment by Oliveira-Lee** [comment]
好的好的，谢谢开发大大
