### ISSUE TITLE
「Bug」双拼分号无法输入

### ISSUE THREAD

**Issue by luochen1990** [imfuxiao/Hamster#664]
**Bug的详细描述**
有些双拼方案中会使用分号进行编码，因为分号是标准指法中右手小拇指的标准位置。

但我发现仓的键盘中没有这个键，导致有些字无法输入。

**Bug 的复现过程**
重现此 Bug 的步骤：
1. 将输入方案设置为双拼，搜狗双拼
2. 尝试输入“性能”，它在搜狗双拼中的编码是“x；ng”
3. 发现无法输入；。

**您的预期行为**
能在搜狗双拼方案下正确输入“性能”

**屏幕截图/视频**
如果可能，请添加截图或视频以帮助解释您的问题。

**设备信息（请填写以下信息）：**
 -  iOS 版本：如 17.5.1
 -  仓输入法版本：商店版 1.11.2

**其他**

在此添加有关该 bug 的任何其他信息。

**Comment by imfuxiao** [comment]
键盘布局 -> 中文26键 -> 点击 “>” 符号，开启「启用分号按键」。

**Comment by BH2WFR** [comment]
也可以在中文26键中, 空格左侧加入 ";" 键
