### ISSUE TITLE
「Feature」希望在软件的主界面加一个输入框

### ISSUE THREAD

**Issue by CrackedPoly** [imfuxiao/Hamster#667]
**您的功能请求是否与某些问题有关？请描述**
这个软件的自定义程度很高，所以用户有时候想要测试更改配置后的效果，但是需要切换到其他软件进行输入。

**描述您想要的解决方案**
在软件的主界面加一个输入框/搜索框，支持输入就好了，不需要完成其他功能。

**描述您考虑过的替代方案**
简明扼要地描述您考虑过的任何替代解决方案或功能。

**其他**
类似于微信输入法的下面这个。
![358741720802205_ pic](https://github.com/user-attachments/assets/6ea572bd-6e15-4830-9045-9fcaf12803bd)

**Comment by imfuxiao** [comment]
感谢您的反馈，后续增加此功能。

**Comment by imfuxiao** [comment]
商店 2.7.0 版本在 App 主界面「关于」上侧，增加了「体验输入法」入口。
