### ISSUE TITLE
商店版PRO和TF版PRO不通用吗？

### ISSUE THREAD

**Issue by elonj** [imfuxiao/Hamster#669]
请问商店版PRO和TF版PRO不通用吗？商店版购买了，但是TF版还需要再次购买，未找到购买记录

**Comment by imfuxiao** [comment]
TF 版本使用的是沙盒环境，是不会扣费的，请重新购买下。

**Comment by elonj** [comment]
> TF 版本使用的是沙盒环境，是不会扣费的，请重新购买下。

好的。请问自定义键盘无法让划动文本显示在下方吗？试了一下定义键盘，上划的划动文本和下划的划动文本都在字母上方。而在键盘布局里同样的操作可以让划动文本显示在字母的上方和下方。

**Comment by imfuxiao** [comment]
抱歉，目前还做不到，当前自定义键盘中预览键盘与实际键盘还是有点区别，后续会优化这里的功能。

**Comment by elonj** [comment]
> 抱歉，目前还做不到，当前自定义键盘中预览键盘与实际键盘还是有点区别，后续会优化这里的功能。

明白了，谢谢！
