### ISSUE TITLE
建议：能否在给每个键加上边界

### ISSUE THREAD

**Issue by tarkky** [imfuxiao/Hamster#67]
最新版的键盘字体大了，好多了。但是经常误触，手指粗。能否给每个按键加上边界？谢谢。

**Comment by imfuxiao** [comment]
您好, 需要您说明一些细节. 

1. 点击哪个地方会误触. 
2. 您需要的边界是指什么

您可以手机截屏, 在图上描述下, 方便理解, 谢谢

**Comment by tarkky** [comment]
> 您好, 需要您说明一些细节.
> 
> 1. 点击哪个地方会误触.
> 2. 您需要的边界是指什么
> 
> 您可以手机截屏, 在图上描述下, 方便理解, 谢谢
类似这样，这个按键跟按键之间有空档，但是你也可以连在一起用方框圈起来。我的意思是，目前的按键，没有边界，按的时候，键其实被手指挡上，怎么说呢，准确性有些降低。
![keyboard](https://user-images.githubusercontent.com/19773978/232696510-dad445ad-862f-4756-9b71-b56cf1ede2cd.jpg)

**Comment by imfuxiao** [comment]
您说到没有边界是按键的边框是么?

**Comment by tarkky** [comment]
> 您说到没有边界是按键的边框是么?

是的，抱歉表述有些模糊。就像上面截图类似

**Comment by imfuxiao** [comment]
了解了,应该是您选择的配色方案的问题, 您换个其他的配色方案看看. 会有按钮边框.

**Comment by tarkky** [comment]
> 了解了,应该是您选择的配色方案的问题, 您换个其他的配色方案看看. 会有按钮边框.

哦，好的，我试试，然后回来反馈。谢谢

**Comment by tarkky** [comment]
刚才试了但凡背景是浅色的都能够显示按键边框。但是左下角的按键是空白。除了冷漠配色是全白以外，其它的都还好。我目前选择的是谷歌。神色方案有些可以看到边框但是很不清晰。我觉得这个可以作为个tip，不用修改了。麻烦作者把issue关了吧。谢谢。
![冷漠](https://user
![碧水](https://user-images.githubusercontent.com/19773978/232700750-82774c8c-913f-47ae-b62f-c15e0b7bb604.png)
-images.githubusercontent.com/19773978/232700736-d27ddd82-e452-4c41-b94a-0f3b9c958653.png)
配色。附图是冷漠和碧水

**Comment by imfuxiao** [comment]
左下角的按键是空白的问题. 关联 #50
