### ISSUE TITLE
请问有直接调整全局按键字体的方式吗？

### ISSUE THREAD

**Issue by wxhenry** [imfuxiao/Hamster#672]
目前按键字体的大小我只知道可以通过`colorSchemas`修改，但是我希望能够继承默认的按键颜色样式（不启用配色时的颜色样式）。请问有什么方式可以通过`hamster.custom.yaml`等配置文件直接修改吗？

**Comment by imfuxiao** [comment]
无法调整，因为默认情况下，系统按钮（如回车键，键盘跳转按键 123），普通按钮（如 a 键）这些按键的字体大小是不一样的。而统一设置字体大小，会导致这些键看起来不和谐。

所以目前无法指定统一的字体大小。

**Comment by wxhenry** [comment]
我知道了，谢谢
