### ISSUE TITLE
「Feature」每次更新不破壞原有划動設置等鍵盤佈局設置

### ISSUE THREAD

**Issue by NobodyHere-rrr** [imfuxiao/Hamster#674]
**您的功能请求是否与某些问题有关？请描述**
简明扼要地描述问题所在。
有時更新完後，設置好的划動設置幾乎都會被破壞。

**描述您想要的解决方案**
简明扼要地描述您希望发生的结果。
划動設置以及其他鍵盤佈局設置不受影響。

**描述您考虑过的替代方案**
简明扼要地描述您考虑过的任何替代解决方案或功能。
每次更新之後將原先的鍵盤佈局配置轉換成新的配置，使使用不受影響。

**其他**
在此处添加有关功能请求的任何其他上下文或截图或视频等等。

**Comment by imfuxiao** [comment]
仓在 2.1 版本升级的时候因配置文件格式问题，调整过一次，那次的确是破坏性升级，无法处理。

本次 2.7.0 调整了两个地方，[「说明文档」](https://ihsiao.com/apps/hamster/docs/)中有关内置键盘的划动配置的地方也已做了更新。

并且在 App 版本说明中明确写了：如果升级有问题且自己无法处理时，应该如何处理。
