### ISSUE TITLE
「Feature」符号键盘返回栏弄宽一点

### ISSUE THREAD

**Issue by chca2** [imfuxiao/Hamster#675]
**您的功能请求是否与某些问题有关？请描述**
符号键盘返回、锁定和删除键所在行的宽度太窄，输入符号后返回不容易精准点按，考虑到符号栏目前可正常显示4.7行，也并非整数，还不如加宽一点返回栏。

**描述您想要的解决方案**
![EB79589F-3174-4143-B25A-2979580E89FD_1_201_a](https://github.com/user-attachments/assets/a39d9923-a0d1-455e-9152-5d72a4fb8178)加大如图的宽度。

**描述您考虑过的替代方案**
无

**其他**
无

**Comment by imfuxiao** [comment]
您好，您指的是将返回按键加宽，还是整个底部加高？

**Comment by chca2** [comment]
> 您好，您指的是将返回按键加宽，还是整个底部加高？

确切说，返回按键所在的行的高度加宽，因为目前返回的高度和比上面符号按键的具体分类（如英文的标签）要明显矮一些，不方便点按。一般进入符号键盘后，敲击了符号后会返回正常键盘打字，如果太矮按起来就需要小心翼翼。

**Comment by imfuxiao** [comment]
哦，了解了，你是指底部整行加高。

**Comment by imfuxiao** [comment]
商店版本 2.7.1 已增高底部行。
