### ISSUE TITLE
导入键盘布局就闪退

### ISSUE THREAD

**Issue by CallMeNP** [imfuxiao/Hamster#676]
**Bug的详细描述**
导入键盘布局就闪退

**Bug 的复现过程**
重现此 Bug 的步骤：
1. 在这里生成配置文件 https://lost-melody.github.io/hamster-tools/ 。（见附件
[custom_configs-20240628-141640.yaml.txt](https://github.com/user-attachments/files/16402448/custom_configs-20240628-141640.yaml.txt)
）
3. 传导手机上导入。
4. app崩溃闪退。

**您的预期行为**
主要是寻求自定义键盘布局的方案，并且支持添加“按键滑动指令”的方式。
内建的自定义键盘设置界面中，没找到相关功能。如果有，麻烦指点一下。

**屏幕截图/视频**
...

**设备信息（请填写以下信息）：**
 -  iOS 版本：如 15.7.1
 -  仓输入法版本：商店版 2.7.0

**其他**

在此添加有关该 bug 的任何其他信息。

**Comment by imfuxiao** [comment]
感谢您的反馈。
* [自定义键盘参考文档](https://ihsiao.com/apps/hamster/docs/CustomKeyboard.html)， 里面有划动相关设置。
* 目前只有内置中文26键支持界面上设置划动，在「键盘布局」-「中文26键」点击 `>` 进入设置页面。
* 其他内置键盘如英文键盘，需要通过配置文件进行设置。具体参考[文档](https://ihsiao.com/apps/hamster/docs/Questions.html#%E5%86%85%E7%BD%AE%E8%8B%B1%E6%96%87%E9%94%AE%E7%9B%98%E5%A6%82%E4%BD%95%E8%87%AA%E5%AE%9A%E4%B9%89%E6%8C%89%E9%94%AE%E5%88%92%E5%8A%A8%E4%B8%8E%E9%95%BF%E6%8C%89)

**Comment by imfuxiao** [comment]
关于导入崩溃的问题，临时解决方式是将文件此文件存放至「我的iPhone」- 「Hamster」文件夹下，然后在应用中选择导入。

**Comment by CallMeNP** [comment]
感谢这么及时的解答。将文件放到Hamster文件夹成功解决了问题。

这个文档真好，之前没注意到，原来在app关于里就有链接。

**Comment by imfuxiao** [comment]
商店版本更新 2.7.1 已修复此问题。
