### ISSUE TITLE
Caps（上挡键）和符号键（#+=）大小不一致

### ISSUE THREAD

**Issue by hanwinbi** [imfuxiao/Hamster#68]
- 符号中的 ，。似乎没有做中英区分，都显示的是英文 ,. 这个无伤大雅
- Caps（上挡键）和符号键（#+=）大小不一致，切换到数字输入的时候这个键看起来会跳
- ABC、#+=、123 和右下角功能键（搜索、换行）字体大小似乎有点大，调整到更小的字号似乎更合适。（十分理解26键要显示上滑候选，将字母调整的比原生键盘要小，但是两种字体大小在同一个界面会形成对比，会不太和谐。）

非常感谢作者花费时间并开源项目~

**Comment by imfuxiao** [comment]
非常感谢您的反馈. 针对您提到的问题.

1. 符号没有区分中英. 这确实是个问题, 这个问题准备在 #24 特性中处理.
2. Caps（上挡键）和符号键（#+=）大小不一致. 这是个问题, 我下来看下.
3. ABC、#+=、123 和右下角功能键（搜索、换行）字体大小似乎有点大, 这个在1.1.4版本有做修改, 您看下是否是最新版本. 

再次感谢您的反馈~
