### ISSUE TITLE
Rime重新部署会覆盖设置

### ISSUE THREAD

**Issue by zhaoguibin** [imfuxiao/Hamster#683]
Rime里面点击重新部署之后，同步路径和同步文件夹名称都还原成了默认的，输入法方案也还原成了默认的

**Comment by imfuxiao** [comment]
是否开启了 iCloud 选项

**Comment by zhaoguibin** [comment]
> 是否开启了 iCloud 选项

对，开了icloud。部署之前需要关上icloud吗

**Comment by imfuxiao** [comment]
检查 iCloud 中存储的内容是否正确

**Comment by zhaoguibin** [comment]
> 检查 iCloud 中存储的内容是否正确

正是这个原因，修改配置之前已经同步到icloud了
