### ISSUE TITLE
IPadOS 浮动键盘候选栏显示问题

### ISSUE THREAD

**Issue by YuxiSR** [imfuxiao/Hamster#689]
**Bug的详细描述**
每次唤出输入法后，候选栏的高度不对，需要切换下中英键盘才能正常，但下次唤出仍有问题

**Bug 的复现过程**
重现此 Bug 的步骤：
1. 唤醒键盘
2. 键盘高度过高
3. 切换中英文
4. 键盘高度正常

**您的预期行为**
每次唤醒键盘高度正常

**屏幕截图/视频**
![截屏 2024-09-20 17 58 56](https://github.com/user-attachments/assets/005477f3-6e2a-404b-9a3a-7fa199273d85)

**设备信息（请填写以下信息）：**
 -  iOS 版本：如 iPadOS 18.0
 -  仓输入法版本：商店版 2.8.0

**其他**

在此添加有关该 bug 的任何其他信息。

**Comment by imfuxiao** [comment]
感谢您的反馈，预计下个版本修复。

**Comment by imfuxiao** [comment]
您好，2.9.1 已修复此问题。
