### ISSUE TITLE
配色方案修改

### ISSUE THREAD

**Issue by imfuxiao** [imfuxiao/Hamster#69]
需求描述: 
1. 希望可以有个配色方案修改功能，直观的预览修改颜色，保存为新颜色方案，写入到配置文件里面。
2. 动识别系统亮色模式和暗黑模式，根据配色设置自动切换不同的配色方案，比如一套亮色模式的和一套暗色的.

**Comment by DawnLi-code** [comment]
建议使用外部解决方案：https://github.com/LEOYoon-Tsaw/Squirrel-Designer
生成代码自己编辑文件写入，这样就不会增加app的负载了。

**Comment by imfuxiao** [comment]
> 建议使用外部解决方案：https://github.com/LEOYoon-Tsaw/Squirrel-Designer 生成代码自己编辑文件写入，这样就不会增加app的负载了。

您的方案非常棒，确实会减少App的负担。

**Comment by imfuxiao** [comment]
目前2.0.0版本已支持配色方案跟随系统浅色/深色模式变更。
