### ISSUE TITLE
Ipad 外接键盘小鹤双拼不生效

### ISSUE THREAD

**Issue by drizzl4** [imfuxiao/Hamster#699]
**Bug的详细描述**
Ipad 外接键盘小鹤双拼不生效

**Bug 的复现过程**
1. 将Hamster配置项只选中小鹤双拼，并添加到ipad中
2. 使用蓝牙键盘连接Ipad输入文字
3. 发现蓝牙键盘双拼不生效，表现行为为全拼。
如果单独调用屏幕上键盘，双拼生效。

**您的预期行为**
希望蓝牙键盘也可以支持小鹤双拼

**屏幕截图/视频**
蓝牙键盘：
![IMG_0009](https://github.com/user-attachments/assets/abb36ad1-2669-4c65-a1f0-6154eb3f527b)

键盘面版：
![IMG_0010](https://github.com/user-attachments/assets/e1bdb780-dd18-43f9-a071-ca9d7e974e40)

**设备信息（请填写以下信息）：**
 -  iOS 版本： 18.1
 -  仓输入法版本：商店版 2.9.4（1） 
 -  键盘：k380、NJ68
**其他**
无

**Comment by imfuxiao** [comment]
您好，系统限制，任何外接键盘都无法使用第三方输入法，所以不是bug。

**Comment by drizzl4** [comment]
> 您好，系统限制，任何外接键盘都无法使用第三方输入法，所以不是bug。

感谢回复，了解了
