### ISSUE TITLE
「Feature」自定义布局问题

### ISSUE THREAD

**Issue by flash201524** [imfuxiao/Hamster#704]
自定义布局里缺少某些按键，比如自带的中文26键布局里，第四行数字旁边可以有一个符号键直达符号输入，但是自定义里没这个键。还有同样是自带布局里右下角有收起键盘键，虽然在快捷方式里也有这样一个键，但是没有收起键盘的图标非常不美观。

还有一个问题就是中英切换时，英文键盘会切换成和自带的中文26键一样的布局，能否在什么地方进行修改？

**Comment by imfuxiao** [comment]
您好，非常感谢您的反馈。

----

问题1: 比如自带的中文26键布局里，第四行数字旁边可以有一个符号键直达符号输入，但是自定义里没这个键。

此问题可以通过自定义 action 的值实现，action 中可以设置 keyboardType 其中，keyboardType 可以设置为 classifySymbolic，具体请查阅[文档 Action 选项](https://ihsiao.com/apps/hamster/docs/CustomKeyboard.html#action-%E9%80%89%E9%A1%B9)

问题2: 还有同样是自带布局里右下角有收起键盘键，虽然在快捷方式里也有这样一个键，但是没有收起键盘的图标非常不美观。

可以通过 systemImageName 属性设置 SF Symbol 中的符号，也可以用使用自定义图标字体，设置字体中的图标。

问题3: 中英切换时，英文键盘会切换成和自带的中文26键一样的布局，能否在什么地方进行修改。

可以自定义一个英文键盘，action 行为设置为点击后跳转到这个自定义键盘中。
