### ISSUE TITLE
「Feature」增加可直接调用指定脚本的action

### ISSUE THREAD

**Issue by xubai2001** [imfuxiao/Hamster#706]
## 背景与现状
当前脚本功能的主要流程包括：
1. 打开脚本页面。
2. 输入信息或获取剪贴板内容。
3. 手动选择目标脚本，并点击执行。

上述操作虽然可以满足一般需求，但当脚本数量过多时，想要找到指定脚本较为麻烦，而且仓的脚本图标数量有限，不能准确区分不同脚本。

## 需求描述
为了提升操作效率，希望新增一个快速执行脚本的功能，具体需求如下：
- 增加一个配置项，允许用户定义一个快捷 **action**。
- 在调用该 **action** 时，可自动完成以下步骤：
  1. 打开脚本页面。
  2. 自动选中并执行指定脚本。

## 预期效果
用户可通过配置 action 实现直接调用指定脚本并完成执行。
脚本调用过程从多步骤缩短为一键或一划完成。

**Comment by imfuxiao** [comment]
已添加此功能。
