### ISSUE TITLE
迭代速度快，考虑整个TestFlight

### ISSUE THREAD

**Issue by androidcn** [imfuxiao/Hamster#73]
迭代速度快，考虑整个TestFlight

**Comment by imfuxiao** [comment]
TestFlight有的, 但是现在迭代太快了, TestFlight外部测试审核速度比正式商店的审核还慢.所以基本上正式版本上架了, 测试版也上架了.

**Comment by imfuxiao** [comment]
Testlight外部测试申请 #37 , 目前外部测试版本等于或晚于正式版, 这是因为目前App本身问题多, 迭代频率快, 而苹果审核的周期慢导致的. 后续App趋于稳定了, 外部测试版就会先上, 还请大家能够理解.
