### ISSUE TITLE
iPhone未解锁状态无法使用仓输入法

### ISSUE THREAD

**Issue by tamhaywoo** [imfuxiao/Hamster#78]
如题，在iPhone锁定状态下，向右滑动进入负一屏点击搜索时，无法选择使用仓输入法。点击地球，也没有可选。

**Comment by imfuxiao** [comment]
感谢反馈, 我排查下.

**Comment by DreamAfar** [comment]
这个应该是iOS的限制，不是Bug。
其他第三方输入法在锁屏状态下，负一屏下拉搜索一样只有系统输入法可用。
一解锁马上第三方的就可以用。

**Comment by lovelock** [comment]
没见过能在负一屏用的第三方输入法

**Comment by imfuxiao** [comment]
收到, 我会排查下这个问题
