### ISSUE TITLE
1.2.0版本还没发布到app store么？

### ISSUE THREAD

**Issue by tarkky** [imfuxiao/Hamster#79]
1分钟前刷，还是上一版。

**Comment by imfuxiao** [comment]
抱歉了各位, 我犯了个错误....昨天只做了保存, 忘记点击提交审核了...刚上去才发现...

**Comment by tarkky** [comment]
> 抱歉了各位, 我犯了个错误....昨天只做了保存, 忘记点击提交审核了...刚上去才发现...
刚刷了app store，还是老版啊。1.30的也没有

**Comment by imfuxiao** [comment]
您好，今天刚提交，最快也要到明天了。
