### ISSUE TITLE
反馈一些问题和建议

### ISSUE THREAD

**Issue by DreamAfar** [imfuxiao/Hamster#8]
感谢作者开发这个App，为iOS上有多一个Rime输入法的选择。

使用后反馈些使用的问题和建议：
1、上传文件界面返回后，再进入会不显示IP地址，但可以正常上传使用。
![image](https://user-images.githubusercontent.com/69999980/231435611-7cfdd520-fbe5-4bd3-9cb9-823ffbeb03cc.jpeg)

2、键盘的震中反馈有延迟，给人感觉就是不跟手。

3、还有就是如果有使用两个方案，没法快速的切换方案输入，例如：我现在使用中文和日文的输入方案，在iRime上可以自定义键盘用一个符号^代替Rime的.next快捷键切换下一个输入方案，希望可以增加一个切换输入方案按键在输入功能设置里面可选打开。

4、测试修改了配色方案文件，上传后可以自动正确识别出颜色，生成预览效果图。说明App已有颜色识别的功能，希望下一步可以有个配色方案修改功能，直观的预览修改颜色，保存为新颜色方案，写入到配置文件里面。

5、还有就是目前键盘开启配色，会和系统配色不搭，特别键盘下面的系统键盘切换栏。
如果以后可以自动识别系统亮色模式和暗黑模式，根据配色设置自动切换不同的配色方案，比如一套亮色模式的和一套暗色的。
![image](https://user-images.githubusercontent.com/69999980/231454615-d09be129-42e4-4a5f-b068-4d94dcede866.jpeg)

6、如果有可能的话可以增加嵌入式编码
（下面是iRime的界面）
![image](https://user-images.githubusercontent.com/69999980/231453870-8ea67288-38f4-40b8-ab63-9ae3ad7765fa.jpeg)

**Comment by imfuxiao** [comment]
候选字的问题已经在改了,  正在加入候选字字体大小调整选项. 

类似iRime上的绑定符号，切换输入方和Emoji表情、符号, 我先思考下, 看怎么融入后续版本.

> 还有就是候选的字太小了，不好按。 有时候点候选会没有上屏，要点多两次才上屏。
> 
> 目前在iRime上，可以这样绑定符号，切换输入方和Emoji表情、符号

**Comment by DreamAfar** [comment]
> 很高兴收到您这么详细的反馈, 万分感谢.
> 
> 
> 
> 针对您提到的bug, 我会尽快修复. 您提到的一些改进方案我先思考下. 随后看怎样排入开发计划中.

辛苦作者了，希望这个倉输入法能发展的更加好和多人使用。加油！

**Comment by imfuxiao** [comment]
> > 很高兴收到您这么详细的反馈, 万分感谢.
> > 针对您提到的bug, 我会尽快修复. 您提到的一些改进方案我先思考下. 随后看怎样排入开发计划中.
> 
> 辛苦作者了，希望这个倉输入法能发展的更加好和多人使用。加油！

客气了, 非常感谢您的使用.

**Comment by imfuxiao** [comment]
1. 上传文件界面返回后，再进入会不显示IP地址，但可以正常上传使用。 #28 
2. 键盘的震中反馈有延迟，给人感觉就是不跟手. #18 
3. 还有就是如果有使用两个方案，没法快速的切换方案输入 #23 
4. 配色方案修改功能. #69
5. #69
6. #25
