### ISSUE TITLE
[功能建议] 展开候选词列表

### ISSUE THREAD

**Issue by maogm12** [imfuxiao/Hamster#86]
键盘顶部候选栏现在只能左右滑动选词，当候选词比较多的时候就比较麻烦，建议增加候选词列表展开功能。类似系统拼音输入法：

https://user-images.githubusercontent.com/1658974/233165109-d83d16de-73a3-45f9-894f-d2cfa19166ec.mov

**Comment by imfuxiao** [comment]
您好, 很高兴收到您的反馈, 此功能的issue重复, 关联 #77, 

期待您的再次反馈.
