### ISSUE TITLE
按键添加功能如复制/粘贴/全选/剪贴等功能

### ISSUE THREAD

**Issue by imfuxiao** [imfuxiao/Hamster#92]
需求: 我期望按键可以添加: 复制，粘贴，全选，剪贴等功能.

**Comment by AeonWorks** [comment]
我认为可以考虑添加，这样手不用离开键盘即可操作，能提高输入效率。

**Comment by imfuxiao** [comment]
> 我认为可以考虑添加，至少添加粘贴功能，这样手不用离开键盘即可操作，能提高输入效率。

收到，已在计划中，具体进度可以看Project的的ToDo

**Comment by SenLief** [comment]
建议增加剪贴板的功能，这样可以保存多个剪贴板。

**Comment by imfuxiao** [comment]
期望可以对输入框内的文字进行快速的复制、粘贴、替换，重新编辑操作

比如我在其他地方复制了一段文字，里面有我需要的部分，和想删掉的一部分。
在键盘上上滑调出编辑功能，键盘读取剪贴板里面的文字
键盘显示快速编辑界面，选取需要的部分，点击粘贴，完成

**Comment by xunidelan** [comment]
建议增加一键清除clipboard，便于保护隐私

**Comment by imfuxiao** [comment]
目前已支持「#复制」，「粘贴」，「剪切」，「全选」快捷指令，对复制后的文字编辑功能，需要整合到「剪切板功能」中。因此关闭此 issue。

**Comment by AeonWorks** [comment]
「全选」没有找到，其他都有了。版本 v2.4.1

**Comment by imfuxiao** [comment]
还未发布商店版本，发布后就有了。
