### ISSUE TITLE
默认亮色皮肤文字对比度差问题

### ISSUE THREAD

**Issue by chca2** [imfuxiao/Hamster#93]
默认的亮色皮肤下，上屏的候选字是使用深灰色凸显，在文字黑色情况下，反而比其他未高亮的候选字更为不明显。
建议参考iOS自带键盘的操作，对于当前候选字，采用白色背景，以增强黑色文字的对比关系。默认的深色背景没有这个问题。

**Comment by imfuxiao** [comment]
收到, 非常感谢您的反馈.

**Comment by imfuxiao** [comment]
应用默认颜色背景色已改为透明色
