### ISSUE TITLE
咨询，如何输入中文省略号？

### ISSUE THREAD

**Issue by Jason4788** [imfuxiao/Hamster#95]
能否把数字切换键出来的字符默认是中文全角标点，如…… ——等，现在找不到

**Comment by imfuxiao** [comment]
临时解决方案: 通过App内的上下滑动功能设置, 将中文符号自定义到某个键的上下滑动中

全局的符号输入功能目前在开发列表中: #24 , 请耐心等待.

**Comment by maogm12** [comment]
可以修改某个键的上下滑动符号为中文省略号
